### PR TITLE
layers: Attempt (again) to solve semaphore race conditions

### LINKED ISSUE #4733: [Regression] 27ba73e0 causes deadlock in mpv
**Describe the Issue**
After commit 27ba73e0, using the validation debug layers with libplacebo/mpv results in an immediate hang of the program. (When certain settings are enabled)

**Valid Usage ID**
```
vo/gpu-next/libplacebo: vk Validation Error: [ UNASSIGNED-VkFence-state-timeout ] Object 0: handle = 0x993a4d000000008f, name = vk_tex_upload, type = VK_OBJECT_TYPE_FENCE; | MessageID = 0xcf5eead0 | Timeout waiting for fence state to update.
vo/gpu-next/libplacebo:     using VkFence: vk_tex_upload (0x993a4d000000008f)
vo/gpu-next/libplacebo:   Backtrace:
vo/gpu-next/libplacebo:     #0  0x00007f4df8f22b5b in vk_dbg_utils_cb+0x2da at /mem/lib64/libplacebo.so.229+0x92b5b
vo/gpu-next/libplacebo:     #1  0x00007f4d9eebd3bf in _ZL13debug_log_msgPK18_debug_report_datajRK13LogObjectListPKcS6_S6_+0xc96 at /home/nand/dev/Vulkan-ValidationLayers/build/layers/./libVkLayer_khronos_validation.so+0x28273bf
vo/gpu-next/libplacebo:     #2  0x00007f4d9eebdf23 in _ZL12LogMsgLockedPK18_debug_report_datajRK13LogObjectListRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPc+0x774 at /home/nand/dev/Vulkan-ValidationLayers/build/layers/./libVkLayer_khronos_validation.so+0x2827f23
vo/gpu-next/libplacebo:     #3  0x00007f4d9ef68379 in _ZNK16ValidationObject8LogErrorI17VulkanTypedHandleEEbT_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKcz+0x16b at /home/nand/dev/Vulkan-ValidationLayers/build/layers/./libVkLayer_khronos_validation.so+0x28d2379
vo/gpu-next/libplacebo:     #4  0x00007f4d9f05bc2c in _ZN11FENCE_STATE13NotifyAndWaitEv+0x164 at /home/nand/dev/Vulkan-ValidationLayers/build/layers/./libVkLayer_khronos_validation.so+0x29c5c2c
vo/gpu-next/libplacebo:     #5  0x00007f4d9edd03f1 in _ZN22ValidationStateTracker27PostCallRecordWaitForFencesEP10VkDevice_TjPKP9VkFence_Tjm8VkResult+0x8f at /home/nand/dev/Vulkan-ValidationLayers/build/layers/./libVkLayer_khronos_validation.so+0x273a3f1
vo/gpu-next/libplacebo:     #6  0x00007f4d9eba011d in _ZN20vulkan_layer_chassis13WaitForFencesEP10VkDevice_TjPKP9VkFence_Tjm+0x358 at /home/nand/dev/Vulkan-ValidationLayers/build/layers/./libVkLayer_khronos_validation.so+0x250a11d
vo/gpu-next/libplacebo:     #7  0x00007f4df8f1fe97 in vk_cmd_poll+0x49 at /mem/lib64/libplacebo.so.229+0x8fe97
vo/gpu-next/libplacebo:     #8  0x00007f4df8f2201a in vk_poll_commands+0x65 at /mem/lib64/libplacebo.so.229+0x9201a
vo/gpu-next/libplacebo:     #9  0x00007f4df8f2aee8 in vk_timer_query+0x5b at /mem/lib64/libplacebo.so.229+0x9aee8
vo/gpu-next/libplacebo:     #10 0x00007f4df8ec8221 in pl_timer_query+0x47 at /mem/lib64/libplacebo.so.229+0x38221
vo/gpu-next/libplacebo:     #11 0x00007f4df8eb5561 in run_pass+0x245 at /mem/lib64/libplacebo.so.229+0x25561
vo/gpu-next/libplacebo:     #12 0x00007f4df8eb6226 in pl_dispatch_finish+0xaea at /mem/lib64/libplacebo.so.229+0x26226
vo/gpu-next/libplacebo:     #13 0x00007f4df8ed46d1 in pass_output_target+0x198b at /mem/lib64/libplacebo.so.229+0x446d1
vo/gpu-next/libplacebo:     #14 0x00007f4df8eda676 in pl_render_image_mix+0x21b5 at /mem/lib64/libplacebo.so.229+0x4a676
vo/gpu-next/libplacebo:     #15 0x000000000051cc08 in draw_frame+0x618 at /home/nand/dev/mpv/build/mpv+0x11cc08
vo/gpu-next/libplacebo:     #16 0x00000000004f38ba in vo_thread+0x50a at /home/nand/dev/mpv/build/mpv+0xf38ba
vo/gpu-next/libplacebo:     #17 0x00007f4df8a489ad in start_thread+0x2cf at /lib64/libc.so.6+0x8e9ad
vo/gpu-next/libplacebo:     #18 0x00007f4df8acf290 in __clone3+0x30 at /lib64/libc.so.6+0x115290
```

**Environment:**
 - OS: openSuSE Tumbleweed
 - GPU: AMD RX 5600 XT
 - SDK or header version if building from repo: v1.2.169
 - Options enabled (synchronization, best practices, etc.): `CMAKE_BUILD_TYPE=Debug` (as per `BUILD.gn`)

**Additional context**
I can only reproduce this in a fairly specific set of circumstances. Here's how I reproduce, for testing:

```
VK_LAYER_PATH=/home/nand/dev/Vulkan-ValidationLayers/build/layers mpv --no-config --no-audio --vo=gpu-next --gpu-api=vulkan  --gpu-debug=yes --dither-depth=8 --vulkan-queue-count=2 -v -v FILE.mp4
```

Removing any of the options (e.g. `--dither-depth=8`, `--vulkan-queue-count=2`) makes it no longer deadlock.

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**
Store signal and wait operation(s) in a single std::map entry. For timeline semaphores, there can only ever be 1 signal operation for each value. For binary semaphores, each signal operation must have exactly 1 wait. Storing the signals and waits together makes it easier to keep track of these conditions. (Reminder: for binary semaphores, timeline-like values are assigned to every signal/wait signal pair by SEMAPHORE_STATE itself)

Stop assuming that completion of any signal operation implies anything about operations with lower timeline values. Instead, only retire the exact timeline value for each semaphore when its queue submission (or host signal operation) completes. The retire should trigger a chain reaction through all of the queues causing prior operations to retire in the correct order.

Fixes #4733

### CODE REVIEW

**Comment by juan-lunarg** [comment]
`ctest` allows you to run tests in parallel. Which I believe reflects the sporadic failures you are trying to reproduce.

I think this might be beneficial for testing your code.

```bash
cd build
ctest  --tests-regex Semaphore -j 20
```

Result from 1 job: `81% tests passed, 7 tests failed out of 37` <- Equivalent to running the test binary directly
Result from 20 jobs: `62% tests passed, 14 tests failed out of 37`

**Comment by jeremyg-lunarg** [comment]
> `ctest` allows you to run tests in parallel. Which I believe reflects the sporadic failures you are trying to reproduce.
> 
> I think this might be beneficial for testing your code.
> 
> ```shell
> cd build
> ctest  --tests-regex Semaphore -j 20
> ```
> 
> Result from 1 job: `81% tests passed, 7 tests failed out of 37` <- Equivalent to running the test binary directly Result from 20 jobs: `62% tests passed, 14 tests failed out of 37` <- Perhaps more representative of what's happening on CI
> 
> FWIW I only get failures when running an Nvidia GPU, Mock/Intel passes fine.

Thanks, I'll give that a try!

**Comment by jeremyg-lunarg** [comment]
Filed https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4821 for the ctest crashes. They can only be reproduced on Linux / NVidia and can be reproduced without this PR.

File: layers/queue_state.h [hunk 1]
```diff
@@ -122,7 +122,6 @@ class SEMAPHORE_STATE : public REFCOUNTED_NODE {
     }
 
     struct SemOp {
-        SemOp() : op_type(kNone), queue(nullptr), seq(0), payload(0) {}
         SemOp(OpType ot, QUEUE_STATE *q, uint64_t queue_seq, uint64_t timeline_payload)
             : op_type(ot), queue(q), seq(queue_seq), payload(timeline_payload) {}
         // NOTE: c++11 doesn't allow aggregate initialization and default member
```
Comment (juan-lunarg) [inline layers/queue_state.h:127]: We have C++17 now :)

**Review by juan-lunarg — APPROVED** [review]
LGTM, especially since it closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4733

**Comment by juan-lunarg** [comment]
FWIW I've been looking over this PR a couple times now. The only other suggestion I have is that the code can be cleaned up now that we have C++17 i.e. VVL_USE_SHARED_MUTEX isn't needed anymore

**Comment by jeremyg-lunarg** [comment]
> FWIW I've been looking over this PR a couple times now. The only other suggestion I have is that the code can be cleaned up now that we have C++17 i.e. VVL_USE_SHARED_MUTEX isn't needed anymore

I think I'll make a separate PR to clean that and the aggregate constructor stuff up.

File: layers/queue_state.h (hunk 1 above)
Comment (jeremyg-lunarg) [reply layers/queue_state.h:127]: I'm just going to take the comment out. I can't remember why I wrote it and there'd be no benefit to default member initialization or aggregate initialization for this struct anymore.

**Review by Tony-LunarG — APPROVED** [review]
Still tricky stuff but LGTM
