### PR TITLE
Fix various gaps in OpRuntimeArray support in SC

### LINKED ISSUE #289: Core validation layer claims usubpassinput input attachment variable must not be associated with R32_UINT image view
Consider the following FS:

```
#version 450

#extension GL_EXT_nonuniform_qualifier : require
 
layout(location = 0) flat in uint in_point_id;
  
  #if 1
      layout(set = 0, binding = 0, input_attachment_index = 0) uniform usubpassInput tested_array[];
  #endif
  
  layout(set = 1, binding = 4, std430) writeonly buffer outputBufferType
  {
      int result[];
  };
  
  void main()
  {
      uint n_invocation = in_point_id;
      int temp = 2;
  
      for (int n_array = 0; n_array < 8; n_array += 2)
      {
          if (subpassLoad(tested_array[n_array]).x != (n_array + 1) )
          {
              temp = 4;
  
              break;
          }
      }
  
      result[n_invocation] = temp;
  }
```

Input attachment binding is paired with a R32_UINT image view. However, at vkCreateGraphicsPipelines() call time, the following VU triggers:

image

image

### PR DESCRIPTION
**Pull request by chrisforbes**
Fixes #289

### CODE REVIEW

File: layers/shader_validation.cpp [hunk 1]
```diff
@@ -419,15 +426,13 @@ static unsigned GetFundamentalType(shader_module const *src, unsigned type) {
         case spv::OpTypeFloat:
             return FORMAT_TYPE_FLOAT;
         case spv::OpTypeVector:
-            return GetFundamentalType(src, insn.word(2));
         case spv::OpTypeMatrix:
-            return GetFundamentalType(src, insn.word(2));
```
Comment (jzulauf-lunarg) [inline layers/shader_validation.cpp]: Aren't there compilers (modern GCC or LLVM) that warn on fall through cases with some comment or pragma...   https://dzone.com/articles/implicit-fallthrough-in-gcc-7

Would like to *not* add warnings.

File: layers/shader_validation.cpp [hunk 2]
```diff
@@ -1375,6 +1381,7 @@ static uint32_t DescriptorTypeToReqs(shader_module const *module, uint32_t type_
     while (true) {
         switch (type.opcode()) {
             case spv::OpTypeArray:
+            case spv::OpTypeRuntimeArray:
```
Comment (jzulauf-lunarg) [inline layers/shader_validation.cpp]: I see we already have fall throughs... hmmm.

File: layers/shader_validation.cpp (hunk 1 above)
Comment (chrisforbes) [reply layers/shader_validation.cpp]: Not aware of anyone who warns on this bunch-of-labels case. Definitely GCC warns if you have code followed by falling through.
