### PR TITLE
syncval: Handle destruction of bindless descriptor resources

### LINKED ISSUE #3717: Crash in sync validation (AccessContext::DetectHazard)
**Describe the Issue**
This is a migration of [Lunarxchange issue 1052](https://vulkan.lunarg.com/issue/view/61558b455df1124cb68c3115)

Original description:
After installing the new Vulkan SDK 1.2.189.2, When I start my application, an exception is occured
Exception thrown at 0x00007FFCB174979F (VkLayer_khronos_validation.dll) in Allplan_99D.exe: 0xC0000005: Access violation reading location 0x00000000000000E4.
at : synchronization_validation.cpp line 1208 :
if (!SimpleBinding(image)) return HazardResult();

in function:
```
template
HazardResult AccessContext::DetectHazard(Detector &detector, const IMAGE_STATE &image,
                                                                      const VkImageSubresourceRange &subresource_range, DetectOptions options) const {
    if (!SimpleBinding(image)) return HazardResult();
    const auto base_address = ResourceBaseAddress(image);
    subresource_adapter::ImageRangeGenerator range_gen(image.fragment_encoder.get(), subresource_range, base_address);
    const auto address_type = ImageAddressType(image);
    for (; range_gen->non_empty(); ++range_gen) {
         HazardResult hazard = DetectHazard(address_type, detector, range_gen, options);
         if (hazard.hazard) return hazard;
    }
    return HazardResult();
}

```

**Valid Usage ID**
none

**Environment:**
 - OS:  Windows
 - GPU:  Intel UHD 630 and NVIDIA 1660 GTX. 
 - SDK or header version if building from repo: SDK 1.2.189.2 and 1.2.198.1
 - Options enabled (synchronization, best practices, etc.): sync validation.

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**
If a descriptor set is created with VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT, it is valid to destroy buffers or images (or views) used by one of its descriptors, as long as that descriptor is not 'dynamically used' by any shader invocations. Because these descriptor sets are often quite large, the state tracker does not remove state pointers from descriptors when a resource is destroyed. Avoid crashing in this case by checking for destroyed state objects.

Fixes #3717

### CODE REVIEW

File: layers/synchronization_validation.cpp [hunk 1]
```diff
@@ -1921,7 +1921,7 @@ bool CommandBufferAccessContext::ValidateDispatchDrawDescriptorSet(VkPipelineBin
                     }
                     case DescriptorClass::TexelBuffer: {
                         auto buf_view_state = static_cast<const TexelDescriptor *>(descriptor)->GetBufferViewState();
-                        if (!buf_view_state) continue;
+                        if (!buf_view_state || buf_view_state->Destroyed() || !buf_view_state->buffer_state) continue;
```
Comment (jzulauf-lunarg) [inline layers/synchronization_validation.cpp:1924]: maybe using `Invalid(const BASE_NODE *p) { return !p || p->Destroyed() || (p->Handle().handle == VK_NULL_HANDLE); }` would be DRY'r and more consistent?   static BASE_NODE function?

**Review by jzulauf-lunarg — COMMENTED** [review]
Not fully consistent (*_state not always checked) ... consider suggested Invalid function.

File: layers/synchronization_validation.cpp (hunk 1 above)
Comment (jeremyg-lunarg) [reply layers/synchronization_validation.cpp:1924]: > Not fully consistent (*_state not always checked) ... consider suggested Invalid function.

Is the inconsistency the difference between *views* which have a buffer or image, and plain buffer or image, which do not?

Comment (jzulauf-lunarg) [reply layers/synchronization_validation.cpp:1924]: right... but if we're checking for buffer_state, maybe`if(Invalid(buf_view_state) || Invalid(buf_view_state->buffer_state)` or some overload or SFINAE for  `*_VIEW_STATE` object meeting a concept that has a BaseState() method?

Comment (jeremyg-lunarg) [reply layers/synchronization_validation.cpp:1924]: or Descriptor::Invalid()?

Comment (jzulauf-lunarg) [reply layers/synchronization_validation.cpp:1924]: Dealer's choice.

File: layers/descriptor_sets.cpp [hunk 2]
```diff
@@ -2986,6 +2986,39 @@ void cvdescriptorset::MutableDescriptor::RemoveParent(BASE_NODE *base_node) {
...
+            return !sampler_state_ || sampler_state_->Destroyed();
+
+        case VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER:
+            return !sampler_state_ || sampler_state_->Invalid() || !image_view_state_ || image_view_state_->Invalid();
+
+        case VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER:
+        case VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER:
+            return !buffer_view_state_ || buffer_view_state_->Invalid();
+
+        case VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE:
```
Comment (jzulauf-lunarg) [inline layers/descriptor_sets.cpp:3001]: Is this a copy/pasta?  for these types, WriteUpdate is setting the image_view_state_

**Review by jzulauf-lunarg — CHANGES_REQUESTED** [review]
I think there's a copy paste error.

I've probably made this more complex by asking you to DRY, but it is way cleaner.

File: layers/descriptor_sets.cpp (hunk 2 above)
Comment (jeremyg-lunarg) [reply layers/descriptor_sets.cpp:3001]: yeah. ugh

**Review by jzulauf-lunarg — APPROVED** [review]
Nice and DRY with the descriptor type and state type specific stuff nicely encapsulated.
