### PR TITLE
VK_EXT_extended_dynamic_state set before draw

### LINKED ISSUE #5764: VUID exist, but validation not happening for Pipeline dynamic state "CullMode"
**Environment:**
 - OS: Windows 10
 - GPU: GTX 1080ti
 - SDK or header version if building from repo: SDK 1.3.243
 - Options enabled (synchronization, best practices, etc.): KhronosValidation, LunargMonitor

**Describe the Issue**

I create some pipelines with dynamic cullMode enabled. I don't use the vkCmdSetCullMode() to set the dynamic value. When I run the application (with validation layers enabled), I don't get any validation errors. The cullMode just seems to default to double-sided. The docs say that, when dynamic cullMode is enabled, that the vkCmdSetCullMode() must be called to set value.

**Expected behavior**

Expected this validation error:
VUID-vkCmdDrawIndexed-None-07840

https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap21.html#VUID-vkCmdDrawIndexed-None-07840

**Valid Usage ID**
VUID-vkCmdDrawIndexed-None-07840

**Additional context**
None

### PR DESCRIPTION
**Pull request by spencer-lunarg**
closes #5764

We were not checking  most of the `VK_EXT_extended_dynamic_state` states that they were being set prior to a draw call

I have positive tests written/ready, just want to get the https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5763 change in first to make use of the `TEST_F` class to hold the common logic

### CODE REVIEW

File: layers/core_checks/cc_cmd_buffer_dynamic.cpp [hunk 1]
```diff
@@ -110,7 +110,19 @@ bool CoreChecks::ValidateDrawDynamicState(const CMD_BUFFER_STATE &cb_state, cons
...
+    skip |= ValidateCBDynamicStatus(cb_state, CB_DYNAMIC_CULL_MODE_SET, cmd_type, vuid.dynamic_cull_mode_07840);
+    skip |= ValidateCBDynamicStatus(cb_state, CB_DYNAMIC_FRONT_FACE_SET, cmd_type, vuid.dynamic_front_face_07841);
+    skip |= ValidateCBDynamicStatus(cb_state, CB_DYNAMIC_PRIMITIVE_TOPOLOGY_SET, cmd_type, vuid.dynamic_primitive_topology_07842);
+    skip |= ValidateCBDynamicStatus(cb_state, CB_DYNAMIC_DEPTH_TEST_ENABLE_SET, cmd_type, vuid.dynamic_depth_test_enable_07843);
+    skip |= ValidateCBDynamicStatus(cb_state, CB_DYNAMIC_DEPTH_WRITE_ENABLE_SET, cmd_type, vuid.dynamic_depth_write_enable_07844);
+    skip |= ValidateCBDynamicStatus(cb_state, CB_DYNAMIC_DEPTH_COMPARE_OP_SET, cmd_type, vuid.dynamic_depth_compare_op_07845);
+    skip |= ValidateCBDynamicStatus(cb_state, CB_DYNAMIC_DEPTH_BOUNDS_TEST_ENABLE_SET, cmd_type,
+                                    vuid.dynamic_depth_bound_test_enable_07846);
+    skip |= ValidateCBDynamicStatus(cb_state, CB_DYNAMIC_STENCIL_TEST_ENABLE_SET, cmd_type, vuid.dynamic_stencil_test_enable_07847);
+    skip |= ValidateCBDynamicStatus(cb_state, CB_DYNAMIC_STENCIL_OP_SET, cmd_type, vuid.dynamic_stencil_op_07848);
```
Comment (juan-lunarg) [inline layers/core_checks/cc_cmd_buffer_dynamic.cpp:123]: IMO a little more clear.

```suggestion
    // VK_EXT_extended_dynamic_state
    {
        skip |= ValidateCBDynamicStatus(cb_state, CB_DYNAMIC_CULL_MODE_SET, cmd_type, 
        ...
        skip |= ValidateCBDynamicStatus(cb_state, CB_DYNAMIC_STENCIL_OP_SET, cmd_type, vuid.dynamic_stencil_op_07848);
    }
```

File: tests/negative/dynamic_state.cpp [hunk 2]
```diff
@@ -3767,3 +3842,77 @@ TEST_F(NegativeDynamicState, SettingCommands) {
...
+    ExtendedDynamicStateDrawNotSet(VK_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE, "VUID-vkCmdDraw-None-07846");
+}
+
+TEST_F(NegativeDynamicState, DrawNotSetStencilTestEnable) {
+    ExtendedDynamicStateDrawNotSet(VK_DYNAMIC_STATE_STENCIL_TEST_ENABLE, "VUID-vkCmdDraw-None-07847");
+}
+
+TEST_F(NegativeDynamicState, DrawNotSetStencilOp) {
+    ExtendedDynamicStateDrawNotSet(VK_DYNAMIC_STATE_STENCIL_OP, "VUID-vkCmdDraw-None-07848");
+}
```
Comment (juan-lunarg) [inline tests/negative/dynamic_state.cpp:3918]: :100:

**Review by juan-lunarg — COMMENTED** [review]
FFTI minor comments. Good job on the testing :+1:

**Review by juan-lunarg — APPROVED** [review]

File: layers/core_checks/cc_cmd_buffer_dynamic.cpp [hunk 3]
```diff
@@ -33,107 +33,147 @@ bool CoreChecks::ValidateCBDynamicStatus(const CMD_BUFFER_STATE &cb_state, CBDyn
...
-    skip |= ValidateCBDynamicStatus(cb_state, CB_DYNAMIC_EXCLUSIVE_SCISSOR_NV_SET, cmd_type, vuid.dynamic_exclusive_scissor_07878);
-    skip |= ValidateCBDynamicStatus(cb_state, CB_DYNAMIC_EXCLUSIVE_SCISSOR_ENABLE_NV_SET, cmd_type,
-                                    vuid.dynamic_exclusive_scissor_enable_07879);
-
-    const auto rp_state = pipeline.RasterizationState();
-    if (rp_state && (rp_state->depthBiasEnable == VK_TRUE)) {
-        skip |= ValidateCBDynamicStatus(cb_state, CB_DYNAMIC_DEPTH_BIAS_SET, cmd_type, vuid.dynamic_depth_bias_07834);
+
+    // VK_EXT_extended_dynamic_state
+    {
```
Comment (ncesario-lunarg) [inline layers/core_checks/cc_cmd_buffer_dynamic.cpp:45]: :100:

File: layers/core_checks/cc_cmd_buffer_dynamic.cpp [hunk 4]
```diff
@@ -33,107 +33,147 @@ bool CoreChecks::ValidateCBDynamicStatus(const CMD_BUFFER_STATE &cb_state, CBDyn
...
+    // VK_EXT_vertex_input_dynamic_state
+    { skip |= ValidateCBDynamicStatus(cb_state, CB_DYNAMIC_VERTEX_INPUT_EXT_SET, cmd_type, vuid.vertex_input_04914); }
+
+    // VK_EXT_color_write_enable
+    {
+        skip |= ValidateCBDynamicStatus(cb_state, CB_DYNAMIC_COLOR_WRITE_ENABLE_EXT_SET, cmd_type,
+                                        vuid.dynamic_color_write_enable_07749);
+    }
+
+    if (const auto *rp_state = pipeline.RasterizationState(); rp_state) {
```
Comment (ncesario-lunarg) [inline layers/core_checks/cc_cmd_buffer_dynamic.cpp:153]: Do all of these checks play nice when `rasterizerDiscardEnable == VK_TRUE`? They _should_, but probably worth adding a test to be sure, especially one that utilizes GPL. I can add one if you prefer.

File: tests/negative/dynamic_state.cpp [hunk 5]
```diff
@@ -15,7 +15,11 @@
 #include "utils/cast_utils.h"
 #include "../framework/layer_validation_tests.h"
 
-class NegativeDynamicState : public VkLayerTest {};
+class NegativeDynamicState : public VkLayerTest {
+  public:
+    // VK_EXT_extended_dynamic_state - not calling vkCmdSet before draw
+    void ExtendedDynamicStateDrawNotSet(VkDynamicState dynamic_state, const char *vuid);
```
Comment (ncesario-lunarg) [inline tests/negative/dynamic_state.cpp:21]: It might be good to indicate this is a helper function used by other tests. I wasn't sure what this was for at first glance.

File: tests/negative/dynamic_state.cpp [hunk 6]
```diff
@@ -513,171 +535,224 @@ TEST_F(NegativeDynamicState, ExtendedDynamicStateEnabled) {
...
+    ASSERT_NO_FATAL_FAILURE(InitState(nullptr, &extended_dynamic_state_features, VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT));
+    ASSERT_NO_FATAL_FAILURE(InitRenderTarget());
 
-    m_errorMonitor->SetDesiredFailureMsg(kErrorBit, "VUID-vkCmdDraw-scissorCount-03418");
-    vk::CmdDraw(commandBuffer.handle(), 1, 1, 0, 0);
-    m_errorMonitor->VerifyFound();
+    VkBufferObj buffer;
+    buffer.init(*m_device, 16, 0, VK_BUFFER_USAGE_VERTEX_BUFFER_BIT);
+    std::vector<VkBuffer> buffers(m_device->props.limits.maxVertexInputBindings + 1ull, buffer.handle());
+    std::vector<VkDeviceSize> offsets(buffers.size(), 0);
```
Comment (ncesario-lunarg) [inline tests/negative/dynamic_state.cpp:573]: These don'ts seem to be used?

**Review by ncesario-lunarg — COMMENTED** [review]
A couple questions/nits, but otherwise LGTM!

File: tests/negative/dynamic_state.cpp (hunk 5 above)
Comment (spencer-lunarg) [reply tests/negative/dynamic_state.cpp:21]: So as we now have this `class NegativeSomething : public VkLayerTest {` inheritance, the idea is we will be adding this functions in there for other tests, in same test group, to use

Will add a comment

File: tests/negative/dynamic_state.cpp (hunk 6 above)
Comment (spencer-lunarg) [reply tests/negative/dynamic_state.cpp:573]: removed these copy-and-paste errors

File: layers/core_checks/cc_cmd_buffer_dynamic.cpp (hunk 4 above)
Comment (spencer-lunarg) [reply layers/core_checks/cc_cmd_buffer_dynamic.cpp:153]: There is a LOT I realized from this change that needs to be improved in the dynamic state, the GPL interaction is just one

Since this PR is not altering the logic of this, would like to defer the testings to a new PR
