### PR TITLE
Fix Spec Constant ID not found

### LINKED ISSUE #2950: Incorrect validation error if API specifies a constant that doesn't exist in the shader
Take the following situation:

- Shader defines constant with id 1
- API specifies values for constants 0 and 1 during pipeline creation

VVL attempts to validate the size of constant 0, which doesn't exist in the shader and produces an error as described [in this comment][1]. This is legal usage per the spec:

> If a `constantID` value is not a specialization constant ID used in the shader, that map entry does not affect the behavior of the pipeline.

[1]: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2903#discussion_r664117108

### PR DESCRIPTION
**Pull request by sfricke-samsung**
Closes #2950

- `GetSpecConstantByteSize` was only used once, so didn't see a need to break it out as own function. Also make logic easier in one place then trying to over-engineer the function
- confirmed in `spirv-val` source what coverage it does (will make sure its a bool/int/float)
- Added `SpecializationUnused` which should cover @ShabbyX use case
- Added some more test in `SpecializationInvalidSizeMismatch` with various spec constant types to confirm change is still working finding the right size

### CODE REVIEW

File: layers/shader_validation.cpp [hunk 1]
```diff
@@ -1758,15 +1758,38 @@ bool CoreChecks::ValidatePipelineShaderStage(VkPipelineShaderStageCreateInfo con
         id_value_map.reserve(specialization_info->mapEntryCount);
         for (auto i = 0u; i < specialization_info->mapEntryCount; ++i) {
             auto const &map_entry = specialization_info->pMapEntries[i];
+            auto itr = module->spec_const_map.find(map_entry.constantID);
```
Comment (ncesario-lunarg) [inline layers/shader_validation.cpp:1761]: I _would_ like to keep the "spirv-parsing-logic" to `shader_module.*` as much as possible. I remember not too long ago "someone" (pretty sure it was you @sfricke-samsung ;)) made a nice change to separate a lot of "spirv-parsing-logic" out of `shader_validation.*` and into `shader_module.*`; if this is clearer, though, I'm good with it.

**Review by ncesario-lunarg — APPROVED** [review]
LGTM, thanks for the quick fix!

File: layers/shader_validation.cpp (hunk 1 above)
Comment (sfricke-samsung) [reply layers/shader_validation.cpp:1761]: ya the separation was me.

I guess I view it as `shader_module` is in charge of building up `spec_const_map` and `shader_validation` is in charge of using it to raise the VUID

**Comment by ShabbyX** [comment]
LGTM! Thanks

File: tests/vklayertests_pipeline_shader.cpp [hunk 2]
```diff
@@ -11016,3 +11016,223 @@ TEST_F(VkLayerTest, SpecializationInvalidSize) {
...
+
+        // float 64 mismatch
+        entries[0].size = 1;
+        CreateComputePipelineHelper::OneshotTest(*this, set_info, kErrorBit, "VUID-VkSpecializationMapEntry-constantID-00776");
+        entries[0].size = 2;
+        CreateComputePipelineHelper::OneshotTest(*this, set_info, kErrorBit, "VUID-VkSpecializationMapEntry-constantID-00776");
+        entries[0].size = 4;
+        CreateComputePipelineHelper::OneshotTest(*this, set_info, kErrorBit, "VUID-VkSpecializationMapEntry-constantID-00776");
+        entries[0].size = 16;
+        CreateComputePipelineHelper::OneshotTest(*this, set_info, kErrorBit, "VUID-VkSpecializationMapEntry-constantID-00776");
```
Comment (ncesario-lunarg) [inline tests/vklayertests_pipeline_shader.cpp:11236]: This appears to be crashing on all platforms (_except_ AMD this time). Haven't investigated very much yet as to what the problem is.

Comment (sfricke-samsung) [reply tests/vklayertests_pipeline_shader.cpp:11236]: I have `int32_t data[4];` so should be enough valid memory to read

Would be willing to add

```
        entries[0].size = 16;
        CreateComputePipelineHelper::OneshotTest(*this, set_info, kErrorBit, "VUID-VkSpecializationMapEntry-constantID-00776");
```

 in a separate PR to investigate if you want to help get the real fix merged in sooner

Comment (ncesario-lunarg) [reply tests/vklayertests_pipeline_shader.cpp]: The problem appears to be the memcpy on line 1797 in `shader_validation.cpp`. The following patch fixes the test for me:
```diff
diff --git a/layers/shader_validation.cpp b/layers/shader_validation.cpp
index a657af3fd..9f8c63dc9 100644
--- a/layers/shader_validation.cpp
+++ b/layers/shader_validation.cpp
@@ -1793,8 +1793,8 @@ bool CoreChecks::ValidatePipelineShaderStage(VkPipelineShaderStageCreateInfo con
             }
 
             if ((map_entry.offset + map_entry.size) <= specialization_info->dataSize) {
-                auto entry = id_value_map.emplace(map_entry.constantID, std::vector<uint32_t>(map_entry.size > 4 ? 2 : 1));
-                memcpy(entry.first->second.data(), specialization_data + map_entry.offset, map_entry.size);
+                const uint32_t* p = reinterpret_cast<const uint32_t*>(specialization_data + map_entry.offset);
+                auto entry = id_value_map.emplace(map_entry.constantID, std::vector<uint32_t>(p, p + map_entry.size));
             }
         }
```
One way or another, it would be nice to see the `memcpy` removed.

Comment (ncesario-lunarg) [reply tests/vklayertests_pipeline_shader.cpp]: I'm not 100% sure this patch is correct. Let's leave this patch out and hold off on the `size == 16` test for now. I created #2955 to track re-adding it and adding a few other test cases in.

**Comment by ncesario-lunarg** [comment]
Latest build failure seems spurious. Re-running.

**Review by ncesario-lunarg — APPROVED** [review]

**Comment by ncesario-lunarg** [comment]
Re-run was successful.
