### PR TITLE
Fix issue 3012

### LINKED ISSUE #3012: Layer warns about swapchain having 0 images if vkGetSwapchainImagesKHR hasn't been called
**Describe the Issue**

When you issue an API call, which involves checking count of swapchain's images (ex. `vkQueuePresentKHR`) before `vkGetSwapchainImagesKHR` has been called on the swapchain, the validation layer will warn about swapchain having 0 images.
<br/>
If you called `vkGetSwapchainImagesKHR` on the swapchain before without once providing a non-null `pSwapchainImages` parameter, validation layer will trigger a page fault on calls, which involve checking swapchain images (ex. `vkQueuePresentKHR`).
<br/>
**Possible reason of the bug**: internal structures of the layer are initialized on `vkGetSwapchainImagesKHR` and not on `vkCreateSwapchainKHR`, so even if valid swapchain object is passed to the layer, it doesn't have valid information about the swapchain.

**Environment:**
 - OS: Windows
 - GPU: NVidia RTX 2060
 - SDK version: 1.2.154.1

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #3012

vkGetSwapchainImagesKHR must be called with non-NULL pSwapchainImages
before calling vkQueuePresentKHR

### CODE REVIEW

File: layers/core_validation.cpp [hunk 1]
```diff
@@ -13616,6 +13616,11 @@ bool CoreChecks::PreCallValidateQueuePresentKHR(VkQueue queue, const VkPresentIn
                     pPresentInfo->pSwapchains[i], validation_error,
                     "vkQueuePresentKHR: pSwapchains[%u] image index is too large (%u). There are only %u images in this swapchain.",
                     i, pPresentInfo->pImageIndices[i], static_cast<uint32_t>(swapchain_data->images.size()));
+            } else if (!swapchain_data->images[pPresentInfo->pImageIndices[i]].image_state) {
```
Comment (ncesario-lunarg) [inline layers/core_validation.cpp:13619]: Should `image_state->acquired` also be checked?

File: tests/vklayertests_wsi.cpp [hunk 2]
```diff
@@ -2067,3 +2067,57 @@ TEST_F(VkLayerTest, PresentIdWaitFeatures) {
...
+    swapchain_info.pQueueFamilyIndices = nullptr;
+    swapchain_info.preTransform = m_surface_capabilities.currentTransform;
+    swapchain_info.compositeAlpha = VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR;
+    swapchain_info.presentMode = m_surface_present_modes[0];
+    swapchain_info.clipped = VK_FALSE;
+
+    vk::CreateSwapchainKHR(device(), &swapchain_info, nullptr, &m_swapchain);
+
+    uint32_t imageCount;
+    vk::GetSwapchainImagesKHR(device(), m_swapchain, &imageCount, nullptr);
```
Comment (ncesario-lunarg) [inline tests/vklayertests_wsi.cpp:2113]: Were you able to reproduce the crash without this call as described in the issue?

**Review by ncesario-lunarg — COMMENTED** [review]
I _think_ this looks good, but adding @jeremyg-lunarg as I think he's been having fun with image states lately.

File: layers/core_validation.cpp (hunk 1 above)
Comment (jeremyg-lunarg) [reply layers/core_validation.cpp:13619]: Yeah I think acquired should be checked too.

File: tests/vklayertests_wsi.cpp (hunk 2 above)
Comment (ziga-lunarg) [reply tests/vklayertests_wsi.cpp:2113]: I think the issue was calling GetSwapchainImagesKHR once, to acquire imageCount, but not calling it the second time with non-NULL pSwapchainImages, which is what this test does. This test would assert on current master.

File: layers/core_validation.cpp (hunk 1 above)
Comment (ziga-lunarg) [reply layers/core_validation.cpp]: I have added that check as well.

**Review by jeremyg-lunarg — APPROVED** [review]

File: tests/vklayertests_wsi.cpp (hunk 2 above)
Comment (ncesario-lunarg) [reply tests/vklayertests_wsi.cpp:2113]: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3012#issuecomment-883095174

I think what you're describing was the original issue, but then they said they can also reproduce the issue without calling `GetSwapchainImagesKHR` even once.

Comment (ncesario-lunarg) [reply tests/vklayertests_wsi.cpp:2113]: :+1: looks like the issue author's account appears to have been deleted, so no need to investigate that further :)

**Review by ncesario-lunarg — APPROVED** [review]
