### PR TITLE
 layers: Improve VUID-VkBindImageMemoryInfo-memory-02629 checking

### LINKED ISSUE #2730: VkMemoryDedicatedAllocateInfo::image at time of vkBindImageMemory
It is unclear whether the image provided in VkMemoryDedicatedAllocateInfo::image at time of vkAllocateMemory needs to remain live at the time of vkBindImageMemory. With dedicatedAllocationImageAliasing feature, I want to "dedicate" the allocation to a worst case _dummy image_ that will be used to vkAllocateMemory, but I will not bind this memory to that image. Instead, new images, smaller or equal in extent to the dummy one, will be created and bound to that memory. This made me think the _dummy image_ could be destroyed immediately after vkAllocateMemory, given that it will not be used any more, but then validation layers report this as violation of VUID-VkBindImageMemoryInfo-memory-02629 when vkBindImageMemory is done. Citing the VUID (emphasis added):
>  If the dedicated allocation image aliasing feature is enabled, and the VkMemoryAllocateInfo provided when memory was allocated included a VkMemoryDedicatedAllocateInfo structure in its pNext chain, and VkMemoryDedicatedAllocateInfo::image was not VK_NULL_HANDLE, then memoryOffset must be zero, and image must be either equal to VkMemoryDedicatedAllocateInfo::image **or an image that was created using the same parameters in VkImageCreateInfo, with the exception that extent and arrayLayers may differ subject to the following restrictions: every dimension in the extent parameter of the image being bound must be equal to or smaller than the original image for which the allocation was created; and the arrayLayers parameter of the image being bound must be equal to or smaller than the original image for which the allocation was created**

I was unable to find any wording in the specification that would suggest that image the allocation was dedicated to has to be kept alive during vkBindMemory which leads me to think doing so is not violation of the above VUID and leaves me confused.

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**
When the dedicatedAllocationImageAliasing is enabled, it should be possible to bind a compatible image to a VkDeviceMemory even after  the original dedicated image is destroyed. Fix this check by caching the dedicated create info in DEVICE_MEMORY_STATE and using this instead  of looking up the dedicated image at bind time.

Update VkLayerTest.DedicatedAllocationImageAliasing to cover it.

Fixes #2730

### CODE REVIEW

File: tests/vklayertests_buffer_image_memory_sampler.cpp [hunk 1]
```diff
@@ -10315,13 +10318,18 @@ TEST_F(VkLayerTest, DedicatedAllocationImageAliasing) {
...
     m_errorMonitor->VerifyFound();
 
     // Bind correctly (depends on the "skip" above)
     m_errorMonitor->ExpectSuccess();
-    vk::BindImageMemory(m_device->handle(), image.handle(), dedicated_image_memory.handle(), 0);
+    vk::BindImageMemory(m_device->handle(), image->handle(), dedicated_image_memory.handle(), 0);
+    m_errorMonitor->VerifyNotFound();
+
+    m_errorMonitor->ExpectSuccess();
+    image = nullptr;  // destroy the original image
```
Comment (ncesario-lunarg) [inline tests/vklayertests_buffer_image_memory_sampler.cpp:10331]: Using `image.reset()` might make it a tiny bit clearer that 1) this is a smart pointer and 2) we're destroying whatever's in it. Purely subjective input on my part.

**Review by ncesario-lunarg — APPROVED** [review]
LGTM!
