### PR TITLE
Fix AddAttachmentUse 

### LINKED ISSUE #2815: Wrong validation error when using the same attachment as input and resolve attachment in the same subpass
**Describe the Issue**
When using the same attachment as resolve attachment and input attachment in the same subpass I’m getting the following validation error:

vkCreateRenderPass2(): subpass 0 uses attachment 2 as both input and resolve attachment. The Vulkan spec states: Any given element of pPreserveAttachments must not also be an element of any other member of the subpass description (https://vulkan.lunarg.com/doc/view/1.2.176.1/windows/1.2-extensions/vkspec.html#VUID-VkSubpassDescription2-pPreserveAttachments-03074)

The preserveAttachmentCount field is 0.

I am not 100% sure if what I am doing here is valid but at least the error that I am getting seems wrong.

**Valid Usage ID**
https://vulkan.lunarg.com/doc/view/1.2.176.1/windows/1.2-extensions/vkspec.html#VUID-VkSubpassDescription2-pPreserveAttachments-03074

**Environment:**
 - OS: Windows and Android
 - GPU: GTX1060, Mali G76, Adreno 620
 - SDK or header version if building from repo: VulkanSDK-1.2.176.1 (Windows)
 - Options enabled (synchronization, best practices, etc.):

**Additional context**

### PR DESCRIPTION
**Pull request by ncesario-lunarg**
Removes the order dependency in CoreChecks::AddAttachmentUse. Also
removes incorrect error report when using the same attachment as a
resolve and input attachment.

Closes #2815.

### CODE REVIEW

File: tests/vkpositivelayertests.cpp [hunk 1]
```diff
@@ -12707,3 +12707,64 @@ TEST_F(VkPositiveLayerTest, DevsimLoaderCrash) {
 
     ASSERT_NO_FATAL_FAILURE(InitFramework(m_errorMonitor));
 }
+
+TEST_F(VkPositiveLayerTest, RenderPassInputResolve) {
+    TEST_DESCRIPTION("Create render pass where input attachment == resolve attachment");
```
Comment (ncesario-lunarg) [inline tests/vkpositivelayertests.cpp:12712]: I couldn't find anything in the spec that specifically prohibits this, though it seems like this could be bad performance-wise?

Comment (jeremyg-lunarg) [reply tests/vkpositivelayertests.cpp:12712]: I can't find anything more authoritative than a reddit thread saying this is allowed. But I feel like I've seen CTS cases that do this.

**Review by jeremyg-lunarg — APPROVED** [review]
Code looks good to me. I'm only 90% sure about the test case.

File: tests/vkpositivelayertests.cpp (hunk 1 above)
Comment (sfricke-samsung) [reply tests/vkpositivelayertests.cpp:12712]: raised https://gitlab.khronos.org/Tracker/vk-gl-cts/-/issues/2931

I checked the spec and I seems valid to me, but also want to confirm there is CTS coverage

**Review by sfricke-samsung — APPROVED** [review]
`AddAttachmentUse` logic is much nicer now
