### PR TITLE
layers: Unwrap device generated commands shader modules

### LINKED ISSUE #3091: VK_NV_device_generated_commands vkCreateGraphicsPipelines crash
**Describe the Issue**
When calling vkCreateGraphicsPipelines with VK_NV_device_generated_commands structure in pNext chain, it crashes with an access violation. After disabling validation layers, everything works fine. 

My pipeline creation code:
https://pastebin.com/KpgWxPVN

**Valid Usage ID**
The application crashes at vkCreateGraphicsPipelines, so there is no Valid Usage ID

**Environment:**
 - OS: Windows 10 / Linux 
 - GPU: NVIDIA GeForce RTX 3080 
 - SDK or header version if building from repo: 1.2.182.0
 - Options enabled (synchronization, best practices, etc.):

**Additional context**

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #3091

### CODE REVIEW

File: layers/layer_chassis_dispatch_manual.cpp [hunk 1]
```diff
@@ -188,6 +188,21 @@ VkResult DispatchCreateGraphicsPipelines(VkDevice device, VkPipelineCache pipeli
                     unwrapped_libs[idx1] = layer_data->Unwrap(link_info->pLibraries[idx1]);
                 }
             }
+
+            auto device_generated_commands =
+                vku::FindStructInPNextChain<VkGraphicsPipelineShaderGroupsCreateInfoNV>(local_pCreateInfos[idx0].pNext);
+            if (device_generated_commands) {
```
Comment (spencer-lunarg) [inline layers/layer_chassis_dispatch_manual.cpp:194]: do we not also `Unwrap` the `VkGraphicsPipelineShaderGroupsCreateInfoNV::pPipelines` handles as well?

I am suprised this whole function is not being generated actually, lots of other `pNext` handles that are probably missing the `Unwrap`

**Review by spencer-lunarg — APPROVED** [review]
created issue to track generating this instead

https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6798
