### PR TITLE
layers: Replace hex values with enum names

### LINKED ISSUE #6841: VUID-VkImageMemoryBarrier2-oldLayout-01209 more description
```
VUID-VkImageMemoryBarrier2-oldLayout-01209(ERROR / SPEC): msgNum: 977395746 - Validation Error: [ VUID-VkImageMemoryBarrier2-oldLayout-01209 ] Object 0: handle = 0x3f36830000000078, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x3a41e022 | vkCmdPipelineBarrier2(): pDependencyInfo->pImageMemoryBarriers[0].newLayout (VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL) is not compatible with VkImage 0x3f36830000000078[] usage flags 0x7. The Vulkan spec states: If srcQueueFamilyIndex and dstQueueFamilyIndex define a queue family ownership transfer or oldLayout and newLayout define an image layout transition, and oldLayout or newLayout is VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL then image must have been created with VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkImageMemoryBarrier2-oldLayout-01209)
```

`0x7` should be expanded to the enum names of the bitfield.

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #6841

### CODE REVIEW

**Review by artem-lunarg — APPROVED** [review]

File: layers/core_checks/cc_cmd_buffer.cpp [hunk 1]
```diff
@@ -1262,8 +1262,7 @@ bool CoreChecks::PreCallValidateCmdExecuteCommands(VkCommandBuffer commandBuffer
                         const auto subresource = image_state->subresource_encoder.Decode(index);
                         skip |= LogError("UNASSIGNED-vkCmdExecuteCommands-commandBuffer-00001", objlist, cb_loc,
                                          "was executed using %s (subresource: aspectMask 0x%x array layer %" PRIu32
-                                         ", "
-                                         "mip level %" PRIu32 ") which expects layout %s--instead, image %s layout is %s.",
+                                         ", mip level %" PRIu32 ") which expects layout %s--instead, image %s layout is %s.",
```
Comment (spencer-lunarg) [inline layers/core_checks/cc_cmd_buffer.cpp:1265]: not sure why your clang-format did this, but it caught this `%" PRIu32 ")` which is wrong, need to make `(%" PRIu32 ")` but I can do in a follow up PR

**Review by spencer-lunarg — APPROVED** [review]
