### PR TITLE
tests: Test creating image view with invalid aspect

### LINKED ISSUE #2500: Assertion failure when running VK-GL-CTS test
**Describe the Issue**
When running the VK-GL-CTS test dEQP-VK.image.mismatched_formats.image_read.d16_unorm_with_r16, the layers (built from source in debug mode) crash with an assertion failure. As of the time I'm writing this, the test [contains a mistake ](https://github.com/KhronosGroup/VK-GL-CTS/blob/b29bf0434c16796dc48a17a52c7fe219d558af31/external/vulkancts/modules/vulkan/image/vktImageMismatchedFormatsTests.cpp#L394) that makes it try to create an image view with the color image aspect for a depth-only image. The layers crash with the following assertion failure:

```
Test case 'dEQP-VK.image.mismatched_formats.image_read.d16_unorm_with_r16'..
Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidImageAspect ] Object 0: handle = 0x80000000008, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x90ef715d | vkCreateImageView(): Depth-only image formats must have the VK_IMAGE_ASPECT_DEPTH_BIT set.
deqp-vk: ../layers/subresource_adapter.h:131: uint32_t subresource_adapter::RangeEncoder::LowerBoundFromMask(VkImageAspectFlags) const: Assertion `mask & limits_.aspectMask' failed.
Aborted (core dumped)
```

**Valid Usage ID**
Prior to the crash, UNASSIGNED-CoreValidation-DrawState-InvalidImageAspect is correctly produced.

**Environment:**
 - OS: Linux
 - GPU: AMD Radeon RX 590 running RADV driver from Mesa master.
 - SDK or header version if building from repo: Building from the repo, commit 79b22370b0b0d6b9258dbb5e74bd671203763c02.
 - Options enabled (synchronization, best practices, etc.):

**Additional context**
Note: there is an in-flight CL to fix validation issues with these tests. When they are removed, the assertion failure will go away too.

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #2500

The CTS test in the issue is not active anymore, but the issues appears to be fixed already.

### CODE REVIEW

File: tests/vklayertests_buffer_image_memory_sampler.cpp [hunk 1]
```diff
@@ -15128,3 +15128,36 @@ TEST_F(VkLayerTest, TestCopyingInterleavedRegions) {
     m_commandBuffer->end();
 
 }
+
+TEST_F(VkLayerTest, CreateColorImageWithDepthAspect) {
+    TEST_DESCRIPTION("Test creating an image with color format but depth aspect.");
+
+    ASSERT_NO_FATAL_FAILURE(InitFramework());
+
+    ASSERT_NO_FATAL_FAILURE(InitState());
```
Comment (ncesario-lunarg) [inline tests/vklayertests_buffer_image_memory_sampler.cpp:15137]: Consolidate to `Init`?

File: tests/vklayertests_buffer_image_memory_sampler.cpp [hunk 2]
```diff
@@ -15128,3 +15128,36 @@ TEST_F(VkLayerTest, TestCopyingInterleavedRegions) {
...
+
+    m_errorMonitor->SetDesiredFailureMsg(kErrorBit, "UNASSIGNED-CoreValidation-DrawState-InvalidImageAspect");
```
Comment (ncesario-lunarg) [inline tests/vklayertests_buffer_image_memory_sampler.cpp:15139]: Can this move to right be fore the call that triggers it?

File: tests/vklayertests_buffer_image_memory_sampler.cpp [hunk 3]
```diff
@@ -15128,3 +15128,36 @@ TEST_F(VkLayerTest, TestCopyingInterleavedRegions) {
     m_commandBuffer->end();
 
 }
+
+TEST_F(VkLayerTest, CreateColorImageWithDepthAspect) {
+    TEST_DESCRIPTION("Test creating an image with color format but depth aspect.");
```
Comment (ncesario-lunarg) [inline tests/vklayertests_buffer_image_memory_sampler.cpp:15133]: Until the default test behavior is changed, might be good to use `ExpectSuccess` and `VerifyNotFound` to ensure no unexpected errors are happening outside the "tested region."

**Review by ncesario-lunarg — COMMENTED** [review]
A few minor nits, but this LGTM!

File: tests/vklayertests_buffer_image_memory_sampler.cpp (hunk 3 above)
Comment (ziga-lunarg) [reply tests/vklayertests_buffer_image_memory_sampler.cpp:15133]: This is why I moved `SetDesiredFailureMsg()` up

**Review by Tony-LunarG — APPROVED** [review]
LGTM once @ncesario-lunarg 's concern are resolved

File: tests/vklayertests_buffer_image_memory_sampler.cpp (hunk 3 above)
Comment (ncesario-lunarg) [reply tests/vklayertests_buffer_image_memory_sampler.cpp:15133]: That's fine for this test since it's pretty small. This is more a reminder we really need to change the default behavior, though.

If this were a larger test, this kind of makes things unnecessarily vague for the next person looking at the code as to _where_ the error is expected to happen. The placement also seems arbitrary; i.e., there are a lot of calls that happen before the SetDesiredFailureMsg (during setup), and while these "setup calls" are "expected to succeed in general," they might not (especially when running this as a single test in a debugging scenario).

Ideally any code that _should not fail_ should be wrapped in `ExpectSuccess`/`VerifyNotFound` and any failures should be wrapped in `SetDesiredFailureMsg`/`VerifyFound`. I realize we're not enforcing this now, but I think we should be. If #3177 were finished, then this wouldn't an issue, but unfortunately that's probably not going get resolved for a while.

**Review by ncesario-lunarg — APPROVED** [review]
