### PR TITLE
Use fresh surface capabilities when validating swapchain creation

### LINKED ISSUE #624: vkCreateSwapChainKHR validation error on out-of-date surface capabilities
Imagine the following scenario:

1. Create xcb window with size WxH.
2. Get surface capabilities (whose currentExtent shows WxH)
3. Create a swapchain with size WxH
4. Resize the window
5. Get new window size with `xcb_get_geometry`: AxB.
6. Recreate swapchain with size AxB.

This results in the following validation error:

```
vkCreateSwapChainKHR() called with imageExtent = (A,B), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (W,H), minImageExtent = (W,H), maxImageExtent = (W,H). The Vulkan spec states: imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)
```

If I add a call to get the surface capabilities (and not use it) between steps 5 and 6, the validation error goes away. My guess is that the capabilities are cached from the last call and are out of date.

Is this expected behavior? Is it not allowed to create a swapchain using sizes that are obtained through other means (which are identical to `currentExtent`) without having queried the surface capabilities?

### PR DESCRIPTION
**Pull request by mark-lunarg**
Validation snapshotted surfaceCaps at the time the app queried them, but this led to bad validation messages when resizing display surfaces.  Validation now queries latest caps at CreateSwapchain-time to narrow the race condition defined by the API.  See the issue for more details.

Also changed the two remaining UNCALLED checks from ERROR to WARNING.

Fixes #624.

### CODE REVIEW

File: layers/core_validation.cpp [hunk 1]
```diff
@@ -11098,138 +11098,137 @@ bool CoreChecks::ValidateCreateSwapchain(const char *func_name, VkSwapchainCreat
...
-        if ((capabilities.maxImageCount > 0) && (pCreateInfo->minImageCount > capabilities.maxImageCount)) {
-            if (log_msg(report_data, VK_DEBUG_REPORT_ERROR_BIT_EXT, VK_DEBUG_REPORT_OBJECT_TYPE_DEVICE_EXT, HandleToUint64(device),
-                        "VUID-VkSwapchainCreateInfoKHR-minImageCount-01272",
-                        "%s called with minImageCount = %d, which is outside the bounds returned by "
-                        "vkGetPhysicalDeviceSurfaceCapabilitiesKHR() (i.e. minImageCount = %d, maxImageCount = %d).",
-                        func_name, pCreateInfo->minImageCount, capabilities.minImageCount, capabilities.maxImageCount))
-                return true;
-        }
+    VkSurfaceCapabilitiesKHR *capabilities = &physical_device_state->surfaceCapabilities;
+    DispatchGetPhysicalDeviceSurfaceCapabilitiesKHR(physical_device_state->phys_device, pCreateInfo->surface, capabilities);
```
Comment (mark-lunarg) [inline layers/core_validation.cpp]: This is the gist of the change -- making the query again and updating the local state.  The rest of the changes are mostly indent diffs.

File: layers/core_validation.cpp [hunk 2]
```diff
@@ -11098,7 +11098,7 @@ bool CoreChecks::ValidateCreateSwapchain(const char *func_name, VkSwapchainCreat
 
     auto physical_device_state = GetPhysicalDeviceState();
     if (physical_device_state->vkGetPhysicalDeviceSurfaceCapabilitiesKHRState == UNCALLED) {
-        if (log_msg(report_data, VK_DEBUG_REPORT_ERROR_BIT_EXT, VK_DEBUG_REPORT_OBJECT_TYPE_PHYSICAL_DEVICE_EXT,
+        if (log_msg(report_data, VK_DEBUG_REPORT_WARNING_BIT_EXT, VK_DEBUG_REPORT_OBJECT_TYPE_PHYSICAL_DEVICE_EXT,
```
Comment (mikes-lunarg) [inline layers/core_validation.cpp]: Good call, none of these are technically invalid

File: layers/core_validation.cpp (hunk 1 above)
Comment (mikes-lunarg) [reply layers/core_validation.cpp]: Should we be saving state in PreCallValidate? Is there any reason to store these if we are going to get a fresh copy each time?

Comment (mikes-lunarg) [reply layers/core_validation.cpp]: Should the other vkGetPhysicalDeviceSurface*State validation dispatch their own queries too?  By changing those UNCALLED errors to warnings we could be masking an actual error if someone uses an unsupported format without querying first.

**Comment by mark-lunarg** [comment]
@mikes-lunarg, I originally did NOT update the surfacecaps state, but that bugged me too.  I think it'd be OK to not save it at all, except there's some settings for protected_capabilities that I was wary of interfering with.  And I'm pretty sure this doesn't make sense for all of the queries -- this particular one manifests easily due to window resizing, but we seem to be OK in other spots and it might even be a bad thing in some cases.  

So, I'm guessing I shouldn't save the caps here at all (though I don't think it'd make a difference) -- what's your preference?

**Comment by mikes-lunarg** [comment]
@mark-lunarg My preference would be to not store the caps.  The protected capabilities code dispatches its own query, and it could be combined with the one you added, but probably isn't worth the extra complexity.

My point about the other queries is that skipping queries is now a warning.  If a user doesn't query they will only get a warning and validation on the results of the query will never run.

**Comment by mark-lunarg** [comment]
made changes suggested by @mikes-lunarg
