### PR TITLE
Guard image access of non-simple bindings

### LINKED ISSUE #2530: syncval: Crash on nullptr deref
**Describe the Issue**
Access violation at synchronization_validation.cpp:890
`Image.fragment_encoder` is null/empty
Fails with commit 1c3d365b
Does not fail with commit 6668e1af
This limits the range to about 7 commits.

**Valid Usage ID**
n/a

**Environment:**
 - OS: Windows 10 
 - GPU: NVIDIA RTX 3070
 - SDK 162 is OK, failing commit given above
 - Options enabled synchronization:

**Additional context**

Call stack:
```
VkLayer_khronos_validation.dll!AccessContext::ImageAddressType(const IMAGE_STATE & image) Line 890 (c:\Users\karl\LunarG\workspaces\Vulkan-ValidationLayers\layers\synchronization_validation.cpp:890)
VkLayer_khronos_validation.dll!SyncOpBarriers::ApplyBarriers<std::vector<SyncImageMemoryBarrier,std::allocator<SyncImageMemoryBarrier> >,SyncOpPipelineBarrierFunctorFactory>(const std::vector<SyncImageMemoryBarrier,std::allocator<SyncImageMemoryBarrier> > & barriers, const SyncOpPipelineBarrierFunctorFactory & factory, const ResourceUsageTag & tag, AccessContext * context) Line 5164 (c:\Users\karl\LunarG\workspaces\Vulkan-ValidationLayers\layers\synchronization_validation.cpp:5164)
VkLayer_khronos_validation.dll!SyncOpPipelineBarrier::Record(CommandBufferAccessContext * cb_context, const ResourceUsageTag & tag) Line 5189 (c:\Users\karl\LunarG\workspaces\Vulkan-ValidationLayers\layers\synchronization_validation.cpp:5189)
VkLayer_khronos_validation.dll!SyncValidator::PreCallRecordCmdPipelineBarrier(VkCommandBuffer_T * commandBuffer, unsigned int srcStageMask, unsigned int dstStageMask, unsigned int dependencyFlags, unsigned int memoryBarrierCount, const VkMemoryBarrier * pMemoryBarriers, unsigned int bufferMemoryBarrierCount, const VkBufferMemoryBarrier * pBufferMemoryBarriers, unsigned int imageMemoryBarrierCount, const VkImageMemoryBarrier * pImageMemoryBarriers) Line 3521 (c:\Users\karl\LunarG\workspaces\Vulkan-ValidationLayers\layers\synchronization_validation.cpp:3521)
VkLayer_khronos_validation.dll!vulkan_layer_chassis::CmdPipelineBarrier(VkCommandBuffer_T * commandBuffer, unsigned int srcStageMask, unsigned int dstStageMask, unsigned int dependencyFlags, unsigned int memoryBarrierCount, const VkMemoryBarrier * pMemoryBarriers, unsigned int bufferMemoryBarrierCount, const VkBufferMemoryBarrier * pBufferMemoryBarriers, unsigned int imageMemoryBarrierCount, const VkImageMemoryBarrier * pImageMemoryBarriers) Line 3504 (c:\Users\karl\LunarG\workspaces\Vulkan-ValidationLayers\layers\generated\chassis.cpp:3504)
```

### PR DESCRIPTION
**Pull request by jzulauf-lunarg**
Restore the SimpleBinding() guards for image address access type and
range generator creation.

h/t @karl-lunarg for finding the missing return... good catch.

Fixes #2530

### CODE REVIEW

File: layers/synchronization_validation.cpp [hunk 1]
```diff
@@ -5144,7 +5146,7 @@ struct SyncOpPipelineBarrierFunctorFactory {
         return (range + base_address);
     }
     ImageRange MakeRangeGen(const IMAGE_STATE &image, const SyncImageMemoryBarrier::SubImageRange &range) const {
-        if (!SimpleBinding(image)) subresource_adapter::ImageRangeGenerator();
+        if (!SimpleBinding(image)) return subresource_adapter::ImageRangeGenerator();
```
Comment (ncesario-lunarg) [inline layers/synchronization_validation.cpp:5149]: Wow, good catch!

**Review by ncesario-lunarg — APPROVED** [review]

**Review by karl-lunarg — APPROVED** [review]
Checks out OK with full PR.
