### PR TITLE
layers: Add missing lock to FormatHandle

### LINKED ISSUE #6802: unguarded concurrent `debugUtilsObjectNameMap` read vs insert causing crashes?
**Environment:**
 - OS: various Windows 10 build nodes and local machines
 - GPU and driver version: mostly NVIDIA, mostly latest GRD, 
 - SDK or header version if building from repo: (downloaded, not built) 1.3.261.1 from https://sdk.lunarg.com/sdk/download/1.3.261.1/windows/VulkanSDK-1.3.261.1-Installer.exe , with runtime from https://sdk.lunarg.com/sdk/download/1.3.261.1/windows/VulkanRT-1.3.261.1-Components.zip
 - Options enabled (synchronization, best practices, etc.): `VK_LAYER_KHRONOS_validation` only; no `VK_EXT_validation_features` etc.

**Describe the Issue**
I'm seeing what I think is `debugUtilsObjectNameMap` inserting/resizing (from `DebugReportSetUtilsObjectName`) out from under a concurrent `find` (from `DebugReportGetUtilsObjectName`).

After seeing similar on a few build nodes and peer's machines, I attempted repro with Application Verifier in play.  I have two stacks (below in Additional context section) from a local run.  The first stack shows the access violation on read, the second shows a thread that is concurrently inserting.

I see a mutex lock on the `DebugReportSetUtilsObjectName` side, but no protection on the `FormatHandle` -> `DebugReportGetUtilsObjectName` side (though I am likely missing things).

**Expected behavior**

No crashes if we `vkSetDebugUtilsObjectNameEXT` concurrently with other commands like `vkCmdDrawIndexed`, `vkCmdBindDescriptorSets`, etc.

**Valid Usage ID**

N/A.

**Additional context**

Faulting stack (`DebugReportGetUtilsObjectName` -> `robin_hood::Table<...>::find`):

```
 	VkLayer_khronos_validation.dll!robin_hood::detail::Table<1,80,unsigned __int64,std::string,robin_hood::hash<unsigned __int64,void>,std::equal_to<unsigned __int64>>::find(const unsigned __int64 & key) Line 1951	C++
 	VkLayer_khronos_validation.dll!_debug_report_data::DebugReportGetUtilsObjectName(const unsigned __int64 object=11862556185284577111) Line 215	C++
 	VkLayer_khronos_validation.dll!_debug_report_data::FormatHandle(const char * handle_type_name=0x00007ffa14686298, unsigned __int64 handle=11862556185284577111) Line 231	C++
 	[Inline Frame] VkLayer_khronos_validation.dll!_debug_report_data::FormatHandle(const VulkanTypedHandle &) Line 242	C++
 	[Inline Frame] VkLayer_khronos_validation.dll!ValidationObject::FormatHandle(const VulkanTypedHandle &) Line 3855	C++
 	VkLayer_khronos_validation.dll!CoreChecks::PreCallValidateCmdBindDescriptorSets(VkCommandBuffer_T * commandBuffer=0x00000001ce651b38, VkPipelineBindPoint pipelineBindPoint=VK_PIPELINE_BIND_POINT_GRAPHICS, VkPipelineLayout_T * layout=0xa4a0440000000757, unsigned int firstSet=2, unsigned int setCount=2, VkDescriptorSet_T * const * pDescriptorSets=0x00007ff4e18ba6e0, unsigned int dynamicOffsetCount=0, const unsigned int * pDynamicOffsets=0x0000000000000000) Line 195	C++
 	VkLayer_khronos_validation.dll!vulkan_layer_chassis::CmdBindDescriptorSets(VkCommandBuffer_T * commandBuffer=0x00000001ce651b38, VkPipelineBindPoint pipelineBindPoint=VK_PIPELINE_BIND_POINT_GRAPHICS, VkPipelineLayout_T * layout=0xa4a0440000000757, unsigned int firstSet=2, unsigned int descriptorSetCount=2, VkDescriptorSet_T * const * pDescriptorSets=0x00007ff4e18ba6d8, unsigned int dynamicOffsetCount=0, const unsigned int * pDynamicOffsets=0x0000000000000000) Line 3006	C++
>	vtest.exe!vgpu_vk_cmd_bind_descriptor_sets(_vgpu_command_buffer_t * command_buffer=0x00000001cc5b7f38, _vgpu_pipeline_t * pipeline=0x000000019e89b9a8, _vgpu_pipeline_bind_e bind_point=k_vgpu_pipeline_bind_graphics, _vgpu_descriptor_set_t * * descriptor_sets=0x00007ff4e18ba6d0, unsigned int first_set=1, unsigned int set_count=3) Line 9462	C
 	[Inline Frame] vtest.exe!vgpu_cmd_bind_descriptor_sets(_vgpu_command_buffer_t *) Line 488	C
 	vtest.exe!_vrender_execute_one_draw(__vrender_render_pass_execute_data_t * pass_data=0x000000005a446688, __vrender_traversal_result_t * td=0x00000001bb36cfb8, _vgpu_command_buffer_t * cbuf=0x00000001cc5b7f38, bool needs_lightgrid=false) Line 498	C
 	vtest.exe!_vrender_execute_render_pass(__vrender_render_pass_execute_data_t * pass_data=0x000000005a446688, _vgpu_command_buffer_t * cbuf=0x00000001cc5b7f38) Line 403	C
 	vtest.exe!_vrender_execute_render_passes(void * data=0x000000005a446688) Line 91	C
 	vtest.exe!_job_fiber_worker(void * data=0x000000006b8ac980) Line 2558	C
 	vtest.exe!_fiber_entry(_vfiber_t * fiber=0x000000006b8b6f38) Line 317	C
 	vtest.exe!_fiber_startup() Line 154	Unknown
```

Another thread, nearby, attempting to set an object name (`DebugReportSetUtilsObjectName` -> `robin_hood::Table<...>::operator[]` -> `insertKeyPrepareEmptySpot`):

```
 	 	[External Code]	
 	VkLayer_khronos_validation.dll!robin_hood::detail::Table<1,80,QFOBufferTransferBarrier,CMD_BUFFER_STATE const *,hash_util::HasHashMember<QFOBufferTransferBarrier>,std::equal_to<QFOBufferTransferBarrier>>::initData(unsigned __int64 max_elements) Line 2329	C++
 	VkLayer_khronos_validation.dll!robin_hood::detail::Table<1,80,unsigned __int64,std::string,robin_hood::hash<unsigned __int64,void>,std::equal_to<unsigned __int64>>::rehashPowerOfTwo(unsigned __int64 numBuckets, bool) Line 2226	C++
 	VkLayer_khronos_validation.dll!robin_hood::detail::Table<1,80,unsigned __int64,std::string,robin_hood::hash<unsigned __int64,void>,std::equal_to<unsigned __int64>>::insertKeyPrepareEmptySpot<unsigned __int64 const &>(const unsigned __int64 & key=10258478671522173324) Line 2348	C++
 	VkLayer_khronos_validation.dll!robin_hood::detail::Table<1,80,unsigned __int64,std::string,robin_hood::hash<unsigned __int64,void>,std::equal_to<unsigned __int64>>::operator[]<std::string>(const unsigned __int64 & key=10258478671522173324) Line 1732	C++
 	[Inline Frame] VkLayer_khronos_validation.dll!_debug_report_data::DebugReportSetUtilsObjectName(const VkDebugUtilsObjectNameInfoEXT *) Line 197	C++
 	VkLayer_khronos_validation.dll!vulkan_layer_chassis::SetDebugUtilsObjectNameEXT(VkDevice_T * device=0x00000000f5aed688, const VkDebugUtilsObjectNameInfoEXT * pNameInfo=0x00007ff4e187a3b0) Line 10072	C++
 	vulkan-1.dll!SetDebugUtilsObjectNameEXT(VkDevice_T * device, const VkDebugUtilsObjectNameInfoEXT * pNameInfo) Line 5486	C
 	[Inline Frame] vtest.exe!_vgpu_set_obj_name(_vgpu_vk_impl_t * object, unsigned __int64 name, VkObjectType) Line 1723	C
 	vtest.exe!_create_render_pass_frame_data(_vgpu_vk_impl_t * vgpu=0x000000006f7ac158, _vgpu_vk_swapchain_impl_t * rp_swap=0x00000000c8216c38, _vgpu_vk_render_pass_impl_t * render_pass=0x00000000c5f3abb8) Line 5952	C
 	vtest.exe!vgpu_vk_cmd_begin_render_pass(_vmem_t * allocator=0x00007ff4e1960000, _vgpu_command_buffer_t * command_buffer=0x0000000139bf9f38, _vgpu_render_pass_t * render_pass=0x00000000c5f3abb8, _vgpu_swapchain_t * swapchain=0x00000000c8216c38, _vgpu_viewport_t viewport, _vgpu_scissor_t scissor) Line 9158	C
>	[Inline Frame] vtest.exe!vgpu_cmd_begin_render_pass(_vmem_t *) Line 478	C
 	vtest.exe!_vrender_execute_render_pass(__vrender_render_pass_execute_data_t * pass_data=0x000000005a446b98, _vgpu_command_buffer_t * cbuf=0x0000000139bf9f38) Line 233	C
 	vtest.exe!_vrender_execute_render_passes(void * data=0x000000005a446b98) Line 91	C
 	vtest.exe!_job_fiber_worker(void * data=0x000000006b8ac9f0) Line 2558	C
 	vtest.exe!_fiber_entry(_vfiber_t * fiber=0x000000006b8b7078) Line 317	C
 	vtest.exe!_fiber_startup() Line 154	Unknown
```

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #6802

### CODE REVIEW

File: layers/error_message/logging.h [hunk 1]
```diff
@@ -229,6 +229,7 @@ typedef struct _debug_report_data {
     }
 
     std::string FormatHandle(const char *handle_type_name, uint64_t handle) const {
+        std::unique_lock<std::mutex> lock(debug_output_mutex);
```
Comment (artem-lunarg) [inline layers/error_message/logging.h:232]: Suggestion to lock `GetUtilsObjectName`  \ `GetMarkerObjectName` instead (skipped DebugReport prefix), similar to `SetUtilsObjectName` \ `SetMarkerObjectName` . Makes implementation more uniform and will allow to re-use in other places. `DebugReportGetUtilsObjectName` is already has another use.

Hopefully no double locking happens with another use of the mutex, but if does, might be another opportunity to improve design.

**Review by jeremyg-lunarg — APPROVED** [review]

File: layers/error_message/logging.h (hunk 1 above)
Comment (ziga-lunarg) [reply layers/error_message/logging.h:232]: At first I tried to put the locks in `GetUtilsObjectName` and `GetMarkerObjectName`, but yes, double locking occurs. Maybe we would want a separate lock just for `debugObjectNameMap`?

Comment (artem-lunarg) [reply layers/error_message/logging.h:232]: Maybe, I did not check if there's a reason that `debugUtilsObjectNameMap` and `debugObjectNameMap` use the same lock.

**Review by artem-lunarg — APPROVED** [review]

**Review by spencer-lunarg — APPROVED** [review]
