### PR TITLE
layers: Check if zero allocation size is allowed

### LINKED ISSUE #4060: VUID-VkMemoryAllocateInfo-allocationSize-00638(ERROR / SPEC): when using VkImportMemoryWin32HandleInfoKHR
**Describe the Issue**
I'm importing a ```ID3D12Resource``` into Vulkan, and for that I'm using a ```VkImportMemoryWin32HandleInfoKHR```, I get a validation message:
```
VUID-VkMemoryAllocateInfo-allocationSize-00638(ERROR / SPEC): msgNum: 830614613 - Validation Error: [ VUID-VkMemoryAlloc
ateInfo-allocationSize-00638 ] Object 0: handle = 0x165cdd30040, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x31822c55
| vkAllocateMemory: allocationSize is 0. The Vulkan spec states: allocationSize must be greater than 0 (https://vulkan.l
unarg.com/doc/view/1.3.211.0/windows/1.3-extensions/vkspec.html#VUID-VkMemoryAllocateInfo-allocationSize-00638)
    Objects: 1
        [0] 0x165cdd30040, type: 3, name: NULL
```

**The spec says:**
If the parameters define an import operation and the external handle type is ```VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_BIT```, ```VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_KMT_BIT```, or ```VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_RESOURCE_BIT```, ```allocationSize``` is ignored. The implementation must query the size of these allocations from the OS.

So in my opinion it must be valid to let ```allocationSize``` be 0.

My code example:
```CPP
VkImportMemoryWin32HandleInfoKHR import_memory_win32_handle_info = {
    .sType = VK_STRUCTURE_TYPE_IMPORT_MEMORY_WIN32_HANDLE_INFO_KHR,
    .handleType = VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_RESOURCE_BIT,
    .handle = handle
};
VkMemoryAllocateInfo memory_allocate_info = {
    .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
    .pNext = &import_memory_win32_handle_info
};

VkDeviceMemory memory;
throw_if_failed(vkAllocateMemory(device, &memory_allocate_info, nullptr, &memory), "vkAllocateMemory");
```

**Environment:**
 - OS: Windows 10
 - GPU: NVIDIA GeForce RTX 3090
 - SDK or header version if building from repo: 1.3.204.0
 - Options enabled (synchronization, best practices, etc.): /

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #4060 

Don't think I can write a test for that, but the change is simple.

### CODE REVIEW

File: layers/core_validation.cpp [hunk 1]
```diff
@@ -5042,9 +5069,9 @@ bool CoreChecks::PreCallValidateAllocateMemory(VkDevice device, const VkMemoryAl
     if (IsExtEnabled(device_extensions.vk_android_external_memory_android_hardware_buffer)) {
         skip |= ValidateAllocateMemoryANDROID(pAllocateInfo);
     } else {
-        if (0 == pAllocateInfo->allocationSize) {
+        if (!IsZeroAllocationSizeAllowed(pAllocateInfo) && 0 == pAllocateInfo->allocationSize) {
```
Comment (ncesario-lunarg) [inline layers/core_validation.cpp:5072]: Is this the only place this needs to be made? grepping for `allocationSize`, it looks like there are a lot of references (mostly in core, but some in BP).

**Review by ncesario-lunarg — COMMENTED** [review]
This LGTM, though I'm not sure if the added check needs to be in more places?

As for testing, can something similar to https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/31d112a3a5567886b812efc43cd68e1c5f1e385e/tests/positive/image_buffer.cpp#L1141 be used?

**Comment by ziga-lunarg** [comment]
> This LGTM, though I'm not sure if the added check needs to be in more places?
> 
> As for testing, can something similar to
> 
> https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/31d112a3a5567886b812efc43cd68e1c5f1e385e/tests/positive/image_buffer.cpp#L1141
> 
> be used?

Tried to write a test, but it crashes in the driver without any VUIDs being reported.

**Review by ncesario-lunarg — APPROVED** [review]
