### PR TITLE
chassis: Remove tls caching of device/instance state

### LINKED ISSUE #9181: Sporadic crashes with ANGLE tests
**Environment:**
 - OS: Android
 - GPU and driver version: Pixel 4 and Pixel 6.
 - SDK or header version if building from repo:
 - Options enabled (synchronization, best practices, etc.):

**Describe the Issue**

Sporadic crashes with the ANGLE tests below since `3d4d51952c44d435345d781adc4597697676d43c`.   The associated commit is [this change](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/3d4d51952c44d435345d781adc4597697676d43c).    

Some notes:
- The previous commit `bed9aacefede19795cc0c5849ce31d0825e0b206` passed ~600 times without a crash.
- The crashed test cases could vary, but we've observed the below cases during bisecting:

| Test Name                                                                            | Count |
| ------------------------------------------------------------------------------------ | ----- |
| EGLMemoryUsageReportTest.BasicQuery/ES3_Vulkan                                       |    22 |
| EGLPreRotationBlitFramebufferTest.BlitColorFromDefault/ES2_Vulkan_NoFixture__PreRotationDisabled |    16 |
| EGLSurfacelessContextTest.Switcheroo/ES2_Vulkan_NoFixture                            |     8 |
| AtomicCounterBufferTest.AtomicCounterBufferBindings/ES3_Vulkan                       |     4 |
| BindUniformLocationTest.ConflictsDetection/ES2_Vulkan                                |     2 |

```sh
#!/bin/bash
# use --gtest_repeat to control the # of runs.  50 should be enough to see at least 1 crash.
autoninja -C out/Android angle_end2end_tests && out/Android/angle_end2end_tests --gtest_filter=GLSLTest.MaxVaryingVec3AndOneFloat/ES3_Vulkan:FramebufferTest_ES3.SampleFromAttachedTextureWithDifferentLODAndFBOSwitch/ES3_Vulkan_EmulatedPrerotation270:VertexAttributeTest.UnsignedShortNormalized/ES2_Vulkan:PbufferTest.UseAsFramebufferColorThenDeferredDestroy/ES2_Vulkan:GLSLTest.NestedCompoundStructsWithSamplersAsFunctionArg/ES3_Vulkan_AvoidOpSelectWithMismatchingRelaxedPrecision:EGLContextCompatibilityTest.PbufferSameConfig/Vulkan_R5G6B5D24S8:BlitFramebufferTest.BlitFramebufferSizeOverflow2/ES3_Vulkan_EmulatedPrerotation180:Texture2DTest.CopySubImageFloat_RGB_RGB/ES2_Vulkan:MultisampledRenderToTextureTest.ScissoredDrawTest/ES3_1_Vulkan:MaterialsTest.SetParameters/ES1_Vulkan:GLSLTest.MaxVaryingVec4/ES3_Vulkan_AvoidOpSelectWithMismatchingRelaxedPrecision:FramebufferTest_ES3.ResizeTextureLargeToSmall/ES3_Vulkan_EnableParallelCompileAndLink:OcclusionQueriesTest.MultiContext/ES3_Vulkan_EnableParallelCompileAndLink:FramebufferTest_ES3.ClearIncompatibleAttachments/ES3_Vulkan_EmulatedPrerotation90:GLSLTest_ES3.NonScalarEqualOperator/ES3_Vulkan_AvoidOpSelectWithMismatchingRelaxedPrecision:EGLPreRotationBlitFramebufferTest.BlitColorFromDefault/ES2_Vulkan_NoFixture__PreRotationDisabled:FramebufferFetchES31.DrawWithAndWithoutDepthAndStencilAndColorMSAA/ES3_1_Vulkan:IncompatibleTextureTest.Test/ES3_Vulkan_EnableParallelCompileAndLink__SamplerTypeShadow_TextureTypeSignedNormalized_TextureCompareModeRef:CopyTextureVariationsTest.CopySubTextureRectangle/ES2_Vulkan__LAToRGBPremultiplyAlpha:GLSLTest.VectorAndMatrixScalarizationDoesNotAffectRendering/ES2_Vulkan:SimpleStateChangeTestES3.ReadFramebufferDrawFramebufferDifferentAttachments/ES3_Vulkan:CompressedTextureASTCTest.Test/ES2_Vulkan__RGBA_ASTC_5x5:WebGL2ValidationStateChangeTest.AttachmentTypeRedefinition/ES3_Vulkan_EnableParallelCompileAndLink:GLSLTest.InvariantAllBoth/ES3_Vulkan_NoSupportsSPIRV14:DrawElementsTest.DeleteVertexArrayAndUploadIndex/ES3_Vulkan:VulkanPerformanceCounterTest.MaskedColorClearDoesNotBreakRenderPass/ES3_Vulkan_PadBuffersToMaxVertexAttribStride:Texture2DTestES3.TextureBaseMaxLevelRoundingValidation/ES3_Vulkan_EnableParallelCompileAndLink:GLSLTest_ES3.TooManyFieldsInStruct/ES3_Vulkan_ForceInitShaderVariables:MultisampledRenderToTextureES3Test.RenderbufferClearDrawCopyThenBlendWithDepthStencilSameProgram/ES3_Vulkan_NoSupportsExtendedDynamicState2_RobustResourceInit:GLSLTest.MaxVaryingVec3Array/ES3_Vulkan:PixelLocalStorageTest.ImplementationDependentLimits/ES3_Vulkan_EmulatePixelLocalStorage:UniformBlockWithOneLargeArrayMemberTest.MemberTypeIsMatrixAndInstanced/ES3_Vulkan_EnableParallelCompileAndLink:FramebufferTest_ES3.RenderAndInvalidateImmutableTextureWithSubImageWithBeyondMaxLevel/ES3_Vulkan_EmulatedPrerotation180:GLSLTest_ES31.NegativeIOBlocksLinkMemberArraySizeMismatch/ES3_1_Vulkan:FramebufferTest_ES3.3DAttachmentInvalidLayer/ES3_Vulkan_EmulatedPrerotation180:RobustResourceInitTestES31.Multisample2DTextureArray/ES3_1_Vulkan_AllocateNonZeroMemory:VulkanPerformanceCounterTest.DepthStencilInvalidateAndClear/ES3_Vulkan:BlendIntegerTest.MRTSigned/ES3_Vulkan:ShadingRateQcomTest.Basic/ES2_Vulkan:WebGLCompatibilityTest.DrawArraysBufferOutOfBoundsInstancedANGLE/ES3_Vulkan_EnableParallelCompileAndLink:BlitFramebufferTest.drawBlitAndDrawAgain/ES3_Vulkan_EmulatedPrerotation180:CopyTextureVariationsTest.CopySubTexture/ES2_Vulkan__AToBGRAFlipYUnmultiplyAlpha:GLSLTest.NamelessScopedStructs/ES3_Vulkan:CopyTextureVariationsTest.CopyTexture/ES2_Vulkan__BGRAToBGRAFlipYPremultiplyAlphaUnmultiplyAlpha:ShadowSamplerFunctionTextureCubeArrayTest.Test/ES3_1_Vulkan__Texture_Mipmapped:GLSLTest.EmbeddedStructUniform/ES3_Vulkan_EnableParallelCompileAndLink:MultisampledRenderToTextureWithAdvancedBlendTest.RenderbufferClearThenDraw/ES3_Vulkan_NoSupportsSPIRV14_RobustResourceInit:CopyTextureVariationsTest.CopySubTextureRectangle/ES2_Vulkan__RGBToRGBFlipYPremultiplyAlpha:Texture3DTestES3.PixelUnpackStateTexSubImage/ES3_Vulkan_EnableParallelCompileAndLink:PixelLocalStorageTestES31.ImplicitDisables_TextureAttachments/ES3_1_Vulkan_EmulatePixelLocalStorage:WebGLCompatibilityTest.DrawArraysBufferOutOfBoundsNonInstanced/ES3_Vulkan:PbufferTest.BindTexImagePbufferReleaseWhileBoundToFBOColorBuffer/ES2_Vulkan:EGLChooseConfigTest.Defaults/ES2_Vulkan:BlitFramebufferTest.BlitFramebufferSizeOverflow2/ES3_Vulkan_DisableFlippingBlitWithCommand:CompressedTextureSamplerASTCSliced3DTest.Test/ES2_Vulkan__SRGB8_ALPHA8_ASTC_12x12:CopyTextureVariationsTest.CopyTexture/ES2_Vulkan__RGBToRGBFlipYUnmultiplyAlphaMesaYFlip:StateChangeTestES3.SampleCoverageFramebufferAttachmentSwitch/ES3_Vulkan_NoUsePrimitiveRestartEnableDynamicState:GLSLTest_ES3.NameWithWebgl/ES3_Vulkan_ForceInitShaderVariables:DepthWriteTest.Test/ES2_Vulkan__DepthRangeFull_Clipped_VertexDepthInsideClipVolume_FragmentDepthPassthrough_Depth16Unorm:LineLoopPrimitiveRestartXfbTest.OneVertexBeforeRestartIndex/ES3_2_Vulkan:CopyTextureVariationsTest.CopySubTextureRectangle/ES2_Vulkan__LAToSRGBAPremultiplyAlphaMesaYFlip:WebGLCompatibilityTest.EnableExtensionTextureLOD/ES2_Vulkan:ClearTestES3.ClearStencilWithNonOverlappingWriteMaskAndReferenceBits/ES3_Vulkan_EnableParallelCompileAndLink:LightsTest.NegativeInvalidValue/ES1_Vulkan_EnableParallelCompileAndLink:GetImageTestES31.Texture3D/ES3_1_Vulkan:CopyTextureVariationsTest.CopySubTexture/ES2_Vulkan__RGBToRGBA:ProgramInterfaceTestES31.GetProgramInterface/ES3_1_Vulkan__cached:Texture2DTestES3.TexStorage2DMultipleYuvSamplersSwitchBoundTextures/ES3_Vulkan:GLSLTest.StructEmptyDeclaratorBug/ES3_Vulkan_AvoidOpSelectWithMismatchingRelaxedPrecision:TextureMultisampleArrayTest.MultiSampleArrayTexImage/ES3_Vulkan:SimpleStateChangeTestES3.InvalidateThenGenerateMipmapsThenBlend/ES3_Vulkan:TextureCubeTestES3.IncompatibleLayerAThenCompatibleLayerB/ES3_Vulkan_EnableParallelCompileAndLink:EGLContextSharingTest.DeleteReaderOfSharedTexture/ES2_Vulkan:DepthWriteTest.Test/ES3_Vulkan__DepthRangeFull_Clipped_VertexDepthGreaterThanOne_FragmentDepthUnused_Depth16Unorm:GLSLTest.InvariantVaryingIn/ES3_Vulkan_AvoidOpSelectWithMismatchingRelaxedPrecision:CopyTextureTestES3.SwizzleOnSource/ES3_Vulkan_EnableParallelCompileAndLink:ReadPixelsTextureTest.MipLayerAttachment3D/ES3_Vulkan:CopyTextureVariationsTest.CopySubTexture/ES2_Vulkan__BGRAToRGBFlipY:MipmapTestES3.GenerateMipmapZeroSize/ES3_Vulkan:GetImageTest.CompressedTexImageNegativeAPI/ES3_Vulkan:VertexAttributeTestES31.OnlyUpdateBindingByBindVertexBuffer/ES3_1_Vulkan_NoUseVertexInputBindingStrideDynamicState_NoSupportsGraphicsPipelineLibrary:GeometryShaderTest.ReferencedByGeometryShader/ES3_1_Vulkan_EmulatedPrerotation180:GLSLTest_ES3.InvariantVaryingBoth/ES3_Vulkan_EnableParallelCompileAndLink:FragDepthRedeclarationTest.Less/ES3_Vulkan:MipmapTestES3.BaseLevelTextureBug/ES3_Vulkan:FramebufferTest_ES3.ScissoredDrawSubInvalidateThenNonScissoredDraw/ES3_Vulkan_EmulatedPrerotation270:WebGL2CompatibilityTest.InstancedDrawZeroDivisor/ES3_Vulkan_EnableParallelCompileAndLink:MultisampleResolveTest.ResolveD16Samples/ES3_Vulkan_PreferDrawClearOverVkCmdClearAttachments:ViewportTest.FullWindow/ES2_Vulkan:CopyTextureVariationsTest.CopySubTextureRectangle/ES2_Vulkan__LAToSRGBAPremultiplyAlphaUnmultiplyAlpha:UniformTest.Sampler/ES3_Vulkan:VulkanPerformanceCounterTest.ChangingUBOsHitsDescriptorSetCache/ES3_Vulkan:BlitFramebufferTest.MultisampleDepthClear/ES3_Vulkan_EmulatedPrerotation180:PackUnpackTest.PackUnpackSnormOverflow/ES3_Vulkan:CopyTextureVariationsTest.CopyTextureRectangle/ES2_Vulkan__BGRAToSRGBAFlipY:IncompatibleTextureTest.Test/ES3_Vulkan_EnableParallelCompileAndLink__SamplerTypeFloat_TextureTypeUnsignedInteger_TextureCompareModeNone:Texture2DTestES3.TexStorage2DSimultaneousUseOfMultipleYuvSourcesNoData/ES3_Vulkan_EnableParallelCompileAndLink:RobustBufferAccessBehaviorTest.DrawElementsIndexOutOfRangeWithStaticDraw/ES3_Vulkan_NoFixture:StateChangeTestES3.BlitFramebufferSync/ES3_Vulkan_NoUsePrimitiveRestartEnableDynamicState:BufferSubDataTest.MapInvalidateThenBufferSubData/ES3_Vulkan__BufferSubData:CopyTextureVariationsTest.CopyTextureRectangle/ES2_Vulkan__RGBToBGRAFlipYPremultiplyAlphaMesaYFlip:CopyTextureVariationsTest.CopyTextureRectangle/ES2_Vulkan__LToRGBFlipYUnmultiplyAlphaMesaYFlip:DepthWriteTest.Test/ES3_Vulkan__DepthRangeFull_Clamped_VertexDepthLessThanMinusOne_FragmentDepthUnused_Depth32Float:Texture2DDepthStencilTestES3.TexSampleModesWithStencil8Swizzled/ES3_Vulkan_EnableParallelCompileAndLink:EXTBlendFuncExtendedDrawTestES3.FragmentArrayOutputLocationsInShader/ES3_Vulkan:Texture2DTestES3Foveation.DrawChangeFoveationParametersThenDraw/ES3_Vulkan_EnableParallelCompileAndLink:RobustResourceInitTest.UninitializedPartsOfCopied2DTexturesAreBlack/ES2_Vulkan_AllocateNonZeroMemory:CopyTextureVariationsTest.CopyTextureRectangle/ES2_Vulkan__AToRGBFlipYUnmultiplyAlpha:VertexAttributeTest.UnsignedPacked1010102ExtensionUnnormalized/ES3_Vulkan_EnableParallelCompileAndLink:SimpleOperationTest.LinkProgramWithUniforms/ES3_Vulkan:ColorMaskTest.AMDZeroColorMaskBug/ES3_Vulkan:DepthWriteTest.Test/ES3_Vulkan__DepthRangeFull_Clipped_VertexDepthGreaterThanOne_FragmentDepthUnused_Depth32Float:CopyTextureVariationsTest.CopyTextureRectangle/ES2_Vulkan__AToRGBFlipYPremultiplyAlpha:ComputeShaderTest.ImageLoadMipmapSlice/ES3_1_Vulkan:CopyTextureTestES3.InvalidateBlitThenBlend1000Layers/ES3_Vulkan:MaskedScissoredClearTest.Test/ES3_Vulkan_EnableParallelCompileAndLink__clear_cs_mask_cs:CompressedTextureASTCTest.Test/ES3_Vulkan_EnableParallelCompileAndLink__RGBA_ASTC_12x12:SixteenBppTextureTestES3.RGBA4UploadRGBA8/ES3_Vulkan_EnableParallelCompileAndLink:MultisampleResolveTest.ResolveD24Samples/ES3_Vulkan_EmulatedPrerotation90:UniformBlockWithOneLargeArrayMemberTest.MemberTypeIsMixStructFloatAndMat4/ES3_Vulkan_EnableParallelCompileAndLink:SimpleOperationTest.DrawElementsLineLoopUsingUByteClientSideMemory/ES3_Vulkan:GeometryShaderTest.LayeredFramebufferCompletenessWithDepthAttachment/ES3_1_Vulkan_EmulatedPrerotation180:DepthWriteTest.Test/ES3_Vulkan_EnableParallelCompileAndLink__DepthRangeFull_Clipped_VertexDepthInsideClipVolume_FragmentDepthPassthrough_Depth32Float:GLSLTest.StructSpecifiersUniforms/ES3_Vulkan_AvoidOpSelectWithMismatchingRelaxedPrecision:EGLMemoryUsageReportTest.BasicQuery/ES3_Vulkan:CopyTextureVariationsTest.CopyTextureRectangle/ES2_Vulkan__BGRAToBGRAFlipYPremultiplyAlphaUnmultiplyAlpha:ShadowSamplerFunctionTextureCubeTest.Test/ES3_Vulkan_EnableParallelCompileAndLink__TextureLod_NonMipmapped:DepthWriteTest.Test/ES3_Vulkan__DepthRangeFull_Clamped_VertexDepthGreaterThanOne_FragmentDepthPassthrough_Depth32Float:GLSLTest.MaxMinusTwoVaryingVec2PlusOneSpecialVariable/ES3_Vulkan_AvoidOpSelectWithMismatchingRelaxedPrecision:FramebufferTest_ES3.ScissoredDrawSubInvalidateThenNonScissoredDraw/ES3_Vulkan_EnableParallelCompileAndLink:DepthWriteTest.Test/ES3_Vulkan_EnableParallelCompileAndLink__DepthRangeFull_Clipped_VertexDepthLessThanMinusOne_FragmentDepthNegative_Depth16Unorm:GLSLTest.ArrayOfStructsWithSamplersAsFunctionArg/ES3_Vulkan_EnableParallelCompileAndLink:ClipDistanceAPPLETest.OutOfRangeArraySize/ES3_Vulkan_EnableParallelCompileAndLink:ClipCullDistanceTest.Pruned/ES3_Vulkan__ANGLE:Texture2DTestES3.TextureRGB9E5ImplicitAlpha1/ES3_Vulkan:BlitFramebufferANGLETest.BlitStencilWithMesaYFlip/ES2_Vulkan:WebGLCompatibilityTest.GenerateMipmapUnsizedFloatingPointTexture/ES2_Vulkan:PixelLocalStorageTest.ClearValues_rgba8/ES3_Vulkan_EmulatePixelLocalStorage:CopyTextureVariationsTest.CopySubTexture/ES2_Vulkan__RGBAToRGB:StateChangeTestES31.SampleShading/ES3_1_Vulkan:MultisampledRenderToTextureES31Test.MixedMultisampledAndMultisampledRenderToTexture/ES3_1_Vulkan:ComputeShaderTest.DispatchComputeWithRenderingProgram/ES3_1_Vulkan:GLSLTest.DefinedInMacroSucceeds/ES3_Vulkan_NoSupportsSPIRV14:RobustResourceInitTestES3.ReadingOutOfBoundsCopiedTextureWithUnpackBuffer/ES3_Vulkan:VulkanExternalImageTest.TextureFormatCompatChromiumFd/ES2_Vulkan:GLSLTest.StructWithInitializer/ES3_Vulkan:RobustResourceInitTestES3.CheckDepthStencilRenderbufferIsCleared/ES3_Vulkan:GLSLTest_ES31.MixedRowAndColumnMajorMatrices/ES3_1_Vulkan_ForceInitShaderVariables:EGLSurfacelessContextTest.Switcheroo/ES2_Vulkan_NoFixture:BlitFramebufferTest.BlitMultisampleStencilToDefault/ES3_Vulkan_EmulatedPrerotation180:TransformFeedbackTest.PackingBug/ES3_Vulkan_NoSupportsTransformFeedbackExtension:CopyTextureVariationsTest.CopySubTextureRectangle/ES2_Vulkan__LToSRGBAFlipYMesaYFlip:FramebufferFetchES31.MultipleRenderTarget_NonCoherent_FragData/ES3_1_Vulkan:CopyTextureVariationsTest.CopyTextureRectangle/ES2_Vulkan__RGBAToRGB:ClearTestES3.RepeatedStencilClearWithBlitAfterClearAndDrawInBetween/ES3_Vulkan_EnableParallelCompileAndLink:GLSLTest.FrontFacingAndVarying/ES3_Vulkan_AvoidOpSelectWithMismatchingRelaxedPrecision:ClipCullDistanceTest.UnusedFragmentVaryingNoCrash/ES3_1_Vulkan__ANGLE:MultiviewRenderDualViewTest.DrawElements/ES3_1_Vulkan__multiview_layered_samples_2:RobustResourceInitTest.ClearWithScissor/ES2_Vulkan:WebGL2CompatibilityTest.TransformFeedbackDoubleBinding/ES3_Vulkan:Texture2DTest.CopySubImageFloat_RGBA_R/ES2_Vulkan:ViewportTest.TripleWindowCentered/ES2_Vulkan:GLSLTest_ES3.WriteIntoDynamicIndexingOfSwizzledVector/ES3_Vulkan_AvoidOpSelectWithMismatchingRelaxedPrecision:LinkAndRelinkTest.AttachShaderThenCompile/ES3_Vulkan_EnableParallelCompileAndLink:TextureMultisampleArrayTest.ShaderWithoutExtension/ES3_2_Vulkan_EnableParallelCompileAndLink:FragDepthTest.DepthBufferBound/ES3_Vulkan_EnableParallelCompileAndLink:VulkanPerformanceCounterTest.Source2DAndRepeatedlyRespecifyTarget2DWithSameParameter/ES3_Vulkan:GLSLTest_ES3.InoutWithArrayRefs/ES3_Vulkan:DepthWriteTest.Test/ES2_Vulkan__DepthRangeReduced_Clamped_VertexDepthInsideClipVolume_FragmentDepthPassthrough_Depth16Unorm:CompressedTextureSamplerASTCSliced3DTest.Test/ES2_Vulkan__RGBA_ASTC_4x4:CopyTextureVariationsTest.CopySubTextureRectangle/ES2_Vulkan__BGRAToSRGBAFlipYPremultiplyAlpha:MultisampleTest.Point/ES3_1_Vulkan:FramebufferObjectTest.FramebufferObject/ES1_Vulkan:GLSLTest_ES3.DynamicIndexingOfSwizzledLValuesShouldWork2/ES3_Vulkan:VertexAttributeTestES31.MismatchingSignsChangingAttributeType/ES3_1_Vulkan:BlitFramebufferTest.BlitFramebufferSizeOverflow/ES3_Vulkan_EmulatedPrerotation270:Texture3DTestES3.DrawWithLevelsOutsideRangeWithInconsistentDimensions/ES3_Vulkan_EnableParallelCompileAndLink:GLSLTest.UniformStructWithoutInitializer/ES3_Vulkan_NoSupportsSPIRV14:GLSLTest.MemoryExhaustedTest/ES3_Vulkan_ForceInitShaderVariables:MultisampledRenderToTextureTest.2DColorDepthMultisampleDrawTest/ES3_Vulkan_EnableParallelCompileAndLink:VulkanExternalImageTest.WaitSemaphoresRetainsContentZirconVmo/ES3_OpenGLES:BlitFramebufferANGLETest.ErrorFlipping/ES3_Vulkan_EmulatedPrerotation180:EGLContextSharingTestNoFixture.EglDestoryContextManyTimesSameContext/ES2_Vulkan_NoFixture:ImageTest.ValidationGLEGLImageExternalESSL3/ES3_Vulkan_EnableParallelCompileAndLink:GLSLTest_ES3.SwitchFinalCaseHasEmptyBlock/ES3_Vulkan_NoSupportsSPIRV14:CopyTextureVariationsTest.CopySubTextureRectangle/ES2_Vulkan__RGBToBGRAPremultiplyAlphaUnmultiplyAlpha:AtomicCounterBufferTest.AtomicCounterBufferBindings/ES3_Vulkan:MultiDrawNoInstancingSupportTest.InvalidOperation/ES2_Vulkan_AlwaysEnableEmulatedMultidrawExtensions__DynamicDraw__Instanced:ClipCullDistanceTest.ClipInterpolation/ES3_Vulkan__ANGLE:FramebufferFormatsTest.ReadDrawCompleteness/ES3_Vulkan:GLSLTest.NestedTernaryAndShortCircuit/ES3_Vulkan_EnableParallelCompileAndLink:GLSLTest_ES3.SwitchFinalCaseHasEmptyBlock/ES3_Vulkan_AvoidOpSelectWithMismatchingRelaxedPrecision:EGLContextSharingTestNoSyncTextureUploads.NoSync/ES3_Vulkan_ForceSubmitImmutableTextureUpdates:MultisampledRenderToTextureTest.RenderbufferClearDrawCopyThenBlendSameProgram/ES3_Vulkan:GLSLTest_ES3.FlatVaryingMatrixArray/ES3_Vulkan_ForceInitShaderVariables:IncompleteTextureTest.UpdateTexture/ES2_Vulkan:StateChangeTestES3.UniformBlockBinding/ES3_Vulkan_NoSupportsIndexTypeUint8:CompressedTextureDXT1Test.Test/ES3_Vulkan__RGB_S3TC_DXT1:DepthStencilTest.StencilOnlyDrawThenCopyThenDraw/ES2_Vulkan:CopyTextureVariationsTest.CopySubTextureRectangle/ES2_Vulkan__LToBGRAUnmultiplyAlpha:VertexAttributeTest.DrawArraysWithDisabledAttribute/ES3_Vulkan_ForceFallbackFormat:TransformFeedbackWithDepthBufferTest.RecordAndDrawWithDepthWriteEnabled/ES3_Vulkan_EnableParallelCompileAndLink:GLSLTest.ESSL1ExtensionMacros/ES3_Vulkan_ForceInitShaderVariables:TransformFeedbackTestES31.SameArrayElementVaryings/ES3_1_Vulkan:GLSLTest_ES3.SwitchWithVariableDeclarationInside/ES3_Vulkan_NoSupportsSPIRV14:ImageTestES31.TargetRenderbufferDeletedWhileInUseAsResolve2/ES3_1_Vulkan:InstancingTest.Instances5Divisor1/ES2_Vulkan:MaskedScissoredClearTest.Test/ES3_Vulkan_NoSupportsExtendedDynamicState2__scissored_clear_cds_mask_cd:MultisampledRenderToTextureTest.RenderbufferCopyTexImageTest/ES3_Vulkan_EnableParallelCompileAndLink:BindUniformLocationTest.ConflictsDetection/ES2_Vulkan:TransformFeedbackTest.BufferOutOfMemory/ES3_Vulkan_NoSupportsTransformFeedbackExtension_NoSupportsSPIRV14:GPUTestConfigTest.GPUTestConfigConditions_Vulkan_PreRotation270/ES3_Vulkan:GetImageTest.GetTexImageAlpha/ES2_Vulkan:CopyTextureVariationsTest.CopySubTextureRectangle/ES2_Vulkan__RGBAToRGBFlipYUnmultiplyAlpha:DrawBuffersTest.FirstHalfNULL/ES3_Vulkan_EnableParallelCompileAndLink:WebGLCompatibilityTest.EnableExtensionStandardDerivitives/ES2_Vulkan:MultithreadingTest.MultiContextDrawWithSwapBuffers/ES3_Vulkan:FramebufferFormatsTest.RGBA4/ES2_Vulkan:Texture2DTestES3.CopyImageOES/ES3_Vulkan:GLSLTest_ES31.BuiltInsWithOutParameters/ES3_1_Vulkan_NoSupportsSPIRV14:FramebufferFetchES31.DrawNonFetchDrawFetchWithDifferentAttachments_Coherent/ES3_1_Vulkan:Texture2DTestES3.ChangeTexSizeWithTexStorage/ES3_Vulkan:CopyTextureVariationsTest.CopyTextureRectangle/ES2_Vulkan__RGBAToBGRAMesaYFlip:CopyTextureVariationsTest.CopyTexture/ES2_Vulkan__LToSRGBAFlipYUnmultiplyAlpha:SimpleOperationTest.DrawIndexedQuad/ES3_Vulkan:ParallelShaderCompileTest.Basic/ES2_Vulkan:CopyTextureVariationsTest.CopySubTexture/ES2_Vulkan__BGRAToSRGBAFlipYUnmultiplyAlphaMesaYFlip:CopyTextureVariationsTest.CopySubTextureRectangle/ES2_Vulkan__LToRGBAMesaYFlip:MultisampledRenderToTextureTest.RenderbufferParameterCheck/ES3_Vulkan_RobustResourceInit:MultisampledRenderToTextureTest.RenderbufferDrawCopyDrawThenMaskedClear/ES3_Vulkan_NoSupportsSPIRV14:QueryObjectTest.QueryObjectResultAvailableBeforeBegin/ES3_Vulkan__ValidationDisabled:DXT1CompressedTextureTestES3.CompressedTexSubImageValidation/ES3_Vulkan:BufferDataTestES3.bufferReadFromRenderPassAndOutsideRenderPassWithFenceSyncInBetween/ES3_Vulkan_EnableParallelCompileAndLink:Texture2DDepthTest.DepthTextureES3Compatibility/ES3_Vulkan --verbose  --gtest_repeat=50 > /tmp/log_end2end

```

**Expected behavior**

Consistently passing the group of tests 600 times.

**Valid Usage ID**
If applicable, please include the validation messages encountered leading up to the issue

**Additional context**
- The investigation started from https://anglebug.com/387828389.  Sample logs are available at https://anglebug.com/387828389#comment11

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**
It is possible for a the tls cache to contain a destroyed object in multithreaded applications.

Fixes #9181

### CODE REVIEW

**Comment by jeremyg-lunarg** [comment]
With ASAN enabled and WITHOUT the fix in this PR, the new DestroyDeviceRace test triggers this:

```
eremyg-lappy3000:~/src/Vulkan-ValidationLayers/build>./tests/vk_layer_validation_tests --gtest_filter=*DestroyDeviceRace
Note: Google Test filter = *DestroyDeviceRace
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from NegativeInstanceless
[ RUN      ] NegativeInstanceless.DestroyDeviceRace
=================================================================
==100776==ERROR: AddressSanitizer: heap-use-after-free on address 0x523000026ab0 at pc 0x701d532fe3f9 bp 0x7ffc5870e4e0 sp 0x7ffc5870e4d0
READ of size 8 at 0x523000026ab0 thread T0
    #0 0x701d532fe3f8 in GetDeviceFromKey /home/jeremyg/src/Vulkan-ValidationLayers/layers/chassis/dispatch_object_manual.cpp:72
    #1 0x701d532fe572 in vvl::dispatch::GetData(VkDevice_T*) /home/jeremyg/src/Vulkan-ValidationLayers/layers/chassis/dispatch_object_manual.cpp:80
    #2 0x701d54de8cec in StatelessValidation::PostCallRecordCreateDevice(VkPhysicalDevice_T*, VkDeviceCreateInfo const*, VkAllocationCallbacks const*, VkDevice_T**, RecordObject const&) /home/jeremyg/src/Vulkan-ValidationLayers/layers/stateless/sl_instance_device.cpp:295
    #3 0x701d532da64e in vulkan_layer_chassis::CreateDevice(VkPhysicalDevice_T*, VkDeviceCreateInfo const*, VkAllocat
```
With the fix, this test completes successfully.

File: tests/unit/instanceless.cpp [hunk 1]
```diff
@@ -252,8 +253,7 @@ TEST_F(NegativeInstanceless, DestroyInstanceAllocationCallbacksCompatibility) {
     }
 }
 
-// When address/tread sanitizer is on, this tends to fail tests after it
-TEST_F(NegativeInstanceless, DISABLED_DestroyInstanceHandleLeak) {
+TEST_F(NegativeInstanceless, Disabled_DestroyInstanceHandleLeak) {
```
Comment (spencer-lunarg) [inline tests/unit/instanceless.cpp:256]: I think it needs to be all caps for GTEST to disable

**Review by spencer-lunarg — APPROVED** [review]

File: tests/unit/instanceless.cpp (hunk 1 above)
Comment (jeremyg-lunarg) [reply tests/unit/instanceless.cpp:256]: yeah that stuff shouldn't have been touched at all. fixing

**Comment by spencer-lunarg** [comment]
@jeremyg-lunarg added this change to the `vulkan-sdk-1.4.304` branch

File: layers/chassis/dispatch_object_manual.cpp [hunk 2]
```diff
@@ -35,21 +35,15 @@ vvl::concurrent_unordered_map<uint64_t, uint64_t, 4, HashedUint64> HandleWrapper
 bool HandleWrapper::wrap_handles{true};
 
 // Generally we expect to get the same device and instance, so we keep them handy
```
Comment (filnet) [inline layers/chassis/dispatch_object_manual.cpp:37]: obsolete comment ?
