### PR TITLE
Fix issue 3222, Adding vuid 02674 02675, Validate AcquireFullScreenExclusiveModeEXT 

### LINKED ISSUE #3222: No Validation Error with vk(Acquire/Release)FullScreenExclusiveModeEXT
**Describe the Issue**
When I made swapchain with `VkSurfaceFullScreenExclusiveWin32InfoEXT` & `VkSurfaceFullScreenExclusiveInfoEXT` removed from the `pNext` chain of `VkSwapchainCreateInfoKHR` and then I call `vkAcquireFullScreenExclusiveModeEXT` using the pointer to this function, I got only `VK_ERROR_INITIALIZATION_FAILED` as the return value and no validation error was printed. I made sure that the other validation errors were printed to the debug output. For example, when I set the second argument of `vkAcquireFullScreenExclusiveModeEXT` to `VK_NULL_HANDLE`, then I got validation error `VUID-vkAcquireFullScreenExclusiveModeEXT-swapchain-parameter`.

**Valid Usage ID**
I expected to get `VUID-vkAcquireFullScreenExclusiveModeEXT-swapchain-02675` error.

**Environment:**
 - OS: Windows 10 Home Edition / with OS build 19042.1165
 - GPU: NVIDIA GeForce GTX 1660 SUPER / with GeForce Game Ready Driver version 471.68
 - SDK version: 1.2.176.1

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #3222 

Swapchain must not be retired and must have been created with VkSurfaceFullScreenExclusiveInfoEXT in the pNext chain with
fullScreenExclusive equal to VK_FULL_SCREEN_EXCLUSIVE_APPLICATION_CONTROLLED_EXT

### CODE REVIEW

File: tests/vklayertests_wsi.cpp [hunk 1]
```diff
@@ -2121,3 +2121,99 @@ TEST_F(VkLayerTest, GetSwapchainImagesCountButNotImages) {
...
+    }
+
+    auto vkAcquireFullScreenExclusiveModeEXT = reinterpret_cast<PFN_vkAcquireFullScreenExclusiveModeEXT>(
+        vk::GetInstanceProcAddr(instance(), "vkAcquireFullScreenExclusiveModeEXT"));
+
+    m_errorMonitor->SetDesiredFailureMsg(kErrorBit, "VUID-vkAcquireFullScreenExclusiveModeEXT-swapchain-02675");
+    vkAcquireFullScreenExclusiveModeEXT(device(), m_swapchain);
+    m_errorMonitor->VerifyFound();
+
+    const POINT ptZero = {0, 0};
```
Comment (ncesario-lunarg) [inline tests/vklayertests_wsi.cpp:2181]: `snake_case`.

**Review by ncesario-lunarg — CHANGES_REQUESTED** [review]
Couple minor nits, but otherwise LGTM!

**Review by ncesario-lunarg — APPROVED** [review]
