### PR TITLE
layers: Fix checking for std::shared_mutex support

### LINKED ISSUE #3323: Vulkan-ValidationLayers uses shared_mutex when compiled as C++14
**Describe the Issue**
Same as #1921 reported by @randomascii 

The condition now is

```
#if _MSC_FULL_VER >= 190023918 && NTDDI_VERSION > NTDDI_WIN10_RS2
```

Defined in `vk_layer_utils.h`. Right now in Chromium / Clang / Windows / C++14 this condition is true, and `std::shared_mutex` is enabled even though it's not available.

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**
On Windows, clang sets _MSC_VER and _MSC_FULL_VER so we should
only look at these variables if !defined(__clang__). Add comments
explaining as much of the conditions as are still known.

Closes #3323

### CODE REVIEW

File: layers/vk_layer_utils.h [hunk 1]
```diff
@@ -268,9 +268,16 @@ static inline int u_ffs(int val) {
...
 // Minimum Visual Studio 2015 Update 2, or libc++ with C++17
-#if defined(_MSC_FULL_VER)
-#if _MSC_FULL_VER >= 190023918 && NTDDI_VERSION > NTDDI_WIN10_RS2
+// But, before Visual Studio 2017 version 15.7, __cplusplus is not set
+// correctly. See:
+//   https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-160
+// Also, according to commit e2a6c442cb1e4, SDKs older than NTDDI_WIN10_RS2 do not
+// support shared_mutex.
+#if _MSC_FULL_VER >= 190023918 && NTDDI_VERSION > NTDDI_WIN10_RS2 && \
+    (!defined(_LIBCPP_VERSION) || __cplusplus >= 201703)
```
Comment (ncesario-lunarg) [inline layers/vk_layer_utils.h:280]: :sob:

**Review by ncesario-lunarg — APPROVED** [review]

**Comment by null77** [comment]
@jeremy-lunarg can confirm it fixes the build on our end. Please land when it's ready. Thanks!
