### PR TITLE
layers: Fix dual source blend with dynamic rendering

### LINKED ISSUE #4036: Dynamic Rendering + Dual Source Blending crashes
**Describe the Issue**
Recent changes for dual source blending have caused a regression with dynamic rendering.  Specifically on line 1330 of core_validation.cpp I crash here when using dynamic rendering:

```if (pPipeline->fragment_output_state->dual_source_blending) {
        uint32_t count = pCB->activeRenderPass->createInfo.pSubpasses[pCB->activeSubpass].colorAttachmentCount;
        if (count > phys_dev_props.limits.maxFragmentDualSrcAttachments) {
            skip |=
                LogError(pPipeline->pipeline(), "VUID-RuntimeSpirv-Fragment-06427",
                         "%s: Dual source blend mode is used, but the number of written fragment shader output attachment (%" PRIu32
                         ") is greater than maxFragmentDualSrcAttachments (%" PRIu32 ")",
                         caller, count, phys_dev_props.limits.maxFragmentDualSrcAttachments);
        }
    }
```

pSubpassess == nullptr.  Callstack:

	VkLayer_khronos_validation.dll!CoreChecks::ValidatePipelineDrawtimeState(const LAST_BOUND_STATE & state, const CMD_BUFFER_STATE * pCB, CMD_TYPE cmd_type, const PIPELINE_STATE * pPipeline) Line 1330	C++
 	VkLayer_khronos_validation.dll!CoreChecks::ValidateCmdBufDrawState(const CMD_BUFFER_STATE * cb_node, CMD_TYPE cmd_type, const bool indexed, const VkPipelineBindPoint bind_point) Line 1508	C++
 	VkLayer_khronos_validation.dll!CoreChecks::ValidateCmdDrawType(const CMD_BUFFER_STATE & cb_state, bool indexed, VkPipelineBindPoint bind_point, CMD_TYPE cmd_type) Line 1111	C++
 	VkLayer_khronos_validation.dll!CoreChecks::PreCallValidateCmdDrawIndexed(VkCommandBuffer_T * commandBuffer, unsigned int indexCount, unsigned int instanceCount, unsigned int firstIndex, int vertexOffset, unsigned int firstInstance) Line 1198	C++
 	VkLayer_khronos_validation.dll!vulkan_layer_chassis::CmdDrawIndexed(VkCommandBuffer_T * commandBuffer, unsigned int indexCount, unsigned int instanceCount, unsigned int firstIndex, int vertexOffset, unsigned int firstInstance) Line 3055	C++

**Valid Usage ID**
If applicable, please include the validation messages encountered leading up to the issue

**Environment:**
 - OS: Win10
 - GPU: NVIDIA
 - SDK or header version if building from repo: master 269798f64c452a78fb058893843edc7f95d0c40f
 - Options enabled (synchronization, best practices, etc.):

**Additional context**
CC @ziga-lunarg

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #4036

### CODE REVIEW

File: layers/core_validation.cpp [hunk 1]
```diff
@@ -1326,7 +1326,8 @@ bool CoreChecks::ValidatePipelineDrawtimeState(const LAST_BOUND_STATE &state, co
         }
     }
 
-    if (pPipeline->fragment_output_state->dual_source_blending) {
+    if (pPipeline->fragment_output_state->dual_source_blending  &&
+        pCB->activeRenderPass  && !pCB->activeRenderPass->use_dynamic_rendering) {
```
Comment (ncesario-lunarg) [inline layers/core_validation.cpp:1330]: Is this check not applicable for dynamic rendering?

**Review by ncesario-lunarg — COMMENTED** [review]
One question about ignoring the check for dynamic rendering, but otherwise LGTM.

File: layers/core_validation.cpp (hunk 1 above)
Comment (ziga-lunarg) [reply layers/core_validation.cpp:1330]: You are right, it was missing

**Review by ncesario-lunarg — APPROVED** [review]
