### PR TITLE
layers: Further clean up of FENCE_STATE, SEMAPHORE_STATE and QUEUE_STATE

### LINKED ISSUE #3590: Queue Submission tracking no longer retiring correctly when Timeline Semaphores are reused across queues
**Describe the Issue**
I've updated my local SDK from 1.2.189.2 to 1.2.198.1 and started getting errors like "resource still in use" where I did not get them before. I did some investigation and I think it's related to the recent refactoring of Queue submission state tracking ~@jeremy-lunarg~ . **EDIT:** I pinged the wrong Jeremy, sorry! @jeremyg-lunarg 

The current version seems to be retiring work on the specific queue that is going to signal this semaphore (not 100% sure) https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/57642989cc83adc8620d385d08bda0d60977c6c9/layers/queue_state.cpp#L161

Whereas the previous version, before it was refactored, iterated all the queues to check what work can be retired as of this semaphore:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/7801b4151580e0750471ffa099a976af7252d4f6/layers/queue_state.cpp#L224

With this observation in mind, I modified my app to never reuse the same Timeline Semaphore for submissions across different queue families. It normally does a dependency analysis to pack submissions onto the smallest number of timeline semaphores (unique paths through a DAG).

This resolved my issue and I haven't seen it since. I don't have a simple C++ repro, but I believe this issue arises when:
1. A Timeline Semaphore is used as a signal semaphore on queue A
2. The same Timeline Semaphore is used as a signal on queue B of a different family
3. `vkWaitSemaphores` is used on the host to wait for the first submission to complete

I'm not sure if the validation layers end up retiring the second submission on queue B correctly. The errors I saw implied they haven't retired the first one.

Interestingly, I could not reproduce this with multiple queues of the same family. My graph analysis also finds independent compute work and submits them to different queues within the same family, but that doesn't seem to cause an issue.

**Valid Usage ID**
All the ones for "resource still in use" could probably get this. I've personally seen errors from vkResetCommandPool and vkDestroyAccelerationStructure:
* `VUID-vkResetCommandPool-commandPool-00040`

**Environment:**
 - OS:  Windows 10 64b
 - GPU: RX 6900 XT with driver: 21.11.3
 - SDK or header version if building from repo: SDK 1.2.198.1
 - Options enabled (synchronization, best practices, etc.): Just the standard_validation layer

**Additional context**

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**
Make all non-const member data private and restructure semaphore tracking to allow it to eventually be made thread safe. The biggest change is that each semaphore's state now keeps a queue of pending operations, which removes the need to frequently walk all pending submissions in every queue.

Add VkPositiveLayerTest.QueueSubmitTimelineSemaphore2Queue to show that this PR fixes #3590

### CODE REVIEW

File: layers/core_validation.cpp [hunk 1]
```diff
@@ -15763,14 +15657,23 @@ bool CoreChecks::ValidateAcquireNextImage(VkDevice device, const AcquireVersion
...
-        const char *vuid = version == ACQUIRE_VERSION_2 ? "VUID-VkAcquireNextImageInfoKHR-semaphore-01288"
-                                                        : "VUID-vkAcquireNextImageKHR-semaphore-01286";
-        skip |= LogError(semaphore, vuid, "%s: Semaphore must not be currently signaled or in a wait state.", func_name);
+    if (semaphore_state) {
+        if (semaphore_state->type != VK_SEMAPHORE_TYPE_BINARY) {
+            skip |= LogError(semaphore, semaphore_type_vuid, "%s: %s is not a VK_SEMAPHORE_TYPE_BINARY", func_name,
+                             report_data->FormatHandle(semaphore).c_str());
+        } else if (semaphore_state->Scope() == kSyncScopeInternal) {
+            auto last_op = semaphore_state->LastOp();
+            // TODO: VUIDs 01779 and 01781 cover the case where there are pending wait or signal operations on the
```
Comment (jeremyg-lunarg) [inline layers/core_validation.cpp:15666]: the test for these VUIDs is https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3650 I'm not 100% sure we have enough info available for acquire / present semaphores to check this reliably.  Binary semaphores are not my favorite thing.

File: layers/image_state.cpp [hunk 2]
```diff
@@ -254,21 +254,22 @@ void IMAGE_STATE::Unlink() {
         alias_state->aliasing_images.erase(this);
     }
     aliasing_images.clear();
-    if (bind_swapchain) {
```
Comment (jeremyg-lunarg) [inline layers/image_state.cpp:257]: the changes in this file could be a separate PR. It is a pre-existing problem but I started hitting it when working on the other changes in this PR.

File: layers/queue_state.h [hunk 3]
```diff
@@ -26,8 +26,9 @@
  */
 #pragma once
 #include "base_node.h"
-#include <vector>
 #include <deque>
+#include <set>
+#include <vector>
```
Comment (jeremyg-lunarg) [inline layers/queue_state.h:32]: I have a follow-on commit to make all of these objects threadsafe. But this PR is complicated enough that its probably best to do that part separately.

**Review by mark-lunarg — APPROVED** [review]
YIKES.  This LGTM, for what that's worth.  YIKES again!

**Comment by jeremyg-lunarg** [comment]
> YIKES. This LGTM, for what that's worth. YIKES again!

I agree with the YIKES. I have tested it with manual-vvltraces and as of this version it is not changing error counts.  But you can see from the number of times I've had to push this, it has been tough. I'm going to leave this one open for a while to see if anyone else has time to check it out.

File: tests/positive/sync.cpp [hunk 4]
```diff
@@ -1947,3 +1947,169 @@ TEST_F(VkPositiveLayerTest, DoubleLayoutTransition) {
...
+    VkCommandBufferObj cb1(m_device, &pool1);
+    cb1.begin();
+    vk::CmdCopyBuffer(cb1.handle(), buffer_c->handle(), buffer_b->handle(), 1, &region);
+    cb1.end();
+
+    VkSemaphoreTypeCreateInfoKHR semaphore_type_create_info{};
+    semaphore_type_create_info.sType = VK_STRUCTURE_TYPE_SEMAPHORE_TYPE_CREATE_INFO_KHR;
+    semaphore_type_create_info.semaphoreType = VK_SEMAPHORE_TYPE_TIMELINE_KHR;
+
+    VkSemaphoreCreateInfo semaphore_create_info{};
```
Comment (ziga-lunarg) [inline tests/positive/sync.cpp:2031]: `LvlInitStruct<VkSemaphoreCreateInfo>(&semaphore_type_create_info);` could be used.

File: layers/core_validation.cpp [hunk 5]
```diff
@@ -3612,35 +3596,43 @@ struct SemaphoreSubmitState {
...
                     } else {
                         unsignaled_semaphores.erase(semaphore);
                         signaled_semaphores.insert(semaphore);
                     }
                 }
                 break;
-            case VK_SEMAPHORE_TYPE_TIMELINE:
-                if (value <= semaphore_state->payload) {
+            case VK_SEMAPHORE_TYPE_TIMELINE: {
+                auto completed = semaphore_state->Completed();
```
Comment (ziga-lunarg) [inline layers/core_validation.cpp:3623]: Could this be `const auto&` and same for the one above?

**Review by ncesario-lunarg — APPROVED** [review]
Some minor comments/questions, but LGTM!

File: layers/image_state.cpp (hunk 2 above)
Comment (jeremyg-lunarg) [reply layers/image_state.cpp:257]: This was a separate commit and it got moved to a different PR because it turns out the reason I started hitting it is I disabled robin-hood-hashing in my debug build. If you do that, the existing swapchain test cases will crash without this fix.  There's a CI build with robin hood off coming soon.

File: layers/core_validation.cpp [hunk 6]
```diff
@@ -3756,49 +3735,37 @@ bool CoreChecks::ValidateSemaphoresForSubmit(SemaphoreSubmitState &state, VkQueu
...
     using sync_vuid_maps::SubmitError;
     bool skip = false;
-    const auto semaphore_state = Get<SEMAPHORE_STATE>(semaphore);
 
-    if (semaphore_state->type != VK_SEMAPHORE_TYPE_TIMELINE) return false;
-
-    uint64_t diff = value > semaphore_state->payload ? value - semaphore_state->payload : semaphore_state->payload - value;
+    if (semaphore_state.type != VK_SEMAPHORE_TYPE_TIMELINE) return false;
 
+    auto semaphore = semaphore_state.Handle();
```
[the remark this answers is not in the document]
Comment (jeremyg-lunarg) [reply layers/core_validation.cpp:3748]: Handle() returns a VulkanTypedHandle. semaphore() returns a VkSemaphore.  when calling into log message stuff, Handle() is better because it will preserve the type information of non-dispatchable handle types in 32 bit builds. I'd really like to make the log messages understand how to do the right thing if passed a const BASE_NODE& but I can never get the template magic to work right for that.

File: layers/core_validation.cpp [hunk 7]
```diff
@@ -3634,29 +3590,51 @@ struct SemaphoreSubmitState {
...
+        const auto semaphore_state = core->Get<SEMAPHORE_STATE>(semaphore);
+        if (!semaphore_state) {
+            return skip;
+        }
+        switch (semaphore_state->type) {
+            case VK_SEMAPHORE_TYPE_BINARY:
+                if ((semaphore_state->Scope() == kSyncScopeInternal || internal_semaphores.count(semaphore))) {
+                    if (CannotSignal(*semaphore_state)) {
+                        VkQueue other_queue;
+                        auto last_op = semaphore_state->LastOp();
```
[the remark this answers is not in the document]
Comment (jeremyg-lunarg) [reply layers/core_validation.cpp:3602]: I think I got all the ones I added
