### PR TITLE
layers: Check for destroyed swapchain

### LINKED ISSUE #12122: Crash in Fence::NotifyAndWait
I have an app, where if I resize the window I will get a crash in 

```
std::vector<vvl::SwapchainImage,std::allocator<vvl::SwapchainImage>>::operator[](const unsigned __int64 _Pos) Line 1930	C++
>	vvl::Fence::NotifyAndWait(const Location & loc) Line 96	C++
vvl::DeviceState::PostCallRecordWaitForFences(VkDevice_T * device, unsigned int fenceCount, VkFence_T * const * pFences, unsigned int waitAll, unsigned __int64 timeout, const RecordObject & record_obj) Line 1665	C++
vulkan_layer_chassis::WaitForFences(VkDevice_T * device, unsigned int fenceCount, VkFence_T * const * pFences, unsigned int waitAll, unsigned __int64 timeout) Line 1534	C++
```

The issue is that the size of acquired_image_swapchain_->images is 0, but it is being accessed. 

Might be important that I am using VK_KHR_swapchain_maintenance1 and present fences. I don't know how to reproduce with a VVL test. I can provide apidump or gfxr capture if needed.

### PR DESCRIPTION
**Pull request by artem-lunarg**
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/12122

In the issue the swapchain was destroyed after it was retired (used as oldSwapchain)

### CODE REVIEW

File: layers/state_tracker/fence_state.cpp [hunk 1]
```diff
@@ -91,7 +91,7 @@ void vvl::Fence::NotifyAndWait(const Location& loc) {
                 queue_ = nullptr;
                 seq_ = 0;
                 // Update the swapchain image acquire state if the fence was used by the acquire operation
-                if (acquired_image_swapchain_) {
+                if (acquired_image_swapchain_ && !acquired_image_swapchain_->Destroyed()) {
```
Comment (artem-lunarg) [inline layers/state_tracker/fence_state.cpp:94]: There are two way to solve similar problems. Another one is more "clean" - swapchain knows when it is being destroyed, so it can notify all its users (including fences/semaphrores) and users perform cleanup (in this case set acquired_image_swapchain_ to null). Then this code works without modifications. The problem with such approach is that it adds additional state. Depending on subsystem it might be better solution or not.  Swapchain state tracking is already complicated, so the preference here is to add logic than state.

**Review by ziga-lunarg — APPROVED** [review]

**Review by spencer-lunarg — APPROVED** [review]
