### PR TITLE
Prevent null pointer access for GetSwapchainImages out-of-order calls

### LINKED ISSUE #1955: Segmentation Fault During vkAcquireNextImageKHR while using VK_LAYER_KHRONOS_validation
If I call vkGetSwapchainImagesKHR to fetch the number of images, and then make no subsequent call to fetch the images into an array, when I then go to call vkAcquireNextImageKHR later on, a segfault is caused inside core_validation.cpp (looks to be https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/core_validation.cpp#L11131-L11133), where it is trying to iterate over the swapchain images. 

Inspecting the swapchain in gdb at the place the exception is thrown, shows the following in the unhappy path:
```
(gdb) p swapchain_data->images
$2 = std::vector of length 3, capacity 3 = {{image = 0x0, bound_images = std::unordered_set with 0 elements}, {image = 0x0,
    bound_images = std::unordered_set with 0 elements}, {image = 0x0, bound_images = std::unordered_set with 0 elements}}
```

If removing both calls, swapchain_data contains the following:
```
(gdb) p swapchain_data->images
$3 = std::vector of length 0, capacity 0
```

If calling twice, once to get length and then to populate an array:
```
(gdb) p swapchain_data->images
$1 = std::vector of length 3, capacity 3 = {{image = 0xd000000000d, bound_images = std::unordered_set with 1 element = {[0] = 0xd000000000d}}, {image = 0xe000000000e,
    bound_images = std::unordered_set with 1 element = {[0] = 0xe000000000e}}, {image = 0xf000000000f, bound_images = std::unordered_set with 1 element = {
      [0] = 0xf000000000f}}}
```

API dump and AddressSanitizer bailout:
https://gist.github.com/Moggers/14d0f5cf9542ade502bd4d26883bdbdb
If a minimal reproduction is required, I can hack one together.

### PR DESCRIPTION
**Pull request by mark-lunarg**
Validation could croak if this two-part query was only called by the application to retrieve the count but not the images.

i.e., though it seems weird, it's legal to do this:

```
GetSwapchainImages(count, null);
AcquireNextImage(index);
GetSwapchainImages(count, pointer_to_image_array);
```

Wrote a positive test for this case, but it dies on Android consistently and so left it out.  Highlighted this in BP tracking issue #24 (it was already there) to spit out a warning when this happens.

Fixes #1955.

### CODE REVIEW

File: layers/core_validation.cpp [hunk 1]
```diff
@@ -11131,9 +11131,13 @@ bool CoreChecks::ValidateAcquireNextImage(VkDevice device, const CommandVersion
         auto physical_device_state = GetPhysicalDeviceState();
         // TODO: this is technically wrong on many levels, but requires massive cleanup
         if (physical_device_state->vkGetPhysicalDeviceSurfaceCapabilitiesKHR_called) {
-            const uint32_t acquired_images =
-                static_cast<uint32_t>(std::count_if(swapchain_data->images.begin(), swapchain_data->images.end(),
-                                                    [=](SWAPCHAIN_IMAGE image) { return GetImageState(image.image)->acquired; }));
+            uint32_t acquired_images = 0;
+            for (auto item : swapchain_data->images) {
+                auto image_state = GetImageState(item.image);
+                if ((image_state) && image_state->acquired) {
```
Comment (jeremy-lunarg) [inline layers/core_validation.cpp:11137]: Why not modify the lambda?

Comment (mark-lunarg) [reply layers/core_validation.cpp]: Ignorance!  Pushed a redo.
