### PR TITLE
layers: Fix ImageSubresourceLayoutMap update corner cases

### LINKED ISSUE #2910: Error in the tracking for VUID_Core_DrawState_InvalidImageLayout
I think there's an issue in the tracking of the required image layout. CC @jeremy-lunarg since this is similar to #2793 (and is part of the same [Dawn issue](https://bugs.chromium.org/p/dawn/issues/detail?id=785), we just didn't finish fixing it previously).

**Environment:**
 - OS: macOS (doesn't matter)
 - GPU: Swiftshader
 - SDK or header version if building from repo: f12691a7fca240719ae0be8c6186cf90cca94265
 - Options enabled (synchronization, best practices, etc.): VVL with synchronization validation enabled.

Running the command below with this [Dawn commit](https://dawn-review.googlesource.com/c/dawn/+/55780) causes an incorrect (as far as I can tell) warning to be produced:

`./out/Debug/dawn_end2end_tests --gtest_filter=ShaderTests.A/Vulkan_SwiftShader_Device_Subzero --enable-backend-validation`

The invalid warning is:

> [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object 0: handle = 0x1400df470, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x4dae5635 | Submitted command buffer expects VkImage 0x40000000004[] (subresource: aspectMask 0x1 array layer 0, mip level 1) to be in layout VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL--instead, current layout is VK_IMAGE_LAYOUT_UNDEFINED.

I think it is invalid because the code uses only mip level 0 as an attachment, not mip level 1. The test is [here](https://dawn-review.googlesource.com/c/dawn/+/55780/3/src/tests/end2end/ShaderTests.cpp) and reads like Vulkan-lite with implicit zero-initialization of resources. Roughly what it does is the following:

 - Create a texture with two mip levels.
 - Make a barrier for mip level 0 going from `UNDEFINED` to `OUTPUT_ATTACHMENT_OPTIMAL`.
 - "Discard" mip level 0.
 - Make two barriers to transition mip level 0 (resp. 1) from `OUTPUT_ATTACHMENT_OPTIMAL` (resp. `UNDEFINED`) to `TRANSFER_DST_OPTIMAL`.
 - Copy from a buffer to both mips.
 - Transition mip level 0-1 from `TRANSFER_DST_OPTIMAL` to `SHADER_READ_ONLY_OPTIMAL`.
 - Run a trivial dispatch that uses a descriptor set that uses mip level 0-1.

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**
Handle more cases where the range we're updating partially overlaps  with an existing range, by only updating the intersection of the two. This seems to require more paranoia about invalidating the cached lower bound after changes.
    
This fix exposes another problem with VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT Images.  These ImageViews affect the entire mip level, not just the slice the view references. Rather than swapping depth and arrayLayer in the Image subresource range, just store the simpler subresource range in the ImageView. 

Fixes #2910

### CODE REVIEW

File: layers/range_vector.h [hunk 1]
```diff
@@ -1720,7 +1720,8 @@ bool splice(DstRangeMap &to, const SrcRangeMap &from, SourceIterator begin, Sour
                     // otherwise we need to split the destination range.
                     auto value_to_update = write_it->second; // intentional copy
                     updated |= updater.update(value_to_update, read_it->second);
-                    to.overwrite_range(to_lb->lower_bound, std::make_pair(range, value_to_update));
+                    auto intersected_range = write_it->first & range;
```
Comment (jzulauf-lunarg) [inline layers/range_vector.h:1723]: we need some unit tests for the range_vector operations.... (as well as other bits of the libraries and data structures we've added (optional/small_vector/etc.) @ncesario-lunarg  --- not sure where we'd fit this into the VVL project.

**Review by jzulauf-lunarg — APPROVED** [review]
Nice job straightening out this furball.

**Comment by jeremyg-lunarg** [comment]
Good point about the range_vector unit tests.  This change passed vvltrace performance and error count tests last night. Manual CTS runs show same behavior as current master branch.
