### PR TITLE
Fix warning for loading deprecated extension

### LINKED ISSUE #4293: Best practices layer warns about deprecated extension based on instance version
**Describe the Issue**
When creating an instance with (in my case) 1.3.216 and then calling vkCreateDevice for a device that supports 1.1.217, I get the following warning from the best practices layer:
> CreateDevice(): Attempting to enable deprecated extension VK_KHR_timeline_semaphore, but this extension has been promoted to VK_VERSION_1_2.

This is nonsense, as determining the proper extensions for device creation is device specific and depends on the api version of the device, not the instance. The device does not know of `KHR_timeline_semaphore` being deprecated as it doesn't know about 1.2. Currently, the message is absolutely useless. Although, simply by checking by physical device's apiVersion, the message makes sense again and is actually something a developer should consider. (Also there's a `vk` prefix missing on the CreateDevice() at the start of the string.)

### PR DESCRIPTION
**Pull request by paul-lunarg**
When requesting an API version that deprecates an extension that is enabled on the device, a BP warning is always triggered, even if the device doesn't support the requested API version and hasn't deprecated the extension.
This fix compares the extension deprecation version to the device version instead of the instance API version.

Closes #4293

### CODE REVIEW

File: layers/best_practices_utils.cpp [hunk 1]
```diff
@@ -271,7 +271,7 @@ bool BestPractices::PreCallValidateCreateDevice(VkPhysicalDevice physicalDevice,
                                extension_name);
         }
 
-        skip |= ValidateDeprecatedExtensions("CreateDevice", extension_name, api_version,
+        skip |= ValidateDeprecatedExtensions("CreateDevice", extension_name, device_api_version,
```
Comment (ncesario-lunarg) [inline layers/best_practices_utils.cpp:274]: Is this sufficient? I vaguely remember looking at this issue and it seemed like we needed to know whether or not `extension_name` is an instance or device extension, and then compare to `api_version` or `device_api_version` respectively. This would likely require adding some information in the generated code.

Comment (paul-lunarg) [reply layers/best_practices_utils.cpp:274]: Well I thought that since it is in CreateDevice it wouldn't make sense for there to be instance extensions

Comment (paul-lunarg) [reply layers/best_practices_utils.cpp]: Since this same function checks if the extension is instance and issues a warning (I would have thought it would be an error) I used that to decide to compare with `api_version` or `device_api_version`.

Comment (ncesario-lunarg) [reply layers/best_practices_utils.cpp]: Yeah, this looks good. I was either over-thinking it or thinking about a different issue.

**Review by ncesario-lunarg — APPROVED** [review]

File: layers/best_practices_utils.cpp (hunk 1 above)
Comment (paul-lunarg) [reply layers/best_practices_utils.cpp]: There's actually a case where api version is lower than device version so I'm taking the minimum of the two to validate device extensions

**Review by jeremyg-lunarg — APPROVED** [review]
