### PR TITLE
Fix GPU-AV features path when no app features

### LINKED ISSUE #2422: shaderInt64 is needed for GPU-AV, but only for some checks, but it is being enabled unconditionally.
**Describe the Issue**
shaderInt64 is needed for GPU-AV, but only for some checks (debug printf), but it is being enabled unconditionally.

**Environment:**
 - OS:  macOS
 - GPU:
 - SDK or header version if building from repo: 1.2.162.0
 - Options enabled (synchronization, best practices, etc.): GPU-AV

Fixing this might enable GPU-AV to be supported on macOS with MoltenVK

### PR DESCRIPTION
**Pull request by Tony-LunarG**
Fixes #2422 and should allow vkcube to run on MacOS with GPU-AV enabled

### CODE REVIEW

File: layers/gpu_utils.cpp [hunk 1]
```diff
@@ -253,21 +253,23 @@ void UtilPreCallRecordCreateDevice(VkPhysicalDevice gpu, safe_VkDeviceCreateInfo
...
-            if (*supported && *desired) {
-                *feature_ptr = true;
-            }
-            supported++;
-            desired++;
-            feature_ptr++;
+    VkPhysicalDeviceFeatures new_features = {};
+    VkBool32 *desired = reinterpret_cast<VkBool32 *>(&desired_features);
+    VkBool32 *feature_ptr;
+    if (features)
```
Comment (mark-lunarg) [inline layers/gpu_utils.cpp:259]: This all LGTM, other than "Use curly braces for the controlled statements following if, else if and else. ".

**Review by mark-lunarg — APPROVED** [review]
