### PR TITLE
corechecks: Fix logic for VUID 04152 checking

### LINKED ISSUE #2854: False positive in vkUpdateDescriptorSets() in some cases
**Describe the Issue**
I was fixing some tests in Vulkan CTS while I encountered this unexpected validation error. The tests I was fixing are `dEQP-VK.image.astc_decode_mode.*` (the current tests still contain bugs, and causes other validation errors too, but those will be fixed once my changes are merged into CTS). The false positive validation error is emitted if a storage image descriptor is updated with image layout `VK_IMAGE_LAYOUT_GENERAL` and `VK_KHR_shared_presentable_image` device extension is enabled.

I think the issue is here:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/1dfbd1790542a628a86b07a2aa1b0229391a9062/layers/descriptor_sets.cpp#L2141

The else if statement in the quoted code probably should be something like:
```
else if (!((VK_IMAGE_LAYOUT_GENERAL == image_layout) || ((VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR == image_layout) &&
                                                                     (device_extensions.vk_khr_shared_presentable_image)))) {
```

**Valid Usage ID**
```ERROR: Validation Error: [ VUID-VkWriteDescriptorSet-descriptorType-04152 ] 
Object 0: handle = 0xcee22d000000000f, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0xa46cfc69 | 
vkUpdateDescriptorSets() pDescriptorWrites[2] failed write update validation for VkDescriptorSet 0xcee22d000000000f[] with error:
Write update to VkDescriptorSet 0xcee22d000000000f[] allocated with VkDescriptorSetLayout 0x3d3145000000000d[] binding #2 failed with error message: 
Attempted write update to image descriptor failed due to: 
Descriptor update with descriptorType VK_DESCRIPTOR_TYPE_STORAGE_IMAGE is being updated with invalid imageLayout VK_IMAGE_LAYOUT_GENERAL for image VkImage 0xa3c6870000000008[] in imageView VkImageView 0xa8b035000000000c[]. 
Allowed layouts are: VK_IMAGE_LAYOUT_GENERAL or VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR. 
The Vulkan spec states: If descriptorType is VK_DESCRIPTOR_TYPE_STORAGE_IMAGE the imageLayout member of each element of pImageInfo must be a member of the list given in Storage Image (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkWriteDescriptorSet-descriptorType-04152) (code 0x00000000 from Validation at DescriptorSet:ffffffffa46cfc69)
```

**Environment:**
 - OS: Android 11
 - GPU: Pixel 5
 - SDK or header version if building from repo:  v1.2.179
 - Options enabled (synchronization, best practices, etc.):

**Additional context**

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**
This VUID requires that the image layout be VK_IMAGE_LAYOUT_GENERAL
or VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR. By DeMorgan's law that means
the check needs to be !GENERAL && !SHARED_PRESENT.

Fixes #2854

### CODE REVIEW

File: layers/descriptor_sets.cpp [hunk 1]
```diff
@@ -2138,8 +2138,8 @@ bool CoreChecks::ValidateImageUpdate(VkImageView image_view, VkImageLayout image
             if (!(usage & VK_IMAGE_USAGE_STORAGE_BIT)) {
                 error_usage_bit = "VK_IMAGE_USAGE_STORAGE_BIT";
                 *error_code = "VUID-VkWriteDescriptorSet-descriptorType-00339";
-            } else if ((VK_IMAGE_LAYOUT_GENERAL != image_layout) || ((VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR != image_layout) &&
-                                                                     (device_extensions.vk_khr_shared_presentable_image))) {
+            } else if ((VK_IMAGE_LAYOUT_GENERAL != image_layout) && (!device_extensions.vk_khr_shared_presentable_image ||
+                                                                     (VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR != image_layout))) {
```
Comment (sfricke-samsung) [inline layers/descriptor_sets.cpp:2142]: Note that when https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2826 is merged, there is no reason to have `device_extensions.vk_khr_shared_presentable_image` in this check

**Review by sfricke-samsung — APPROVED** [review]
Thanks for fixing that logic here

File: layers/descriptor_sets.cpp (hunk 1 above)
Comment (jeremyg-lunarg) [reply layers/descriptor_sets.cpp:2142]: That is a good argument for #2826! Checking the extension is on everywhere makes it much more confusing.
