### PR TITLE
Fix issue 3451, validation of multiple pipeline barriers on same image

### LINKED ISSUE #3451: Multiple image layout transitions in one VkCmdPipelineBarrier
**Describe the Issue**
The validation layer reports error VUID-VkImageMemoryBarrier-oldLayout-01197 when applying 2 layout transitions on the same image in a single call to VkCmdPipelineBarrier:
```
0: VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL -> VK_IMAGE_LAYOUT_GENERAL
1: VK_IMAGE_LAYOUT_GENERAL -> VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL
```

`Validation Error: [ VUID-VkImageMemoryBarrier-oldLayout-01197 ] Object 0: handle = 0x25975881090, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x124ffb34 | vkCmdPipelineBarrier(): .pImageMemoryBarriers[1] VkImage 0xfa21a40000000003[] cannot transition the layout of aspect=1 level=0 layer=0 from VK_IMAGE_LAYOUT_GENERAL when the previous known layout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL. The Vulkan spec states: If srcQueueFamilyIndex and dstQueueFamilyIndex define a queue family ownership transfer or oldLayout and newLayout define an image layout transition, oldLayout must be VK_IMAGE_LAYOUT_UNDEFINED or the current layout of the image subresources affected by the barrier (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-VkImageMemoryBarrier-oldLayout-01197)`

The error does not occur if the 2 transitions are done with 2 calls to VkCmdPipelineBarrier.
Now of course this is not optimal, but I don't expect an error here.
Also I could not find/understand in the specs anything preventing me from doing that.

**Environment:**
 - OS: Win64
 - GPU: RTX 2070
 - SDK or header version if building from repo:1.2.189.2

**Additional context**
You can reproduce the error with the following test:

```
TEST_F(VkLayerTest, DoubleLayoutTransition) {
    TEST_DESCRIPTION("Attempt vkCmdPipelineBarrier with 2 layout transitions of the same image.");

    ASSERT_NO_FATAL_FAILURE(InitFramework(m_errorMonitor));
    ASSERT_NO_FATAL_FAILURE(InitState(nullptr, nullptr, VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT));

    VkImageCreateInfo image_create_info = {};
    image_create_info.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
    image_create_info.pNext = NULL;
    image_create_info.imageType = VK_IMAGE_TYPE_2D;
    image_create_info.format = VK_FORMAT_B8G8R8A8_UNORM;
    image_create_info.extent.width = 32;
    image_create_info.extent.height = 1;
    image_create_info.extent.depth = 1;
    image_create_info.mipLevels = 1;
    image_create_info.arrayLayers = 1;
    image_create_info.samples = VK_SAMPLE_COUNT_1_BIT;
    image_create_info.tiling = VK_IMAGE_TILING_OPTIMAL;
    image_create_info.usage = VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT;
    image_create_info.flags = 0;

    VkImageSubresource image_sub = VkImageObj::subresource(VK_IMAGE_ASPECT_COLOR_BIT, 0, 0);
    VkImageSubresourceRange image_sub_range = VkImageObj::subresource_range(image_sub);

    VkImageObj image(m_device);
    image.init(&image_create_info);
    ASSERT_TRUE(image.initialized());

    m_errorMonitor->ExpectSuccess();
    m_commandBuffer->begin();


    {
        VkImageMemoryBarrier image_barriers[] = {
            image.image_memory_barrier(0, VK_ACCESS_TRANSFER_WRITE_BIT, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, image_sub_range) };

        m_errorMonitor->ExpectSuccess();
        vk::CmdPipelineBarrier(m_commandBuffer->handle(), VK_PIPELINE_STAGE_ALL_COMMANDS_BIT, VK_PIPELINE_STAGE_ALL_COMMANDS_BIT, 0, 0, nullptr,
                                   0, nullptr, 1, image_barriers);
        m_errorMonitor->VerifyNotFound();
    }

    {
        VkImageMemoryBarrier image_barriers[] = {
            image.image_memory_barrier(VK_ACCESS_TRANSFER_WRITE_BIT, 104, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, VK_IMAGE_LAYOUT_GENERAL, image_sub_range),
            image.image_memory_barrier(104, 0x27, VK_IMAGE_LAYOUT_GENERAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, image_sub_range) };

        m_errorMonitor->ExpectSuccess();
        vk::CmdPipelineBarrier(m_commandBuffer->handle(), VK_PIPELINE_STAGE_ALL_COMMANDS_BIT, VK_PIPELINE_STAGE_ALL_COMMANDS_BIT, 0, 0, nullptr,
                                   0, nullptr, 2, image_barriers);
        m_errorMonitor->VerifyNotFound();
    }

    m_commandBuffer->end();

    m_commandBuffer->reset();
}
```

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #3451

### CODE REVIEW

File: tests/vkpositivelayertests.cpp [hunk 1]
```diff
@@ -16057,3 +16057,56 @@ TEST_F(VkPositiveLayerTest, DestroyQueryPoolAfterGetQueryPoolResults) {
...
+        vk::CmdPipelineBarrier(m_commandBuffer->handle(), VK_PIPELINE_STAGE_ALL_COMMANDS_BIT, VK_PIPELINE_STAGE_ALL_COMMANDS_BIT, 0,
+                               0, nullptr, 0, nullptr, 1, image_barriers);
+        m_errorMonitor->VerifyNotFound();
+    }
+
+    {
+        VkImageMemoryBarrier image_barriers[] = {
+            image.image_memory_barrier(VK_ACCESS_TRANSFER_WRITE_BIT, 104, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
+                                       VK_IMAGE_LAYOUT_GENERAL, image_sub_range),
+            image.image_memory_barrier(104, 0x27, VK_IMAGE_LAYOUT_GENERAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
```
Comment (jeremyg-lunarg) [inline tests/vkpositivelayertests.cpp:16102]: we should use the access mask bit names rather than constants (104 and 0x27)

File: layers/buffer_validation.cpp [hunk 2]
```diff
@@ -936,23 +933,32 @@ bool CoreChecks::ValidateBarriersToImages(const Location &outer_loc, const CMD_B
...
-                                         value.subresource.aspectMask, value.subresource.mipLevel, value.subresource.arrayLayer,
-                                         string_VkImageLayout(img_barrier.oldLayout), layout_check.message,
-                                         string_VkImageLayout(layout_check.layout));
+                    for (auto pos = subresource_map->Find(normalized_isr); !(pos.AtEnd()) && !subres_skip;
+                         pos.IncrementInterval()) {
+                        if (img_barrier.oldLayout == VK_IMAGE_LAYOUT_UNDEFINED) {
+                            // TODO: Set memory invalid which is in mem_tracker currently
+                        } else {
+                            const auto &value = *pos;
+                            auto old_layout = NormalizeSynchronization2Layout(test_aspect, img_barrier.oldLayout);
```
Comment (jeremyg-lunarg) [inline layers/buffer_validation.cpp:943]: probably need a comment about what this is doing.

File: layers/buffer_validation.cpp [hunk 3]
```diff
@@ -918,11 +919,7 @@ bool CoreChecks::ValidateBarriersToImages(const Location &outer_loc, const CMD_B
             }
 
             const auto *subresource_map = cb_state->GetImageSubresourceLayoutMap(img_barrier.image);
```
Comment (jeremyg-lunarg) [inline layers/buffer_validation.cpp:921]: Then here, do the lookup in layout_updates[] first. If that fails, make a copy of the result of  cb_state->GetImageSubresourceLayoutMap() and add it to layout_updates[]

File: layers/buffer_validation.cpp [hunk 4]
```diff
@@ -936,23 +933,35 @@ bool CoreChecks::ValidateBarriersToImages(const Location &outer_loc, const CMD_B
...
+                                    LogError(cb_state->commandBuffer(), vuid,
+                                             "%s %s cannot transition the layout of aspect=%d level=%d layer=%d from %s when the "
+                                             "%s layout is %s.",
+                                             loc.Message().c_str(), report_data->FormatHandle(img_barrier.image).c_str(),
+                                             value.subresource.aspectMask, value.subresource.mipLevel, value.subresource.arrayLayer,
+                                             string_VkImageLayout(img_barrier.oldLayout), layout_check.message,
+                                             string_VkImageLayout(layout_check.layout));
+                            }
                         }
+                        layout_updates[img_barrier.image][normalized_isr] = NormalizeSynchronization2Layout(test_aspect, img_barrier.newLayout);
```
Comment (jeremyg-lunarg) [inline layers/buffer_validation.cpp:964]: Then here, you call subresource_map->SetSubresourceRangeLayout(). This will update your local cache of the layout map, and avoid the need for layout_updates.find() to get current_layout. You can instead get it out of the 'pos' iterator.

File: layers/buffer_validation.cpp (hunk 3 above)
Comment (ziga-lunarg) [reply layers/buffer_validation.cpp:921]: Copying of ImageSubresourceLayoutMap seems forbidden.

**Comment by jeremyg-lunarg** [comment]
This looks like it does the right stuff, nice! Restarting manual-vvltraces and perf jobs on it.

**Comment by jeremyg-lunarg** [comment]
perf runs look ok, traces has less errors:
```
ERROR: **** Failure Summary ****
ERROR: serioussam: differences between reference errors and generated errors:
- VUID-VkImageMemoryBarrier-oldLayout-01197: 4978
ERROR: talos: differences between reference errors and generated errors:
- VUID-VkImageMemoryBarrier-oldLayout-01197: 7332
```

I bet this is the same false positive that was reported. Let me double check real quick...

**Review by jeremyg-lunarg — APPROVED** [review]
LGTM, spot check of the talos trace shows that it does have multiple barriers for the same image in single vkCmdPipelineBarrier() calls that would trigger the false positive.

**Comment by ziga-lunarg** [comment]
@jeremyg-lunarg Thanks for verifying!
