### PR TITLE
Layers: Fix fragment output compatibility check with output remapping

### LINKED ISSUE #8887: Incorect ShaderFragmentOutputMismatch warning for DRLR with location remaping
**Environment:**
 - OS: Windows 10 Pro
 - GPU and driver version: GeForce RTX 2060 SUPER
 - SDK or header version if building from repo: SDK 1.3.296.0
 - Options enabled (synchronization, best practices, etc.): SYNCHRONIZATION_VALIDATION, warn,error

**Describe the Issue**

In CTS 120+ of attachment_allocation tests for dynamic rendering report validation warning like this:
`Undefined-Value-ShaderFragmentOutputMismatch-DynamicRendering(WARN / SPEC): msgNum: 269640043 - Validation Warning: [ Undefined-Value-ShaderFragmentOutputMismatch-DynamicRendering ] Object 0: handle = 0xcfcda0000000001e, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x1012616b | vkCreateGraphicsPipelines(): pCreateInfos[0] Attachment 1 of type 'VK_FORMAT_R32G32B32A32_UINT' does not match fragment shader output type of 'pointer to Output -> vec4 of float32'; resulting values are undefined`

One of simpler tests with this issue, is:
dEQP-VK.dynamic_rendering.primary_cmd_buff.dedicated_allocation.attachment_allocation.roll.45

**Expected behavior**

roll.45 test uses 2 subpasses and 3 attachments: two uint images and one image with float format.
FS for first subpass reads two uint images and FS for second subpass reads second uint image and float image.
It seams code in [cc_shader_interface.cpp#L761](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/fdbdd359fb2bbb50352e84b259171813957d1ee3/layers/core_checks/cc_shader_interface.cpp#L761) doesn't take account for attachment location remapping provided with `VkRenderingAttachmentLocationInfoKHR` (from `VK_KHR_dynamic_rendering_local_read`).
For roll.45 test remaping is set in [vktRenderPassTests.cpp#L3126](https://github.com/KhronosGroup/VK-GL-CTS/blob/main/external/vulkancts/modules/vulkan/renderpass/vktRenderPassTests.cpp#L3126) .
Fragment shader for second subpass correctly tries to read float format at location 1 because remapping was used and shader gets at location 1 attachment that is at index 2 in pColorAttachments. It seams validation warning is printed incorrectly during pipeline creation for second subpass.

**Valid Usage ID**
Undefined-Value-ShaderFragmentOutputMismatch-DynamicRendering

### PR DESCRIPTION
**Pull request by etang-cw**
Fixes #8887

### CODE REVIEW

File: tests/unit/shader_interface.cpp [hunk 1]
```diff
@@ -1897,6 +1897,69 @@ TEST_F(NegativeShaderInterface, FragmentOutputTypeMismatchDynamicRendering) {
...
+    rendering_info.colorAttachmentCount = std::size(color_attachment);
+    rendering_info.pColorAttachments = color_attachment;
+    rendering_info.layerCount = 1;
+    rendering_info.renderArea = GetRenderTargetArea();
+
+    m_command_buffer.Begin();
+    m_command_buffer.BeginRendering(rendering_info);
+    vk::CmdBindPipeline(m_command_buffer, VK_PIPELINE_BIND_POINT_GRAPHICS, pipe);
+    vk::CmdSetRenderingAttachmentLocationsKHR(m_command_buffer, &locations_info);
+    m_errorMonitor->SetDesiredWarning("Undefined-Value-ShaderFragmentOutputMismatch-DynamicRendering");
```
Comment (spencer-lunarg) [inline tests/unit/shader_interface.cpp:1956]: this error message is now

> Inside the fragment shader, it writes to output Location 0 with a numeric type of SINT but VkRenderingInfo::pColorAttachments[0].imageView is created with VK_FORMAT_R8G8B8A8_UNORM (numeric type of FLOAT) which does not match and the resulting values written will be undefined.


which is misleading as it is actually `VkRenderingInfo::pColorAttachments[1]`

We need to adjust `Undefined-Value-ShaderFragmentOutputMismatch-DynamicRendering` (and `Undefined-Value-ShaderOutputNotConsumed-DynamicRendering`) error message to remap this

I would personally love this error message to say `VkRenderingInfo::pColorAttachments[1].imageView` and then if we detect `bool set_color_locations` we could print at the bottom of the message (in a new line) something like

> "Locations were remapped to [VK_ATTACHMENT_UNUSED, 0] in this render pass"

**Review by spencer-lunarg — CHANGES_REQUESTED** [review]
Looks great! (Thanks so much for doing all of this) but just need to fix the error message and good to go!

File: tests/unit/shader_interface.cpp (hunk 1 above)
Comment (spencer-lunarg) [reply tests/unit/shader_interface.cpp:1956]: you can use `string_Attachment` to print the location as well

Comment (etang-cw) [reply tests/unit/shader_interface.cpp:1956]: How does "Inside the fragment shader, it writes to output Location 0, which was remapped to attachment 1, with a numeric type of SINT but VkRenderingInfo::pColorAttachments[1].imageView is created with VK_FORMAT_R8G8B8A8_UNORM (numeric type of FLOAT) which does not match and the resulting values written will be undefined." sound?

Maybe parentheses "...writes to output Location 0 (which was remapped to attachment 1) with a numeric type..." would be better?

Comment (spencer-lunarg) [reply tests/unit/shader_interface.cpp:1956]: sure, ` (which was remapped to attachment 1) ` works

honestly just something to make it obvious it was remapped and not a bug that `Location 0` doesn't match `pColorAttachments[1]`

File: layers/core_checks/cc_shader_interface.cpp [hunk 2]
```diff
@@ -547,9 +547,20 @@ bool CoreChecks::ValidateFsOutputsAgainstRenderPass(const spirv::Module &module_
     return skip;
 }
 
+static std::string DescribeMappedLocation(uint32_t shader, uint32_t rendering_info) {
+    std::stringstream msg;
+    if (shader == rendering_info) {
+        msg << shader;
+    } else {
+        msg << shader << ", which was remapped to attachment " << rendering_info << ",";
```
Comment (spencer-lunarg) [inline layers/core_checks/cc_shader_interface.cpp]:
```suggestion
        msg << shader << " (which was remapped to attachment " << rendering_info << ") ";
```

also works, will leave it up to you to decide

**Comment by etang-cw** [comment]
image

Really, clang-format?

**Comment by spencer-lunarg** [comment]
> Really, clang-format?

ya, it gets wonky sometimes... anyway, when CI gets done, will get this in

**Comment by etang-cw** [comment]
Squashed the error message fix into the main layer remapping commit, everything's ready from my side.

File: layers/core_checks/cc_shader_interface.cpp (hunk 2 above)
Comment (etang-cw) [reply layers/core_checks/cc_shader_interface.cpp]: Went with this.
