### PR TITLE
gpu: Fix a race condition in submission processing

### LINKED ISSUE #7562: Performance issue with debugPrintfEXT using Vulkan 1.1
**Environment:**
 - OS: Windows 11
 - GPU and driver version: NVIDIA RTX 4070 538.42
 - SDK or header version if building from repo: SDK 1.3.275
 - Options enabled (synchronization, best practices, etc.): -

**Describe the Issue**

When using `debugPrintfEXT` along with `VkValidationFeaturesEXT` to fetch the debug output with a debug messenger callback, performance is so severely impacted, that the application is no longer interactive.

The setup:

Application:

```cpp
	std::vector<VkValidationFeatureEnableEXT>  validation_feature_enables = {VK_VALIDATION_FEATURE_ENABLE_DEBUG_PRINTF_EXT};
	std::vector<VkValidationFeatureDisableEXT> disables{};

	VkValidationFeaturesEXT validation_features{VK_STRUCTURE_TYPE_VALIDATION_FEATURES_EXT};
	validation_features.enabledValidationFeatureCount = 1;
	validation_features.pEnabledValidationFeatures    = validation_feature_enables.data();
	validation_features.pDisabledValidationFeatures   = 0;
	validation_features.pDisabledValidationFeatures   = disables.data();

	VkApplicationInfo app_info{VK_STRUCTURE_TYPE_APPLICATION_INFO};
	app_info.pApplicationName = "Shader debugprintf";
	app_info.pEngineName      = "Vulkan Samples";
	app_info.apiVersion       = VK_API_VERSION_1_2;

	std::vector<const char *> validation_layers = {"VK_LAYER_KHRONOS_validation"};

	VkInstanceCreateInfo instance_create_info{VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO};
	instance_create_info.ppEnabledExtensionNames = enabled_extensions.data();
	instance_create_info.enabledExtensionCount   = static_cast<uint32_t>(enabled_extensions.size());
	instance_create_info.pApplicationInfo        = &app_info;
	instance_create_info.pNext                   = &validation_features;
	instance_create_info.ppEnabledLayerNames     = validation_layers.data();
	instance_create_info.enabledLayerCount       = static_cast<uint32_t>(validation_layers.size());

	VkInstance vulkan_instance;
	result = vkCreateInstance(&instance_create_info, nullptr, &vulkan_instance);

	VkDebugUtilsMessengerCreateInfoEXT debug_utils_messenger_create_info{VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT};
	debug_utils_messenger_create_info.messageSeverity = VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT;
	debug_utils_messenger_create_info.messageType     = VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT;
	debug_utils_messenger_create_info.pfnUserCallback = debug_utils_message_callback;

	VK_CHECK(vkCreateDebugUtilsMessengerEXT(vulkan_instance, &debug_utils_messenger_create_info, nullptr, &debug_utils_messenger));
```

Vertex shader:
```glsl
	if (gl_VertexIndex == 0) {
		debugPrintfEXT("Position = %v4f", outPos);
	}
```
After some debugging with a minimal sample, I noticed that this only happens with Vulkan 1.1 (set in `VkApplicationInfo`). Using any other api version, performance is fine.

Summary:
* VK_API_VERSION_1_0:
  * Debug output works, performance is fine, even though it shouldn't work at all with VK 1.0
* VK_API_VERSION_1_1:
  *  Debug output works, severe slowdown, application is pretty much unusable
* VK_API_VERSION_1_2 and VK_API_VERSION_1_3:
  *  Debug output works, performance is fine

I can only imagine that the combination of `debugPrintfEXT`, `VkValidationFeaturesEXT`  and `VK_API_VERSION_1_1`  triggers an odd constellation in the layers that somehow causes a severe slowdown.

**Expected behavior**

Using `debugPrintfEXT` with `VkValidationFeaturesEXT` shows the same performance no matter what API version.

**Valid Usage ID**
n/a

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**
Move most submission post processing into the PostCallRecord hooks. This avoids adding submission state in the PreCall hook and then looking for it in the PostCall hook. It also avoids adding bad state in case  the submit call fails.

The remaining work in the PreCall hook is setting up resources used by the instrumented shaders we're about to execute and that must happen  before the submit is dispatched.

This problem was hidden by sometimes calling the wrong version (core vs KHR) of vkWaitSemaphores(), which would end up calling a no-op stub set up elsewhere in VVL (and being fixed separately). So if we're using vulkan 1.2 or greater we use the core versions, if we're in 1.1 and have enabled the extensions, use the KHR versions.

Fixes #7562

### CODE REVIEW

File: layers/gpu/core/gpu_state_tracker.cpp [hunk 1]
```diff
@@ -25,9 +25,35 @@ CommandBuffer::CommandBuffer(gpu::GpuShaderInstrumentor &shader_instrumentor, Vk
     : vvl::CommandBuffer(shader_instrumentor, handle, pCreateInfo, pool) {}
 
 Queue::Queue(gpu::GpuShaderInstrumentor &shader_instrumentor, VkQueue q, uint32_t family_index, uint32_t queue_index,
-             VkDeviceQueueCreateFlags flags, const VkQueueFamilyProperties &queueFamilyProperties)
+             VkDeviceQueueCreateFlags flags, const VkQueueFamilyProperties &queueFamilyProperties, bool timeline_khr)
     : vvl::Queue(shader_instrumentor, q, family_index, queue_index, flags, queueFamilyProperties),
+<<<<<<< HEAD
```
Comment (spencer-lunarg) [inline layers/gpu/core/gpu_state_tracker.cpp:30]: image

File: layers/gpu/core/gpu_state_tracker.cpp [hunk 2]
```diff
@@ -25,9 +25,24 @@ CommandBuffer::CommandBuffer(gpu::GpuShaderInstrumentor &shader_instrumentor, Vk
...
+      shader_instrumentor_(shader_instrumentor),
+      timeline_khr_(timeline_khr) {
+    VkSemaphoreTypeCreateInfoKHR semaphore_type_create_info = vku::InitStructHelper();
+    semaphore_type_create_info.semaphoreType = VK_SEMAPHORE_TYPE_TIMELINE_KHR;
+    semaphore_type_create_info.initialValue = 0;
+
+    VkSemaphoreCreateInfo semaphore_create_info = vku::InitStructHelper(&semaphore_type_create_info);
+
+    auto result = DispatchCreateSemaphore(shader_instrumentor_.device, &semaphore_create_info, nullptr, &barrier_sem_);
+    assert(result == VK_SUCCESS);
```
Comment (spencer-lunarg) [inline layers/gpu/core/gpu_state_tracker.cpp:39]: we don't need this assert if we have the full blown `InternalError` to catch it below

File: layers/gpu/core/gpu_state_tracker.cpp [hunk 3]
```diff
@@ -25,9 +25,24 @@ CommandBuffer::CommandBuffer(gpu::GpuShaderInstrumentor &shader_instrumentor, Vk
...
+    if (result != VK_SUCCESS) {
+        Location loc(vvl::Func::vkGetDeviceQueue);
+        shader_instrumentor_.InternalError(shader_instrumentor_.device, loc, "Unable to create barrier semaphore. result=%d",
+                                           result);
```
Comment (spencer-lunarg) [inline layers/gpu/core/gpu_state_tracker.cpp:43]: 1. `string_VkResult()`
2. `InternalError` is not a variadic function, `result` here is setting a boolean

File: layers/gpu/core/gpu_state_tracker.cpp [hunk 4]
```diff
@@ -116,44 +116,38 @@ void Queue::SubmitBarrier(const Location &loc, uint64_t seq) {
         submit_info.signalSemaphoreCount = 1;
         submit_info.pSignalSemaphores = &barrier_sem_;
 
-        DispatchQueueSubmit(vvl::Queue::VkHandle(), 1, &submit_info, VK_NULL_HANDLE);
+        auto result = DispatchQueueSubmit(vvl::Queue::VkHandle(), 1, &submit_info, VK_NULL_HANDLE);
+        assert(result == VK_SUCCESS);
```
Comment (spencer-lunarg) [inline layers/gpu/core/gpu_state_tracker.cpp:120]: CI is about to barf that `result` is unused in release build

File: layers/gpu/core/gpu_state_tracker.cpp [hunk 5]
```diff
@@ -116,44 +116,38 @@ void Queue::SubmitBarrier(const Location &loc, uint64_t seq) {
...
     vvl::Queue::Retire(submission);
     retiring_.emplace_back(submission.cbs);
     if (submission.end_batch) {
         VkSemaphoreWaitInfo wait_info = vku::InitStructHelper();
         wait_info.semaphoreCount = 1;
         wait_info.pSemaphores = &barrier_sem_;
-        wait_info.pValues = &submission.seq;
-        DispatchWaitSemaphoresKHR(shader_instrumentor_.device, &wait_info, 1000000000);
+        wait_info.pValues = &wait_seq;
+        VkResult result;
```
Comment (spencer-lunarg) [inline layers/gpu/core/gpu_state_tracker.cpp:144]: CI is about to barf that `result` is unused in release build

probably good to replace assert with `InternalError` call

**Comment by spencer-lunarg** [comment]
@jeremyg-lunarg confirmed this change fixes the issue!

File: layers/gpu/core/gpu_state_tracker.cpp (hunk 3 above)
Comment (jeremyg-lunarg) [reply layers/gpu/core/gpu_state_tracker.cpp:43]: bleah

Comment (jeremyg-lunarg) [reply layers/gpu/core/gpu_state_tracker.cpp:43]: I've never actually seen this fail so I'm going to skip the pain of printing the value of result.

File: layers/gpu/core/gpu_state_tracker.cpp (hunk 5 above)
Comment (jeremyg-lunarg) [reply layers/gpu/core/gpu_state_tracker.cpp]: oh i missed this one. That is a good idea.

**Review by spencer-lunarg — APPROVED** [review]
