### PR TITLE
corechecks: Fix bad instance cast

### LINKED ISSUE #9854: vkGetDeviceGroupSurfacePresentModesKHR crashes
Any call to `vkGetDeviceGroupSurfacePresentModesKHR()` seems to crash in `vku::concurrent::unordered_map`

```
TEST_F(PositiveWsi, GetDeviceGroupSurfacePresentModes) {
    AddSurfaceExtension();
    RETURN_IF_SKIP(Init());
    RETURN_IF_SKIP(InitSwapchain());

    VkDeviceGroupPresentModeFlagsKHR present_mode_flags;
    vk::GetDeviceGroupSurfacePresentModesKHR(m_device->handle(), m_surface.Handle(), &present_mode_flags);
}

```

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**
CoreChecks::PreCallValidateGetDeviceGroupSurfacePresentModesKHR wants to call a validation method in the core::Instance class but it was using instance_state, which is the state tracker instead of in instance_proxy which is the core::Instance object. Bleah.

Fixes #9854

### CODE REVIEW

**Review by ziga-lunarg — APPROVED** [review]

File: layers/core_checks/cc_wsi.cpp [hunk 1]
```diff
@@ -1507,7 +1507,7 @@ bool CoreChecks::PreCallValidateGetDeviceGroupSurfacePresentModesKHR(VkDevice de
                                                                      VkDeviceGroupPresentModeFlagsKHR *pModes,
                                                                      const ErrorObject &error_obj) const {
     bool skip = false;
-    const auto *core_instance = reinterpret_cast<core::Instance *>(instance_state);
+    const auto *core_instance = dynamic_cast<core::Instance *>(instance_proxy);
```
Comment (spencer-lunarg) [inline layers/core_checks/cc_wsi.cpp:1510]: image

**Review by spencer-lunarg — APPROVED** [review]

File: layers/core_checks/cc_wsi.cpp (hunk 1 above)
Comment (artem-lunarg) [inline layers/core_checks/cc_wsi.cpp:1510]: If result of dymamic_cast is not checked because we know the type then it's the case for:
image

Comment (jeremyg-lunarg) [reply layers/core_checks/cc_wsi.cpp:1510]: well clearly we didn't know the type in the original code and dynamic_cast will at least return null

**Review by artem-lunarg — APPROVED** [review]

File: layers/core_checks/cc_wsi.cpp (hunk 1 above)
Comment (jeremyg-lunarg) [reply layers/core_checks/cc_wsi.cpp]: c++ casts are the worst. I guess I will change this to static_cast so I stop getting memed
