### PR TITLE
corechecks: Improve core_error::Location to VUID lookups

### LINKED ISSUE #2616: timeline_semaphore ValidationStateTracker::PostCallRecordQueueSubmit error
The test in `ValidationStateTracker::PostCallRecordQueueSubmit` is incorrect, as it can access the array of signal or wait semaphore without checking its size. I hit the issue while I have a binary semaphore for wait and timeline semaphore in signal. 

The second issue, it is accessing the timeline semaphore info index, from the global semaphore index. Meaning that if you have a mix of semaphores binary/timeline, the index will be incorrect.

This seems new from 
 - SDK 1.2.170.0

Here is a suggested fix for `ValidationStateTracker::PostCallRecordQueueSubmit()`
See modification in the two for-loop.

```
void ValidationStateTracker::PostCallRecordQueueSubmit(VkQueue queue, uint32_t submitCount, const VkSubmitInfo *pSubmits,
                                                       VkFence fence, VkResult result) {
    if (result != VK_SUCCESS) return;
    auto queue_state = GetQueueState(queue);

    uint64_t early_retire_seq = RecordSubmitFence(queue_state, fence, submitCount);

    // Now process each individual submit
    for (uint32_t submit_idx = 0; submit_idx < submitCount; submit_idx++) {
        CB_SUBMISSION submission;
        const VkSubmitInfo *submit = &pSubmits[submit_idx];
        const uint64_t next_seq = queue_state->seq + queue_state->submissions.size() + 1;
        auto *timeline_semaphore_submit = LvlFindInChain<VkTimelineSemaphoreSubmitInfo>(submit->pNext);
        for (uint32_t i = 0; i < submit->waitSemaphoreCount; ++i) {
            uint64_t w_idx = 0;
            uint64_t value = timeline_semaphore_submit && timeline_semaphore_submit->waitSemaphoreValueCount > w_idx
                                 ? timeline_semaphore_submit->pWaitSemaphoreValues[w_idx]
                                 : 0;
            if (GetSemaphoreState(submit->pWaitSemaphores[i])->type == VK_SEMAPHORE_TYPE_TIMELINE) w_idx++;
            RecordSubmitWaitSemaphore(submission, queue, submit->pWaitSemaphores[i], value, next_seq);
        }

        bool retire_early = false;
        for (uint32_t i = 0; i < submit->signalSemaphoreCount; ++i) {
            uint64_t s_idx = 0;
            uint64_t value = timeline_semaphore_submit && timeline_semaphore_submit->signalSemaphoreValueCount > s_idx
                                 ? timeline_semaphore_submit->pSignalSemaphoreValues[s_idx]
                                 : 0;
            if (GetSemaphoreState(submit->pWaitSemaphores[i])->type == VK_SEMAPHORE_TYPE_TIMELINE) s_idx++;
            retire_early |= RecordSubmitSignalSemaphore(submission, queue, submit->pSignalSemaphores[i], value, next_seq);
        }
        if (retire_early) {
            early_retire_seq = std::max(early_retire_seq, next_seq);
        }

        const auto perf_submit = LvlFindInChain<VkPerformanceQuerySubmitInfoKHR>(submit->pNext);
        submission.perf_submit_pass = perf_submit ? perf_submit->counterPassIndex : 0;

        for (uint32_t i = 0; i < submit->commandBufferCount; i++) {
            RecordSubmitCommandBuffer(submission, submit->pCommandBuffers[i]);
        }
        submission.fence = submit_idx == (submitCount - 1) ? fence : VK_NULL_HANDLE;
        queue_state->submissions.emplace_back(std::move(submission));
    }

    if (early_retire_seq) {
        RetireWorkOnQueue(queue_state, early_retire_seq);
    }
}
```

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**
Make the fuzzy matching of location to VUID be based on
    enums rather than strings. Also try to assert() if there's
    a problem with the lookup (in debug builds).

### CODE REVIEW

File: layers/core_error_location.h [hunk 1]
```diff
@@ -204,4 +199,56 @@ struct LocationCapture {
...
+
+    // consistency check: there should never be more than 1 match in a table
+    assert(std::count_if(table.begin(), table.end(), predicate) <= 1);
+
+    const auto pos = std::find_if(table.begin(), table.end(), predicate);
+    return (pos != table.end()) ? pos->v : empty;
+}
+
+// 2-level look up where the outer container is a map where we need to find
+// have different VUIDs for different values of an enum or bitfield
```
Comment (ncesario-lunarg) [inline layers/core_error_location.h:243]: "find have" -> "find"?

File: layers/sync_vuid_maps.cpp [hunk 2]
```diff
@@ -77,592 +56,657 @@ static const std::string &FindVUID(const Struct &structure, const Field &field,
...
-        if (!result.empty()) {
-            return result;
-        }
+    const auto &result = FindVUID(bit, loc, kAccessMask2Common);
+    if (!result.empty()) {
+        return result;
     }
-    const auto &result2 = FindVUID(loc.structure, loc.field, kFineSyncCommon);
+    const auto &result2 = FindVUID(loc, kFineSyncCommon);
     assert(!result2.empty());
```
Comment (ncesario-lunarg) [inline layers/sync_vuid_maps.cpp:622]: Since `result2.empty()` is now handled, does it make sense to get rid of the assert? There are several other instances like this.

File: layers/sync_vuid_maps.cpp [hunk 3]
```diff
@@ -677,93 +721,177 @@ const std::map<QueueError, std::string> kQueueErrorSummary{
...
 
 const std::string &GetImageBarrierVUID(const Location &loc, ImageError error) {
-    const auto entry = kImageErrors.find(error);
-    assert(entry != kImageErrors.end());
-
-    const auto &result = FindVUID(loc.structure, Field::Empty, entry->second);
-    if (!result.empty()) {
-        return result;
+    const auto &result = FindVUID(error, loc, kImageErrors);
+    assert(!result.empty());
```
Comment (ncesario-lunarg) [inline layers/sync_vuid_maps.cpp:889]: Seems like this should be removed?

**Review by ncesario-lunarg — APPROVED** [review]
Some minor comments/questions, but otherwise LGTM!

File: layers/sync_vuid_maps.cpp (hunk 3 above)
Comment (jeremyg-lunarg) [reply layers/sync_vuid_maps.cpp:889]: yes, GetImageBarrierVUID looks incorrect. I will fix it and retest...

File: layers/sync_vuid_maps.cpp (hunk 2 above)
Comment (jeremyg-lunarg) [reply layers/sync_vuid_maps.cpp:622]: No.  In the cases where there are assert() and then error handling, this is a programmer error that we don't want to get out into the wild. But if it does, we don't want to give an empty string for the VUID because it is super confusing. There's been several cases of this already.

Comment (ncesario-lunarg) [reply layers/sync_vuid_maps.cpp:622]: Ok.

In general (I'm not suggesting any changes for this PR), I would think a "raw assert" is mostly for, "if this happens, we will crash." If it's something that _can_ happen and is handled appropriately at runtime, a "wrapped assert" (e.g., `VVL_EXPECT(!result2.empty);` which just expands to `assert`) might be clearer; otherwise it's a bit confusing (to me at least).

Comment (jeremyg-lunarg) [reply layers/sync_vuid_maps.cpp:622]: Yeah that makes sense, I'll look at making something like that the next time this comes up...

**Comment by jeremyg-lunarg** [comment]
This change passed internal CI in job 4195
