### PR TITLE
Disable test when needed format not avail

### LINKED ISSUE #263: VkLayerTest.DSAspectBitsErrors test fails on Fedora 28 with Intel Mesa
On Fedora 28, with Mesa 18.0.5 or Mesa 18.1.4, the VkLayerTest.DSAspectBitsErrors test fails.

```
[john@localhost tests]$ ./vk_layer_validation_tests --gtest_filter=VkLayerTest.DSAspectBitsErrors
Note: Google Test filter = VkLayerTest.DSAspectBitsErrors
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from VkLayerTest
[ RUN      ] VkLayerTest.DSAspectBitsErrors
INTEL-MESA: warning: Haswell Vulkan support is incomplete
/home/lunarg/Development/Vulkan-Validation/tests/vkrenderframework.cpp:921: Failure
Failed
VkImageObj::init() error: unsupported tiling configuration. Usage: 0x4, supported linear features: 0
Unexpected:  [ UNASSIGNED-GeneralParameterError-RequiredParameter ] Object: VK_NULL_HANDLE (Type = 0) | vkCmdPipelineBarrier: required parameter pImageMemoryBarriers[0].image specified as VK_NULL_HANDLE
Unexpected:  [ VUID-VkImageMemoryBarrier-image-parameter ] Object: VK_NULL_HANDLE (Type = 10) | Invalid Image Object 0x0. The spec valid usage text states 'image must be a valid VkImage handle' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageMemoryBarrier-image-parameter)
Segmentation fault (core dumped)
```

### PR DESCRIPTION
**Pull request by jzulauf-lunarg**
Fixes #263

VkLayerTest.DSAspectBitsErrors was failing as the depth stencil formats
on certain platforms did not support VK_IMAGE_USAGE_SAMPLED_BIT.

This test is now skipped for these platforms.

Change-Id: I5ac270e976a3e1e2163a6111da6d66c8c7352a89

### CODE REVIEW

**Comment by jzulauf-lunarg** [comment]
@johnzupin -- could you pull this and test against your test system?

File: tests/vkrenderframework.cpp [hunk 1]
```diff
@@ -957,6 +957,8 @@ void VkImageObj::Init(uint32_t const width, uint32_t const height, uint32_t cons
                       const std::vector<uint32_t> *queue_families) {
     InitNoLayout(width, height, mipLevels, format, usage, requested_tiling, reqs, queue_families);
 
+	if (!initialized()) return; // We don't have a valid handle from early stage init, and thus SetLayout will fail
```
Comment (jzulauf-lunarg) [inline tests/vkrenderframework.cpp]: Framework didn't survive the Init to get to my application check. Tried to SetLayout with VK_NULL_HANDLE ... so added this.

**Comment by johnzupin** [comment]
Looks good!
