### PR TITLE
layers: Fix clearing heap state

### LINKED ISSUE #12124: Crashes and spurious errors with descriptor heap in CTS
**Environment:**
 - OS: Fedora Linux 43
 - GPU and driver version: RADV from https://gitlab.freedesktop.org/hakzsam/mesa/-/tree/radv_smem_null_prt_wa with `RADV_EXPERIMENTAL=heap` in the environment.
 - SDK or header version if building from repo: 46c36dbf064fdeb7a8267bc6e967907c7c2f8ea8
 - Options enabled (synchronization, best practices, etc.): defaults + synchronization

**Describe the Issue**

I've written some new tests that happen to use descriptor heap in a very simple manner: a compute shader that accesses a couple of resources. I created descriptor heap variants of those tests and used mappings so I wouldn't have to change the shaders. Because this was my first time using descriptor heap, I'm not completely sure the tests are fully correct. However, what I've observed is that repeatedly running the tests from the command line results in:

* Sometimes the tests passing without validation issues.
* Sometimes I get what appear to be spurious validation errors.
* Sometimes the process segfaults in the layers.
* When run under Valgrind, it detects invalid accesses to deleted memory.
* When running without validation, all tests always pass (NB they are designed to hit a RADV issue, so if you use RADV you need the branch that has the fix).

More info about the gerrit CL and internal issue below.

**Expected behavior**

Likely the tests are correct, so no validation errors and no crashes.

**Valid Usage ID**

Some probably spurious `VUID-vkCmdBindResourceHeapEXT-pBindInfo-11236` errors.

**Additional context**

<details>
<summary>Valgrind details</summary>

* Khronos Gitlab: https://gitlab.khronos.org/Tracker/vk-gl-cts/-/issues/6461
* Gerrit CL: 20153
* Test glob: dEQP-VK.sparse_resources.buffer.misc.null_address*

```sh
==292807== Invalid read of size 8
==292807==    at 0x4848E7AD: vvl::range<unsigned long>::includes(unsigned long const&) const (layers/./containers/range.h:36)
==292807==    by 0x485160A0: vvl::range<unsigned long>::intersects(vvl::range<unsigned long> const&) const (layers/./containers/range.h:40)
==292807==    by 0x4857AA9F: CoreChecks::ValidateReservedRangeOverlap(vvl::CommandBuffer const&, VkBindHeapInfoEXT const*, Location const&) const (layers/core_checks/cc_descriptor.cpp:5625)
==292807==    by 0x4857B98F: CoreChecks::PreCallValidateCmdBindResourceHeapEXT(VkCommandBuffer_T*, VkBindHeapInfoEXT const*, ErrorObject const&) const (layers/core_checks/cc_descriptor.cpp:5704)
==292807==    by 0x48A44999: vulkan_layer_chassis::CmdBindResourceHeapEXT(VkCommandBuffer_T*, VkBindHeapInfoEXT const*) (layers/vulkan/generated/chassis.cpp:22583)
==292807==    by 0x4F46BD8: vk::DeviceDriver::cmdBindResourceHeapEXT(vk::VkCommandBuffer_s*, vk::VkBindHeapInfoEXT const*) const (external/vulkancts/framework/vulkan/generated/vulkan/vkDeviceDriverImpl.inl:1693)
==292807==    by 0x328526E: vkt::sparse::(anonymous namespace)::NullAddressInstance::iterate()::$_2::operator()(std::vector<unsigned int, std::allocator<unsigned int> >&, std::vector<unsigned int, std::allocator<unsigned int> > const&) const (external/vulkancts/modules/vulkan/sparse_resources/vktSparseResourcesBufferTests.cpp:2694)
==292807==    by 0x32843AE: vkt::sparse::(anonymous namespace)::NullAddressInstance::iterate() (external/vulkancts/modules/vulkan/sparse_resources/vktSparseResourcesBufferTests.cpp:2772)
==292807==    by 0x1792C04: vkt::TestCaseExecutor::iterate(tcu::TestCase*) (external/vulkancts/modules/vulkan/vktTestPackage.cpp:774)
==292807==    by 0x58B9029: tcu::TestSessionExecutor::iterateTestCase(tcu::TestCase*) (framework/common/tcuTestSessionExecutor.cpp:370)
==292807==    by 0x58B7BCE: tcu::TestSessionExecutor::iterate() (framework/common/tcuTestSessionExecutor.cpp:144)
==292807==    by 0x586AB6C: tcu::App::iterate() (framework/common/tcuApp.cpp:237)
==292807==  Address 0x4ba0c290 is 3,792 bytes inside a block of size 6,144 free'd
==292807==    at 0x69DD108: operator delete(void*, unsigned long) (vg_replace_malloc.c:1184)
==292807==    by 0x52B62A1: std::__new_allocator<glslang::TSourceLoc>::deallocate(glslang::TSourceLoc*, unsigned long) (new_allocator.h:172)
==292807==    by 0x52B626B: deallocate (alloc_traits.h:649)
==292807==    by 0x52B626B: std::_Vector_base<glslang::TSourceLoc, std::allocator<glslang::TSourceLoc> >::_M_deallocate(glslang::TSourceLoc*, unsigned long) (stl_vector.h:396)
==292807==    by 0x52B601D: std::vector<glslang::TSourceLoc, std::allocator<glslang::TSourceLoc> >::_Guard_alloc::~_Guard_alloc() (stl_vector.h:1883)
==292807==    by 0x52B5D8C: void std::vector<glslang::TSourceLoc, std::allocator<glslang::TSourceLoc> >::_M_realloc_append<glslang::TSourceLoc const&>(glslang::TSourceLoc const&) (vector.tcc:640)
==292807==    by 0x52B5A4A: std::vector<glslang::TSourceLoc, std::allocator<glslang::TSourceLoc> >::push_back(glslang::TSourceLoc const&) (stl_vector.h:1427)
==292807==    by 0x52B483F: glslang::TPpContext::scanToken(glslang::TPpToken*) (external/glslang/src/glslang/MachineIndependent/preprocessor/PpContext.h:379)
==292807==    by 0x52C3C40: glslang::TPpContext::tokenize(glslang::TPpToken&) (external/glslang/src/glslang/MachineIndependent/preprocessor/PpScanner.cpp:1231)
==292807==    by 0x525148C: glslang::TScanContext::tokenize(glslang::TPpContext*, glslang::TParserToken&) (external/glslang/src/glslang/MachineIndependent/Scan.cpp:837)
==292807==    by 0x5251432: yylex(YYSTYPE*, glslang::TParseContext&) (external/glslang/src/glslang/MachineIndependent/Scan.cpp:296)
==292807==    by 0x515B829: yyparse(glslang::TParseContext*) (glslang_tab.cpp:5398)
==292807==    by 0x520551B: glslang::TParseContext::parseShaderStrings(glslang::TPpContext&, glslang::TInputScanner&, bool) (external/glslang/src/glslang/MachineIndependent/ParseHelper.cpp:199)
==292807==  Block was alloc'd at
==292807==    at 0x69D92AC: operator new(unsigned long) (vg_replace_malloc.c:488)
==292807==    by 0x52B6162: std::__new_allocator<glslang::TSourceLoc>::allocate(unsigned long, void const*) (new_allocator.h:151)
==292807==    by 0x52B5F4F: allocate (alloc_traits.h:614)
==292807==    by 0x52B5F4F: std::_Vector_base<glslang::TSourceLoc, std::allocator<glslang::TSourceLoc> >::_M_allocate(unsigned long) (stl_vector.h:387)
==292807==    by 0x52B5C56: void std::vector<glslang::TSourceLoc, std::allocator<glslang::TSourceLoc> >::_M_realloc_append<glslang::TSourceLoc const&>(glslang::TSourceLoc const&) (vector.tcc:572)
==292807==    by 0x52B5A4A: std::vector<glslang::TSourceLoc, std::allocator<glslang::TSourceLoc> >::push_back(glslang::TSourceLoc const&) (stl_vector.h:1427)
==292807==    by 0x52B483F: glslang::TPpContext::scanToken(glslang::TPpToken*) (external/glslang/src/glslang/MachineIndependent/preprocessor/PpContext.h:379)
==292807==    by 0x52C3C40: glslang::TPpContext::tokenize(glslang::TPpToken&) (external/glslang/src/glslang/MachineIndependent/preprocessor/PpScanner.cpp:1231)
==292807==    by 0x525148C: glslang::TScanContext::tokenize(glslang::TPpContext*, glslang::TParserToken&) (external/glslang/src/glslang/MachineIndependent/Scan.cpp:837)
==292807==    by 0x5251432: yylex(YYSTYPE*, glslang::TParseContext&) (external/glslang/src/glslang/MachineIndependent/Scan.cpp:296)
==292807==    by 0x515B829: yyparse(glslang::TParseContext*) (glslang_tab.cpp:5398)
==292807==    by 0x520551B: glslang::TParseContext::parseShaderStrings(glslang::TPpContext&, glslang::TInputScanner&, bool) (external/glslang/src/glslang/MachineIndependent/ParseHelper.cpp:199)
==292807==    by 0x525EBD5: (anonymous namespace)::InitializeSymbolTable(std::__cxx11::basic_string<char, std::char_traits<char>, glslang::pool_allocator<char> > const&, int, EProfile, glslang::SpvVersion const&, EShLanguage, glslang::EShSource, TInfoSink&, glslang::TSymbolTable&) (external/glslang/src/glslang/MachineIndependent/ShaderLang.cpp:281)
```

Note the blocks had been allocated and freed by CTS, so maybe the layers are simply using garbage data when verifying reserved ranges in the heap.

</details>

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #12124

### CODE REVIEW

**Comment by ziga-lunarg** [comment]
There is already a comment in line 242 above `CommandBuffer::SetDescriptorMode()` that starts with `This tracking is awful`, so I didn't seem like additional comments were necessary

File: layers/state_tracker/cmd_buffer_state.cpp [hunk 1]
```diff
@@ -345,6 +345,7 @@ void CommandBuffer::ResetCBState() {
     linked_command_buffers.clear();
     bound_tile_memory = nullptr;
 
+    SetDescriptorMode(vvl::DescriptorModeUnknown, vvl::Func::Empty);
```
Comment (spencer-lunarg) [inline layers/state_tracker/cmd_buffer_state.cpp:350]: @ziga-lunarg "why" is this the fix

why does the order here matter? (a comment would be good)

Comment (ziga-lunarg) [reply layers/state_tracker/cmd_buffer_state.cpp:350]: I just typed my reason why above:

There is already a comment in line 242 above CommandBuffer::SetDescriptorMode() that starts with `This tracking is awful`, so I didn't seem like additional comments were necessary

Comment (ziga-lunarg) [reply layers/state_tracker/cmd_buffer_state.cpp:350]: I added a comment, but this really needs a better fix

Comment (spencer-lunarg) [reply layers/state_tracker/cmd_buffer_state.cpp:350]: agree, but your new comment is REALLY helpful when I need to cache this in my brain when we try to fix this

**Review by spencer-lunarg — APPROVED** [review]

**Comment by spencer-lunarg** [comment]
> CI Vulkan-ValidationLayers build # 23190 failed.

unrelated
