### PR TITLE
Fix issue 3350, Fix checking if memory is multi instance

### LINKED ISSUE #3350: VUID-vkMapMemory-memory-00683 being incorrectly reported for multiple apps
**Describe the Issue**
Support for VUID-vkMapMemory-memory-00683 was added in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2084, but the conditions for the error are incorrect.

The error check in code only tests if the VK_MEMORY_HEAP_MULTI_INSTANCE_BIT flag was present on the memory type of the memory being allocated; this is allowed to be true for any memory types, even when a device group is not created - as this query is from a physical device, not a logical device (so has no knowledge of current device groups).

The error check should not be testing for this - instead it should be testing whether multiple instances are _actually_ allocated, as indicated by multiple unique values in `VkBindBufferMemoryDeviceGroupInfo::pDeviceIndices`. The bit flag is completely allowed in the memory type as long as only one instance is actually allocated.

This is causing at least some applications to suddenly start failing validation with the latest SDK due to this one issue.

**Valid Usage ID**
VUID-vkMapMemory-memory-00683

**Environment:**
 - OS: Linux
 - GPU: AMD Radeon 570 (Using AMDVLK)
 - SDK or header version if building from repo: Latest SDK
 - Options enabled (synchronization, best practices, etc.): Core Validation

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #3350

### CODE REVIEW

**Review by ncesario-lunarg — APPROVED** [review]
LGTM!

File: layers/device_memory_state.cpp [hunk 1]
```diff
@@ -65,7 +65,7 @@ static bool IsMultiInstance(const VkMemoryAllocateInfo *p_alloc_info, const VkMe
         auto dev_mask = alloc_flags->deviceMask;
         return ((dev_mask != 0) && (dev_mask & (dev_mask - 1))) != 0;
     } else {
-        return (memory_heap.flags & VK_MEMORY_HEAP_MULTI_INSTANCE_BIT) != 0;
+        return false;
```
Comment (Tobski) [inline layers/device_memory_state.cpp:68]: Ah I didn't realise this would go through so quickly - this change is too conservative and will now _miss_ actual errors.

The check should look something like this:

```c
if (alloc_flags) {
    auto dev_mask = alloc_flags->deviceMask;
    return ((dev_mask != 0) && (dev_mask & (dev_mask - 1))) != 0;
}
if (dev_data->deviceCount > 1) { // Psuedo code - this information isn't actually available here atm
    return (memory_heap.flags & VK_MEMORY_HEAP_MULTI_INSTANCE_BIT) != 0;
}
return false;
```

This is as described by this spec language:

> If VK_MEMORY_ALLOCATE_DEVICE_MASK_BIT is not set, the number of instances allocated depends on whether VK_MEMORY_HEAP_MULTI_INSTANCE_BIT is set in the memory heap. If VK_MEMORY_HEAP_MULTI_INSTANCE_BIT is set, then memory is allocated for every physical device in the logical device (as if deviceMask has bits set for all device indices). If VK_MEMORY_HEAP_MULTI_INSTANCE_BIT is not set, then a single instance of memory is allocated (as if deviceMask is set to one).

Basically, if there's only one device, memory with this flag is fine if no device mask is set - if the device is a group of more devices, then it's implicitly not fine. 

This is part of the language describing [VkMemoryAllocateFlagsInfo](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkMemoryAllocateFlagsInfo.html).

Comment (Tobski) [reply layers/device_memory_state.cpp:68]: @ziga-lunarg Let me know if you want me to raise this as a separate issue, which I will do anyway if I don't hear back from you by tomorrow.

Comment (ziga-lunarg) [reply layers/device_memory_state.cpp:68]: @Tobski Thanks for the help. I missed this as it wasn't clear for the VUID alone, I will fix it.

Comment (ziga-lunarg) [reply layers/device_memory_state.cpp:68]: You can create an issue, I will probably fix it tomorrow.
