### PR TITLE
syncval: Cleanup vkPipelineBarrier2 validation

### LINKED ISSUE #2560: syncval: unaddressed review comment in SyncOpPipelineBarrier::Validate
**Describe the Issue**

In PR 2559, @jzulauf-lunarg  said:
This is safely wrong, and reflects a misapprehension about PipelineBarrier2... only one barrier set. Should just assert and look up the 0th one... but this code parallels the WaitEvents2 path incorrectly, but with correct results except for the odd barrier_set_string in the error message. @jeremyg-lunarg -- this is an @jzulauf-lunarg error, don't know if you want it cleaned up.

We need to fix this in a separate PR

### PR DESCRIPTION
**Pull request by jzulauf-lunarg**
Initial revision had excess support for multiple barrier sets which the
entry point doesn't support, which is now removed.

Fixes #2560

### CODE REVIEW

File: layers/synchronization_validation.cpp [hunk 1]
```diff
@@ -5033,32 +5033,26 @@ bool SyncOpPipelineBarrier::Validate(const CommandBufferAccessContext &cb_contex
...
-                                            cb_context.FormatUsage(hazard).c_str());
-            }
+    const auto &barrier_set = barriers_[0];
+    for (const auto &image_barrier : barrier_set.image_memory_barriers) {
+        if (image_barrier.new_layout == image_barrier.old_layout) continue;  // Only interested in layout transitions at this point.
+        const auto *image_state = image_barrier.image.get();
+        if (!image_state) continue;
+        const auto hazard = context->DetectImageBarrierHazard(image_barrier);
+        if (hazard.hazard) {
+            // PHASE1 TODO -- add tag information to log msg when useful.
```
Comment (ncesario-lunarg) [inline layers/synchronization_validation.cpp:5046]: Not sure if this is new, but adding a "name" to a TODO is part of the style guide: https://google.github.io/styleguide/cppguide.html#TODO_Comments. This was one of the things that popped up when I tried to "format all the VVL code" via clang-tidy.

**Review by ncesario-lunarg — APPROVED** [review]
LGTM!

**Review by jeremyg-lunarg — APPROVED** [review]
LGTM
