### PR TITLE
Fix constant specialization

### LINKED ISSUE #1479: Crash with small specialization constants
I'm creating a VK-GL-CTS test that uses small specialization constants, in the form of 16-bit floats, 16-bit integers and 8-bit integers if supported by the implementation. When enabling validation for these tests, I'm hitting an assertion here:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/834baaf8b22782d38b8da2bf52d046df2eed794f/layers/shader_validation.cpp#L2918

I've reviewed the spec about this and I can find no mention of restrictions regarding the size of specialization constants.

https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#pipelines-specialization-constants

The code appears to assert this due to a subsequent call to spvtools::CreateSetSpecConstantDefaultValuePass, which requires a map using uint32_t vector values.

### PR DESCRIPTION
**Pull request by jeremy-lunarg**
Fix #1479.

### CODE REVIEW

File: layers/shader_validation.cpp [hunk 1]
```diff
@@ -2915,11 +2915,12 @@ bool CoreChecks::ValidatePipelineShaderStage(VkPipelineShaderStageCreateInfo con
...
         for (auto i = 0u; i < specialization_info->mapEntryCount; ++i) {
             auto const &map_entry = specialization_info->pMapEntries[i];
-            assert(map_entry.size % 4 == 0);
 
-            auto const begin = reinterpret_cast<uint32_t const *>(specialization_info->pData) + map_entry.offset / 4;
-            auto const end = begin + map_entry.size / 4;
-            id_value_map.emplace(map_entry.constantID, std::vector<uint32_t>(begin, end));
+            // Expect only scalar types.
+            assert(map_entry.size == 1 || map_entry.size == 2 || map_entry.size == 4 || map_entry.size == 8);
+            auto const spec_data = reinterpret_cast<uint8_t const *>(specialization_info->pData);
```
Comment (jzulauf-lunarg) [inline layers/shader_validation.cpp]: this could be factored outside the loop.  I'm sure the optimizer will do it but it's clearer to the maintainer that it's invariant across map entries if it appears above 2916.

Comment (jeremy-lunarg) [reply layers/shader_validation.cpp]: Fixed. Thanks!
