### PR TITLE
tests: Fix and enable QueueBindSparseMemoryType4 test

### LINKED ISSUE #6808: Fix `NegativeSparseImage.QueueBindSparseMemoryType4`
Fix `NegativeSparseImage.QueueBindSparseMemoryType4`, taking `PositiveExternalMemorySync.ExternalMemory` as a reference.

With the current code, this error occurs on Windows AMD:

```
[ RUN      ] NegativeSparseImage.QueueBindSparseMemoryType4
C:\j\vz1\Debug64\Vulkan-ValidationLayers\tests\framework\error_monitor.cpp(198): error: Failed
Validation Error: [ VUID-VkBufferCreateInfo-pNext-00920 ] | 
MessageID = 0xa3f6ba5a | 
vkCreateBuffer(): pCreateInfo->pNext<VkExternalMemoryBufferCreateInfo>.handleTypes (VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT) is not reported as compatible by vkGetPhysicalDeviceExternalBufferProperties.
The Vulkan spec states: If the pNext chain includes a VkExternalMemoryBufferCreateInfo structure, its handleTypes member must only contain bits that are also in VkExternalBufferProperties::externalMemoryProperties.compatibleHandleTypes, as returned by vkGetPhysicalDeviceExternalBufferProperties with pExternalBufferInfo->handleType equal to any one of the handle types specified in VkExternalMemoryBufferCreateInfo::handleTypes (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkBufferCreateInfo-pNext-00920)
```

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #6808

### CODE REVIEW

File: tests/unit/sparse_image.cpp [hunk 1]
```diff
@@ -778,10 +778,10 @@ TEST_F(NegativeSparseImage, DISABLED_QueueBindSparseMemoryType4) {
 
     // Check for import/export capability
     VkPhysicalDeviceExternalBufferInfoKHR external_buffer_info = {
-        VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_BUFFER_INFO_KHR, nullptr, 0,
+        VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_BUFFER_INFO_KHR, nullptr, VK_BUFFER_CREATE_SPARSE_BINDING_BIT,
```
Comment (ziga-lunarg) [inline tests/unit/sparse_image.cpp:781]: @arno-lunarg `VK_BUFFER_CREATE_SPARSE_BINDING_BIT` was missing here, that is why you were seeing VUID-VkBufferCreateInfo-pNext-00920

**Review by spencer-lunarg — APPROVED** [review]
if CI is happy, I will be happy

File: tests/unit/sparse_image.cpp (hunk 1 above)
Comment (arno-lunarg) [reply tests/unit/sparse_image.cpp:781]: Thank you for fixing that!
