### PR TITLE
layers: Fix null ColorBlendState crash

### LINKED ISSUE #4118: VVL crash
I've talked with @ncesario-lunarg about this before, but it's possible for VVL to crash due to accessing a null pipeline blend state in drawtime validation. I've been using this patch locally to work around it:

```diff
diff --git a/layers/core_validation.cpp b/layers/core_validation.cpp
index 17f136583..eccf22308 100644
--- a/layers/core_validation.cpp
+++ b/layers/core_validation.cpp
@@ -1349,15 +1349,17 @@ bool CoreChecks::ValidatePipelineDrawtimeState(const LAST_BOUND_STATE &state, co
     skip |= ValidateStatus(pCB, CBSTATUS_COLOR_WRITE_ENABLE_SET, "Dynamic color write enable not set for this command buffer",
                            vuid.color_write_enable);
     if (IsDynamic(pPipeline, VK_DYNAMIC_STATE_COLOR_WRITE_ENABLE_EXT) && pCB->status & CBSTATUS_COLOR_WRITE_ENABLE_SET) {
-        uint32_t blend_attachment_count =
-            pCB->GetCurrentPipeline(VK_PIPELINE_BIND_POINT_GRAPHICS)->ColorBlendState()->attachmentCount;
-        if (pCB->dynamicColorWriteEnableAttachmentCount != blend_attachment_count) {
-            skip |= LogError(
-                pCB->commandBuffer(), vuid.color_write_enable,
-                "%s(): Currently bound pipeline was created with VkPipelineColorBlendStateCreateInfo::attachmentCount %" PRIu32
-                " and VK_DYNAMIC_STATE_COLOR_WRITE_ENABLE_EXT, but the number of attachments written by "
-                "vkCmdSetColorWriteEnableEXT() is %" PRIu32 ".",
-                caller, blend_attachment_count, pCB->dynamicColorWriteEnableAttachmentCount);
+        if (pCB->GetCurrentPipeline(VK_PIPELINE_BIND_POINT_GRAPHICS)->ColorBlendState()) {
+           uint32_t blend_attachment_count =
+               pCB->GetCurrentPipeline(VK_PIPELINE_BIND_POINT_GRAPHICS)->ColorBlendState()->attachmentCount;
+           if (pCB->dynamicColorWriteEnableAttachmentCount != blend_attachment_count) {
+               skip |= LogError(
+                   pCB->commandBuffer(), vuid.color_write_enable,
+                   "%s(): Currently bound pipeline was created with VkPipelineColorBlendStateCreateInfo::attachmentCount %" PRIu32
+                   " and VK_DYNAMIC_STATE_COLOR_WRITE_ENABLE_EXT, but the number of attachments written by "
+                   "vkCmdSetColorWriteEnableEXT() is %" PRIu32 ".",
+                   caller, blend_attachment_count, pCB->dynamicColorWriteEnableAttachmentCount);
+           }
         }
     }
     skip |= ValidateStatus(pCB, CBSTATUS_SAMPLE_LOCATIONS_SET, "Dynamic sample locations not set for this command buffer",
```

This can be triggered by running e.g., `KHR-GL46.packed_depth_stencil.verify_read_pixels.depth24_stencil8` on zink.

### PR DESCRIPTION
**Pull request by ncesario-lunarg**
Ensure ColorBlendState is not null, which is legal when no color
attachments are used.

Closes #4118.

### CODE REVIEW

File: tests/positive/pipeline.cpp [hunk 1]
```diff
@@ -7371,3 +7371,96 @@ TEST_F(VkPositiveLayerTest, TestPartiallyBoundDescriptors) {
...
+
+TEST_F(VkPositiveLayerTest, DynamicColorWriteNoColorAttachments) {
+    TEST_DESCRIPTION("Create a graphics pipeline with no color attachments, but use dynamic color write enable.");
+    m_errorMonitor->ExpectSuccess();
+
+    AddRequiredExtensions(VK_EXT_COLOR_WRITE_ENABLE_EXTENSION_NAME);
+    ASSERT_NO_FATAL_FAILURE(InitFramework());
+
+    if (!AreRequestedExtensionsEnabled()) {
+        GTEST_SKIP() << VK_EXT_COLOR_WRITE_ENABLE_EXTENSION_NAME << " not supported";
```
Comment (ziga-lunarg) [inline tests/positive/pipeline.cpp:7383]: Is this a new preferred way of logging missing extensions?

File: tests/positive/pipeline.cpp [hunk 2]
```diff
@@ -7371,3 +7371,96 @@ TEST_F(VkPositiveLayerTest, TestPartiallyBoundDescriptors) {
...
+    }
+
+    auto vkGetPhysicalDeviceFeatures2KHR = reinterpret_cast<PFN_vkGetPhysicalDeviceFeatures2KHR>(
+        vk::GetInstanceProcAddr(instance(), "vkGetPhysicalDeviceFeatures2KHR"));
+    ASSERT_TRUE(vkGetPhysicalDeviceFeatures2KHR != nullptr);
+    auto color_write_features = LvlInitStruct<VkPhysicalDeviceColorWriteEnableFeaturesEXT>();
+    auto features2 = LvlInitStruct<VkPhysicalDeviceFeatures2>(&color_write_features);
+    vk::GetPhysicalDeviceFeatures2(gpu(), &features2);
```
Comment (ziga-lunarg) [inline tests/positive/pipeline.cpp:7391]: You need to set the target api version to `VK_API_VERSION_1_1` to use `GetPhysicalDeviceFeatures2`

**Review by ziga-lunarg — APPROVED** [review]
LGTM when the test api version is added

File: tests/positive/pipeline.cpp (hunk 1 above)
Comment (ncesario-lunarg) [reply tests/positive/pipeline.cpp:7383]: No, this is the preferred way to skip tests now that we're on an updated version of google test. I'll start converting older tests to use this incrementally in the future.

File: tests/positive/pipeline.cpp (hunk 2 above)
Comment (ncesario-lunarg) [reply tests/positive/pipeline.cpp:7391]: I grabbed the `vkGetPhysicalDeviceFeatures2KHR` pointer above...and then didn't use it 🤦‍♂️. Thanks for the catch!
