### PR TITLE
layers: Don't record unvalidated descriptors

### LINKED ISSUE #524: Prevent Recording of update-after-bind descriptor and image_layout information
Previously #523 prevented false positives for update-after-bind descriptors, however record time validation was still treating them as known (and valid) at record time, potentially crashing the validation layer.

--- Orignal description ---
Descriptor validation does not properly account for VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT bit. There's a number of VU statements affected by this bit that need to have checks implemented/updated, as well as new/updated tests.
#523 prevents false positives for descriptors with this bit that have not yet been updated at the time a Draw command goes into a cmd buffer. However, some action should be taken at that point to indicate that the draw-time descriptor validation should instead take place at submit time in this case.
Hopefully the draw-time descriptor validation code can be re-used at submit time to do any checking that had to be delayed due to this bit.

### PR DESCRIPTION
**Pull request by Tony-LunarG**
We're not validating descriptors with VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT_EXT or VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT, we shouldn't be recording their state either.

Fixes #524

### CODE REVIEW

**Comment by tobine** [comment]
Is this intending to address #524?
If so should include "Fixes #524" in description.

File: layers/descriptor_sets.cpp [hunk 1]
```diff
@@ -1205,6 +1205,10 @@ void cvdescriptorset::DescriptorSet::UpdateDrawState(GLOBAL_CB_NODE *cb_node,
     // resources
     for (auto binding_req_pair : binding_req_map) {
         auto binding = binding_req_pair.first;
+        if (p_layout_->GetDescriptorBindingFlagsFromBinding(binding) &
```
Comment (jzulauf-lunarg) [inline layers/descriptor_sets.cpp]: A comment wouldn't go amiss here.
