### PR TITLE
layers: Complete validation of compatible render passes

### LINKED ISSUE #4029: `ValidateRenderPassCompatibility` is incorrect/incomplete
In the spec section "Render Pass Compatibility", it says:
> Two render passes are compatible if their corresponding color, input, resolve, and depth/stencil attachment references are compatible and if they are otherwise identical except for:
> - Initial and final image layout in attachment descriptions
> - Load and store operations in attachment descriptions
> - Image layout in attachment references

The `ValidateRenderPassCompatibility` function in the code checks if the flags are identical, and if the attachment references in subpasses are compatible. But it does not check that the attachment descriptions themselves are compatible (same length, identical other than the mentioned items), and it does not check that subpass dependencies or correlated view masks are identical at all.

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #4029 

Validate render pass compatibility, matching of subpass dependencies and correlated view masks.

### CODE REVIEW

File: layers/core_validation.cpp [hunk 1]
```diff
@@ -565,6 +565,64 @@ bool CoreChecks::ValidateSubpassCompatibility(const char *type1_string, const RE
     return skip;
 }
 
+bool CoreChecks::ValidateDependencyCompatibility(const char *type1_string, const RENDER_PASS_STATE *rp1_state,
+                                                 const char *type2_string, const RENDER_PASS_STATE *rp2_state,
```
Comment (ncesario-lunarg) [inline layers/core_validation.cpp:569]: Looks like `rp*_state` variables are assumed to be non-null, so I would vote for using const references instead of pointers (which would also fit better with the current style guide). Same comment for `LogInvalidDependencyMessage`.

**Review by ncesario-lunarg — APPROVED** [review]
Minor nit about parameter references, but otherwise LGTM!
