### PR TITLE
layers: Validiate layout transition of swapchain images. Part 2

### LINKED ISSUE #365: Missing validation: Can't transition (or otherwise use) swapchain images before acquiring them
Most operations on swapchain images are illegal before acquiring them, including barrier-transitioning their layouts: "An application can acquire use of a presentable image from the presentation engine. Use of a presentable image must occur only after the image is returned by vkAcquireNextImageKHR, and before it is presented by vkQueuePresentKHR. This includes transitioning the image layout and rendering commands."

We accidentally did just this, resulting in https://github.com/hrydgard/ppsspp/issues/11417  - random crashes on a specific device. A hard to track down bug, heroically solved by Hans-Kristian.

The validation layers should definitely warn about this.

### LINKED ISSUE #5240: Missing swapchain-related semaphore synchronization validation
Context: see the commit message and tests added in this ANGLE change: https://chromium-review.googlesource.com/c/angle/angle/+/4194182

A bug was found where ANGLE would acquire a swapchain image, but make a submission without waiting on the acquire semaphore. The semaphore was waited on by a later submission. This reportedly resulted in visible corruption. However, VVL didn't catch this.

To reproduce, revert the above change in ANGLE but keep the tests. Running the tests^1 should then reproduce the bug. Observe no VVL errors.

^1 `EGLSurfaceTest.WaitSemaphoreAddedAfterCommands/ES3_Vulkan_NoFixture` and `EGLSurfaceTest.CommandsSubmittedWithoutWaitSemaphore/ES3_Vulkan_NoFixture`

### PR DESCRIPTION
**Pull request by artem-lunarg**
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/365
Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5240

The restriction on non-acquired image usage is general but here we check only layout transition. This has to be practical enough because if the first operation is not a layout transition but something else (e.g. image copy), then layout mismatch will be detected, so won't be unnoticed. Then attempt to fix the layout will report about missing wait for the acquire signal. Still we might need to extend this with other operations if they do not trigger errors.

### CODE REVIEW

File: tests/unit/sync_val_wsi.cpp [hunk 1]
```diff
@@ -171,39 +172,6 @@ TEST_F(NegativeSyncValWsi, PresentAcquire) {
     m_device->Wait();
 }
 
-// TODO: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5240
-TEST_F(NegativeSyncValWsi, SubmitDoesNotWaitForAcquire) {
```
Comment (artem-lunarg) [inline tests/unit/sync_val_wsi.cpp:175]: This is detected by core checks now, no need for syncval test.
Initially the test was written for syncval because https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5240 suggested it's a syncval issue.

File: tests/unit/sync_val_wsi.cpp [hunk 2]
```diff
@@ -40,7 +40,7 @@ struct NegativeSyncValWsi : public VkSyncValTest {};
         }                                                               \
     }
 
-TEST_F(NegativeSyncValWsi, PresentAcquire) {
+TEST_F(NegativeSyncValWsi, DISABLED_PresentAcquire) {
```
Comment (artem-lunarg) [inline tests/unit/sync_val_wsi.cpp:43]: This syncval test relied on incorrect behavior (now reported by core checks). I need to review it if something left after incorrect parts are removed.

**Comment by artem-lunarg** [comment]
It was `PositiveWsi.MultiSwapchainPresentWithOneBadSwapchain` that hanged on ARM CI machine. Can't reproduce this locally on my ARM machine.

**Review by spencer-lunarg — APPROVED** [review]

**Review by ziga-lunarg — APPROVED** [review]
Nice!

**Comment by artem-lunarg** [comment]
unrelated Mac
