### PR TITLE
Fix issue 2753

### LINKED ISSUE #2753: Incorrect `topology_at_rasterizer`, `VkPipelineShaderStageCreateInfo[]` element order matters when it should not.
I believe the order of elements in the array pointed to by `const VkPipelineShaderStageCreateInfo* VkGraphicsPipelineCreateInfo::pStages` should not matter, and the index of any element has no meaning; each element has a `stage` field. I found a case where the order does matter for the validation layers, which causes it to issue an incorrect warning.
It happened in a pipeline with isoline tessellation and a geometry shader that outputs triangle-strips. The incorrect warning happens if `VK_SHADER_STAGE_GEOMETRY_BIT` appears before the tessellation stages in the array, but not if the GS is after.

I could be wrong, but my guess is `pPipe->topology_at_rasterizer` in `CoreChecks::ValidateDrawStateFlags` may not be correct. [This loop](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/946027b77f409cbcc84d5c23189954372a53ad56/layers/core_validation.cpp#L14760) over the stages array looks suspicious, because each call to `state_data->RecordPipelineShaderStage` passes the same `PIPELINE_STATE *`, and `SHADER_MODULE_STATE::ProcessExecutionModes` may overwrite `pipeline->topology_at_rasterizer`.

**Valid Usage ID**
[ VUID-vkCmdDraw-commandBuffer-02701 ] Object 0: handle = 0x7f405ca63d90, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xa2231429 | VkCommandBuffer 0x7f405ca63d90[]: Dynamic line width state not set for this command buffer.. The Vulkan spec states: If the VkPipeline object bound to the pipeline bind point used by this command requires any dynamic state, that state must have been set for commandBuffer, and done so after any previously bound pipeline with the corresponding state not specified as dynamic (https://vulkan.lunarg.com/doc/view/1.2.162.1~rc2/linux/1.2-extensions/vkspec.html#VUID-vkCmdDraw-commandBuffer-02701)

**Environment:**
 - OS: Ubuntu 20.04
 - SDK: `vkGetPhysicalDeviceToolPropertiesEXT` reports version 162 for "Khronos Validation Layer"
 - Options enabled: Default `VK_LAYER_KHRONOS_validation`

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #2753 

Graphics pipeline shader stages must be recorded in order they are executed

### CODE REVIEW

File: layers/pipeline_state.cpp [hunk 1]
```diff
@@ -89,11 +89,26 @@ void PIPELINE_STATE::initGraphicsPipeline(const ValidationStateTracker *state_da
     }
 
     stage_state.resize(pCreateInfo->stageCount);
+    // Graphics pipeline shader stages need to be recorded in order
+    for (uint32_t stage_idx = 0; stage_idx < 5; ++stage_idx) {
+        for (uint32_t i = 0; i < pCreateInfo->stageCount; i++) {
+            const VkPipelineShaderStageCreateInfo *pssci = &pCreateInfo->pStages[i];
```
Comment (ncesario-lunarg) [inline layers/pipeline_state.cpp:95]: Might as well make this a reference since we are assuming non-null (I know it was copied from before :))?

**Review by ncesario-lunarg — APPROVED** [review]

File: layers/pipeline_state.cpp (hunk 1 above)
Comment (ziga-lunarg) [reply layers/pipeline_state.cpp]: Done.
