### PR TITLE
Fix resetting performance queries

### LINKED ISSUE #6304: Unexpected validation errors with performance queries with multiple passes
**Environment:**
 - OS: Linux
 - GPU: RX 6700 XT (using the RADV Mesa driver)
 - SDK or header version if building from repo: d966a60f13e21ebb2bdd3112861d50c18f1e0620
 - Options enabled (synchronization, best practices, etc.): defaults + synchronization

**Describe the Issue**

When an app uses performance queries that need multiple passes, it's supposed to reset the query either on the host or a separate command buffer, and then submit a command buffer containing a `vkCmdBeginQuery` + stuff + `vkCmdEndQuery` sequence multiple times. In each submission, it has to include a `VkPerformanceQuerySubmitInfoKHR` indicating the pass index in the `pNext` chain of `VkSubmitInfo`. However, when doing that the layers generate `VUID-vkCmdBeginQuery-None-00807` erroneously.

I reproduced this problem with the performance query CTS tests in `dEQP-VK.query_pool.performance_query.*` tests. However, note that, before my changes for Khronos internal CTS issue 4615, the tests contain multiple validation errors. After my changes, `VUID-vkCmdBeginQuery-None-00807` appears to be the only remaining validation issue in those tests.

**Expected behavior**

No validation errors.

**Valid Usage ID**

`VUID-vkCmdBeginQuery-None-00807`

> VUID-vkCmdBeginQuery-None-00807(ERROR / SPEC): msgNum: 680962600 - Validation Error: [ VUID-vkCmdBeginQuery-None-00807 ] Object 0: handle = 0x55ac26bc6d90, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0x967dd1000000000e, type = VK_OBJECT_TYPE_QUERY_POOL; | MessageID = 0x2896aa28 | vkCmdBeginQuery: VkQueryPool 0x967dd1000000000e[] and query 0: query not reset. After query pool creation, each query must be reset before it is used. Queries must also be reset between uses. The Vulkan spec states: All queries used by the command must be unavailable (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdBeginQuery-None-00807)

**Additional context**

Possibly related to issue #1795, but I prefered to create a new one with more context.

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #6304

### CODE REVIEW

File: tests/unit/query_positive.cpp [hunk 1]
```diff
@@ -447,3 +447,102 @@ TEST_F(PositiveQuery, CommandBufferInheritanceFlags) {
...
+        m_commandBuffer->end();
+
+        auto submit_info = vku::InitStruct<VkSubmitInfo>();
+        submit_info.commandBufferCount = 1;
+        submit_info.pCommandBuffers = &m_commandBuffer->handle();
+        vk::QueueSubmit(m_device->m_queue, 1, &submit_info, VK_NULL_HANDLE);
+        vk::DeviceWaitIdle(*m_device);
+    }
+
+    vkt::CommandPool command_pool(*m_device, m_device->graphics_queue_node_index_);
```
Comment (spencer-lunarg) [inline tests/unit/query_positive.cpp:512]: was there a reason to create a new command pool/buffer here?

**Review by spencer-lunarg — APPROVED** [review]

File: tests/unit/query_positive.cpp (hunk 1 above)
Comment (ziga-lunarg) [reply tests/unit/query_positive.cpp:512]: No, removed.
