### PR TITLE
Fix validating image view usage in descriptors

### LINKED ISSUE #3924: Missing Validation for VkWriteDescriptorSet-descriptorType-00337
**Describe the situation in which you encountered the missing validation**
I created a `VkImageView` for a `VkFramebuffer` attachment to render to in `RP1`.  In `RP2`, I was reading that `VkImageView` as a uniform.  The underlying `VkImage` had a usage of `VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_SAMPLED_BIT`  The `VkImageView` had a `pNext` chain containing a `VkImageViewUsageCreateInfo`, where the usage was set to `VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT`.  Because I using the `VkImageView` in a `VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER`, I expect that the validation output should notify that the `VkImageView` does not have the correct usage.

**Valid Usage IDs requested**
`VUID-VkWriteDescriptorSet-descriptorType-00337`

**Additional Context**
API Dump - [console-log.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/8363550/console-log.txt)

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #3924

### CODE REVIEW

File: layers/descriptor_sets.cpp [hunk 1]
```diff
@@ -2434,7 +2434,12 @@ bool CoreChecks::ValidateImageUpdate(VkImageView image_view, VkImageLayout image
     assert(image_node);
 
     format = image_node->createInfo.format;
-    usage = image_node->createInfo.usage;
+    const auto image_view_usage_info = LvlFindInChain<VkImageViewUsageCreateInfo>(iv_state->create_info.pNext);
+    if (image_view_usage_info) {
+        usage = image_view_usage_info->usage;
+    } else {
+        usage = image_node->createInfo.usage;
+    }
```
Comment (nickclark2016) [inline layers/descriptor_sets.cpp:2442]: Question on this fix.  Should usage retrieved from the VkImageStencilUsageCreateInfo be applied before the usage from the VkImageViewUsageCreateInfo?  If so, I think we need to compute all usages from the image first, then mask it against the usage defined in the VkImageViewUsageCreateInfo.

Comment (sfricke-samsung) [reply layers/descriptor_sets.cpp:2442]: So there is a part in the spec about this https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#resources-image-inherited-usage

------

First, `VkImageStencilUsageCreateInfo` should only be applied from the `aspect_mask`

>  If aspectMask includes only VK_IMAGE_ASPECT_STENCIL_BIT, the implicit usage is equal to VkImageStencilUsageCreateInfo::stencilUsage.
>
> If aspectMask includes only VK_IMAGE_ASPECT_DEPTH_BIT, the implicit usage is equal to VkImageCreateInfo::usage.
>
> If both aspects are included in aspectMask, the implicit usage is equal to the intersection of VkImageCreateInfo::usage and VkImageStencilUsageCreateInfo::stencilUsage.

so the logic for appending the `VkImageStencilUsageCreateInfo` value should be adjusted to this

------

The `implicit usage` term was added to make sure that it was clear that

> The implicit usage can be overriden by adding a VkImageViewUsageCreateInfo structure to the pNext chain

**So to answer your question**: Use `VkImageViewUsageCreateInfo` first, then fall back to `VkImageCreateInfo::usage` and `VkImageStencilUsageCreateInfo::stencilUsage`

>  I think we need to compute all usages from the image first, then mask it against the usage

So it has to be a subset (`VUID-VkImageViewCreateInfo-pNext-02662` will catch it otherwise) so no reason to "compute it all" it is just simply `overridden`

Comment (nickclark2016) [reply layers/descriptor_sets.cpp:2442]: That makes sense.  Appreciate the response.

File: layers/descriptor_sets.cpp [hunk 2]
```diff
@@ -2434,7 +2434,12 @@ bool CoreChecks::ValidateImageUpdate(VkImageView image_view, VkImageLayout image
...
     const auto stencil_usage_info = LvlFindInChain<VkImageStencilUsageCreateInfo>(image_node->createInfo.pNext);
     if (stencil_usage_info) {
```
Comment (jeremyg-lunarg) [inline layers/descriptor_sets.cpp:2444]: @sfricke-samsung  are you saying above that this block needs changing as well?

Comment (sfricke-samsung) [reply layers/descriptor_sets.cpp:2444]: Yes, well it is one of those things where if we are going to fix this part of the function, might as well fix it all correctly. The issue here is if you are making use of the separate depth stencil extension
