### PR TITLE
layers: Address issue 2955

### LINKED ISSUE #2955: Investigate solution for bad specialization constant entries
#2952 exposes a crash at https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/b5dd25f4cd9c22a017370d88420a27866ad2ee92/layers/shader_validation.cpp#L1774

- [ ] This memcpy should be removed
- [ ] Add a test case with  specialization map entry size >8
- [ ] Add test cases for single and half precision specialization constants

FYI @sfricke-samsung

### PR DESCRIPTION
**Pull request by ncesario-lunarg**
Closes #2955.

Completely forgot about this (along with many other things I'm sure...).

@sfricke-samsung I think I've convinced myself that your `shaderInt8` tests cover the "less than 4 byte" case I was worried about. I had made some tweaks a while back, but think I reverted them all (let me know if something looks awry).

### CODE REVIEW

**Review by sfricke-samsung — APPROVED** [review]
LGTM

**Review by sfricke-samsung — COMMENTED** [review]
So I think this logic makes sense and stepping through it, doing what I expect, but I think I am finding strange errors with `CreateSetSpecConstantDefaultValuePass` trying to update `shaderInt8` spec constants, but seems unrelated to what this code is changing

**Comment by ncesario-lunarg** [comment]
@sfricke-samsung if it's causing an unexpected error, that's probably bad :)

This change gets rid of he crash I was seeing, which was the primary goal, but that's no good if it's causing other side effects.

File: layers/shader_validation.cpp [hunk 1]
```diff
@@ -1897,8 +1903,7 @@ bool CoreChecks::ValidatePipelineShaderStage(VkPipelineShaderStageCreateInfo con
         optimizer.RegisterPass(spvtools::CreateSetSpecConstantDefaultValuePass(id_value_map));
         optimizer.RegisterPass(spvtools::CreateFreezeSpecConstantValuePass());
         std::vector<uint32_t> specialized_spirv;
-        auto const optimized =
-            optimizer.Run(module->words.data(), module->words.size(), &specialized_spirv, spvtools::ValidatorOptions(), true);
+        auto const optimized = optimizer.Run(module->words.data(), module->words.size(), &specialized_spirv);
```
Comment (ncesario-lunarg) [inline layers/shader_validation.cpp:1906]: Changed this based due to apparent deprecation: https://github.com/KhronosGroup/SPIRV-Tools/blob/7dadcf9c76a9109a5a493a416ae59c2b3c02070f/include/spirv-tools/optimizer.hpp#L181.

**Comment by ncesario-lunarg** [comment]
@sfricke-samsung small update to 0 out the map entries before passing them to the optimizer.

I verified that #3039 works with this change when using Vulkan 1.2 (see https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3039#discussion_r678536012), or with the assembly you fixed up.

File: tests/vklayertests_pipeline_shader.cpp [hunk 2]
```diff
@@ -11519,3 +11519,226 @@ TEST_F(VkLayerTest, CreatePipelineWithDuplicatedSpecializationConstantID) {
...
     CreatePipelineHelper::OneshotTest(*this, set_info, kErrorBit, "VUID-VkSpecializationInfo-constantID-04911");
 }
+
+TEST_F(VkLayerTest, SpecializationInvalidSizeMismatch) {
+    TEST_DESCRIPTION("Make sure an error is logged when a specialization map entry's size is not correct with type");
+
+    SetTargetApiVersion(VK_API_VERSION_1_2);
+
+    bool int8_support = false;
+    bool float64_support = false;
```
Comment (ncesario-lunarg) [inline tests/vklayertests_pipeline_shader.cpp:11529]: @sfricke-samsung I may have copied this wrong from your original test, but I needed to change the default here to false and instead check for support. Getting CI failures on some devices without that.

Comment (sfricke-samsung) [reply tests/vklayertests_pipeline_shader.cpp:11529]: my original test might have been wrong 😄 

Ya go ahead, do what you need to make the CI monsters happy again

**Review by jeremyg-lunarg — APPROVED** [review]
LGTM
