### PR TITLE
layers: Fix getting imageView layerCount

### LINKED ISSUE #4102: erroneous layerCount errors with VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT
I'm not sure what's causing this, but I'm reasonably sure it's a VVL issue.

If I run:

`ZINK_DEBUG=validation MESA_LOADER_DRIVER_OVERRIDE=zink ./glcts -n dEQP-GLES31.functional.geometry_shading.instanced.multiple_layers_per_invocation_3d` 

then I get this error

```
VUID-VkRenderPassBeginInfo-framebuffer-03213(ERROR / SPEC): msgNum: 1714817613 - Validation Error: [ VUID-VkRenderPassBeginInfo-framebuffer-03213 ] Object 0: handle = 0x210d07000000003a, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x66360a4d | vkCmdBeginRenderPass: Image view #0 created with a subresource range with a layerCount of 1, but image info #0 used to create the framebuffer had layerCount set as 4 The Vulkan spec states: If framebuffer was created with a VkFramebufferCreateInfo::flags value that included VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT, each element of the pAttachments member of a VkRenderPassAttachmentBeginInfo structure included in the pNext chain must be a VkImageView of an image created with a value of VkImageViewCreateInfo::subresourceRange.layerCount equal to the layerCount member of the corresponding element of VkFramebufferAttachmentsCreateInfo::pAttachmentImageInfos used to create framebuffer (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkRenderPassBeginInfo-framebuffer-03213)
    Objects: 1
        [0] 0x210d07000000003a, type: 18, name: NULL
```

I've examined the image involved, and this is a 2D array view created from a 3D image for framebuffer usage with VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT. My guess is that VVL is trying to clamp to a layerCount of 1 because the base image is 3D and ignoring the fact that this is now an array. Likely also going to be a factor for EXT_image_2d_view_of_3d validation.

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #4102

### CODE REVIEW

File: layers/core_validation.cpp [hunk 1]
```diff
@@ -13971,12 +13971,15 @@ bool CoreChecks::VerifyFramebufferAndRenderPassImageViews(const VkRenderPassBegi
...
 
-                    if (framebuffer_attachment_image_info->layerCount != subresource_range.layerCount) {
-                        skip |=
-                            LogError(pRenderPassBeginInfo->renderPass, "VUID-VkRenderPassBeginInfo-framebuffer-03213",
-                                     "%s: Image view #%u created with a subresource range with a layerCount of %u, "
-                                     "but image info #%u used to create the framebuffer had layerCount set as %u",
-                                     func_name, i, subresource_range.layerCount, i, framebuffer_attachment_image_info->layerCount);
+                    const uint32_t layerCount =
+                        image_view_state->create_info.subresourceRange.layerCount != VK_REMAINING_ARRAY_LAYERS
+                        ? image_view_state->create_info.subresourceRange.layerCount : image_create_info->extent.depth;
```
Comment (ncesario-lunarg) [inline layers/core_validation.cpp:13976]: I thought this is part of what is accounted for in the "normalized range," no?

Comment (ziga-lunarg) [reply layers/core_validation.cpp:13976]: `IsDepthSliced()` returns true, so `layerCount` gets set to 1.

Comment (jeremyg-lunarg) [reply layers/core_validation.cpp:13976]: 'normalized' doesn't cover the 2d view of 3d image case very well, which is what is being hit here. It would have been much easier to handle this case if they hadn't overloaded extent.depth and had instead added a separate field to the view create info.

**Review by jeremyg-lunarg — APPROVED** [review]
LGTM. 2d view of 3d image is the gift that keeps on giving...
