### PR TITLE
Fix issue 1596

### LINKED ISSUE #1596: Validation layer does not warn of a compute shader with too large LDS
If a compute shader has an LDS array of a size exceeding the device limit, the validation layer will not warn of this. However, the shader module or the compute pipeline will fail on their create functions.

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #1596

Check if shared memory used by compute shader exceeds VkPhysicalDeviceLimits::maxComputeSharedMemorySize

### CODE REVIEW

File: layers/shader_validation.cpp [hunk 1]
```diff
@@ -712,6 +712,53 @@ bool CoreChecks::ValidateShaderStageGroupNonUniform(SHADER_MODULE_STATE const *m
     return skip;
 }
 
+uint32_t CoreChecks::get_type_size(SHADER_MODULE_STATE const *src, spirv_inst_iter iter) const {
+    uint32_t opcode = iter.opcode();
+    if (opcode == spv::OpConstant) {
+        return iter.word(3);
```
Comment (ncesario-lunarg) [inline layers/shader_validation.cpp:718]: Wouldn't this return the _value_ of the constant, not the _type size_ (https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#OpConstant)? Based on the function name `get_type_size` I would have expected this to return the size of this type? I think there is already a `GetConstantValue` helper function; I would vote for using that directly where it should be used here. (i.e., OpTypeArray, etc.).

File: layers/shader_validation.cpp [hunk 2]
```diff
@@ -712,6 +712,53 @@ bool CoreChecks::ValidateShaderStageGroupNonUniform(SHADER_MODULE_STATE const *m
     return skip;
 }
 
+uint32_t CoreChecks::get_type_size(SHADER_MODULE_STATE const *src, spirv_inst_iter iter) const {
```
[the remark this answers is not in the document]
Comment (ncesario-lunarg) [reply layers/shader_validation.cpp:715]: Seems like this should be a `SHADER_MODULE_STATE` member function.

[the remark this answers is not in the document]
Comment (ncesario-lunarg) [reply layers/shader_validation.cpp:715]: `spirv_inst_iter` -> `const spirv_inst_iter&`?

File: layers/shader_validation.cpp [hunk 3]
```diff
@@ -712,6 +712,53 @@ bool CoreChecks::ValidateShaderStageGroupNonUniform(SHADER_MODULE_STATE const *m
...
+        for (uint32_t i = 2; i < iter.len(); ++i) {
+            total_size += get_type_size(src, src->get_def(iter.word(i)));
+        }
+        return total_size;
+    }
+    return 0;
+}
+
+uint32_t CoreChecks::CalcComputeSharedMemory(SHADER_MODULE_STATE const *src, VkShaderStageFlagBits stage,
+                                             spirv_inst_iter &insn) const {
```
Comment (ncesario-lunarg) [inline layers/shader_validation.cpp:748]: Also seems like this should be a `SHADER_M0DULE_STATE` member function.

Comment (ncesario-lunarg) [reply layers/shader_validation.cpp:748]: `spirv_inst_iter&` -> `const spirv_inst_iter&`?

File: tests/vklayertests_pipeline_shader.cpp [hunk 4]
```diff
@@ -11943,3 +11943,32 @@ TEST_F(VkLayerTest, ColorBlendAdvanced) {
...
+    TEST_DESCRIPTION("Validate compute shader shared memory does not exceed maxComputeSharedMemorySize");
+
+    ASSERT_NO_FATAL_FAILURE(Init());
+
+    const auto max_shared_memory_size = m_device->phy().properties().limits.maxComputeSharedMemorySize;
+    const auto max_shared_ints = max_shared_memory_size / 32;
+
+    std::stringstream csSource;
+    // Make sure compute pipeline has a compute shader stage set
+    csSource << R"(
```
Comment (ncesario-lunarg) [inline tests/vklayertests_pipeline_shader.cpp:11957]: Might as well toss a `glsl` in there to pick up syntax highlighting in some environments?

File: layers/core_validation.h [hunk 5]
```diff
@@ -530,6 +530,8 @@ class CoreChecks : public ValidationStateTracker {
     bool ValidateShaderStageMaxResources(VkShaderStageFlagBits stage, const PIPELINE_STATE* pipeline) const;
     bool ValidateShaderStageGroupNonUniform(SHADER_MODULE_STATE const* src, VkShaderStageFlagBits stage,
                                             spirv_inst_iter& insn) const;
+    uint32_t get_type_size(SHADER_MODULE_STATE const* src, spirv_inst_iter iter) const;
+    uint32_t CalcComputeSharedMemory(SHADER_MODULE_STATE const* src, VkShaderStageFlagBits stage, spirv_inst_iter& insn) const;
```
Comment (ncesario-lunarg) [inline layers/core_validation.h:534]: Looks like these belong in `shader_module.*` and `SHADER_MODULE_STATE`.

File: layers/shader_validation.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (ncesario-lunarg) [reply layers/shader_validation.cpp:715]: Since SPIR-V specifies type width in bits, might be good to make it explicit whether this is returning size in bits or bytes (e.g., `GetTypeByteSize`).

**Review by ncesario-lunarg — CHANGES_REQUESTED** [review]
Some clarifying questions/requests, but I think this looks good!

File: layers/shader_validation.cpp (hunk 1 above)
Comment (ziga-lunarg) [reply layers/shader_validation.cpp:718]: Correct, that is actually what I wanted but it shouldn't be in this function.

File: tests/vklayertests_pipeline_shader.cpp (hunk 4 above)
Comment (ncesario-lunarg) [reply tests/vklayertests_pipeline_shader.cpp:11957]: Strange, should be no difference (just a raw string). The following seems to work fine on gcc 11.1 and clang 12.0.1? What error are you seeing?
```cpp
    std::stringstream csSource;
    // Make sure compute pipeline has a compute shader stage set
    csSource << R"glsl(
        #version 450
        shared int a[)glsl";
    csSource << (max_shared_ints + 16);
    csSource << R"glsl(];
        void main(){
        }
    )glsl";
```

File: layers/shader_module.cpp [hunk 6]
```diff
@@ -1746,6 +1746,53 @@ spirv_inst_iter SHADER_MODULE_STATE::GetImageFormatInst(uint32_t id) const
...
 }
 
+uint32_t SHADER_MODULE_STATE::GetConstantValue(const spirv_inst_iter &iter) const { return iter.word(3); }
+
+uint32_t SHADER_MODULE_STATE::GetTypeBitsSize(const spirv_inst_iter &iter) const {
+    const uint32_t opcode = iter.opcode();
+    if (opcode == spv::OpTypeFloat || opcode == spv::OpTypeInt) {
+        return iter.word(2);
+    } else if (opcode == spv::OpTypeVector) {
+        auto component_type = get_def(iter.word(2));
```
Comment (ncesario-lunarg) [inline layers/shader_module.cpp:1756]: Could be `const` (here and elsewhere)?

File: layers/shader_module.cpp [hunk 7]
```diff
@@ -1746,6 +1746,53 @@ spirv_inst_iter SHADER_MODULE_STATE::GetImageFormatInst(uint32_t id) const
     } while (true);
 }
 
+uint32_t SHADER_MODULE_STATE::GetConstantValue(const spirv_inst_iter &iter) const { return iter.word(3); }
```
Comment (ncesario-lunarg) [inline layers/shader_module.cpp:1749]: Isn't this already define on line 1797?

File: layers/shader_validation.cpp [hunk 8]
```diff
@@ -1964,10 +1964,18 @@ bool CoreChecks::ValidatePipelineShaderStage(VkPipelineShaderStageCreateInfo con
...
     // and mainly only checking the instruction in detail for a single operation
+    uint32_t total_shared_size = 0;
     for (auto insn : *module) {
         skip |= ValidateShaderCapabilitiesAndExtensions(module, insn);
         skip |= ValidatePropertiesAndFeatures(module, insn);
         skip |= ValidateShaderStageGroupNonUniform(module, pStage->stage, insn);
+        total_shared_size += module->CalcComputeSharedMemory(pStage->stage, insn);
+    }
+
+    if (total_shared_size > phys_dev_props.limits.maxComputeSharedMemorySize) {
```
Comment (ncesario-lunarg) [inline layers/shader_validation.cpp:1975]: This limit is in bytes, but isn't `total_shared_size` in bits?

**Review by ncesario-lunarg — CHANGES_REQUESTED** [review]
Just a couple more nits/questions!

File: tests/vklayertests_pipeline_shader.cpp (hunk 4 above)
Comment (ziga-lunarg) [reply tests/vklayertests_pipeline_shader.cpp:11957]: Ah I forgot the `glsl`s in the middle, you're right this works fine.

File: layers/shader_validation.cpp (hunk 8 above)
Comment (ziga-lunarg) [reply layers/shader_validation.cpp:1975]: Good catch.

**Review by ncesario-lunarg — APPROVED** [review]
Nice work!
