### PR TITLE
Fix checking aspect mask in vkCmdSetAttachmentFeedbackLoopEnableEXT

### LINKED ISSUE #6563: VUID-vkCmdSetAttachmentFeedbackLoopEnableEXT-aspectMask-08863
> VUID-vkCmdSetAttachmentFeedbackLoopEnableEXT-aspectMask-08863(ERROR / SPEC): msgNum: 885951759 - Validation Error: [ VUID-vkCmdSetAttachmentFeedbackLoopEnableEXT-aspectMask-08863 ] Object 0: handle = 0x2f7c480, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x34ce8d0f | vkCmdSetAttachmentFeedbackLoopEnableEXT(): aspestMask is VK_IMAGE_ASPECT_DEPTH_BIT|VK_IMAGE_ASPECT_STENCIL_BIT. The Vulkan spec states: aspectMask must only include VK_IMAGE_ASPECT_NONE, VK_IMAGE_ASPECT_COLOR_BIT, VK_IMAGE_ASPECT_DEPTH_BIT, and VK_IMAGE_ASPECT_STENCIL_BIT (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdSetAttachmentFeedbackLoopEnableEXT-aspectMask-08863)

I don't understand this error on latest VVL main. The mask may only include those bits, and the passed mask does include only those bits, so... ?

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #6563

### CODE REVIEW

File: layers/core_checks/cc_cmd_buffer_dynamic.cpp [hunk 1]
```diff
@@ -2266,8 +2266,8 @@ bool CoreChecks::PreCallValidateCmdSetAttachmentFeedbackLoopEnableEXT(VkCommandB
                          string_VkImageAspectFlags(aspectMask).c_str());
     }
 
-    if (aspectMask != VK_IMAGE_ASPECT_NONE && aspectMask != VK_IMAGE_ASPECT_COLOR_BIT && aspectMask != VK_IMAGE_ASPECT_DEPTH_BIT &&
-        aspectMask != VK_IMAGE_ASPECT_STENCIL_BIT) {
+    if ((aspectMask &
+         ~(VK_IMAGE_ASPECT_NONE | VK_IMAGE_ASPECT_COLOR_BIT | VK_IMAGE_ASPECT_DEPTH_BIT | VK_IMAGE_ASPECT_STENCIL_BIT)) > 0) {
```
Comment (artem-lunarg) [inline layers/core_checks/cc_cmd_buffer_dynamic.cpp:2270]: nit: `!= 0` for comparison to sleep better, it's tricky business with signed/unsigned types . Enum values are by default signed, aspect mask is unsigned and then it goes beyond my understanding.

**Review by artem-lunarg — APPROVED** [review]

**Review by juan-lunarg — APPROVED** [review]
