### PR TITLE
Fix input attachment layout validation

### LINKED ISSUE #373: Depth/Stencil input attachments layouts generate incorrect errors
Input attachments for depth/stencil are allowed to be in a layout in which only one of depth and stencil are READ_ONLY, but the validation layers currently give an error. It looks like this hasn't been updated with the maintenance2(ish) additions to the layouts.

I'm seeing this problem in, for example, dEQP-VK.renderpass.suballocation.formats.d24_unorm_s8_uint.input.clear.store.draw_depth_read_only in the CTS.

### PR DESCRIPTION
**Pull request by gnl21**
The new layout from KHR_maintenance2 were not allowed in the checks of input attachments, so spurious errors were produced.

Fixes #373.

### CODE REVIEW

File: layers/buffer_validation.cpp [hunk 1]
```diff
@@ -3123,6 +3123,14 @@ bool ValidateLayouts(const core_validation::layer_data *device_data, VkDevice de
                                     "Layout for input attachment is GENERAL but should be READ_ONLY_OPTIMAL.");
                     break;
 
+                case VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR:
```
Comment (jzulauf-lunarg) [inline layers/buffer_validation.cpp]: 👍
