### PR TITLE
practices: Fix BestPractices-ImageBarrierAccessLayout again

### LINKED ISSUE #4735: Incorrect best practices message BestPractices-ImageBarrierAccessLayout
RAR and WAR hazards don't require a memory barrier (https://github.com/KhronosGroup/Vulkan-Docs/wiki/Synchronization-Examples#first-dispatch-reads-from-a-storage-buffer-second-dispatch-writes-to-that-storage-buffer)

So if the image layout is e.g. `VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL`, it's perfectly fine for `srcAccessMask` to be 0. Best practices could warn about this for `dstAccessMask`, but shouldn't for `srcAccessMask`.

Also, there is syncval, what's the point of this?

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**
It turns out that the table from #2918 had an implicit "(can be 0)" on almost every line. The only weird case is:

- PRESENT_SRC_KHR - Must be 0

Fixes #4735

### CODE REVIEW

File: layers/best_practices_utils.cpp [hunk 1]
```diff
@@ -1615,18 +1615,18 @@ bool BestPractices::ValidateAccessLayoutCombination(const std::string& api_name,
...
 
     // Combinations taken from https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2918
     switch (layout) {
         case VK_IMAGE_LAYOUT_UNDEFINED:
             allowed = all;
-            none_allowed = true;
             break;
         case VK_IMAGE_LAYOUT_GENERAL:
             allowed = all;
+            none_allowed = false;  // PR table says "Any (must not be 0)"
```
Comment (Tobski) [inline layers/best_practices_utils.cpp:1629]: Looking back at my table and per my comment on the new issue this is incorrect, this is allowed to be zero because of semaphore interactions just like everything else, so this whole "none_allowed" path should be removed per my comment.

**Review by Tobski — CHANGES_REQUESTED** [review]
One comment as mentioned on the issue, but otherwise LGTM.

**Review by Tobski — APPROVED** [review]
LGTM, thanks!
