### PR TITLE
Validate shader object nextStage

### LINKED ISSUE #9823: VkShaderCreateInfoEXT.nextStage is not validated
When using shader objects, it is mandatory to specify the possible next stages of each shader using `VkShaderCreateInfoEXT.nextStage` :

> The stage of the shader being compiled is specified by stage. Applications must also specify which stage types will be allowed to immediately follow the shader being created. For example, a vertex shader might specify a nextStage value of VK_SHADER_STAGE_FRAGMENT_BIT to indicate that the vertex shader being created will always be followed by a fragment shader (and never a geometry or tessellation shader). Applications that do not know this information at shader creation time or need the same shader to be compatible with multiple subsequent stages can specify a mask that includes as many valid next stages as they wish. For example, a vertex shader can specify a nextStage mask of VK_SHADER_STAGE_GEOMETRY_BIT | VK_SHADER_STAGE_FRAGMENT_BIT to indicate that the next stage could be either a geometry shader or fragment shader (but not a tessellation shader).

https://docs.vulkan.org/features/latest/features/proposals/VK_EXT_shader_object.html

This does not seem to be currently tested by the validation layer. Using RADV with a graphic pipeline consisting of vertex, geometry, and fragment shaders without specifying `VkShaderCreateInfoEXT.nextStage` causes a segfault on the draw call without triggering the validation layer.

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #9823

### CODE REVIEW

File: layers/core_checks/cc_shader_object.cpp [hunk 1]
```diff
@@ -558,6 +558,53 @@ bool CoreChecks::PreCallValidateGetShaderBinaryDataEXT(VkDevice device, VkShader
...
+    }
+    ShaderObjectStage previous_stage = ShaderObjectStage::LAST;
+    for (const auto& stage : stages) {
+        if (last_bound_state.IsValidShaderBound(stage)) {
+            const auto previous_state = last_bound_state.GetShaderStateIfValid(previous_stage);
+            if (previous_stage != ShaderObjectStage::LAST &&
+                (previous_state->create_info.flags & VK_SHADER_CREATE_LINK_STAGE_BIT_EXT) == 0 &&
+                (previous_state->create_info.nextStage & ShaderObjectStageToVkShaderStage(stage)) == 0) {
+                const auto state = last_bound_state.GetShaderStateIfValid(stage);
+                skip |= LogError(vuid.pipeline_or_shaders_bound_08607, last_bound_state.cb_state.Handle(), vuid.loc(),
```
Comment (spencer-lunarg) [inline layers/core_checks/cc_shader_object.cpp:589]: my only real concern/question is why we now have 2 large checks for `08607`... I don't think anything to solve here, but it causes these types of gaps... might be a spec issue

Like I get this error

>  vkCmdDraw(): The combination of shader objects bound to VK_PIPELINE_BIND_POINT_GRAPHICS is invalid, because shader stages VK_SHADER_STAGE_VERTEX_BIT (VkShaderEXT 0x70000000007) and VK_SHADER_STAGE_FRAGMENT_BIT (VkShaderEXT 0x80000000008) are bound with no other stages between them, but VK_SHADER_STAGE_VERTEX_BIT was created with nextStage VkShaderStageFlags(0).

I am still confused what is suppose to be done or not... do I need a non-zero `nextStage`? Do I need to bind another shader?

File: layers/core_checks/cc_shader_object.cpp [hunk 2]
```diff
@@ -558,6 +558,53 @@ bool CoreChecks::PreCallValidateGetShaderBinaryDataEXT(VkDevice device, VkShader
     return skip;
 }
 
+bool CoreChecks::ValidateShaderObjectNextStage(const LastBound& last_bound_state, const VkPipelineBindPoint bind_point,
+                                               const vvl::DrawDispatchVuid& vuid) const {
+    bool skip = false;
+
+    std::vector<ShaderObjectStage> stages;
```
Comment (spencer-lunarg) [inline layers/core_checks/cc_shader_object.cpp:565]: can we just have 2 `const static std::array` and then pick which one to loop

also we have a 

```
    const std::array graphics_stages = {VK_SHADER_STAGE_VERTEX_BIT, VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT,
                                        VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT, VK_SHADER_STAGE_GEOMETRY_BIT,
                                        VK_SHADER_STAGE_FRAGMENT_BIT};
```

already in this file, maybe make this global to this file as we seem to need these list a lot

File: layers/core_checks/cc_shader_object.cpp [hunk 3]
```diff
@@ -558,6 +558,53 @@ bool CoreChecks::PreCallValidateGetShaderBinaryDataEXT(VkDevice device, VkShader
...
+    } else {
+        stages = {
+            ShaderObjectStage::TASK,
+            ShaderObjectStage::MESH,
+            ShaderObjectStage::FRAGMENT,
+        };
+    }
+    ShaderObjectStage previous_stage = ShaderObjectStage::LAST;
+    for (const auto& stage : stages) {
+        if (last_bound_state.IsValidShaderBound(stage)) {
```
Comment (spencer-lunarg) [inline layers/core_checks/cc_shader_object.cpp:583]:
```suggestion
        if (!last_bound_state.IsValidShaderBound(stage)) continue;
```

File: tests/framework/shader_object_helper.cpp [hunk 4]
```diff
@@ -13,13 +13,55 @@
 #include "shader_object_helper.h"
 #include <vulkan/utility/vk_struct_helper.hpp>
 
+void SetNextStage(VkShaderCreateInfoEXT& info) {
```
Comment (spencer-lunarg) [inline tests/framework/shader_object_helper.cpp:16]: why do we have this and `Shader::SetNextStage` ... they are similar but different?

File: layers/core_checks/cc_shader_object.cpp [hunk 5]
```diff
@@ -558,6 +558,53 @@ bool CoreChecks::PreCallValidateGetShaderBinaryDataEXT(VkDevice device, VkShader
...
+            const auto previous_state = last_bound_state.GetShaderStateIfValid(previous_stage);
```
Comment (spencer-lunarg) [inline layers/core_checks/cc_shader_object.cpp:584]:
```suggestion
            const auto previous_state = last_bound_state.GetShaderStateIfValid(previous_stage);
            ASSERT_AND_CONTINUE(previous_state);
```

File: layers/core_checks/cc_shader_object.cpp [hunk 6]
```diff
@@ -558,6 +558,53 @@ bool CoreChecks::PreCallValidateGetShaderBinaryDataEXT(VkDevice device, VkShader
     return skip;
```
Comment (spencer-lunarg) [inline layers/core_checks/cc_shader_object.cpp:558]: not sure where to put, but I fail

```
[  FAILED  ] NegativeShaderObject.MissingCmdSetRasterizationStreamEXT
[  FAILED  ] NegativeShaderObject.MissingLineStippleEnable
[  FAILED  ] NegativeShaderObject.SetPrimitiveTopologyNonPatch
[  FAILED  ] PositiveShaderObject.DrawWithAllGraphicsShaderStagesUsed
[  FAILED  ] PositiveShaderObject.IndirectDraw
```

on ToT Lavapipe with this change (getting the new error)

File: layers/core_checks/cc_shader_object.cpp [hunk 7]
```diff
@@ -558,6 +558,53 @@ bool CoreChecks::PreCallValidateGetShaderBinaryDataEXT(VkDevice device, VkShader
...
+        if (last_bound_state.IsValidShaderBound(stage)) {
+            const auto previous_state = last_bound_state.GetShaderStateIfValid(previous_stage);
+            if (previous_stage != ShaderObjectStage::LAST &&
+                (previous_state->create_info.flags & VK_SHADER_CREATE_LINK_STAGE_BIT_EXT) == 0 &&
+                (previous_state->create_info.nextStage & ShaderObjectStageToVkShaderStage(stage)) == 0) {
+                const auto state = last_bound_state.GetShaderStateIfValid(stage);
+                skip |= LogError(vuid.pipeline_or_shaders_bound_08607, last_bound_state.cb_state.Handle(), vuid.loc(),
+                                 "The combination of shader objects bound to %s is invalid, because shader stages %s (%s) and "
+                                 "%s (%s) are bound with no other stages between them, but %s was created with nextStage %s.",
+                                 string_VkPipelineBindPoint(bind_point),
```
Comment (spencer-lunarg) [inline layers/core_checks/cc_shader_object.cpp:592]: can this not be Graphics? If it can be compute, write a test, otherwise just hardcode to Graphics

**Review by spencer-lunarg — CHANGES_REQUESTED** [review]

File: layers/core_checks/cc_shader_object.cpp (hunk 1 above)
Comment (ziga-lunarg) [reply layers/core_checks/cc_shader_object.cpp:589]: I agree there could be a more specific VU for this, but at the moment there is not

File: tests/framework/shader_object_helper.cpp (hunk 4 above)
Comment (ziga-lunarg) [reply tests/framework/shader_object_helper.cpp:16]: They are similar, but one knows if tessellation and geometry shader features are enabled, and the other does not

File: layers/core_checks/cc_shader_object.cpp (hunk 7 above)
Comment (ziga-lunarg) [reply layers/core_checks/cc_shader_object.cpp:592]: Only graphics pipeline bind point applies here, done.

File: tests/framework/shader_object_helper.cpp (hunk 4 above)
Comment (spencer-lunarg) [reply tests/framework/shader_object_helper.cpp:16]: can we either 
- get it down to 1 (with some param)
- Create different names
- add comment why we have 2 in 2 different helpers

File: layers/core_checks/cc_shader_object.cpp (hunk 1 above)
Comment (spencer-lunarg) [reply layers/core_checks/cc_shader_object.cpp:575]: I guess my question/issue is reading this VU message, it doesn't tell me what is wrong... like it would be nice here to explain if we detect `nextStage == 0` what the user likely might need to do

Change the `nextStage` or bind other stages? (I realize the issue reference the extension proposal)

Comment (ziga-lunarg) [reply layers/core_checks/cc_shader_object.cpp:575]: I've updated the message

**Review by spencer-lunarg — APPROVED** [review]
Thanks, this is now a lot cleaner and will test on RADV for my issues once this is in
