### PR TITLE
layers: Fix deadlock in vkCmdBeginRenderPass()

### LINKED ISSUE #4376: Deadlock/hang on Windows when unbinding resources during vkRenderPassBegin
**Describe the Issue**
Hello, our engine has encountered an issue where the validation layer deadlocks while trying to take out an exclusive write lock after a specific series of commands. What seems to be happening is that `CMD_BUFFER_STATE::lock` is locked exclusively for writing in `ValidationStateTracker::PreCallRecordCmdBeginRenderPass`, but then the call to `CMD_BUFFER_STATE::UnbindResources()` in `CMD_BUFFER_STATE::BeginRenderPass` causes `CMD_BUFFER_STATE::NotifyInvalidate` to once again try to lock the same lock exclusively. It looks like the lock uses `std::shared_mutex`, which ultimately uses [SRWLock](https://docs.microsoft.com/en-us/windows/win32/sync/slim-reader-writer--srw--locks) on Windows, which cannot be locked recursively.  Here's the relevant part of the callstack for context:

```
ntdll.dll!RtlAcquireSRWLockExclusive()    
VkLayer_khronos_validation.dll!std::shared_mutex::lock()
VkLayer_khronos_validation.dll!ReadWriteLock::lock()
VkLayer_khronos_validation.dll!std::unique_lock<ReadWriteLock>::{ctor}(ReadWriteLock &)
VkLayer_khronos_validation.dll!CMD_BUFFER_STATE::WriteLock()
VkLayer_khronos_validation.dll!CMD_BUFFER_STATE::NotifyInvalidate(const small_vector<std::shared_ptr<BASE_NODE>,4,unsigned int> & invalid_nodes={...}, bool unlink=96)
VkLayer_khronos_validation.dll!BASE_NODE::NotifyInvalidate(const small_vector<std::shared_ptr<BASE_NODE>,4,unsigned int> & invalid_nodes, bool unlink)
VkLayer_khronos_validation.dll!BASE_NODE::Invalidate(bool)
VkLayer_khronos_validation.dll!BASE_NODE::Destroy()
VkLayer_khronos_validation.dll!LAST_BOUND_STATE::Reset()
VkLayer_khronos_validation.dll!CMD_BUFFER_STATE::UnbindResources()
VkLayer_khronos_validation.dll!CMD_BUFFER_STATE::BeginRenderPass(CMD_TYPE cmd_type, const VkRenderPassBeginInfo * pRenderPassBegin=0x000000da93bfe040, VkSubpassContents contents=VK_SUBPASS_CONTENTS_INLINE)
VkLayer_khronos_validation.dll!ValidationStateTracker::PreCallRecordCmdBeginRenderPass(VkCommandBuffer_T * commandBuffer, const VkRenderPassBeginInfo * pRenderPassBegin=0x000000da93bfe040, VkSubpassContents contents=VK_SUBPASS_CONTENTS_INLINE)
VkLayer_khronos_validation.dll!CoreChecks::PreCallRecordCmdBeginRenderPass(VkCommandBuffer_T * commandBuffer=0x0000023530b0aef0, const VkRenderPassBeginInfo * pRenderPassBegin=0x000000da93bfe040, VkSubpassContents contents=VK_SUBPASS_CONTENTS_INLINE)
VkLayer_khronos_validation.dll!vulkan_layer_chassis::CmdBeginRenderPass(VkCommandBuffer_T * commandBuffer=0x0000023530b0aef0, const VkRenderPassBeginInfo * pRenderPassBegin=0x000000da93bfe040, VkSubpassContents contents=VK_SUBPASS_CONTENTS_INLINE)
```

This issue seems to be trigged by this rough sequence of events:
* vkCmdBeginRenderPass, no multi-view
* draw
* vkCmdEndRenderPass
* A few dispatches and barriers
* vkCmdBeginRenderPass, multi-view enabled 

That last call to vkCmdBeginRenderPass is where it deadlocks, since it looks like the validation layer specifically tries to clear out bindings when multi-view is enabled

**Valid Usage ID**
This was not tied to a specific validation message

**Environment:**
 - OS: Windows 10 21H2
 - GPU: Nvidia RTX 2080 Ti
 - SDK or header version if building from repo: SDK 1.3.216.0
 - Options enabled (synchronization, best practices, etc.): everything is at default settings

**Additional context**

I tried disabling fine-grained locking through the Vulkan Configurator, but I still hit the same deadlock.

Thanks in advance! Also I appreciate that the SDK included PDBs so that I could track this down. 🙂

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**
The push descriptorset state object should have cb->RemoveChild() called on it before it is destroyed, to avoid deadlock in CMD_BUFFER_STATE::NotifyInvalidate().

Fixes #4376

### CODE REVIEW

**Comment by jeremyg-lunarg** [comment]
Note: The other possible fix is to call cb->RemoveChild() on the push descriptor set before the Destroy() call. Starting to think that's more correct.

File: tests/positive/render_pass.cpp [hunk 1]
```diff
@@ -1006,8 +1002,134 @@ TEST_F(VkPositiveLayerTest, CreateRenderPassWithViewMask) {
...
+        GTEST_SKIP() << RequiredExtensionsNotSupported() << " not supported";
+    }
+
+    auto vulkan_11_features = LvlInitStruct<VkPhysicalDeviceVulkan11Features>();
+    auto features2 = LvlInitStruct<VkPhysicalDeviceFeatures2>(&vulkan_11_features);
+
+    vk::GetPhysicalDeviceFeatures2(gpu(), &features2);
+    if (vulkan_11_features.multiview == VK_FALSE) {
+        GTEST_SKIP() << "multiview feature not supported, skipping test.";
+        return;
```
Comment (ncesario-lunarg) [inline tests/positive/render_pass.cpp:1029]: The `return` shouldn't be required.

**Review by ncesario-lunarg — APPROVED** [review]
Just the question/nit regarding `GTEST_SKIP`, but LGTM!

File: tests/positive/render_pass.cpp (hunk 1 above)
Comment (jeremyg-lunarg) [reply tests/positive/render_pass.cpp:1029]: doh. That was me converting a printf() too quickly. I'm surprised clang doesn't complain.

**Comment by Tony-LunarG** [comment]
I'm seeing a 06574 and 06603 in the positive test, but I see CI is too.

**Comment by jeremyg-lunarg** [comment]
> I'm seeing a 06574 and 06603 in the positive test, but I see CI is too.

Repushed to fix those. For some reason I wasn't getting them on RADV but I do on NV / Windows

**Review by Tony-LunarG — APPROVED** [review]
LGTM
