### PR TITLE
layers: Add VK_KHR_dynamic_rendering VUs

### LINKED ISSUE #3595: Dynamic rendering CTS test crash in validation
**Describe the Issue**
dEQP-VK.dynamic_rendering.suballocation.load_store_op_none.color_load_op_none_store_op_none_resolve
crashes in CoreChecks::ValidateFsOutputsAgainstDynamicRenderingRenderPass:
```
for (uint32_t location = 0; location < pipeline->rp_state->dynamic_rendering_pipeline_create_info.colorAttachmentCount; ++location) {
    const auto output = location_map[location].output;
    if (!output && pipeline->attachments[location].colorWriteMask != 0) {
       skip |= LogWarning(fs->vk_shader_module(), kVUID_Core_Shader_InputNotProduced,
           "Attachment %" PRIu32
           " not written by fragment shader; undefined values will be written to attachment",
           location);
    }
```
pipelines->attachments is size 1
pipeline->rp_state->dynamic_rendering_pipeline_create_info.colorAttachmentCount is 2
Unclear if this is a validation or test problem.

**Environment:**
 - OS:  Win 10
 - GPU: GeForce RTX 2080
 - SDK or header version if building from repo: ee8a454f
 - Options enabled (synchronization, best practices, etc.): Nothing extra.

CTS 1.2.8.0

### PR DESCRIPTION
**Pull request by AaronHaganAMD**
VU Statements:
VUID-VkCommandBufferInheritanceRenderingInfoKHR-colorAttachmentCount-06004
VUID-VkCommandBufferInheritanceRenderingInfoKHR-variableMultisampleRate-06005
VUID-vkCmdDraw*-pDepthAttachment-06189
VUID-vkCmdDraw*-pStencilAttachment-06190
VUID-vkCmdDraw*-renderPass-06198
VUID-VkGraphicsPipelineCreateInfo-renderPass-06055
VUID-VkGraphicsPipelineCreateInfo-renderPass-06057
VUID-VkGraphicsPipelineCreateInfo-renderPass-06058
VUID-VkGraphicsPipelineCreateInfo-renderPass-06060
VUID-VkGraphicsPipelineCreateInfo-renderPass-06062
VUID-VkRenderingAttachmentInfoKHR-imageView-06129
VUID-VkRenderingAttachmentInfoKHR-imageView-06130

Tests:
VUID-VkCommandBufferInheritInfoKHR-colorAttachmentCount-06004
VUID-VkCommandBufferInheritInfoKHR-variableMultisampleRate-06005
VUID-VkCommandBufferInheritInfoKHR-pColorAttachmentFormats-06006
VUID-VkCommandBufferInheritInfoKHR-depthAttachmentFormat-06007
VUID-VkCommandBufferInheritInfoKHR-multiview-06008
VUID-VkCommandBufferInheritInfoKHR-viewMask-06009
VUID-VkCommandBufferInheritInfoKHR-stencilAttachmentFormat-06199
VUID-VkCommandBufferInheritInfoKHR-depthAttachmentFormat-06200
VUID-VkCommandBufferBeginInfo-flags-06003
VUID-vkCmdDraw-pDepthAttachment-06189
VUID-vkCmdDraw-pStencilAttachment-06190
VUID-VkGraphicsPipelineCreateInfo-renderPass-06055
VUID-VkGraphicsPipelineCreateInfo-renderPass-06057 
VUID-VkGraphicsPipelineCreateInfo-renderPass-06058
VUID-VkGraphicsPipelineCreateInfo-renderPass-06060
VUID-VkGraphicsPipelineCreateInfo-renderPass-06062
VUID-VkPipelineRenderingCreateInfoKHR-pColorAttachmentFormats-06064
VUID-VkPipelineRenderingCreateInfoKHR-multiview-06066

Other:
Fixes #3595

### CODE REVIEW

File: layers/core_validation.cpp [hunk 1]
```diff
@@ -790,6 +796,32 @@ bool CoreChecks::ValidatePipelineDrawtimeState(const LAST_BOUND_STATE &state, co
                 }
             }
         }
+
+        if ((p_attachment_sample_count_info_amd || p_attachment_sample_count_info_nv) == false) {
+            if ((pCB->activeRenderPass->dynamic_rendering_begin_rendering_info.pDepthAttachment != nullptr) &&
+                (pCB->activeRenderPass->dynamic_rendering_begin_rendering_info.pDepthAttachment->imageView != VK_NULL_HANDLE)) {
+                auto depth_view_state = Get<IMAGE_VIEW_STATE>(pCB->activeRenderPass->dynamic_rendering_begin_rendering_info.pDepthAttachment->imageView);
```
Comment (ziga-lunarg) [inline layers/core_validation.cpp:803]: This could be `const auto&` so shared_ptr doesn't get copied

File: layers/core_validation.cpp [hunk 2]
```diff
@@ -1400,8 +1432,11 @@ bool CoreChecks::ValidateGraphicsPipelineBlendEnable(const PIPELINE_STATE *pPipe
             VkFormatFeatureFlags format_features;
 
             if (pPipeline->rp_state->use_dynamic_rendering) {
-                format_features = GetPotentialFormatFeatures(
-                    pPipeline->rp_state->dynamic_rendering_pipeline_create_info.pColorAttachmentFormats[i]);
+                if (create_info.pColorBlendState->attachmentCount != numberColorAttachments) { 
+                    LogError(device, "VUID-VkGraphicsPipelineCreateInfo-renderPass-06055",
```
Comment (ziga-lunarg) [inline layers/core_validation.cpp:1436]: This is missing `skip |=` in front

File: layers/core_validation.cpp [hunk 3]
```diff
@@ -790,6 +796,32 @@ bool CoreChecks::ValidatePipelineDrawtimeState(const LAST_BOUND_STATE &state, co
                 }
             }
         }
+
+        if ((p_attachment_sample_count_info_amd || p_attachment_sample_count_info_nv) == false) {
```
Comment (ncesario-lunarg) [inline layers/core_validation.cpp:800]: This seems a bit more confusing than just `(!p_attachment_sample_count_info_amd && !p_attachment_sample_count_info_nv)`, but that might just be me.

File: layers/core_validation.h [hunk 4]
```diff
@@ -96,6 +96,9 @@ struct DrawDispatchVuid {
     const char* dynamic_rendering_depth_sample = kVUIDUndefined;
     const char* dynamic_rendering_stencil_sample = kVUIDUndefined;
     const char* dynamic_rendering_multi_sample = kVUIDUndefined;
+    const char* dynamic_rendering_06189 = kVUIDUndefined;
```
Comment (ncesario-lunarg) [inline layers/core_validation.h:99]: Appending the VUID here makes a lot of sense! I wonder why this wasn't done before 🤔?

File: layers/shader_validation.cpp [hunk 5]
```diff
@@ -215,7 +215,7 @@ bool CoreChecks::ValidateFsOutputsAgainstDynamicRenderingRenderPass(SHADER_MODUL
     const bool alpha_to_coverage_enabled = pipeline->create_info.graphics.pMultisampleState != NULL &&
         pipeline->create_info.graphics.pMultisampleState->alphaToCoverageEnable == VK_TRUE;
 
-    for (uint32_t location = 0; location < pipeline->rp_state->dynamic_rendering_pipeline_create_info.colorAttachmentCount; ++location) {
+    for (uint32_t location = 0; location < location_map.size(); ++location) {
```
Comment (ncesario-lunarg) [inline layers/shader_validation.cpp:218]: This LGTM, but I'm curious if this fixed a specific error you were hitting?

**Review by ncesario-lunarg — COMMENTED** [review]
This code LGTM! Can we have tests added for each of these VUIDs?

The failure on Github Actions is failing during the mock ICD build before VVL is ever touched, so this might be an unrelated problem with the state of the Vulkan-Tools repo; haven't verified this yet.

The internal CI failure is due to a crash on our nvidia machine in the `VkPositiveLayerTest.CreateGraphicsPipelineDynamicRenderingNoInfo` test.

File: layers/shader_validation.cpp (hunk 5 above)
Comment (AaronHaganAMD) [reply layers/shader_validation.cpp:218]: This should prevent #3595 from crashing.

**Comment by AaronHaganAMD** [comment]
> pipeline->rp_state->dynamic_rendering_pipeline_create_info.colorAttachmentCount

the failing test should be fixed now.

File: layers/core_validation.h (hunk 4 above)
Comment (AaronHaganAMD) [reply layers/core_validation.h:99]: yeah.. I can go back and re-name the other dynamic rendering VUIDs

**Comment by AaronHaganAMD** [comment]
> This code LGTM! Can we have tests added for each of these VUIDs?
> 
> The failure on Github Actions is failing during the mock ICD build before VVL is ever touched, so this might be an unrelated problem with the state of the Vulkan-Tools repo; haven't verified this yet.
> 
> The internal CI failure is due to a crash on our nvidia machine in the `VkPositiveLayerTest.CreateGraphicsPipelineDynamicRenderingNoInfo` test.

Yes. will work on adding tests as well for the VUIDs

**Comment by jeremyg-lunarg** [comment]
Shouldn't the commit message be tagged "corechecks: ..." or "layers: ..."? "tests:" indicates a change to the unit tests. Otherwise this LGTM

**Comment by AaronHaganAMD** [comment]
> Shouldn't the commit message be tagged "corechecks: ..." or "layers: ..."? "tests:" indicates a change to the unit tests. Otherwise this LGTM

Yes.. I updated it to "layers"

File: layers/shader_validation.cpp (hunk 5 above)
Comment (ncesario-lunarg) [reply layers/shader_validation.cpp:218]: FYI @Tony-LunarG.

**Comment by ncesario-lunarg** [comment]
_Hopefully_ https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3606 resolves the github checks 🤞. Once that's in, then I think just adding tests for these VUIDs should be all that's left!

File: layers/shader_validation.cpp (hunk 5 above)
Comment (Tony-LunarG) [reply layers/shader_validation.cpp:218]: While this does fix 
dEQP-VK.dynamic_rendering.suballocation.load_store_op_none.color_load_op_none_store_op_none_resolve, 
it now causes 
VkPositiveLayerTest.CreateGraphicsPipelineDynamicRenderingNoInfo 
to crash at 
```
227 auto format = pipeline->rp_state->dynamic_rendering_pipeline_create_info.pColorAttachmentFormats[location];
```
location is zero and pColorAttachmentFormats is NULL

Comment (AaronHaganAMD) [reply layers/shader_validation.cpp:218]: Crashes should be resolved with 85e4bcc293495cd22676b5edd989008dc28b8661

File: tests/vklayertests_dynamic_rendering.cpp [hunk 6]
```diff
@@ -0,0 +1,187 @@
...
+ */
+
+#include "cast_utils.h"
+#include "layer_validation_tests.h"
+
+TEST_F(VkLayerTest, CommandBufferInheritanceRenderingInfoKHR) {
+    // Create VkCommandBufferInheritanceRenderingInfoKHR tests
+    TEST_DESCRIPTION("VkCommandBufferInheritanceRenderingInfoKHR Dynamic Rendering Tests.");
+
+    SetTargetApiVersion(VK_API_VERSION_1_2);
```
Comment (ncesario-lunarg) [inline tests/vklayertests_dynamic_rendering.cpp:24]: If 1.2 is needed, a `if (DeviceValidationVersion() < VK_API_VERSION_1_2) ...` check should be made after any `InitFramework` (or `Init` in this case, which calls `InitFramework`).

File: tests/vklayertests_dynamic_rendering.cpp [hunk 7]
```diff
@@ -0,0 +1,187 @@
...
+    
+    if (!AreRequestedExtensionsEnabled()) {
+        printf("%s %s is not supported; skipping\n", kSkipPrefix, VK_KHR_DYNAMIC_RENDERING_EXTENSION_NAME);
+        return;
+    }
+
+    VkAttachmentSampleCountInfoAMD sample_count_info_amd = {};
+    VkCommandBufferBeginInfo cmd_buffer_begin_info = {};
+    VkCommandBufferInheritanceInfo cmd_buffer_inheritance_info = {};
+    VkCommandBufferInheritanceRenderingInfoKHR cmd_buffer_inheritance_rendering_info = {};
```
Comment (ncesario-lunarg) [inline tests/vklayertests_dynamic_rendering.cpp:40]: Might be a bit more readable and more inline with the [style guide](https://google.github.io/styleguide/cppguide.html#Local_Variables) if these are declared when initialized. You can use the auto-generated `LvlInitStruct<>` functions to cut down on the repetition a bit.

File: tests/vklayertests_dynamic_rendering.cpp [hunk 8]
```diff
@@ -0,0 +1,187 @@
...
+    m_errorMonitor->SetDesiredFailureMsg(kErrorBit,
+                                         "VUID-VkCommandBufferInheritanceRenderingInfoKHR-stencilAttachmentFormat-06199");
+    m_errorMonitor->SetDesiredFailureMsg(kErrorBit,
+                                         "VUID-VkCommandBufferInheritanceRenderingInfoKHR-depthAttachmentFormat-06200");
+    m_errorMonitor->SetDesiredFailureMsg(kErrorBit,
+                                         "VUID-VkCommandBufferInheritanceRenderingInfoKHR-pColorAttachmentFormats-06006");
+    cmd_buffer_begin_info.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
+    cmd_buffer_begin_info.flags = VK_COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT;
+    cmd_buffer_begin_info.pInheritanceInfo = &cmd_buffer_inheritance_info;
+    vk::BeginCommandBuffer(secondary_cmd_buffer, &cmd_buffer_begin_info);
```
Comment (ncesario-lunarg) [inline tests/vklayertests_dynamic_rendering.cpp:82]: It would be great if we could have one `VerifyFound` per check, as that will make it easier to pinpoint failures in the future. e.g.,
```cpp
// state setup for 06003
m_errorMonitor->SetDesiredFailure(...06003);
vk::BeginCommandBuffer(...);
m_errorMonitor->VerifyFound();

// state setup for 06004
m_errorMonitor->SetDesiredFailure(...06004);
vk::BeginCommandBuffer(...);
...
m_errorMonitor->VerifyFound();
...
```

**Review by ncesario-lunarg — COMMENTED** [review]
Added a few comments before realizing this is a draft :)

Looks good though!

File: tests/vklayertests_dynamic_rendering.cpp (hunk 8 above)
Comment (AaronHaganAMD) [reply tests/vklayertests_dynamic_rendering.cpp]: I seem to be getting the other VU errors when separating the VUs like this. for example...

    m_errorMonitor->SetDesiredFailureMsg(kErrorBit, "VUID-VkGraphicsPipelineCreateInfo-renderPass-06055");
    pipe.CreateVKPipeline(pl.handle(), VK_NULL_HANDLE, &create_info);
    m_errorMonitor->VerifyFound();

    m_errorMonitor->SetDesiredFailureMsg(kErrorBit, "VUID-VkGraphicsPipelineCreateInfo-renderPass-06057");
    pipe.CreateVKPipeline(pl.handle(), VK_NULL_HANDLE, &create_info);
    m_errorMonitor->VerifyFound();

On the first VerifyFound it is reporting that "VUID-VkGraphicsPipelineCreateInfo-renderPass-06057" is hit and unhandled...

Comment (ncesario-lunarg) [reply tests/vklayertests_dynamic_rendering.cpp]: Ah, ok, if they are really coupled (i.e., it's impossible to trigger one without also triggering others), then what you currently have is necessary.

File: tests/vklayertests_dynamic_rendering.cpp [hunk 9]
```diff
@@ -0,0 +1,281 @@
...
+    VkPipelineObj pipe(m_device);
+
+    VkPipelineColorBlendAttachmentState color_blend_attachment_state = {};
+
+    auto color_blend_state_create_info = LvlInitStruct<VkPipelineColorBlendStateCreateInfo>();
+    color_blend_state_create_info.attachmentCount = 1;
+    color_blend_state_create_info.pAttachments = &color_blend_attachment_state;
+ 
+    VkPipelineMultisampleStateCreateInfo multisample_state_create_info = LvlInitStruct<VkPipelineMultisampleStateCreateInfo>();
+    multisample_state_create_info.rasterizationSamples = VK_SAMPLE_COUNT_2_BIT;
```
Comment (ncesario-lunarg) [inline tests/vklayertests_dynamic_rendering.cpp:241]: Looks like this is unused (causing a warning on linux compilers)?

**Review by ncesario-lunarg — CHANGES_REQUESTED** [review]
This is causing `VkLayerTest.ExecuteDiffertQueueFlagsSecondaryCB` to crash. I haven't dug into this too much, but adding the following to that test seems to fix it:
```diff
diff --git a/tests/vklayertests_command.cpp b/tests/vklayertests_command.cpp
index 08c84cb74..23612cd21 100644
--- a/tests/vklayertests_command.cpp
+++ b/tests/vklayertests_command.cpp
@@ -5183,8 +5183,13 @@ TEST_F(VkLayerTest, ExecuteDiffertQueueFlagsSecondaryCB) {
     command_buffer_allocate_info.level = VK_COMMAND_BUFFER_LEVEL_SECONDARY;
     vk::AllocateCommandBuffers(m_device->device(), &command_buffer_allocate_info, &command_buffer[1]);
 
-    VkCommandBufferBeginInfo begin_info = {};
-    begin_info.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
+    auto inheritance_info = LvlInitStruct<VkCommandBufferInheritanceInfo>();
+    inheritance_info.renderPass = m_renderPass;
+    inheritance_info.subpass = 0;
+    inheritance_info.framebuffer = m_framebuffer;
+
+    auto begin_info = LvlInitStruct<VkCommandBufferBeginInfo>();
+    begin_info.pInheritanceInfo = &inheritance_info;
 
     // secondary
     vk::BeginCommandBuffer(command_buffer[1], &begin_info);
```

FYI @sfricke-samsung (original author?) as I'm not sure how this test was working before since it hits VUID-00051 (no inheritance info for the secondary command buffer)? I really need to get #3177 in sooner than later...

File: tests/vklayertests_dynamic_rendering.cpp (hunk 9 above)
Comment (AaronHaganAMD) [reply tests/vklayertests_dynamic_rendering.cpp]: VkLayerTest.ExecuteDiffertQueueFlagsSecondaryCB and this warning should be fixed with 802f7da14a9f819787b5088143cb98a90e1dcd57

**Comment by sfricke-samsung** [comment]
>  I'm not sure how this test was working before since it hits VUID-00051

So the issue I think is how the error message is wrapped

```cpp
    // secondary
    vk::BeginCommandBuffer(command_buffer[1], &begin_info);
    vk::EndCommandBuffer(command_buffer[1]);

    // Try using different pool's command buffer as secondary
    vk::BeginCommandBuffer(command_buffer[0], &begin_info);
    m_errorMonitor->SetDesiredFailureMsg(kErrorBit, "VUID-vkCmdExecuteCommands-pCommandBuffers-00094");
    vk::CmdExecuteCommands(command_buffer[0], 1, &command_buffer[1]);
    m_errorMonitor->VerifyFound();
    vk::EndCommandBuffer(command_buffer[0]);
  ```
  
  so because it was done prior to ` m_errorMonitor->SetDesiredFailureMsg` it doesn't get caught I think... but 100% agree it is currently wrong

**Review by ncesario-lunarg — CHANGES_REQUESTED** [review]
Some minor test nits, but looks like this is still missing the other test fixes?

File: tests/vklayertests_dynamic_rendering.cpp [hunk 10]
```diff
@@ -0,0 +1,278 @@
...
+    }
+
+    VkFormat color_format = VK_FORMAT_D32_SFLOAT;
+
+    auto cmd_buffer_inheritance_rendering_info = LvlInitStruct<VkCommandBufferInheritanceRenderingInfoKHR>();
+    cmd_buffer_inheritance_rendering_info.colorAttachmentCount = 1;
+    cmd_buffer_inheritance_rendering_info.pColorAttachmentFormats = &color_format;
+    cmd_buffer_inheritance_rendering_info.depthAttachmentFormat = VK_FORMAT_R8G8B8_UNORM;
+    cmd_buffer_inheritance_rendering_info.stencilAttachmentFormat = VK_FORMAT_R8G8B8_SNORM;
+    cmd_buffer_inheritance_rendering_info.viewMask = 0xff;
```
Comment (ncesario-lunarg) [inline tests/vklayertests_dynamic_rendering.cpp:52]: This will need a similar solution to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3616/files#r772606427, but I think there is also a change necessary for `MostSignificantBit`.

Comment (AaronHaganAMD) [reply tests/vklayertests_dynamic_rendering.cpp]: I updated similar to #3616

**Review by ncesario-lunarg — APPROVED** [review]
