### PR TITLE
layers: Fix recording of VkTimelineSemaphoreSubmitInfo

### LINKED ISSUE #2616: timeline_semaphore ValidationStateTracker::PostCallRecordQueueSubmit error
The test in `ValidationStateTracker::PostCallRecordQueueSubmit` is incorrect, as it can access the array of signal or wait semaphore without checking its size. I hit the issue while I have a binary semaphore for wait and timeline semaphore in signal. 

The second issue, it is accessing the timeline semaphore info index, from the global semaphore index. Meaning that if you have a mix of semaphores binary/timeline, the index will be incorrect.

This seems new from 
 - SDK 1.2.170.0

Here is a suggested fix for `ValidationStateTracker::PostCallRecordQueueSubmit()`
See modification in the two for-loop.

```
void ValidationStateTracker::PostCallRecordQueueSubmit(VkQueue queue, uint32_t submitCount, const VkSubmitInfo *pSubmits,
                                                       VkFence fence, VkResult result) {
    if (result != VK_SUCCESS) return;
    auto queue_state = GetQueueState(queue);

    uint64_t early_retire_seq = RecordSubmitFence(queue_state, fence, submitCount);

    // Now process each individual submit
    for (uint32_t submit_idx = 0; submit_idx < submitCount; submit_idx++) {
        CB_SUBMISSION submission;
        const VkSubmitInfo *submit = &pSubmits[submit_idx];
        const uint64_t next_seq = queue_state->seq + queue_state->submissions.size() + 1;
        auto *timeline_semaphore_submit = LvlFindInChain<VkTimelineSemaphoreSubmitInfo>(submit->pNext);
        for (uint32_t i = 0; i < submit->waitSemaphoreCount; ++i) {
            uint64_t w_idx = 0;
            uint64_t value = timeline_semaphore_submit && timeline_semaphore_submit->waitSemaphoreValueCount > w_idx
                                 ? timeline_semaphore_submit->pWaitSemaphoreValues[w_idx]
                                 : 0;
            if (GetSemaphoreState(submit->pWaitSemaphores[i])->type == VK_SEMAPHORE_TYPE_TIMELINE) w_idx++;
            RecordSubmitWaitSemaphore(submission, queue, submit->pWaitSemaphores[i], value, next_seq);
        }

        bool retire_early = false;
        for (uint32_t i = 0; i < submit->signalSemaphoreCount; ++i) {
            uint64_t s_idx = 0;
            uint64_t value = timeline_semaphore_submit && timeline_semaphore_submit->signalSemaphoreValueCount > s_idx
                                 ? timeline_semaphore_submit->pSignalSemaphoreValues[s_idx]
                                 : 0;
            if (GetSemaphoreState(submit->pWaitSemaphores[i])->type == VK_SEMAPHORE_TYPE_TIMELINE) s_idx++;
            retire_early |= RecordSubmitSignalSemaphore(submission, queue, submit->pSignalSemaphores[i], value, next_seq);
        }
        if (retire_early) {
            early_retire_seq = std::max(early_retire_seq, next_seq);
        }

        const auto perf_submit = LvlFindInChain<VkPerformanceQuerySubmitInfoKHR>(submit->pNext);
        submission.perf_submit_pass = perf_submit ? perf_submit->counterPassIndex : 0;

        for (uint32_t i = 0; i < submit->commandBufferCount; i++) {
            RecordSubmitCommandBuffer(submission, submit->pCommandBuffers[i]);
        }
        submission.fence = submit_idx == (submitCount - 1) ? fence : VK_NULL_HANDLE;
        queue_state->submissions.emplace_back(std::move(submission));
    }

    if (early_retire_seq) {
        RetireWorkOnQueue(queue_state, early_retire_seq);
    }
}
```

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**
Handle null pointer dereferences or out of bounds accesses if
the SemaphoreValues arrays are null or incorrectly sized.

Add a test case that prevents this regression from happening again.
    
Fixes #2616

### CODE REVIEW

**Review by ncesario-lunarg — APPROVED** [review]
LGTM!

File: layers/state_tracker.cpp [hunk 1]
```diff
@@ -2392,13 +2392,21 @@ void ValidationStateTracker::PostCallRecordQueueSubmit(VkQueue queue, uint32_t s
         const uint64_t next_seq = queue_state->seq + queue_state->submissions.size() + 1;
         auto *timeline_semaphore_submit = LvlFindInChain<VkTimelineSemaphoreSubmitInfo>(submit->pNext);
         for (uint32_t i = 0; i < submit->waitSemaphoreCount; ++i) {
-            uint64_t value = timeline_semaphore_submit ? timeline_semaphore_submit->pWaitSemaphoreValues[i] : 0;
+            uint64_t value = 0; 
+            if (timeline_semaphore_submit && timeline_semaphore_submit->pWaitSemaphoreValues != nullptr
+                && i < timeline_semaphore_submit->pWaitSemaphoreValues[i]) {
```
Comment (jeremyg-lunarg) [inline layers/state_tracker.cpp:2397]: Should be i <  timeline_semaphore_submit->pWaitSemaphoreValueCount...

**Comment by jeremyg-lunarg** [comment]
This change passed internal CI in job 4192
