### PR TITLE
Fix Clang compiler warnings

### LINKED ISSUE #1608: Remove clang compiler warnings when building
I have had it a few times now where I get a build error/warning that is important but it was suppressed in the noise of warnings I get currently

I normally build with clang 6, but checked a gcc 7 build and see that doesn't spit warnings so these seems to be clang warnings

Basically to sum up all the warnings:

Unused functions clang can't resolve
```
vk_extension_helper.h:53:13: warning: unused function 'IsExtEnabled' [-Wunused-function]

state_tracker.h:222:68: warning: unused function 'GetDslFromPipelineLayout' [-Wunused-function]

core_validation_types.h:522:13: warning: unused function 'ImageLayoutMatches' [-Wunused-function]
```

unused const variables clang can't resolve
```
parameter_validation.cpp:47:28: warning: unused variable 'AllVkFormatFeatureFlagBits' [-Wunused-const-variable]
```

Not sure why `noexcept` is causing this
```
vktestbinding.cpp:242:9: warning: function previously declared with an explicit exception specification redeclared with an implicit exception
      specification [-Wimplicit-exception-spec-mismatch]
Device::~Device() {
        ^
vktestbinding.h:195:5: note: previous declaration is here
    ~Device() NOEXCEPT;
     ^
```

My main question is what of the 3 possible options would we want to take:
- set `-Wno-unused-function -Wno-unused-const-variable -Wno-implicit-exception-spec-mismatch` in cmake
- add pragamas for clang to ignore these
- acknowledge this is just how it is and that if you are building for clang it is in your best interest to set those `-Wno` manually

### PR DESCRIPTION
**Pull request by mark-lunarg**
The number of warnings made the clang build output unusable.  Fixed existing warnings, next step will be to turn on warnings-as-errors for these builds in addition to the other builds.

@jzulauf-lunarg, @locke-lunarg, added y'all since the three of us were responsible for even shares of the problems.

Fixes #1608.

### CODE REVIEW

File: layers/state_tracker.h [hunk 1]
```diff
@@ -219,14 +219,8 @@ using std::unordered_map;
 #define VALSTATETRACK_MAP_AND_TRAITS_INSTANCE_SCOPE(handle_type, state_type, map_member) \
     VALSTATETRACK_MAP_AND_TRAITS_IMPL(handle_type, state_type, map_member, true)
 
-static std::shared_ptr<cvdescriptorset::DescriptorSetLayout const> GetDslFromPipelineLayout(
```
Comment (jeremy-lunarg) [inline layers/state_tracker.h]: I think it is the static that is causing the warning.

File: layers/generated/vk_extension_helper.h [hunk 2]
```diff
@@ -44,13 +44,20 @@
 
 #define VK_VERSION_1_1_NAME "VK_VERSION_1_1"
 
+// Suppress unused warning on Linux
+#if defined(__GNUC__)
+#define DECORATE_UNUSED __attribute__((unused))
```
Comment (jeremy-lunarg) [inline layers/generated/vk_extension_helper.h]: Will this be defined in two places?

File: layers/state_tracker.h (hunk 1 above)
Comment (mark-lunarg) [reply layers/state_tracker.h]: Yeah, I could have done this 'decorate_unused' hack for all of these guys, but I thought it made more sense to split the declaration from the definition, instead of having it all in the header file?  What's the Right Thing To Do?

File: layers/generated/vk_extension_helper.h (hunk 2 above)
Comment (mark-lunarg) [reply layers/generated/vk_extension_helper.h]: Do you mean 'simultaneously', which would cause a problem, or, Ever?

Comment (mark-lunarg) [reply layers/generated/vk_extension_helper.h]: Because this would be the eighth definition in the repo.

File: layers/state_tracker.h (hunk 1 above)
Comment (jeremy-lunarg) [reply layers/state_tracker.h]: Looks like it's used by two translation units. This is probably okay for now. It just looked a little odd.

File: layers/generated/vk_extension_helper.h (hunk 2 above)
Comment (jeremy-lunarg) [reply layers/generated/vk_extension_helper.h]: eight? okay, then.
