### PR TITLE
layers: Add VUIDs 04961 and 04962

### LINKED ISSUE #3097: Access violation in ValidateCmdBeginRenderPass
**Describe the Issue**

I had some code incorrectly call `vkCmdBeginRenderPass2` without passing any clear value, even if some attachment was specifying a clear operation.

In `core_validation.cpp` the check `if (clear_op_size > pRenderPassBegin->clearValueCount)` happens after `ValidateClearDepthStencilValue`, which tries to access a null `pRenderPassBegin->pClearValues[i]` with no checks.

This causes an access violation.

**Environment:**
 - OS: Windows 10.0.19043
 - GPU: Ryzen 5 4600H APU
 - SDK or header version if building from repo: VK_HEADER_VERSION 185
 - Options enabled (synchronization, best practices, etc.):

**Additional context**

### PR DESCRIPTION
**Pull request by ncesario-lunarg**
Adds missing manual parameter validation for `vkCmdClearColorImage` and `vkCmdBeginRenderPass*`.

This also adds a null check to avoid a crash at CmdBeginRenderPass time.

Closes #3097.

### CODE REVIEW

File: tests/vklayertests_command.cpp [hunk 1]
```diff
@@ -9160,3 +9160,38 @@ TEST_F(VkLayerTest, CommandBufferMissingOcclusionQueryEnabled) {
...
+    image_ci.extent.height = 32;
+    image_ci.extent.depth = 1;
+    image_ci.mipLevels = 1;
+    image_ci.arrayLayers = 1;
+    image_ci.samples = VK_SAMPLE_COUNT_1_BIT;
+    image_ci.tiling = VK_IMAGE_TILING_OPTIMAL;
+    image_ci.usage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT;
+    image_ci.flags = 0;
+    VkImageObj image(m_device);
+    image.init(&image_ci);
```
Comment (Tony-LunarG) [inline tests/vklayertests_command.cpp:9183]: image.Init(32, 32, 1, VK_FORMAT_B8G8R8A8_UNORM, VK_IMAGE_USAGE_TRANSFER_DST_BIT, VK_IMAGE_TILING_OPTIMAL, 0); and avoid image_ci?  Just a suggestion.

**Review by Tony-LunarG — APPROVED** [review]
LGTM

File: tests/vklayertests_command.cpp (hunk 1 above)
Comment (ncesario-lunarg) [reply tests/vklayertests_command.cpp:9183]: Yeah, that's definitely cleaner. Some day I'll catalog all of the test utilities we have :)

Comment (Tony-LunarG) [reply tests/vklayertests_command.cpp]: Please share that catalog when you do!
