### PR TITLE
Make gpuav work with descriptor heap

### LINKED ISSUE #11640: Crash when using GPU-AV and descriptor heaps
Enabling GPU-AV when using descriptor heaps is causing crashes for me in a very simple application. Validation is clean.

Tested with both the latest SDK (1.4.341.1) and layers built from source (commit e2888d92911bf5f0fcab0b017f6ffb797d268409).

The crash happens when issuing a draw call via `vkCmdDrawIndexed` with a uniform buffer, image and sampler bound via descriptor heaps.

Looking at the call stack, the crash seems to be caused by an assert inside [`PipelineSubState::GetPipelineLayoutUnion`](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/e2888d92911bf5f0fcab0b017f6ffb797d268409/layers/gpuav/resources/gpuav_state_trackers.cpp#L673):

Image

PipelineLayout sound suspicious, as that's something no longer required with descriptor heap. So maybe GPU-AV still expect a pipeline layout.

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #11640

### CODE REVIEW

File: layers/gpuav/instrumentation/gpuav_instrumentation.cpp [hunk 1]
```diff
@@ -205,6 +205,97 @@ void UpdateInstrumentationDescBuffer(Validator &gpuav, CommandBufferSubState &cb
     }
 }
 
+void UpdateInstrumentationDescHeap(Validator &gpuav, CommandBufferSubState &cb_state, void *resource_heap_memory,
+                                   const std::array<uint32_t, 2> dynamic_offsets, const VkDeviceSize write_offset,
```
Comment (arno-lunarg) [inline layers/gpuav/instrumentation/gpuav_instrumentation.cpp]: For clarity and ease of use, I think a struct with appropriately named members would be nicer than a std::array?

File: layers/gpuav/instrumentation/vertex_attribute_fetch_oob.cpp [hunk 2]
```diff
@@ -368,6 +368,61 @@ void RegisterVertexAttributeFetchOobValidation(Validator &gpuav, CommandBufferSu
...
+    cb.on_instrumentation_desc_heap_update_functions.emplace_back(
+        [&gpuav, error_info](CommandBufferSubState &cb, VkPipelineBindPoint, const Location &loc,
+                             VkDeviceAddressRangeEXT &out_address_range, uint32_t &out_dst_binding) {
+            if (!vvl::IsCommandDrawVertex(loc.function)) {
+                return;
+            }
+
+            VkDeviceAddressRangeEXT vertex_attribute_fetch_limits_buffer_ar;
+            // This check is only for indexed draws
+            if (vvl::IsCommandDrawVertexIndexed(loc.function)) {
```
Comment (arno-lunarg) [inline layers/gpuav/instrumentation/vertex_attribute_fetch_oob.cpp:390]: I think that's a copy paste? This needs to be in a single function, the logic is not trivial and I had to come back to it to fix it, so better to have at a single spot

File: layers/gpuav/core/gpuav_validation_pipeline.h [hunk 3]
```diff
@@ -23,6 +23,7 @@
 #include <vector>
 #include <vulkan/vulkan.h>
 #include <vulkan/utility/vk_safe_struct.hpp>
+#include "gpuav/core/gpuav.h"
```
Comment (spencer-lunarg) [inline layers/gpuav/core/gpuav_validation_pipeline.h]: remove including headers from headers unless needed please

**Comment by spencer-lunarg** [comment]
There a few things I want to change, mainly because they way I looked at how descriptor buffers work.

instead of blocking this, going to just merge, and work on top of this
