### PR TITLE
layers: Extension dep error message fix

### LINKED ISSUE #12111: Missing extension validation should state type of extension (and is prob. a bit misleading)
**Environment:**
 - OS: Windows11
 - GPU and driver version: NVIDIA RTX 4070 with latest 
 - SDK or header version if building from repo: Latest from repo
 - Options enabled (synchronization, best practices, etc.): n/a

**Describe the Issue**

No idea why I never noticed, but `VUID-vkCreateDevice-ppEnabledExtensionNames-01387` doesn't mention the type of extension to enable.

Example:

```sh
vkCreateDevice(): pCreateInfo->ppEnabledExtensionNames[0] Missing extension required by the device extension VK_KHR_compute_shader_derivatives: VK_KHR_get_physical_device_properties2.
The Vulkan spec states: All required device extensions for each extension in the VkDeviceCreateInfo::ppEnabledExtensionNames list must also be present in that list (https://docs.vulkan.org/spec/latest/chapters/devsandqueues.html#VUID-vkCreateDevice-ppEnabledExtensionNames-01387)
```

This tells you that `VK_KHR_get_physical_device_properties2` is required to use `VK_KHR_compute_shader_derivatives`, but doesn't tell you that `VK_KHR_get_physical_device_properties2` is an instance extensions. Instead it actually says that `All required device extensions for each extension in the VkDeviceCreateInfo::ppEnabledExtensionNames list must also be present in that list`, which in this case isn't true.

**Expected behavior**

The VUID states what type an extension is (device or instance) and (if instance) refers to `VkInstanceCreateInfo::ppEnabledExtensionNames` instead of `VkDeviceCreateInfo::ppEnabledExtensionNames`.

**Valid Usage ID**
VUID-vkCreateDevice-ppEnabledExtensionNames-01387

### PR DESCRIPTION
**Pull request by spencer-lunarg**
closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/12111

new message (for device extension missing dependency) will look like

```
vkCreateDevice(): pCreateInfo->ppEnabledExtensionNames[0] Missing extension required to enable device extension VK_KHR_shared_presentable_image:
 - VK_KHR_get_surface_capabilities2 (instance extension, which needs to be set at VkInstanceCreateInfo::ppEnabledExtensionNames)
```

when it requires an instance extension

### CODE REVIEW

File: layers/stateless/sl_instance_device.cpp [hunk 1]
```diff
@@ -97,12 +60,35 @@ bool Instance::ValidateExtensionReqs(const ExtensionState& extensions, const cha
...
+
+    } else {
+        std::ostringstream ss;
+        ss << "Missing extension" << ((missing.size() > 1) ? "s" : "") << " required to enable device extension "
+           << String(extension) << ":\n";
+        for (auto missing_name : missing) {
+            ss << " - " << missing_name;
+            vvl::Extension missing_extension = GetExtension(missing_name);
+            if (IsInstanceExtension(missing_extension)) {
+                ss << " (instance extension, which needs to be set at VkInstanceCreateInfo::ppEnabledExtensionNames)";
```
Comment (arno-lunarg) [inline layers/stateless/sl_instance_device.cpp]:
```suggestion
                ss << " (instance extension, which needs to be added to VkInstanceCreateInfo::ppEnabledExtensionNames)";
```
Maybe? Not sure

**Review by arno-lunarg — APPROVED** [review]

File: layers/stateless/sl_instance_device.cpp (hunk 1 above)
Comment (spencer-lunarg) [reply layers/stateless/sl_instance_device.cpp]: sure

**Comment by spencer-lunarg** [comment]
> CI Vulkan-ValidationLayers build # 23165 aborted.

unrelated
