### PR TITLE
Fix vkCreateSwapchainKHR imageExtent check

### LINKED ISSUE #1340: vkCreateSwapchainKHR imageExtent surface capabilities false positive
`CoreChecks::ValidateCreateSwapchain` checks that the supplied `imageExtent` falls within the bounds given by `vkGetPhysicalDeviceSurfaceCapabilitiesKHR`. However, it's possible that a correct application will call `vkGetPhysicalDeviceSurfaceCapabilitiesKHR`, followed by the underlying surface being resized before the call to `vkCreateSwapchainKHR`, causing the layer's own call to produce different results. To ensure consistency, the layer should probably cache the results from the most recent call made by the application, if any.

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #1340 

This PR removes the false positives, by allowing the values from the last `vkGetPhysicalDeviceSurfaceCapabilitiesKHR` call to be valid. A warning is still produced if the extent is not within the bounds of current values returned by `vkGetPhysicalDeviceSurfaceCapabilitiesKHR`.

### CODE REVIEW

File: layers/core_validation.cpp [hunk 1]
```diff
@@ -15704,14 +15704,35 @@ bool CoreChecks::ValidateCreateSwapchain(const char *func_name, VkSwapchainCreat
...
-        if (LogError(device, "VUID-VkSwapchainCreateInfoKHR-imageExtent-01274",
-                     "%s called with imageExtent = (%d,%d), which is outside the bounds returned by "
-                     "vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (%d,%d), minImageExtent = (%d,%d), "
-                     "maxImageExtent = (%d,%d).",
-                     func_name, pCreateInfo->imageExtent.width, pCreateInfo->imageExtent.height, capabilities.currentExtent.width,
-                     capabilities.currentExtent.height, capabilities.minImageExtent.width, capabilities.minImageExtent.height,
-                     capabilities.maxImageExtent.width, capabilities.maxImageExtent.height)) {
-            return true;
+        const auto cached_capabilities = surface_state->GetCapabilities(physical_device);
+        if ((pCreateInfo->imageExtent.width < cached_capabilities.minImageExtent.width) ||
```
Comment (jeremyg-lunarg) [inline layers/core_validation.cpp:15708]: It might be worth making a utility function of some sort to do this comparison of 2 extents, since it also occurs right above this new block.

**Comment by Ralith** [comment]
> A warning is still produced if the extent is not within the bounds of current values returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR.

Is this justified? It's *very* easy to trigger this case routinely in correct code due to races, so such a warning is noisy and will tend to desensitize people to real issues.

File: layers/core_validation.cpp [hunk 2]
```diff
@@ -15704,14 +15704,35 @@ bool CoreChecks::ValidateCreateSwapchain(const char *func_name, VkSwapchainCreat
...
+                         "maxImageExtent = (%d,%d).",
+                         func_name, pCreateInfo->imageExtent.width, pCreateInfo->imageExtent.height,
+                         capabilities.currentExtent.width, capabilities.currentExtent.height, capabilities.minImageExtent.width,
+                         capabilities.minImageExtent.height, capabilities.maxImageExtent.width,
+                         capabilities.maxImageExtent.height)) {
+                return true;
+            }
+        } else {
+            skip |= LogWarning(
+                device, "VUID-VkSwapchainCreateInfoKHR-imageExtent-01274",
```
Comment (jeremyg-lunarg) [inline layers/core_validation.cpp:15724]: Would it be worthwhile to give this a different UNASSIGNED VUID so that people can filter it out this warning if they want?

File: tests/vklayertests_wsi.cpp [hunk 3]
```diff
@@ -2417,3 +2417,51 @@ TEST_F(VkLayerTest, TestCreatingWin32Surface) {
...
+    swapchain_ci.imageSharingMode = VK_SHARING_MODE_EXCLUSIVE;
+    swapchain_ci.preTransform = VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR;
+    swapchain_ci.compositeAlpha = m_surface_composite_alpha;
+    swapchain_ci.presentMode = m_surface_non_shared_present_mode;
+    swapchain_ci.clipped = VK_FALSE;
+    swapchain_ci.oldSwapchain = 0;
+
+    VkSwapchainKHR swapchain;
+    vk::CreateSwapchainKHR(device(), &swapchain_ci, nullptr, &swapchain);
+
```
Comment (jeremyg-lunarg) [inline tests/vklayertests_wsi.cpp:2465]: Would it be possible to test the WARNING as well, or would that require weird window system interactions to get the surface to resize?

Comment (ziga-lunarg) [reply tests/vklayertests_wsi.cpp:2465]: This is not application controlled, so impossible for me to test.

Comment (jeremyg-lunarg) [reply tests/vklayertests_wsi.cpp:2465]: Given that, I am starting to agree that having even the warning might be too much noise.  @mark-lunarg & @ncesario-lunarg what do you think?

**Review by ncesario-lunarg — COMMENTED** [review]
1 nit, and I think the warning _probably_ belongs in BP, but overall LGTM.

File: tests/vklayertests_wsi.cpp (hunk 3 above)
Comment (ncesario-lunarg) [reply tests/vklayertests_wsi.cpp:2465]: So, this is still clearly an error in the spec (thanks @mark-lunarg for reminding me...I had forgotten the long history on this and related issues 😬). So, while _something should be done_, I think it needs to happen in Vulkan-Docs first (i.e., https://github.com/KhronosGroup/Vulkan-Docs/issues/1144, https://github.com/KhronosGroup/Vulkan-Docs/issues/388, which are still outstanding). Once the WG agrees on a spec change, then we can implement it here.

@Tony-LunarG @jeremyg-lunarg @ziga-lunarg @aitor-lunarg thoughts?

Comment (jeremyg-lunarg) [reply tests/vklayertests_wsi.cpp:2465]: If we can push either of those docs issues to resolution that'd be great. In the meantime I think this patch without the warning at all would be good  since it does quiet down errors that can otherwise never be fixed.

Comment (ncesario-lunarg) [reply tests/vklayertests_wsi.cpp:2465]: Yes, I think that makes sense. @ziga-lunarg what do you think?

Comment (ziga-lunarg) [reply tests/vklayertests_wsi.cpp:2465]: I agree, I've updated the PR.
