### PR TITLE
201 header

### LINKED ISSUE #3585: Beta extensions build broken due to Vulkan-Headers changes
**Describe the Issue**
Building the vulkan validation layers with `VK_ENABLE_BETA_EXTENSIONS` doesn't work because Vulkan-headers removed VK_VIDEO_ENCODE_RATE_CONTROL_RESET_BIT_KHR and added VK_VIDEO_ENCODE_RATE_CONTROL_RESERVED_0_BIT_KHR in https://github.com/KhronosGroup/Vulkan-Headers/pull/247.

**Environment:**
 - OS: Any (Windows/Mac/Linux/Android)
 - GPU: N/A
 - SDK or header version if building from repo: https://github.com/KhronosGroup/Vulkan-Headers/commit/ea61f32f24d2ce28b358e154910fb4eb410ffd79
 - Options enabled (synchronization, best practices, etc.): `-DVK_ENABLE_BETA_EXTENSIONS`

**Additional context**
Example build log:
https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket/8829049900737553297/+/u/compile__with_patch_/raw_io.output_text_failure_summary_
From this change:
https://chromium-review.googlesource.com/c/chromium/src/+/3310131/3

### PR DESCRIPTION
**Pull request by mikes-lunarg**
build: Update to header 1.2.201 

- Update known-good
- Generate source
 
layers: VUID cleanup for 201 header 

- Change redundant VUIDs 06081/06082 and 02854/02855 to 06166/06167
- Remove 04875/04879/04884/03420 from vkCmdDrawMeshTasksIndirectCountNV,
  vkCmdDrawMeshTasksIndirectNV, vkCmdDrawMeshTasksNV
- Leaving inconsistencies 02547 and 03342 for #3571 to address

Fixes #3585 
ping @sfricke-samsung, I tried not to step on your depthStencilResolve PR

### CODE REVIEW

**Review by jeremyg-lunarg — APPROVED** [review]
LGTM

**Review by mark-lunarg — APPROVED** [review]

File: layers/generated/vk_validation_error_messages.h [hunk 1]
```diff
@@ -4612,7 +4609,6 @@ static const vuid_spec_text_pair vuid_spec_text[] = {
     {"VUID-VkSubpassDescription-colorAttachmentCount-00845", "colorAttachmentCount must be less than or equal to VkPhysicalDeviceLimits::maxColorAttachments", "1.2-extensions"},
     {"VUID-VkSubpassDescription-flags-00856", "If flags includes VK_SUBPASS_DESCRIPTION_PER_VIEW_POSITION_X_ONLY_BIT_NVX, it must also include VK_SUBPASS_DESCRIPTION_PER_VIEW_ATTRIBUTES_BIT_NVX", "1.2-extensions"},
     {"VUID-VkSubpassDescription-flags-03341", "If flags includes VK_SUBPASS_DESCRIPTION_SHADER_RESOLVE_BIT_QCOM, and if pResolveAttachments is not NULL, then each resolve attachment must be VK_ATTACHMENT_UNUSED", "1.2-extensions"},
-    {"VUID-VkSubpassDescription-flags-03342", "If flags includes VK_SUBPASS_DESCRIPTION_SHADER_RESOLVE_BIT_QCOM, and if pDepthStencilResolveAttachmentKHR is not NULL, then the depth/stencil resolve attachment must be VK_ATTACHMENT_UNUSED", "1.2-extensions"},
```
Comment (sfricke-samsung) [inline layers/generated/vk_validation_error_messages.h:4615]: @mikes-lunarg either feel free to do it now, or can wait for my PR to do it, but this was changed to 
`VUID-VkRenderPassCreateInfo2-flags-04908` in `core_validation.cpp`

https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/4950

**Review by sfricke-samsung — APPROVED** [review]

File: layers/generated/vk_validation_error_messages.h (hunk 1 above)
Comment (sfricke-samsung) [reply layers/generated/vk_validation_error_messages.h:4615]: nvm, just saw your comment in the PR message... sounds good!
