### PR TITLE
layers: Fix sparse_container::splice()

### LINKED ISSUE #2793: Regression in image layout validation (VUID_Core_DrawState_InvalidImageLayout)
I believe after the following changes by @jeremyg-lunarg, image layout transition validation (VUID_Core_DrawState_InvalidImageLayout) is incorrect.
Reverting the following commits fixes the issue we're seeing
 - layers: Fix Image Layout range splitting (884579ec2928a26cffac0573101f48efe82d87de)
 - corechecks: Simplify Image Layout Transition maps (5363130b75709e96e75cfecb75750c7ffe458b3e)
 - layers: Add a more flexible version of sparse_container::splice (a72a0b1dac7c0e6028dcf6a15c804efa303d3760)

It seems like updates to a single array layer subresource image layout end up impacting all of the subresources in an image such that VVL's internal storage of the current layout is incorrect.

Repro steps:
1. Create a VkImage with 5 array layers
2. Transition all 5 array layers to VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL
3. Create a command buffer, insert a pipeline barrier containing a VkImageMemoryBarrier which transitions array layer 0 (baseArrayLayer = 0; layerCount = 1) to VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, and submit the command buffer
4. At this point, the first subresource should have layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL and all other subresources VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL.
5. Create a command buffer, insert a pipeline barrier containing a VkImageMemoryBarrier which transitions array layer 3 (or 1 or 2 or 4) to VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, and submit the command buffer
6. Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object 0: handle = 0x2180c0241a0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x4dae5635 | Submitted command buffer expects VkImage 0xf000000000f[] (subresource: aspectMask 0x1 array layer 3, mip level 0) to be in layout VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL--instead, current layout is VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL.

I did some logging inside VVL and observed that `CoreChecks::SetImageLayout` is being called with the expected subresource ranges. For some reason, the data must be stored incorrectly or `ValidateCmdBufImageLayouts` is not correctly observing the updates.

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**
Commit a72a0b1d introduced a bug into splice where it incorrectly splits existing ranges in some cases.
 
Add 2 unit tests to prevent this from regressing again.

Fixes #2793

### CODE REVIEW

File: layers/range_vector.h [hunk 1]
```diff
@@ -1713,7 +1713,10 @@ bool splice(DstRangeMap &to, const SrcRangeMap &from, SourceIterator begin, Sour
             // Because of how the parallel iterator walk, "to" is valid over the whole range or it isn't (ranges don't span
             // transitions between map entries or between valid and invalid ranges)
             if (to_lb->valid) {
-                updated |= updater.update(write_it->second, read_it->second);
+                auto orig_value = write_it->second;
+                updated |= updater.update(orig_value, read_it->second);
+                to.overwrite_range(to_lb->lower_bound, std::make_pair(range, orig_value));
```
Comment (jzulauf-lunarg) [inline layers/range_vector.h:1718]: orig_value is confusing.  The logic works, but it should be something like `value_to_update` or something...  also, maybe look to see if the write_it->first isn't equal to range, and only do the overwrite_range logic in that case.

**Review by jzulauf-lunarg — APPROVED** [review]
LGTM
