### PR TITLE
Remove invalid gpuav assert

### LINKED ISSUE #11932: Failed assertion when using GPU-AV and descriptor heaps
**Environment:**
 - OS: Windows 11
 - GPU and driver version: NVIDA RTX 4070 with latest VK developer beta
 - SDK or header version if building from repo: Building from top of repo
 - Options enabled (synchronization, best practices, etc.): GPU-AV

**Describe the Issue**

I'm still working on a descriptor heap sample that uses untyped pointers and I'm getting the following assert when I try to use GPU-AV:

Image

The assert happens in `VertexAttributeFetchOobPass::Instrument`:

Image

**Expected behavior**

GPU-AV does not assert.

**Valid Usage ID**
n/a

**Additional context**

<details>

Call-Stack:
```sh
 	ucrtbased.dll!00007ffc53aff575()	Unknown
 	ucrtbased.dll!00007ffc53aff393()	Unknown
 	ucrtbased.dll!00007ffc53b01c7f()	Unknown
>	VkLayer_khronos_validation.dll!gpuav::spirv::VertexAttributeFetchOobPass::Instrument() Line 58	C++
 	VkLayer_khronos_validation.dll!gpuav::spirv::Pass::Run() Line 36	C++
 	VkLayer_khronos_validation.dll!gpuav::GpuShaderInstrumentor::InstrumentShader(const vvl::enumeration<unsigned int const ,unsigned int const *> & input_spirv, const gpuav::spirv::InstrumentationInterface & interface, std::vector<unsigned int,std::allocator<unsigned int>> & out_instrumented_spirv) Line 1689	C++
 	VkLayer_khronos_validation.dll!gpuav::GpuShaderInstrumentor::PreCallRecordPipelineCreationShaderInstrumentation<vku::safe_VkGraphicsPipelineCreateInfo>(const VkAllocationCallbacks * pAllocator, vvl::Pipeline & pipeline_state, vku::safe_VkGraphicsPipelineCreateInfo & modified_pipeline_ci, unsigned int stages_count, const Location & loc, std::vector<chassis::ShaderInstrumentationMetadata,std::allocator<chassis::ShaderInstrumentationMetadata>> & shader_instrumentation_metadata) Line 1260	C++
 	VkLayer_khronos_validation.dll!gpuav::GpuShaderInstrumentor::PreCallRecordCreateGraphicsPipelines(VkDevice_T * device, VkPipelineCache_T * pipelineCache, unsigned int count, const VkGraphicsPipelineCreateInfo * pCreateInfos, const VkAllocationCallbacks * pAllocator, VkPipeline_T * * pPipelines, const RecordObject & record_obj, std::vector<std::shared_ptr<vvl::Pipeline>,std::allocator<std::shared_ptr<vvl::Pipeline>>> & pipeline_states, chassis::CreateGraphicsPipelines & chassis_state) Line 664	C++
 	VkLayer_khronos_validation.dll!vulkan_layer_chassis::CreateGraphicsPipelines(VkDevice_T * device, VkPipelineCache_T * pipelineCache, unsigned int createInfoCount, const VkGraphicsPipelineCreateInfo * pCreateInfos, const VkAllocationCallbacks * pAllocator, VkPipeline_T * * pPipelines) Line 535	C++
 	[External Code]	
 	descriptorheap.exe!VulkanExample::preparePipelines() Line 424	C++
 	descriptorheap.exe!VulkanExample::prepare() Line 467	C++
 	descriptorheap.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * __formal, int __formal) Line 563	C++
 	[External Code]	

```

</details>

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #11932

### CODE REVIEW

File: layers/gpuav/spirv/vertex_attribute_fetch_oob_pass.cpp [hunk 1]
```diff
@@ -54,9 +54,7 @@ bool VertexAttributeFetchOobPass::Instrument() {
         for (; word < total_words; word++) {
             const uint32_t interface_id = entry_point->Word(word);
             const Variable* variable = type_manager_.FindVariableById(interface_id);
-            // guaranteed by spirv-val to be a OpVariable
```
Comment (spencer-lunarg) [inline layers/gpuav/spirv/vertex_attribute_fetch_oob_pass.cpp:57]: ... give me a second, I need to know if this is a gap in spirv-val (and the glsl is generating garbage) or this is correct

Comment (ziga-lunarg) [reply layers/gpuav/spirv/vertex_attribute_fetch_oob_pass.cpp:57]: If you replaced the untyped pointer heap with a regular heap it will not assert

Comment (spencer-lunarg) [reply layers/gpuav/spirv/vertex_attribute_fetch_oob_pass.cpp:57]: @ziga-lunarg updated this, right change you had, but I want it to be clear for when I try to add untyped pointer support to the passes later

File: tests/unit/gpu_av_positive.cpp [hunk 2]
```diff
@@ -2818,3 +2818,73 @@ TEST_F(PositiveGpuAV, ConstantFoldingCompositeShuffle) {
...
+    SetTargetApiVersion(VK_API_VERSION_1_3);
+    AddRequiredExtensions(VK_EXT_DESCRIPTOR_HEAP_EXTENSION_NAME);
+    AddRequiredExtensions(VK_KHR_SHADER_UNTYPED_POINTERS_EXTENSION_NAME);
+    AddRequiredFeature(vkt::Feature::descriptorHeap);
+    AddRequiredFeature(vkt::Feature::shaderUntypedPointers);
+    RETURN_IF_SKIP(InitGpuAvFramework());
+    RETURN_IF_SKIP(InitState());
+    InitRenderTarget();
+
+    const char* vsSource = R"glsl(
```
Comment (spencer-lunarg) [inline tests/unit/gpu_av_positive.cpp:2832]: @ziga-lunarg ... so this GLSL crashes Intel ANV at pipeline creation time lol, can you add this to CTS

(it seems to crash trying to calculate the offset of a matrix in a heap, so clearly all our untyped pointer tests didn't have a matrix inside them (or array of matrix)

Comment (spencer-lunarg) [reply tests/unit/gpu_av_positive.cpp:2832]: (note, it crashes with GPU-AV turned off)

**Comment by spencer-lunarg** [comment]
> CI Vulkan-ValidationLayers build # 22874 failed.

unrelated, likely from driver update woes
