### PR TITLE
Avoid crashes/report errors for condition where attachment handles have become stale

### LINKED ISSUE #329: Validation layers don't catch deleted image views in framebuffer
If a framebuffer references some image views which are deleted, the validation layers crash. For me at least in this code because `view_state == NULL`, but other places will maybe fail if that is fixed:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/fc819201d66625159a66f128abbe3be772e46cb0/layers/buffer_validation.cpp#L329-L337

I ran into this because I cached a framebuffer pointing at the backbuffer, but recreated the underlying image views upon resize.

### PR DESCRIPTION
**Pull request by jzulauf-lunarg**
During BeginRenderpass, if a framebuffer contain references to (incorrectly) deleted image view objects, the stale handles could cause a variety of crashes.

Validation error reporting and crash prevention/robustness checks have been added, and a unit test created for the condition (thanks @karl-lunarg for the ULT)

Fixes #329 .

### CODE REVIEW

File: layers/buffer_validation.cpp [hunk 1]
```diff
@@ -297,8 +297,7 @@ void SetImageLayout(layer_data *device_data, GLOBAL_CB_NODE *cb_node, const IMAG
 }
 
 // Set image layout for all slices of an image view
-void SetImageViewLayout(layer_data *device_data, GLOBAL_CB_NODE *cb_node, VkImageView imageView, const VkImageLayout &layout) {
-    auto view_state = GetImageViewState(device_data, imageView);
+void SetImageViewLayout(layer_data *device_data, GLOBAL_CB_NODE *cb_node, IMAGE_VIEW_STATE *view_state, const VkImageLayout &layout) {
```
Comment (jzulauf-lunarg) [inline layers/buffer_validation.cpp]: As we're going to do the IMAGE_VIEW_STATE lookup to check for staleness, no need to duplicated that here.

File: layers/buffer_validation.cpp [hunk 2]
```diff
@@ -329,7 +333,16 @@ bool VerifyFramebufferAndRenderPassLayouts(layer_data *device_data, GLOBAL_CB_NO
     for (uint32_t i = 0; i < pRenderPassInfo->attachmentCount; ++i) {
         const VkImageView &image_view = framebufferInfo.pAttachments[i];
         auto view_state = GetImageViewState(device_data, image_view);
-        assert(view_state);
+
+        if (!view_state) {
```
Comment (jzulauf-lunarg) [inline layers/buffer_validation.cpp]: If we don't have a valid image view handle, I'm going to assert the framebuffer object is no longer valid as it references stale contents.  Yes, this is part of a larger class of "deep validity" checks that we don't generally have, don't have VU's , but do have support in the text.

File: layers/buffer_validation.cpp [hunk 3]
```diff
@@ -361,8 +374,10 @@ bool VerifyFramebufferAndRenderPassLayouts(layer_data *device_data, GLOBAL_CB_NO
 void TransitionAttachmentRefLayout(layer_data *device_data, GLOBAL_CB_NODE *pCB, FRAMEBUFFER_STATE *pFramebuffer,
                                    VkAttachmentReference ref) {
     if (ref.attachment != VK_ATTACHMENT_UNUSED) {
-        auto image_view = pFramebuffer->createInfo.pAttachments[ref.attachment];
-        SetImageViewLayout(device_data, pCB, image_view, ref.layout);
+        auto image_view = GetAttachmentImageViewState(device_data, pFramebuffer, ref.attachment);
```
Comment (jzulauf-lunarg) [inline layers/buffer_validation.cpp]: Since we've reported the error, we simply avoid crashing here and below

File: layers/core_validation.cpp [hunk 4]
```diff
@@ -260,6 +260,17 @@ GlobalQFOTransferBarrierMap<VkBufferMemoryBarrier> &GetGlobalQFOReleaseBarrierMa
     return dev_data->qfo_release_buffer_barrier_map;
 }
 
+// Get the image viewstate for a given framebuffer attachement
```
Comment (jzulauf-lunarg) [inline layers/core_validation.cpp]: The framebuffer has cached state that was crashing us, but since I'd like to reenable it, I've encapsulated the lookup.

File: layers/core_validation.cpp [hunk 5]
```diff
@@ -6042,8 +6053,10 @@ VKAPI_ATTR VkResult VKAPI_CALL AllocateCommandBuffers(VkDevice device, const VkC
 static void AddFramebufferBinding(layer_data *dev_data, GLOBAL_CB_NODE *cb_state, FRAMEBUFFER_STATE *fb_state) {
     AddCommandBufferBinding(&fb_state->cb_bindings, {HandleToUint64(fb_state->framebuffer), kVulkanObjectTypeFramebuffer},
                             cb_state);
-    for (auto attachment : fb_state->attachments) {
-        auto view_state = attachment.view_state;
+
+    const uint32_t attachmentCount = fb_state->createInfo.attachmentCount;
```
Comment (jzulauf-lunarg) [inline layers/core_validation.cpp]: more crash avoidance...

File: layers/core_validation.cpp [hunk 6]
```diff
@@ -9890,7 +9905,9 @@ VKAPI_ATTR void VKAPI_CALL CmdBeginRenderPass(VkCommandBuffer commandBuffer, con
     auto framebuffer = pRenderPassBegin ? GetFramebufferState(dev_data, pRenderPassBegin->framebuffer) : nullptr;
     if (cb_state) {
         skip |= PreCallValidateCmdBeginRenderPass(dev_data, render_pass_state, cb_state, framebuffer, pRenderPassBegin);
-        PreCallRecordCmdBeginRenderPass(dev_data, cb_state, framebuffer, render_pass_state, pRenderPassBegin, contents);
+        if (!skip) {
```
Comment (jzulauf-lunarg) [inline layers/core_validation.cpp]: During ULT the Begin was being skip, but the begin was recorded, leading to "UNEXPECTED" -- need to skip recording things we skip dispatching

File: tests/layer_validation_tests.cpp [hunk 7]
```diff
@@ -17193,6 +17193,79 @@ TEST_F(VkLayerTest, FramebufferIncompatible) {
...
+    attach_desc.format = VK_FORMAT_B8G8R8A8_UNORM;
+    attach_desc.samples = VK_SAMPLE_COUNT_1_BIT;
+    attach_desc.finalLayout = VK_IMAGE_LAYOUT_GENERAL;
+    rpci.pAttachments = &attach_desc;
+    rpci.sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
+    VkRenderPass rp;
+    VkResult err = vkCreateRenderPass(m_device->device(), &rpci, NULL, &rp);
+    ASSERT_VK_SUCCESS(err);
+
+    auto createView = lvl_init_struct<VkImageViewCreateInfo>();
```
Comment (jzulauf-lunarg) [inline tests/layer_validation_tests.cpp]: The testing framework objects have no way of "releasing" or "destroying" their underlying objects, so need to create one  the hard way.

File: tests/layer_validation_tests.cpp [hunk 8]
```diff
@@ -17193,6 +17193,79 @@ TEST_F(VkLayerTest, FramebufferIncompatible) {
...
+    err = vkCreateFramebuffer(device(), &fb_info, NULL, &fb);
+    vkDestroyImageView(device(), iv, NULL);
+    ASSERT_VK_SUCCESS(err);
+
+    m_errorMonitor->SetDesiredFailureMsg(VK_DEBUG_REPORT_ERROR_BIT_EXT, "VUID-VkRenderPassBeginInfo-framebuffer-parameter");
+
+    auto rpbi = lvl_init_struct<VkRenderPassBeginInfo>();
+    rpbi.renderPass = rp;
+    rpbi.framebuffer = fb;
+    rpbi.renderArea = {{
```
Comment (jzulauf-lunarg) [inline tests/layer_validation_tests.cpp]: Yes this *is* what clang-format did... don't know why ... I just noticed the random trailing comma....

**Comment by tobine** [comment]
clang-format

File: layers/core_validation.cpp [hunk 9]
```diff
@@ -7693,15 +7706,15 @@ static bool ValidateImageBarrierImage(layer_data *device_data, const char *funcN
     bool sub_image_found = false;  // Do we find a corresponding subpass description
     VkImageLayout sub_image_layout = VK_IMAGE_LAYOUT_UNDEFINED;
     uint32_t attach_index = 0;
-    uint32_t index_count = 0;
     // Verify that a framebuffer image matches barrier image
-    for (const auto &fb_attach : fb_state->attachments) {
-        if (img_bar_image == fb_attach.image) {
+    const auto attachmentCount = fb_state->createInfo.attachmentCount;
+    for (uint32_t attachement = 0; attachement < attachmentCount; ++attachement) {
```
[the remark this answers is not in the document]
Comment (jzulauf-lunarg) [reply layers/core_validation.cpp]: in a global search and replace...

**Comment by jzulauf-lunarg** [comment]
@tobine -- I learned to spell "attachment". Good to go?

**Comment by shannon-lunarg** [comment]
Okay, this is probably really picky, but a note anyway:  "w/" is presented w/ and w/o a trailing space in your commit messages.
