### PR TITLE
layers: Track supported extensions

### LINKED ISSUE #9746: False positive VUID-VkDebugUtilsMessengerCreateInfoEXT-messageType-parameter
Trying to create a `VkDebugUtilsMessengerEXT`, by using `VkDebugUtilsMessengerCreateInfoEXT` that has `VK_DEBUG_UTILS_MESSAGE_TYPE_DEVICE_ADDRESS_BINDING_BIT_EXT` in `messageType` will give:

```
VUID-VkDebugUtilsMessengerCreateInfoEXT-messageType-parameter(ERROR / SPEC): msgNum: -553000032 - Validation Error: [ VUID-VkDebugUtilsMessengerCreateInfoEXT-messageType-parameter ] Object 0: handle = 0x182660e5b40, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xdf09e3a0 | vkCreateDebugUtilsMessengerEXT(): pCreateInfo->messageType has VkDebugUtilsMessageTypeFlagBitsEXT values (VK_DEBUG_UTILS_MESSAGE_TYPE_DEVICE_ADDRESS_BINDING_BIT_EXT) that requires the extensions VK_EXT_device_address_binding_report.
The Vulkan spec states: messageType must be a valid combination of VkDebugUtilsMessageTypeFlagBitsEXT values (https://docs.vulkan.org/spec/latest/chapters/debugging.html#VUID-VkDebugUtilsMessengerCreateInfoEXT-messageType-parameter)
```

But `VK_EXT_device_address_binding_report` is a device extension and there is no device here

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #9746

I think this could also be used to remove the extensions in `special_supported.h`

### CODE REVIEW

File: layers/chassis/dispatch_object_manual.cpp [hunk 1]
```diff
@@ -42,6 +42,18 @@ StatelessDeviceData::StatelessDeviceData(vvl::dispatch::Instance *instance, VkPh
     api_version = std::min(APIVersion(device_properties.apiVersion), instance->api_version);
 
     extensions = DeviceExtensions(instance->extensions, api_version, pCreateInfo);
+    uint32_t extensionCount = 0u;
+    DispatchEnumerateDeviceExtensionProperties(physical_device, nullptr, &extensionCount, nullptr);
```
Comment (spencer-lunarg) [inline layers/chassis/dispatch_object_manual.cpp]: just searching, we do the `DispatchEnumerateDeviceExtensionProperties` query 5 times already in VVL (2 already in Stateless outside of this PR)

We clearly are missing some unified logic (especially in stateless)

File: layers/vulkan/generated/vk_extension_helper.h [hunk 2]
```diff
@@ -75,7 +76,9 @@ Times to NOT use it
       is enabled, then we already validated that extension is enabled.
     - Some variables (ex. viewMask) require the extension to be used if non-zero
 */
-[[maybe_unused]] static bool IsExtEnabled(ExtEnabled extension) { return (extension != kNotEnabled); }
+[[maybe_unused]] static bool IsExtEnabled(ExtEnabled extension) { return (extension != kNotEnabled && extension != kSupported); }
```
Comment (spencer-lunarg) [inline layers/vulkan/generated/vk_extension_helper.h]: I think this would break things, when I have called this, I had the mental model that extension could be supported, but the developer didn't enable it

otherwise you will get a VVL or no-VVL error depending on the machine you run

Comment (ziga-lunarg) [reply layers/vulkan/generated/vk_extension_helper.h]: `IsExtEnabled` works as before, it will return true if the state is one of
`kEnabledByCreateinfo`
`kEnabledByApiLevel`
`kEnabledByInteraction`

Comment (ziga-lunarg) [reply layers/vulkan/generated/vk_extension_helper.h]: I think it would be better and more clear to make the condition:
extension == kEnabledByCreateinfo || extension == kEnabledByApiLevel || extension == kEnabledByInteraction

Comment (ziga-lunarg) [reply layers/vulkan/generated/vk_extension_helper.h]: I guess it would be better to rename 
kSupported => kNotEnabled
and 
kNotEnabled => kNotSupported

File: layers/chassis/dispatch_object_manual.cpp (hunk 1 above)
Comment (spencer-lunarg) [reply layers/chassis/dispatch_object_manual.cpp]: happy to defer ... for now https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/10747

File: layers/chassis/dispatch_object_manual.cpp [hunk 3]
```diff
@@ -42,14 +42,26 @@ StatelessDeviceData::StatelessDeviceData(vvl::dispatch::Instance *instance, VkPh
...
+
     GetEnabledDeviceFeatures(pCreateInfo, &enabled_features, api_version);
 
     instance->GetPhysicalDeviceMemoryProperties(physical_device, &phys_dev_mem_props);
     instance->GetPhysicalDeviceProperties(physical_device, &phys_dev_props);
 
     // Vulkan 1.1 and later can get properties from single struct.
     // The goal is to only use the phys_dev_props_core field and funnel the properties from promoted extensions
-    if (extensions.vk_feature_version_1_2) {
+    if (IsExtEnabled(extensions.vk_feature_version_1_2)) {
```
Comment (spencer-lunarg) [inline layers/chassis/dispatch_object_manual.cpp:69]: regardless of this change, these fixes were needed

File: layers/vulkan/generated/vk_extension_helper.h [hunk 4]
```diff
@@ -41,10 +41,11 @@
 vvl::Extension GetExtension(std::string extension);
 
 enum ExtEnabled : unsigned char {
-    kNotEnabled,
+    kNotSupported,
```
Comment (artem-lunarg) [inline layers/vulkan/generated/vk_extension_helper.h:44]: I'm checking this PR mostly to learn how this works. Just by looking at enum, I like the idea of having kNotSupported and kNotEnabled. But various existing kEnabledByGoodWeather seems like a different concept (again I'm new to this and it's a high chance I'm wrong or will change opinion). But still maybe ideas for future changes, @ziga what do you think of having the following: ?
ExtEnabled { kNotSupported, kNotEnabled, kEnabled}
and then also separate enum
ExtEnablingSource {kEnabledByCreateInfo, kEnabledByApiLevel, kEnabledByDependency} - and variable of this type can be std::optional, so it's empty when ExtEnabled is not kEnabled.

File: layers/chassis/dispatch_object_manual.cpp [hunk 5]
```diff
@@ -42,14 +42,26 @@ StatelessDeviceData::StatelessDeviceData(vvl::dispatch::Instance *instance, VkPh
     api_version = std::min(APIVersion(device_properties.apiVersion), instance->api_version);
 
     extensions = DeviceExtensions(instance->extensions, api_version, pCreateInfo);
+    uint32_t extensionCount = 0u;
```
Comment (artem-lunarg) [inline layers/chassis/dispatch_object_manual.cpp]: nit: underscore style

Image

File: layers/chassis/dispatch_object_manual.cpp [hunk 6]
```diff
@@ -42,14 +42,26 @@ StatelessDeviceData::StatelessDeviceData(vvl::dispatch::Instance *instance, VkPh
...
+    DispatchEnumerateDeviceExtensionProperties(physical_device, nullptr, &extensionCount, nullptr);
+    std::vector<VkExtensionProperties> supportedExtensions(extensionCount);
+    DispatchEnumerateDeviceExtensionProperties(physical_device, nullptr, &extensionCount, supportedExtensions.data());
+    for (uint32_t i = 0; i < extensionCount; i++) {
+        vvl::Extension extension = GetExtension(supportedExtensions[i].extensionName);
+        auto &info = extensions.GetInfo(extension);
+        if (info.state && (extensions.*(info.state)) == kNotSupported) {
```
Comment (artem-lunarg) [inline layers/chassis/dispatch_object_manual.cpp]: Is this condition needed? Can we have  ExtEnabled value that is kEnabledByX here?

File: layers/vulkan/generated/vk_extension_helper.h (hunk 4 above)
Comment (ziga-lunarg) [reply layers/vulkan/generated/vk_extension_helper.h:44]: In my opinion those states belong together. 
kNotEnabled means device supports it, but the application did not enabled it
kNotSupported means device does not support it and the application did not enabled it
All 3 others mean device supports it and the application did enable it (in different ways)

These are exclusive, so it for me it makes sense to keep a single variable

File: layers/chassis/dispatch_object_manual.cpp [hunk 7]
```diff
@@ -664,6 +676,27 @@ Instance::~Instance() {
...
+    instance_dispatch_table.EnumeratePhysicalDevices(instance, &physicalDeviceCount, nullptr);
+    std::vector<VkPhysicalDevice> physicalDevices(physicalDeviceCount);
+    instance_dispatch_table.EnumeratePhysicalDevices(instance, &physicalDeviceCount, physicalDevices.data());
+    for (const auto physicalDevice : physicalDevices) {
+        uint32_t extensionCount = 0u;
+        instance_dispatch_table.EnumerateDeviceExtensionProperties(physicalDevice, nullptr, &extensionCount, nullptr);
+        std::vector<VkExtensionProperties> supportedExtensions(extensionCount);
+        instance_dispatch_table.EnumerateDeviceExtensionProperties(physicalDevice, nullptr, &extensionCount,
+                                                                   supportedExtensions.data());
+        for (uint32_t i = 0; i < extensionCount; i++) {
```
Comment (artem-lunarg) [inline layers/chassis/dispatch_object_manual.cpp]: probably nit: this loop also exists above, we can have a (templated?) function something like `void MarkSupportedExtensionsAsNotEnabled(const std::vector<VkExtensionProperties>&  extension_properties, Extensions& extensions)`, so some code reuse, not exactly sure if that's worth it though

File: layers/chassis/dispatch_object_manual.cpp (hunk 6 above)
Comment (ziga-lunarg) [reply layers/chassis/dispatch_object_manual.cpp]: Yes it is needed, because the extensions are set to enabled before this.

File: layers/chassis/dispatch_object_manual.cpp (hunk 5 above)
Comment (ziga-lunarg) [reply layers/chassis/dispatch_object_manual.cpp]: Done

File: layers/chassis/dispatch_object_manual.cpp (hunk 7 above)
Comment (ziga-lunarg) [reply layers/chassis/dispatch_object_manual.cpp]: Done

File: layers/vulkan/generated/vk_extension_helper.h (hunk 4 above)
Comment (artem-lunarg) [reply layers/vulkan/generated/vk_extension_helper.h:44]: Well that's how you look into it. If we model this as state machine then yes it's good design for state machine. 

The following design is not a state machine just different variables that has precise meaning and there is some correlation between them, but it's easy to keep invariant

bool supported;
bool enabled;
EnabllingSource enabling source;

It's hard here to make mistake, if you need to check if extension is enabled you check `bool enabled` variable. The same for supported. There is correlation betwene supported and enabled, so when supported is false then enabled is also false but it's simple logic that ensures this, but then usage looks simpler.

Comment (artem-lunarg) [reply layers/vulkan/generated/vk_extension_helper.h:44]: But also the first example:
```
ExtEnabled { kNotSupported, kNotEnabled, kEnabled}
ExtEnablingSource {kEnabledByCreateInfo, kEnabledByApiLevel, kEnabledByDependency} 
```

it's not about that this violatese somehow exlcusitivty. ExtEnabled describe three independent states. std::optional<ExtEnablingSource>  just adds additional information if ExtEnabled is kEnabled.

Comment (artem-lunarg) [reply layers/vulkan/generated/vk_extension_helper.h:44]: Marking as resolved, this is not the ask to change in this PR just possibilities how this can be changed in the future (if needed).

Comment (ziga-lunarg) [reply layers/vulkan/generated/vk_extension_helper.h:44]: You say it is hard to make a mistake in your case, but I can query ExtEnablingSource, even when the extension is not enabled or supported.

But I guess I might also be biased because I don't like std::optional

File: layers/vulkan/generated/valid_flag_values.cpp [hunk 8]
```diff
@@ -31,73 +31,90 @@
 //    - if the value is even found in the API
 // so the this file is only focused on checking for extensions being supported
 
-vvl::Extensions stateless::Context::IsValidFlagValue(vvl::FlagBitmask flag_bitmask, VkFlags value) const {
+vvl::Extensions stateless::Context::IsValidFlagValue(vvl::FlagBitmask flag_bitmask, VkFlags value, bool instance_function) const {
     switch (flag_bitmask) {
         case vvl::FlagBitmask::VkAccessFlagBits:
             if (value & (VK_ACCESS_NONE)) {
-                if (!IsExtEnabled(extensions.vk_khr_synchronization2)) {
+                if ((instance_function && !IsExtSupported(extensions.vk_khr_synchronization2)) ||
```
Comment (artem-lunarg) [inline layers/vulkan/generated/valid_flag_values.cpp:38]: @ziga-lunarg is this new logic that's how this PR solves the linked issue?

File: layers/vulkan/generated/vk_extension_helper.h (hunk 4 above)
Comment (artem-lunarg) [reply layers/vulkan/generated/vk_extension_helper.h:44]: ExtEnablingSource  -the type name literally says that's the way how it was enabled. It's bug if it is queried in the places when there is no guarantee extensions is not enabled (e.g. there is not previous check for kEnabled). The idea you usualy work with ExtEnabled. It covers case if extension supported or not, enabled or not. Then the second variable will be used when by the logic the need to know specific way how extension way enabled, and by definition such logic at first will need to determine or get list of enabled extensions. For my liking it's fine :)

Comment (artem-lunarg) [reply layers/vulkan/generated/vk_extension_helper.h:44]: > I don't like std::optional

me too, but used to use it at work.

File: layers/vulkan/generated/valid_flag_values.cpp (hunk 8 above)
Comment (ziga-lunarg) [reply layers/vulkan/generated/valid_flag_values.cpp:38]: Yes. The scenarios are these:
1) An instance function is using a flag provided by an instance extensions
2) A device function is using a flag provided by a device extension
3) A device function is using a flag provided by an instance extension
4) An instance function is using a flag provided by a device extensions


4 Is currently failing, because in an instance function we are checking if a device extension is enabled. But there is no device parameter to instance functions, so there is no possible way to check this. The correct way to validate this is by checking if any of physical devices support the required device extension. 

There already are VUIDs that say "extensions must be supported by any physical device"

We are handling those cases via variables in `special_supported.h`, the extensions in there could be removed after this PR and just check if the extension is kNotEnabled or kNotSupported

This will also make it easier to handle such cases if any new VUIDs come in that say "supported" and not "enabled"

File: layers/vulkan/generated/valid_flag_values.cpp [hunk 9]
```diff
@@ -31,73 +31,90 @@
...
+                    (!instance_function && !IsExtEnabled(extensions.vk_khr_synchronization2))) {
                     return {vvl::Extension::_VK_KHR_synchronization2};
                 }
             }
             if (value & (VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT | VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT |
                          VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT)) {
-                if (!IsExtEnabled(extensions.vk_ext_transform_feedback)) {
+                if ((instance_function && !IsExtSupported(extensions.vk_ext_transform_feedback)) ||
```
Comment (artem-lunarg) [inline layers/vulkan/generated/valid_flag_values.cpp:45]: nit: I know this is a generated code, but if you like the idea to get rid of this "to be or not to be", then  helper might help, something like IsFlagAllowed(ExtEnabled extension_state, bool instance_function)

File: layers/chassis/validation_object.h [hunk 10]
```diff
@@ -119,6 +119,7 @@ class Instance : public Logger {
         PreCallRecordCreateDevice(physicalDevice, pCreateInfo, pAllocator, pDevice, record_obj);
     }
     void CopyDispatchState() { instance = dispatch_instance_->instance; }
+    void CopyExtensions() { extensions = dispatch_instance_->extensions; }
```
Comment (artem-lunarg) [inline layers/chassis/validation_object.h:123]: @ziga-lunarg I'd appreciate if you provide intuition why we need to copy now and didn't need it before

File: layers/stateless/stateless_validation.h [hunk 11]
```diff
@@ -284,10 +284,12 @@ class Context {
                                      const FlagType flag_type, const char *vuid, const char *flags_zero_vuid = nullptr) const;
 
     bool ValidateFlags(const Location &loc, vvl::FlagBitmask flag_bitmask, VkFlags all_flags, VkFlags value,
```
Comment (artem-lunarg) [inline layers/stateless/stateless_validation.h:286]: Also one idea is to have two versions ValidateFlags and ValidateInstanceFunctionFlags (or better name) so easy to search for both types instead of boolean flag  (IsValidFlagValue is fine with bool parameter, used in small number of places to implement high level stuff). If you think that's help in any way.

**Review by artem-lunarg — APPROVED** [review]
LGTM. Mostly code styling nits, but the logic looks solid as for my understanding, can't see an easier way to have more unified check than the current functionality that tests two options: instance with supported  and non-instance with enabled. These's a discussion what's the best way to represent extension enabled status but that looks like a separate design axis.

File: layers/vulkan/generated/vk_extension_helper.h (hunk 2 above)
Comment (artem-lunarg) [reply layers/vulkan/generated/vk_extension_helper.h]: > I guess it would be better to rename
kSupported => kNotEnabled
and
kNotEnabled => kNotSupported

Yes, new naming was pretty self explaining when I reviewed the PR

File: layers/chassis/validation_object.h (hunk 10 above)
Comment (ziga-lunarg) [reply layers/chassis/validation_object.h:123]: This is just due to the order of things in chassis_manual.cpp `CreateInstance()`
`instance_dispatch` object has a vector `object_dispatch`
Before VkInstance is actually created, for each `object_dispatch` we call `PreCallRecordCreateInstance()` and in there if set the extensions to one of the enabled states, if they are enabled. However the VkInstance has not been created yet, that is why we cannot set `kNotSupported` here.
So back in `CreateInstance()`, VkInstance is created after that. Now we can query the supported extensions and we do that for `instance_dispatch`. But not we must forward those values to `object_dispatch`.
Because of this order is why that `if` from before 
`if (info.state && (extensions.*(info.state)) == kNotSupported) {`
was also needed

Comment (artem-lunarg) [reply layers/chassis/validation_object.h:123]: Thanks, great explanation

File: layers/vulkan/generated/valid_flag_values.cpp (hunk 9 above)
Comment (ziga-lunarg) [reply layers/vulkan/generated/valid_flag_values.cpp:45]: This `if` is not that simple, it is not the same for every case. If you look at the change in valid_flag_values_generator.py:107
That condition is handling the following cases:
1) If this is an instance function and the extension is a device extension we need `IsExtSupported`
2) If this is an instance function and the extension is an instance extension we need `IsExtEnabled`

File: layers/stateless/stateless_validation.h (hunk 11 above)
Comment (ziga-lunarg) [reply layers/stateless/stateless_validation.h:286]: Wouldn't that just duplicate the code? However a case for template based on instance_function could be made

Comment (artem-lunarg) [reply layers/stateless/stateless_validation.h:286]: there can be a helper i guess, I mean even code duplication is not that important because it’s a single place where functions are defined but the question is about ergonomics of many use places. But yeah, I didn't mean duplication.

File: layers/vulkan/generated/vk_extension_helper.h (hunk 2 above)
Comment (ziga-lunarg) [reply layers/vulkan/generated/vk_extension_helper.h]: In the original commit it was more confusing

File: layers/chassis/validation_object.h (hunk 10 above)
Comment (spencer-lunarg) [reply layers/chassis/validation_object.h:123]: @ziga-lunarg comment in code please

File: scripts/generators/stateless_validation_helper_generator.py [hunk 12]
```diff
@@ -1044,9 +1044,18 @@ def genFuncBody(self, members: list[Member], funcName, errorLoc, valuePrefix, di
                             invalidVuid = self.GetVuid(callerName, f"{member.name}-parameter")
                             zeroVuid = invalidVuid
                         allFlagsName = 'All' + flagBitsName
-                        zeroVuidArg = '' if member.optional else ', ' + zeroVuid
+                        zeroVuidArg = ', nullptr' if member.optional else ', ' + zeroVuid
                         condition = [item for item in self.structMemberValidationConditions if (item['struct'] == structTypeName and item['field'] == flagBitsName)]
-                        usedLines.append(f'skip |= {context}ValidateFlags({errorLoc}.dot(Field::{member.name}), vvl::FlagBitmask::{flagBitsName}, {allFlagsName}, {valuePrefix}{member.name}, {flagsType}, {invalidVuid}{zeroVuidArg});\n')
+                        isInstanceFunction = 'false'
+                        if (struct):
```
Comment (spencer-lunarg) [inline scripts/generators/stateless_validation_helper_generator.py:1050]: 1. `genFuncBody` is **by far** the worse code gen we have ... this is as good as it will get
2. Will just say, I love how easy this is to read compared to the nightmare 3 years ago
