### PR TITLE
Fix issue 1458 2521, Fix updating queries 

### LINKED ISSUE #1458: Violation of implicit ordering guarantees of query commands inside ValidationStateTracker can cause false positive
I've stumbled upon a case where issuing query commands after a call to `vkCmdResetQueryPool` still produces warnings about queries not being reset, when combined with queue synchronization operations such as `vkWaitForFences` or `vkQueueWaitIdle`.

Essentially what happens is that while the state tracker correctly updates the global query state maps upon command buffer submission (thus modeling the implicit ordering guarantees of query commands), queue synchronization can cause newer query states to be overwritten with older ones. I think it's easiest explained by first looking at a code sample (I've repurposed the `VkPositiveLayerTest.ResetQueryPoolFromDifferentCB` test to reproduce this issue, so you should be able to just copy/paste this into the test suite -- but never mind the name):

```cpp
TEST_F(VkPositiveLayerTest, ResetQueryPoolFromDifferentCB) {
    TEST_DESCRIPTION("Reset a query on one CB and use it in another.");

    ASSERT_NO_FATAL_FAILURE(Init());

    m_errorMonitor->ExpectSuccess();

    VkFence ts_fence;
    VkFenceCreateInfo fence_info{};
    fence_info.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
    fence_info.flags = VK_FENCE_CREATE_SIGNALED_BIT;
    vk::CreateFence(m_device->device(), &fence_info, nullptr, &ts_fence);

    VkQueryPool query_pool;
    VkQueryPoolCreateInfo query_pool_create_info{};
    query_pool_create_info.sType = VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO;
    query_pool_create_info.queryType = VK_QUERY_TYPE_TIMESTAMP;
    query_pool_create_info.queryCount = 1;
    vk::CreateQueryPool(m_device->device(), &query_pool_create_info, nullptr, &query_pool);

    VkCommandBuffer command_buffer[2];
    VkCommandBufferAllocateInfo command_buffer_allocate_info{};
    command_buffer_allocate_info.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
    command_buffer_allocate_info.commandPool = m_commandPool->handle();
    command_buffer_allocate_info.commandBufferCount = 2;
    command_buffer_allocate_info.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
    vk::AllocateCommandBuffers(m_device->device(), &command_buffer_allocate_info, command_buffer);

    {
        VkCommandBufferBeginInfo begin_info{};
        begin_info.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
        begin_info.flags = VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT;

        vk::BeginCommandBuffer(command_buffer[0], &begin_info);
        vk::CmdResetQueryPool(command_buffer[0], query_pool, 0, 1);
        vk::EndCommandBuffer(command_buffer[0]);

        vk::BeginCommandBuffer(command_buffer[1], &begin_info);
        vk::CmdWriteTimestamp(command_buffer[1], VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT, query_pool, 0);
        vk::EndCommandBuffer(command_buffer[1]);
    }

    VkSubmitInfo submit_info{};
    submit_info.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    submit_info.commandBufferCount = 1;
    submit_info.pCommandBuffers = nullptr;
    submit_info.signalSemaphoreCount = 0;
    submit_info.pSignalSemaphores = nullptr;

    // Begin by resetting the query pool.
    {
        submit_info.pCommandBuffers = &command_buffer[0];
        // This causes the global query state map to be updated from QUERYSTATE_UNKNOWN to QUERYSTATE_RESET.
        vk::QueueSubmit(m_device->m_queue, 1, &submit_info, VK_NULL_HANDLE);
    }

    // Write a timestamp, and add a fence to be signalled.
    {
        submit_info.pCommandBuffers = &command_buffer[1];
        vk::ResetFences(m_device->device(), 1, &ts_fence);
        // This verifies that the local/global query state is QUERYSTATE_RESET (which it is) and updates the state to QUERYSTATE_ENDED.
        vk::QueueSubmit(m_device->m_queue, 1, &submit_info, ts_fence);
    }

    // Reset query pool again.
    {
        submit_info.pCommandBuffers = &command_buffer[0];
        // Update global query state map to QUERYSTATE_RESET again.
        vk::QueueSubmit(m_device->m_queue, 1, &submit_info, VK_NULL_HANDLE);
    }

    // Finally, write a second timestamp, but before that, wait for the fence.
    {
        submit_info.pCommandBuffers = &command_buffer[1];
        // Here is the problem:
        // - Inside RetireWorkOnQueue, all command buffers up until the fence are visited again.
        // - Both previous commands (reset followed by timestamp) cause updates in the *local* query state map.
        // - However, the timestamp also causes an update in the *global* query state map, overwriting the state
        //   change from the query pool reset queue submission that happened after the fence.
        vk::WaitForFences(m_device->device(), 1, &ts_fence, true, std::numeric_limits<uint64_t>::max());
        // This check now fails as the global query state contains QUERYSTATE_AVAILABLE.
        vk::QueueSubmit(m_device->m_queue, 1, &submit_info, VK_NULL_HANDLE);
    }

    vk::QueueWaitIdle(m_device->m_queue);

    vk::FreeCommandBuffers(m_device->device(), m_commandPool->handle(), 2, command_buffer);
    vk::DestroyQueryPool(m_device->device(), query_pool, nullptr);
    vk::DestroyFence(m_device->device(), ts_fence, nullptr);

    m_errorMonitor->VerifyNotFound();
}
```

So what happens is:
1) The initial `vkCmdResetQueryPool` submission causes the global query state map to be initialized from `QUERYSTATE_UNKNOWN` to `QUERYSTATE_RESET` inside `ValidationStateTracker::PostCallRecordQueueSubmit` [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/2be3fe0f84713f6ce914886279f10f3ba16aaaff/layers/state_tracker.cpp#L1439).
2) The first call to `vkCmdWriteTimestamp` verifies that the state is `QUERYSTATE_RESET` ([here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/2be3fe0f84713f6ce914886279f10f3ba16aaaff/layers/core_validation.cpp#L6896)), which it is. It then update the state to `QUERYSTATE_ENDED`.
3) Then we reset again.
4) Before the second call to `vkCmdWriteTimestamp`, we wait for the fence submitted with the first call. This causes the first reset and timestamp commands to be visited again inside `ValidationStateTracker::RetireWorkOnQueue`. Now here is the problem: If any of the query update functions produces `QUERYSTATE_ENDED` as the new state (which the first timestamp does), this will be written into the global query state map [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/2be3fe0f84713f6ce914886279f10f3ba16aaaff/layers/state_tracker.cpp#L1317). This effectively overwrites the reset in step 3 and causes the subsequent call to `vkCmdWriteTimestamp` to fail the state check.

---

This might be the cause of #1179, but as I'm not sure and I'm pretty confident I have pinned down the exact problem in this case, I decided to open a new issue.

### PR DESCRIPTION
**Pull request by ziga-lunarg**
When a command buffer is executed only update query status if no command buffer submitted after updates the same query

Closes #1458 and #2521

### CODE REVIEW

File: layers/queue_state.cpp [hunk 1]
```diff
@@ -90,6 +90,24 @@ layer_data::optional<CB_SUBMISSION> QUEUE_STATE::NextSubmission(uint64_t until_s
     return result;
 }
 
+layer_data::unordered_set<QueryObject> QUEUE_STATE::GetQueriesUpdatedAfter() {
+    layer_data::unordered_set<QueryObject> queries;
+    auto guard = WriteLock();
```
Comment (jeremyg-lunarg) [inline layers/queue_state.cpp:95]: It seems like this method could be const and use a read lock, since you don't change the contents of the queue.

**Review by jeremyg-lunarg — COMMENTED** [review]
Running perf tests on this change...

**Comment by danginsburg** [comment]
I can confirm that this PR fixes the bug for the case I was seeing in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1458

**Comment by jeremyg-lunarg** [comment]
This change has a pretty big performance impact in 5 of our trace-based tests, need to investigate that further before it can go in.

File: layers/queue_state.cpp [hunk 2]
```diff
@@ -90,6 +90,24 @@ layer_data::optional<CB_SUBMISSION> QUEUE_STATE::NextSubmission(uint64_t until_s
...
+    layer_data::unordered_set<QueryObject> queries;
+    auto guard = ReadLock();
+
+    for (const auto &submission : submissions_) {
+        for (uint32_t j = 0; j < submission.cbs.size(); ++j) {
+            const auto next_cb_node = submission.cbs[j];
+            if (!next_cb_node) {
+                continue;
+            }
+            for (const auto &updatedQuery : next_cb_node->updatedQueries) {
```
Comment (jeremyg-lunarg) [inline layers/queue_state.cpp:103]: I was able to reproduce a perf drop from this PR, though not as bad as what internal CI is getting.  All the 'new' CPU time appears to be in merging the query maps in this loop. I did try using unordered_map::insert instead of the loop but that doesn't change the result.  You might need to change this method into something like bool QueryHasUpdatesAfter(const QueryObject&) so that no data needs to be copied.

File: layers/queue_state.cpp [hunk 3]
```diff
@@ -90,6 +90,24 @@ layer_data::optional<CB_SUBMISSION> QUEUE_STATE::NextSubmission(uint64_t until_s
     return result;
 }
 
+layer_data::unordered_set<QueryObject> QUEUE_STATE::GetQueriesUpdatedAfter() const {
+    layer_data::unordered_set<QueryObject> queries;
+    auto guard = ReadLock();
+
+    for (const auto &submission : submissions_) {
+        for (uint32_t j = 0; j < submission.cbs.size(); ++j) {
+            const auto next_cb_node = submission.cbs[j];
```
Comment (jeremyg-lunarg) [inline layers/queue_state.cpp:99]: this line copies the smart_ptr, which shouldn't  be necessary. It doesn't show up as a problem in profiling though.

**Comment by jeremyg-lunarg** [comment]
started a new perf run on this PR
