### PR TITLE
threading: Handle vkRegisterDisplayEventEXT

### LINKED ISSUE #2743: thread_safety assertion failed with vkRegisterDisplayEventEXT
Using vk_khr_display and VK_EXT_display_control, I'm getting a FindObject assertion failure on the VkDisplayKHR handle during thread safety validation.  This appears similar to #1569 and #1987.

```
main.app: /build/Vulkan-ValidationLayers/layers/generated/thread_safety.h:143: std::shared_ptr<ObjectUseData> counter<T>::FindObject(T) [with T = VkDisplayKHR_T*]: Assertion `object_table.contains(object)' failed.
Aborted (core dumped)
```

Using SDK 1.2.174 on aarch64.   The VK_EXT_display_control extension performs correctly when validation layers are disabled.

It appears that `display` is never added to `layer_data` for `device` by any Vulkan command in layer_chassis_dispatch.cpp.  Rather `display` is added to `layer_data` for `physicalDevice` by `DispatchGetPhysicalDeviceDisplayPropertiesKHR`.  

Because `vkRegisterDisplayEventEXT` doesn't have `physicalDevice` as an argument, there is no direct way for `DispatchRegisterDisplayEventEXT` to correctly unwrap `display`.   Somehow the `physicalDevice` would need to be derived from the `device`.

A workaround is to bypass threading checks on `display` in thread_safety.cpp:
```
void ThreadSafety::PreCallRecordRegisterDisplayEventEXT(
    VkDevice                                    device,
    VkDisplayKHR                                display,
    const VkDisplayEventInfoEXT*                pDisplayEventInfo,
    const VkAllocationCallbacks*                pAllocator,
    VkFence*                                    pFence) {
    StartReadObjectParentInstance(device, "vkRegisterDisplayEventEXT");
    //StartReadObject(display, "vkRegisterDisplayEventEXT");
}

void ThreadSafety::PostCallRecordRegisterDisplayEventEXT(
    VkDevice                                    device,
    VkDisplayKHR                                display,
    const VkDisplayEventInfoEXT*                pDisplayEventInfo,
    const VkAllocationCallbacks*                pAllocator,
    VkFence*                                    pFence,
    VkResult                                    result) {
    FinishReadObjectParentInstance(device, "vkRegisterDisplayEventEXT");
    //FinishReadObject(display, "vkRegisterDisplayEventEXT");
```

However then another failure occurs in vkWaitForFences waiting on the VkFence created by `vkRegisterDisplayEventEXT`:
```
main.app: /build/Vulkan-ValidationLayers/layers/generated/thread_safety.h:143: std::shared_ptr<ObjectUseData> counter<T>::FindObject(T) [with T = VkFence_T*]: Assertion `object_table.contains(object)' failed.
Aborted (core dumped)
```

For some reason the VkFence created by vkRegisterDisplayEventEXT isn't known to the layers.  It's not yet clear to me where the problem is, since `DispatchRegisterDisplayEventEXT` seems to do the same wrapping that `DispatchCreateFence` does.

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**
The autogenerated code was crashing because looking up a VkDisplayKHR handle from a VkDevice state object failed, and because the VkFence created by this function wasn't tracked.
    
Fixes #2743

### CODE REVIEW

File: tests/positive/sync.cpp [hunk 1]
```diff
@@ -1947,3 +1950,40 @@ TEST_F(VkPositiveLayerTest, DoubleLayoutTransition) {
...
+
+    auto vkGetPhysicalDeviceDisplayPropertiesKHR = reinterpret_cast<PFN_vkGetPhysicalDeviceDisplayPropertiesKHR>(vk::GetInstanceProcAddr(instance(), "vkGetPhysicalDeviceDisplayPropertiesKHR"));
+    auto vkRegisterDisplayEventEXT = reinterpret_cast<PFN_vkRegisterDisplayEventEXT>(vk::GetInstanceProcAddr(instance(), "vkRegisterDisplayEventEXT"));
+    ASSERT_TRUE(vkGetPhysicalDeviceDisplayPropertiesKHR != nullptr);
+    ASSERT_TRUE(vkRegisterDisplayEventEXT != nullptr);
+
+    m_errorMonitor->ExpectSuccess();
+    uint32_t prop_count = 0;
+    vkGetPhysicalDeviceDisplayPropertiesKHR(gpu(), &prop_count, nullptr);
+    if (prop_count == 0) {
```
Comment (Tony-LunarG) [inline tests/positive/sync.cpp:1974]: Have you seen this test get past this point?  My RADV system and apparently the Intel CI system both get 0 for prop_count, but the call returns VK_SUCCESS and it's not clear to me why it would return 0.

Comment (jeremyg-lunarg) [reply tests/positive/sync.cpp:1974]: Yes I've been having trouble finding an environment where this call returns anything except 0. There's something different happening on the NV CI devices but I'm not sure what yet.

**Review by ziga-lunarg — APPROVED** [review]

**Comment by jeremyg-lunarg** [comment]
> LGTM - It would be nice if the test ran somewhere, but not necessary

based on where the test is crashing on our Linux Nvidia CI machine I think it is getting a non-0 number of displays, so once that crash is fixed we should have 1 place it runs.

**Comment by ChristophHaag** [comment]
The problem is that the displays can't be actually used with a swapchain unless the app can acquire drm master.

mesa opted to not enumerate any displays when the app doesn't have drm master, like when an X server or wayland compositor runs. When logged into a tty, the connected displays should be enumerated.

nvidia doesn't care about that, it always enumerates displays. But when an X server or wayland compositor runs, using a swapchain directly with such a display will fail too.

"To acquire permission to directly access a display in Vulkan from an X11 server, call: vkAcquireXlibDisplayEXT", which takes a VkDisplayKHR as a parameter.

On nvidia you get the display anyway from vkGetPhysicalDeviceDisplayPropertiesKHR, but the X11 desktop must not be extended to the display in question or some vulkan call will fail, I think it's vkAcquireXlibDisplayEXT.

On mesa you first get get a VkDisplayKHR from a randr output with `vkGetRandROutputDisplayEXT`.
