### PR TITLE
Fix issue 2304

### LINKED ISSUE #2304: Workgroup size not validated when the size comes from an object decorated with `WorkgroupSize`
The workgroup size for compute shaders can be specified using two mechanisms:

1. `LocalSize` execution mode
1. Using an object (constant or specialisation constant) decorated with `WorkgroupSize`

Workgroup sizes are only validated against device limits when specified with the `LocalSize` execution mode. They should always be validated.

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #2304 

Check if specialization for WorkGroupSize is within VkPhysicalDeviceLimits::maxComputeWorkGroupSize

### CODE REVIEW

File: layers/shader_validation.cpp [hunk 1]
```diff
@@ -712,6 +712,76 @@ bool CoreChecks::ValidateShaderStageGroupNonUniform(SHADER_MODULE_STATE const *m
...
+                                uint32_t spec_id) {
+    uint32_t value = 0;
+    if (spec && iter.opcode() == spv::OpSpecConstant) {
+        uint32_t vector_result_type_id = iter.word(1);
+        auto vector_result_type = src->get_def(vector_result_type_id);
+        if (vector_result_type.opcode() == spv::OpTypeInt) {
+            value = iter.word(3);  // Default value
+            for (uint32_t i = 0; i < spec->mapEntryCount; ++i) {
+                if (spec->pMapEntries[i].constantID == spec_id && spec->pMapEntries[i].size == sizeof(uint32_t)) {
+                    memcpy(&value, (uint8_t *)spec->pData + spec->pMapEntries[i].offset, spec->pMapEntries[i].size);
```
Comment (ncesario-lunarg) [inline layers/shader_validation.cpp:725]: `memcpy` necessary here? This code will only happen if size == 4, so there is no variable size to account for.

I'd personally prefer something like `std::copy` over `memcpy`, or something that gives the "option" for being more type safe.

File: layers/shader_validation.cpp [hunk 2]
```diff
@@ -712,6 +712,76 @@ bool CoreChecks::ValidateShaderStageGroupNonUniform(SHADER_MODULE_STATE const *m
     return skip;
 }
 
+uint32_t GetSpecializationValue(SHADER_MODULE_STATE const *src, VkSpecializationInfo const *spec, spirv_inst_iter iter,
```
[the remark this answers is not in the document]
Comment (ncesario-lunarg) [reply layers/shader_validation.cpp:715]: Looks like this function will always return 0 unless the OpSpecConstant is a 32 bit integer?

File: layers/shader_validation.cpp [hunk 3]
```diff
@@ -712,6 +712,76 @@ bool CoreChecks::ValidateShaderStageGroupNonUniform(SHADER_MODULE_STATE const *m
...
+                    memcpy(&value, (uint8_t *)spec->pData + spec->pMapEntries[i].offset, spec->pMapEntries[i].size);
+                    break;
+                }
+            }
+        }
+    }
+    return value;
+}
+
+bool CoreChecks::ValidateWorkgroupSize(SHADER_MODULE_STATE const *src, VkPipelineShaderStageCreateInfo const *pStage) const {
```
Comment (ncesario-lunarg) [inline layers/shader_validation.cpp:734]: Looks like there is some overlap with https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/f1ea8fba12fadae976a96455e8fc897194669658/layers/shader_validation.cpp#L1865?

Maybe there is some way to use some of the specialization tracking there rather than looping through the spir-v again?

File: layers/shader_validation.cpp [hunk 4]
```diff
@@ -712,6 +712,76 @@ bool CoreChecks::ValidateShaderStageGroupNonUniform(SHADER_MODULE_STATE const *m
...
+    for (auto insn : *src) {
+        uint32_t opcode = insn.opcode();
+        if (opcode == spv::OpDecorate) {
+            uint32_t decoration = insn.word(2);
+            if (decoration == spv::DecorationBuiltIn) {
+                uint32_t builtin = insn.word(3);
+                if (builtin == spv::BuiltInWorkgroupSize) {
+                    work_group_size_id = insn.word(1);
+                }
+            } else if (decoration == spv::DecorationSpecId) {
```
Comment (ncesario-lunarg) [inline layers/shader_validation.cpp:751]: We effectively do this at https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/f1ea8fba12fadae976a96455e8fc897194669658/layers/shader_validation.cpp#L1297 as well. Maybe it's time to add this to `SHADER_MODULE_STATE` and avoid the duplicate map buildup?

File: layers/shader_validation.cpp [hunk 5]
```diff
@@ -712,6 +712,76 @@ bool CoreChecks::ValidateShaderStageGroupNonUniform(SHADER_MODULE_STATE const *m
...
+            uint32_t result_id = insn.word(2);
+            if (result_id == work_group_size_id) {
+                uint32_t result_type_id = insn.word(1);
+                auto result_type = src->get_def(result_type_id);
+                if (result_type.opcode() == spv::OpTypeVector) {
+                    uint32_t component_count = result_type.word(3);
+                    for (uint32_t i = 0; i < component_count; ++i) {
+                        auto constituent = src->get_def(insn.word(3 + i));
+                        uint32_t spec_id = spec_ids[constituent.word(2)];
+                        uint32_t workGroupSize = GetSpecializationValue(src, spec, constituent, spec_id);
```
Comment (ncesario-lunarg) [inline layers/shader_validation.cpp:766]: `snake_case` for variables.

File: layers/shader_validation.cpp [hunk 6]
```diff
@@ -712,6 +712,76 @@ bool CoreChecks::ValidateShaderStageGroupNonUniform(SHADER_MODULE_STATE const *m
...
+                        if (workGroupSize > phys_dev_props.limits.maxComputeWorkGroupSize[i]) {
+                            const char *member = i == 0 ? "x" : i == 1 ? "y" : "z";
```
Comment (ncesario-lunarg) [inline layers/shader_validation.cpp:768]: `const char member = 'x' + static_cast<int8_t>(i)`?

File: layers/shader_validation.cpp (hunk 1 above)
Comment (ncesario-lunarg) [reply layers/shader_validation.cpp:725]: For the memcpy, while we do have C-style casts in the code base, they are technically not allowed according to the [style guide](https://google.github.io/styleguide/cppguide.html#Casting), so we should probably avoid adding new ones.

**Review by ncesario-lunarg — CHANGES_REQUESTED** [review]
A few nits/questions/requests, but I think the core idea here looks good!

File: layers/shader_module.cpp [hunk 7]
```diff
@@ -1746,6 +1746,47 @@ spirv_inst_iter SHADER_MODULE_STATE::GetImageFormatInst(uint32_t id) const
...
+
+    for (const auto &builtin : builtin_decoration_list) {
+        if (builtin.builtin == spv::BuiltInWorkgroupSize) {
+            work_group_size_id = at(builtin.offset).word(1);
+            break;
+        }
+    }
+    for (auto insn : *this) {
+        uint32_t opcode = insn.opcode();
+        if (opcode == spv::OpSpecConstantComposite) {
```
Comment (ncesario-lunarg) [inline layers/shader_module.cpp:1763]: @sfricke-samsung any chance you know if this is required to be an `OpSpecConstantComposite`, or can it also be an `OpSpecConstant`? e.g., the following seems to pass `spirv-val`:
```
; SPIR-V
; Version: 1.5
; Generator: Khronos Glslang Reference Front End; 10
; Bound: 11
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %main "main"
               OpExecutionMode %main LocalSize 1 1 1
               OpSource GLSL 450
               OpName %main "main"
               OpDecorate %7 SpecId 3
               OpDecorate %7 BuiltIn WorkgroupSize
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
       %uint = OpTypeInt 32 0
          %7 = OpSpecConstant %uint 1
       %main = OpFunction %void None %3
          %5 = OpLabel
               OpReturn
               OpFunctionEnd
```

Comment (sfricke-samsung) [reply layers/shader_module.cpp:1763]: when running `spirv-val` make sure to use `--target-env vulkan1.2` 

```
spirv-val test.spv --target-env vulkan1.2
error: line 13: [VUID-WorkgroupSize-WorkgroupSize-04427] According to the Vulkan spec BuiltIn WorkgroupSize variable needs to be a 3-component 32-bit int vector. ID <3> (OpSpecConstant) is not an int vector.
  %gl_WorkGroupSize = OpSpecConstant %uint 1
```

but regardless, let me double check as I know there is another edge case for something else related to Workgroup sizes Vulkan doesn't allow that SPIR-V does

Comment (sfricke-samsung) [reply layers/shader_module.cpp:1763]: ok, @ncesario-lunarg the reason you **need** `OpSpecConstantComposite` is because of `VUID-WorkgroupSize-WorkgroupSize-04427` which requires a `int vec3` to declare the `WorkgroupSize` decoration

`OpSpecConstant` can is just a scalar, so you will never be able to declare it

Valid example btw:

```swift
               OpDecorate %x SpecId 0
               OpDecorate %y SpecId 1
               OpDecorate %z SpecId 2
               OpDecorate %workGroupSize BuiltIn WorkgroupSize
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
       %uint = OpTypeInt 32 0
      %uvec3 = OpTypeVector %uint 3
          %x = OpSpecConstant %uint 1
          %y = OpSpecConstant %uint 1
          %z = OpSpecConstant %uint 1
%workGroupSize = OpSpecConstantComposite %uvec3 %x %y %z ; turns scalars into uvec3
```

Comment (sfricke-samsung) [reply layers/shader_module.cpp:1763]: btw, 100% would add a comment in the code so no one has to look this up again :)
