### PR TITLE
layers: Prevent layer calls with null dispatches.

### LINKED ISSUE #304: Validation layers don't check core version availbility for 1.1 functions
In `vkGetDeviceProcAddr` the validation layers check for extensions being enabled, and return `NULL` for the corresponding functions if the extension isn't enabled. This is good, but I think it needs to be extended for 1.1 core functions - if a 1.1 context isn't available then `NULL` should be returned for functions promoted to core like `GetBufferMemoryRequirements2`.

To test this, you'll need either a 1.0 driver with `VK_KHR_get_memory_requirements_2` or you can hack the validation layers in `vk_dispatch_table_helper.h` to force `NULL` instead of `gpa(device, "vkGetBufferMemoryRequirements2");` which is what I did.

Then run cube.c with this diff:

```diff
diff --git a/cube.c b/cube_mod.c
index 8edbd65..74d44d4 100644
--- a/cube.c
+++ b/cube_mod.c
@@ -3175,6 +3175,8 @@ static void demo_init_vk(struct demo *demo) {
         free(device_extensions);
     }

+    demo->extension_names[demo->enabled_extension_count++] = VK_KHR_GET_MEMORY_REQUIREMENTS_2_EXTENSION_NAME;
+
     if (!swapchainExtFound) {
         ERR_EXIT("vkEnumerateDeviceExtensionProperties failed to find the " VK_KHR_SWAPCHAIN_EXTENSION_NAME
                  " extension.\n\nDo you have a compatible Vulkan installable client driver (ICD) installed?\n"
@@ -3241,6 +3243,8 @@ static void demo_init_vk(struct demo *demo) {
 }

 static void demo_create_device(struct demo *demo) {
+    VkBufferMemoryRequirementsInfo2 buf_req;
+    VkBufferCreateInfo buf_info;
     VkResult U_ASSERT_ONLY err;
     float queue_priorities[1] = {0.0};
     VkDeviceQueueCreateInfo queues[2];
@@ -3273,6 +3277,32 @@ static void demo_create_device(struct demo *demo) {
     }
     err = vkCreateDevice(demo->gpu, &device, NULL, &demo->device);
     assert(!err);
+
+    memset(&buf_info, 0, sizeof(buf_info));
+    buf_info.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
+    buf_info.usage = VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT;
+    buf_info.size = 1024;
+
+    memset(&buf_req, 0, sizeof(buf_req));
+    buf_req.sType = VK_STRUCTURE_TYPE_BUFFER_MEMORY_REQUIREMENTS_INFO_2;
+    vkCreateBuffer(demo->device, &buf_info, NULL, &buf_req.buffer);
+
+    PFN_vkGetBufferMemoryRequirements2KHR khr_variant =
+      (PFN_vkGetBufferMemoryRequirements2KHR)vkGetDeviceProcAddr(demo->device, "vkGetBufferMemoryRequirements2KHR");
+
+    VkMemoryRequirements2 reqs;
+    memset(&reqs, 0, sizeof(reqs));
+    reqs.sType = VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2_KHR;
+
+    khr_variant(demo->device, &buf_req, &reqs);
+
+    PFN_vkGetBufferMemoryRequirements2 core_variant =
+      (PFN_vkGetBufferMemoryRequirements2)vkGetDeviceProcAddr(demo->device, "vkGetBufferMemoryRequirements2");
+
+    memset(&reqs, 0, sizeof(reqs));
+    reqs.sType = VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2;
+
+    core_variant(demo->device, &buf_req, &reqs);
 }

 static void demo_init_vk_swapchain(struct demo *demo) {
```

Which will call both KHR and non-KHR variants - the non-KHR variant returns non-NULL but then eventually crashes at the end of the validation layer chain with nowhere in the driver to call forward to.

I'm not sure how this extends to instance-level functionality exactly. I tried testing with an instance function promoted to core in 1.1 like `vkGetPhysicalDeviceProperties2` but think the loader started emulating the 1.1 core function on top of the KHR function (which is probably fine and doesn't lead to crashes). Maybe it also happens version checking, I'm not actually sure.

### PR DESCRIPTION
**Pull request by jzulauf-lunarg**
Change GetDeviceProcAddr policy such that nullptr are returned for any
entry point which has a nullptr in the dispatch table.

Fixes #304

### CODE REVIEW

File: layers/core_validation.cpp [hunk 1]
```diff
@@ -2327,6 +2327,7 @@ static bool PreCallValidateCreateDevice(instance_layer_data *instance_data, cons
     return skip;
 }
 
+std::unordered_map<std::string, void *> &GetNameToFuncptrMap();
```
Comment (jzulauf-lunarg) [inline layers/core_validation.cpp]: The way that core_validation declare this table requires some forward declaration and indirection to get it where it needs.

File: layers/core_validation.cpp [hunk 2]
```diff
@@ -14228,7 +14230,7 @@ VKAPI_ATTR PFN_vkVoidFunction VKAPI_CALL GetPhysicalDeviceProcAddr(VkInstance in
 VKAPI_ATTR PFN_vkVoidFunction VKAPI_CALL GetInstanceProcAddr(VkInstance instance, const char *funcName);
 
 // Map of all APIs to be intercepted by this layer
-static const std::unordered_map<std::string, void *> name_to_funcptr_map = {
+static std::unordered_map<std::string, void *> name_to_funcptr_map = {
```
Comment (jzulauf-lunarg) [inline layers/core_validation.cpp]: Since this is now updated when the dispatch table is populated it has to be non-const... here and where codegen'd below

File: scripts/dispatch_table_helper_generator.py [hunk 3]
```diff
@@ -238,7 +238,16 @@ def OutputDispatchTableHelper(self, table_type):
         table = ''
         if table_type == 'device':
             entries = self.device_dispatch_list
-            table += 'static inline void layer_init_device_dispatch_table(VkDevice device, VkLayerDispatchTable *table, PFN_vkGetDeviceProcAddr gpa) {\n'
+            table += 'static inline void layer_init_device_dispatch_table(VkDevice device, VkLayerDispatchTable *table, PFN_vkGetDeviceProcAddr gpa_func,\n'
```
Comment (jzulauf-lunarg) [inline scripts/dispatch_table_helper_generator.py]: The critical change is to add the update of the function table the *current* layer returns as the return from GerDeviceProcAddr, s.t. it never returns a non-null entrypoint when the matching entry in it's dispatch table is null.
