### PR TITLE
layers: Fix a race condition in FENCE_STATE::Retire()

### LINKED ISSUE #4271: False positive VUID-vkQueueSubmit-fence-00063 with fence and signal semaphore
Sometimes I will get incorrect validation errors from VUID-vkQueueSubmit-fence-00063. I call vkWaitForFences on a single fence that was previously used in a call to vkQueueSubmit. I immediately call vkResetFences. Then sometime later I reuse the fence in another call to vkQueueSubmit and the validation warning is sometimes triggered.

I believe the problem originates when there is both a fence and a signal semapore on the queue submission.

**Valid Usage ID**
VUID-vkQueueSubmit-fence-00063: Validation Error: [ VUID-vkQueueSubmit-fence-00063 ] Object 0: handle = 0xf443490000000006, type = VK_OBJECT_TYPE_FENCE; | MessageID = 0x6f35a2b3 | vkQueueSubmit(): VkFence 0xf443490000000006[] submitted in SIGNALED state.  Fences must be reset before being submitted The Vulkan spec states: If fence is not VK_NULL_HANDLE, fence must be unsignaled (https://vulkan.lunarg.com/doc/view/1.3.216.0/linux/1.3-extensions/vkspec.html#VUID-vkQueueSubmit-fence-00063)

**Environment:**
 - OS: Linux
 - GPU: NVIDIA Corporation GP106 [GeForce GTX 1060 3GB] (rev a1)
 - SDK or header version if building from repo: 1.3.216.0
 - Options enabled (synchronization, best practices, etc.): VK_LAYER_KHRONOS_validation

This occurs on the graphics queue submission and I include a fence and a semephore that I latter pass to vkQueuePresentKHR. In a separate thread I call vkWaitForFences on the fence.

The rest is speculation: I think the presentation library calls vkWaitSemaphores in another thread. When the queue finishes running, both threads are freed to run. There is a race to call QUEUE_STATE::Retire. The presentation thread wins that race and begins processing the submission. My thread returns and immediatly calls vkFenceReset that sets the FENCE_STATE::state_ to FENCE_UNSIGNALED. The presentation thread continues processing the submission and finishes by calling FENCE_STATE::Retire, which promptly sets FENCE_STATE::state_ back to FENCE_RETIRED (incorrectly).

I'm not sure how all this works, but maybe you could check the FENCE_STATE::queue_ to see if the fence still needs to be reset?

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**
This method could get called concurrently, such as if a wait on a semaphore and the fence occur simultaneously in different threads. Avoid bad state transitions in Retire() by only changing state if the fence is INFLIGHT, which will weed out any extra Retire() calls that happen.

Fixes #4271

### CODE REVIEW

**Comment by jhs67** [comment]
I think the problem could still occur if the client called vkResetFences and then vkQueueSubmit all before the QUEUE_STATE::Retire call to FENCE_STATE::Retire is reached. Seems unlikely, I admit. Perhaps you could check the FENCE_STATE::queue_ and FENCE_STATE::seq_ in QUEUE_STATE::Retire to be sure the fence is still tied to the submission is question?

File: tests/positive/sync.cpp [hunk 1]
```diff
@@ -2094,3 +2094,98 @@ TEST_F(VkPositiveLayerTest, ResetQueryPoolFromDifferentCBWithFenceAfter) {
 
     m_errorMonitor->VerifyNotFound();
 }
+
+struct fence_thread_race_data {
```
Comment (ncesario-lunarg) [inline tests/positive/sync.cpp:2098]: CamelCase

File: tests/positive/sync.cpp [hunk 2]
```diff
@@ -2094,3 +2094,98 @@ TEST_F(VkPositiveLayerTest, ResetQueryPoolFromDifferentCBWithFenceAfter) {
...
+    VkDevice device;
+    VkSemaphore sem;
+    bool *bailout;
+    uint64_t wait_value;
+    uint64_t timeout;
+    uint32_t iterations;
+};
+
+extern "C" void *WaitTimelineSem(void *arg) {
+    auto *data = reinterpret_cast<struct fence_thread_race_data *>(arg);
```
Comment (ncesario-lunarg) [inline tests/positive/sync.cpp:2108]: I don't think the `struct` is necessary (I think pure C that requires that?).

File: tests/positive/sync.cpp [hunk 3]
```diff
@@ -2094,3 +2094,98 @@ TEST_F(VkPositiveLayerTest, ResetQueryPoolFromDifferentCBWithFenceAfter) {
...
+        fpWaitSemaphores(data->device, &wait_info, data->timeout);
+        if (*data->bailout) {
+            break;
+        }
+    }
+    return nullptr;
+}
+
+TEST_F(VkPositiveLayerTest, FenceSemThreadRace) {
+    test_platform_thread thread;
```
Comment (ncesario-lunarg) [inline tests/positive/sync.cpp:2126]: No `std::thread` for tests? Can't recall if this was banned for reasons.

**Review by ncesario-lunarg — COMMENTED** [review]
LGTM with some nits and questions, though based on @jhs67's comment it looks like there might be additional work needed?

File: tests/positive/sync.cpp (hunk 3 above)
Comment (jeremyg-lunarg) [reply tests/positive/sync.cpp:2126]: not sure.. I'll try to do all instances of this in a separate PR to see if it passes CI on our platforms. There are a bunch of uses.

**Comment by jeremyg-lunarg** [comment]
>

**Comment by jeremyg-lunarg** [comment]
> I think the problem could still occur if the client called vkResetFences and then vkQueueSubmit all before the QUEUE_STATE::Retire call to FENCE_STATE::Retire is reached. Seems unlikely, I admit. Perhaps you could check the FENCE_STATE::queue_ and FENCE_STATE::seq_ in QUEUE_STATE::Retire to be sure the fence is still tied to the submission in question?

Yeah I think it does need to be more paranoid.

**Review by ncesario-lunarg — APPROVED** [review]
