### PR TITLE
Replace core validation error enums with VUID-like strings

### LINKED ISSUE #159: Wrong VU for vkCmdExecuteCommands
`Object: 0x1eedc5ce820 (Type = 6) | vkCmdExecuteCommands() cannot be called in a subpass using inline commands. The spec valid usage text states 'Each of fence, semaphore, and swapchain that are valid handles must have been created, allocated, or retrieved from the same VkInstance' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VUID-VkAcquireNextImageInfoKHR-commonparent)`

The error is good, but the VU seems unrelated.

### PR DESCRIPTION
**Pull request by daveh-lunarg**
Swap the non-VUID core error enums for string equivalents.

Fixes #159

### CODE REVIEW

File: layers/buffer_validation.cpp [hunk 1]
```diff
@@ -1093,7 +1093,7 @@ bool PreCallValidateCreateImage(layer_data *device_data, const VkImageCreateInfo
 
     if ((pCreateInfo->flags & VK_IMAGE_CREATE_SPARSE_ALIASED_BIT) && (!GetEnabledFeatures(device_data)->sparseResidencyAliased)) {
         skip |= log_msg(report_data, VK_DEBUG_REPORT_ERROR_BIT_EXT, VK_DEBUG_REPORT_OBJECT_TYPE_UNKNOWN_EXT, 0,
-                        DRAWSTATE_INVALID_FEATURE,
+                        kVUID_Core_DrawState_InvalidFeature,
```
Comment (mark-lunarg) [inline layers/buffer_validation.cpp]: This looks like VUID-VkImageCreateInfo-flags-01924

File: layers/core_validation_error_enums.h [hunk 2]
```diff
@@ -19,189 +19,217 @@
...
-    SHADER_CHECKER_PUSH_CONSTANT_OUT_OF_RANGE,
-    SHADER_CHECKER_PUSH_CONSTANT_NOT_ACCESSIBLE_FROM_STAGE,
-    SHADER_CHECKER_DESCRIPTOR_TYPE_MISMATCH,
-    SHADER_CHECKER_DESCRIPTOR_NOT_ACCESSIBLE_FROM_STAGE,
-    SHADER_CHECKER_FEATURE_NOT_ENABLED,
-    SHADER_CHECKER_BAD_CAPABILITY,
-    SHADER_CHECKER_MISSING_INPUT_ATTACHMENT,
-    SHADER_CHECKER_INPUT_ATTACHMENT_TYPE_MISMATCH,
-};
+static const char DECORATE_UNUSED *kVUID_Core_MemTrack_FenceState = "UNASSIGNED-CoreValidation-MemTrack-FenceState";
```
Comment (jzulauf-lunarg) [inline layers/core_validation_error_enums.h]: Why the hybrid Camel_SnakeCase? https://google.github.io/styleguide/cppguide.html#Constant_Names

File: layers/buffer_validation.cpp [hunk 3]
```diff
@@ -1383,7 +1383,7 @@ bool PreCallValidateCmdClearDepthStencilImage(layer_data *device_data, VkCommand
                     "vkCmdClearDepthStencilImage aspectMasks for all subresource ranges must be set to VK_IMAGE_ASPECT_DEPTH_BIT "
                     "and/or VK_IMAGE_ASPECT_STENCIL_BIT";
                 skip |= log_msg(report_data, VK_DEBUG_REPORT_ERROR_BIT_EXT, VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT,
-                                HandleToUint64(commandBuffer), DRAWSTATE_INVALID_IMAGE_ASPECT, str);
+                                HandleToUint64(commandBuffer), kVUID_Core_DrawState_InvalidImageAspect, str);
```
Comment (mark-lunarg) [inline layers/buffer_validation.cpp]: Hmmm.  Spec says "The aspectMask of each image subresource range in pRanges **can** include VK_IMAGE_ASPECT_DEPTH_BIT if the image format has a depth component, and VK_IMAGE_ASPECT_STENCIL_BIT if the image format has a stencil component."  Does 'can' imply that it could be other stuff?

File: layers/buffer_validation.cpp (hunk 1 above)
Comment (daveh-lunarg) [reply layers/buffer_validation.cpp]: Argh. I forgot to scrub for old errors the have promoted to VUIDs.  Hold on.

File: layers/core_validation_error_enums.h (hunk 2 above)
Comment (daveh-lunarg) [reply layers/core_validation_error_enums.h]: Makes clear the the hierarchy.  Core validation, Memory Tracker group, Fence state error.

File: layers/buffer_validation.cpp (hunk 3 above)
Comment (tobine) [reply layers/buffer_validation.cpp]: Spec if interesting on this one.
Under [VkSubresourceLayout](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VkSubresourceLayout):

> For depth/stencil formats, aspectMask must be either VK_IMAGE_ASPECT_DEPTH_BIT or VK_IMAGE_ASPECT_STENCIL_BIT.

And under [VkImageSubresourceRange](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VkImageSubresourceRange):

> If using a depth/stencil format with both depth and stencil components, aspectMask must include at least one of VK_IMAGE_ASPECT_DEPTH_BIT and VK_IMAGE_ASPECT_STENCIL_BIT, and can include both.

I believe the check in question is derived from this second requirement.

**Comment by daveh-lunarg** [comment]
Found a couple VUIDs that could be swapped for generic core val errors.  And a little tidying.

Take a look at the 2nd commit.
