### PR TITLE
tests: Update missing extension test to reenable

### LINKED ISSUE #262: ExtensionNotEnabled test is broken
A bug in this test was exposed by the change made GetProcAddr return nullptr for API functions without their parent extensions enabled. The test is now guaranteed to skip on any config. Is there anyway to still hit the test's expected error or is that validation message now dead code?

### PR DESCRIPTION
**Pull request by jzulauf-lunarg**
Modified the ExtensionNotEnabled test to exercise the test case that had
been renderer ineffective by unrelated updates.  Updated test to use the
simplest test case to reproduce.

Had to create a situation where the specific extension *was* enabled, but that prerequisite *other* extensions were not, so the change is a little larger than would be otherwise.

Fixes #262 .

### CODE REVIEW

File: tests/layer_validation_tests.cpp [hunk 1]
```diff
@@ -23556,25 +23556,42 @@ TEST_F(VkLayerTest, ExecuteSecondaryCBWithLayoutMismatch) {
...
+    // Do NOT enable VK_KHR_maintenance1
+    if (DeviceExtensionSupported(gpu(), nullptr, VK_KHR_SAMPLER_YCBCR_CONVERSION_EXTENSION_NAME)) {
+        m_device_extension_names.push_back(VK_KHR_SAMPLER_YCBCR_CONVERSION_EXTENSION_NAME);
+    } else {
+        printf("%s test requires KHR YCBR conversion extension, not available.  Skipping.\n", kSkipPrefix);
         return;
     }
 
+    // Need to ignore this error to get to the one we're testing
+    m_errorMonitor->SetUnexpectedError("VUID-vkCreateDevice-ppEnabledExtensionNames-01387");
```
Comment (mikes-lunarg) [inline tests/layer_validation_tests.cpp]: Now that this check exists, I'm not sure why we still need a validation check for the extension dependencies inside each extension entry point.  I think it would be sufficient to validate all extension dependencies at vkCreateDevice/Instance time and then validate the single* "top-level" extension inside the entry point.  This test relies on vkCreateDevice succeeding after being handed an invalid list of extensions which is not guaranteed.

*some entry points do require combinations of extensions to be enabled that cannot be derived from the extension dependency graph.  One example: it is valid to enable VK_KHR_device_group and VK_KHR_surface individually but vkGetDeviceGroupPresentCapabilitiesKHR requires them both.

Comment (daveh-lunarg) [reply tests/layer_validation_tests.cpp]: >This test relies on vkCreateDevice succeeding after being handed an invalid list of extensions which is not guaranteed

True, but wouldn't the driver would have to maintain it's own dependency graph to know that? Seems un-Vulkan. I'd risk it.

No disagreement about consolidating the dependency checks to CreateDevice.

Comment (mikes-lunarg) [reply tests/layer_validation_tests.cpp]: Fair.  Another thing that makes this assumption somewhat safe is that I seem to remember CTS not always enabling all of the required extension dependencies.  Nobody wants to start returning VK_ERROR_INITIALIZATION_FAILED to that application 😉

Comment (jzulauf-lunarg) [reply tests/layer_validation_tests.cpp]: There is the extension dependency table code gen'd into vk_extension_helper from the registry.
