### PR TITLE
layers: Fix CMD_BUFFER_STATE potential deadlock

### LINKED ISSUE #5011: DynamicRenderingNullDepthStencilExecuteCommands | Deadlock
**Describe the Issue**
```
[ RUN      ] VkLayerTest.DynamicRenderingNullDepthStencilExecuteCommands
==================
WARNING: ThreadSanitizer: lock-order-inversion (potential deadlock) (pid=15335)
  Cycle in lock order graph: M0 (0x7b740001df80) => M1 (0x7b740001e980) => M0
```

Run `DynamicRenderingNullDepthStencilExecuteCommands` with a thread sanitized build.

<details>

<summary>Full ASAN Log</summary>

```
[ RUN      ] VkLayerTest.DynamicRenderingNullDepthStencilExecuteCommands
==================
WARNING: ThreadSanitizer: lock-order-inversion (potential deadlock) (pid=16833)
  Cycle in lock order graph: M0 (0x7b740001df80) => M1 (0x7b740001e980) => M0

  Mutex M1 acquired here while holding mutex M0 in main thread:
    #0 pthread_rwlock_rdlock <null> (vk_layer_validation_tests+0x31688a) (BuildId: 655a6717424f7bc5707081155d2c11ce71651f2f)
    #1 std::__glibcxx_rwlock_rdlock(pthread_rwlock_t*) /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/shared_mutex:78:3 (libVkLayer_khronos_validation.so+0x1898f13) (BuildId: 036adb65bc27970aa02946267092770927a02df7)
    #2 std::__shared_mutex_pthread::lock_shared() /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/shared_mutex:229:10 (libVkLayer_khronos_validation.so+0x191295d) (BuildId: 036adb65bc27970aa02946267092770927a02df7)
    #3 std::shared_mutex::lock_shared() /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/shared_mutex:426:34 (libVkLayer_khronos_validation.so+0x1912905) (BuildId: 036adb65bc27970aa02946267092770927a02df7)
    #4 std::shared_lock<std::shared_mutex>::shared_lock(std::shared_mutex&) /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/shared_mutex:727:13 (libVkLayer_khronos_validation.so+0x19128ab) (BuildId: 036adb65bc27970aa02946267092770927a02df7)
    #5 CMD_BUFFER_STATE::ReadLock() const /home/juan/projects/vvl/layers/cmd_buffer_state.h:340:45 (libVkLayer_khronos_validation.so+0x1f5c77c) (BuildId: 036adb65bc27970aa02946267092770927a02df7)
    #6 LockedSharedPtr<CMD_BUFFER_STATE const, std::shared_lock<std::shared_mutex> > ValidationStateTracker::GetRead<CMD_BUFFER_STATE, state_object::Traits<CMD_BUFFER_STATE>, LockedSharedPtr<CMD_BUFFER_STATE const, std::shared_lock<std::shared_mutex> > >(state_object::Traits<CMD_BUFFER_STATE>::HandleType) const /home/juan/projects/vvl/layers/state_tracker.h:417:31 (libVkLayer_khronos_validation.so+0x1f0d93c) (BuildId: 036adb65bc27970aa02946267092770927a02df7)
    #7 CoreChecks::PreCallValidateCmdExecuteCommands(VkCommandBuffer_T*, unsigned int, VkCommandBuffer_T* const*) const /home/juan/projects/vvl/layers/core_validation.cpp:16394:29 (libVkLayer_khronos_validation.so+0x1ea22a1) (BuildId: 036adb65bc27970aa02946267092770927a02df7)
    #8 vulkan_layer_chassis::CmdExecuteCommands(VkCommandBuffer_T*, unsigned int, VkCommandBuffer_T* const*) /home/juan/projects/vvl/layers/generated/chassis.cpp:3748:67 (libVkLayer_khronos_validation.so+0x18084d8) (BuildId: 036adb65bc27970aa02946267092770927a02df7)
    #9 VkLayerTest_DynamicRenderingNullDepthStencilExecuteCommands_Test::TestBody() /home/juan/projects/vvl/tests/vklayertests_dynamic_rendering.cpp:5610:5 (vk_layer_validation_tests+0xb9a4c8) (BuildId: 655a6717424f7bc5707081155d2c11ce71651f2f)
    #10 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/juan/projects/vvl/external/googletest/googletest/src/gtest.cc:2599:10 (vk_layer_validation_tests+0x12b309a) (BuildId: 655a6717424f7bc5707081155d2c11ce71651f2f)
    #11 main /home/juan/projects/vvl/tests/layer_validation_tests.cpp:3758:14 (vk_layer_validation_tests+0x3b6c9c) (BuildId: 655a6717424f7bc5707081155d2c11ce71651f2f)

    Hint: use TSAN_OPTIONS=second_deadlock_stack=1 to get more informative warning message

  Mutex M0 acquired here while holding mutex M1 in main thread:
    #0 pthread_rwlock_wrlock <null> (vk_layer_validation_tests+0x316c5a) (BuildId: 655a6717424f7bc5707081155d2c11ce71651f2f)
    #1 std::__glibcxx_rwlock_wrlock(pthread_rwlock_t*) /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/shared_mutex:80:3 (libVkLayer_khronos_validation.so+0x1898f73) (BuildId: 036adb65bc27970aa02946267092770927a02df7)
    #2 std::__shared_mutex_pthread::lock() /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/shared_mutex:193:19 (libVkLayer_khronos_validation.so+0x1912b95) (BuildId: 036adb65bc27970aa02946267092770927a02df7)
    #3 std::shared_mutex::lock() /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/shared_mutex:420:27 (libVkLayer_khronos_validation.so+0x1912b45) (BuildId: 036adb65bc27970aa02946267092770927a02df7)
    #4 std::unique_lock<std::shared_mutex>::lock() /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/unique_lock.h:139:17 (libVkLayer_khronos_validation.so+0x1912ad5) (BuildId: 036adb65bc27970aa02946267092770927a02df7)
    #5 std::unique_lock<std::shared_mutex>::unique_lock(std::shared_mutex&) /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/unique_lock.h:69:2 (libVkLayer_khronos_validation.so+0x1912a17) (BuildId: 036adb65bc27970aa02946267092770927a02df7)
    #6 CMD_BUFFER_STATE::WriteLock() /home/juan/projects/vvl/layers/cmd_buffer_state.h:341:41 (libVkLayer_khronos_validation.so+0x1ce6afc) (BuildId: 036adb65bc27970aa02946267092770927a02df7)
    #7 CMD_BUFFER_STATE::NotifyInvalidate(small_vector<std::shared_ptr<BASE_NODE>, 4ul, unsigned int> const&, bool) /home/juan/projects/vvl/layers/cmd_buffer_state.cpp:289:22 (libVkLayer_khronos_validation.so+0x1f9be5e) (BuildId: 036adb65bc27970aa02946267092770927a02df7)
    #8 BASE_NODE::NotifyInvalidate(small_vector<std::shared_ptr<BASE_NODE>, 4ul, unsigned int> const&, bool) /home/juan/projects/vvl/layers/base_node.cpp:108:19 (libVkLayer_khronos_validation.so+0x1f8e30c) (BuildId: 036adb65bc27970aa02946267092770927a02df7)
    #9 BASE_NODE::Invalidate(bool) /home/juan/projects/vvl/layers/base_node.cpp:94:16 (libVkLayer_khronos_validation.so+0x1f8d903) (BuildId: 036adb65bc27970aa02946267092770927a02df7)
    #10 CMD_BUFFER_STATE::Reset() /home/juan/projects/vvl/layers/cmd_buffer_state.cpp:183:5 (libVkLayer_khronos_validation.so+0x1f9b165) (BuildId: 036adb65bc27970aa02946267092770927a02df7)
    #11 CMD_BUFFER_STATE::Destroy() /home/juan/projects/vvl/layers/cmd_buffer_state.cpp:282:9 (libVkLayer_khronos_validation.so+0x1f9bd20) (BuildId: 036adb65bc27970aa02946267092770927a02df7)
    #12 void ValidationStateTracker::Destroy<CMD_BUFFER_STATE, state_object::Traits<CMD_BUFFER_STATE> >(state_object::Traits<CMD_BUFFER_STATE>::HandleType) /home/juan/projects/vvl/layers/state_tracker.h:341:27 (libVkLayer_khronos_validation.so+0x1fabf92) (BuildId: 036adb65bc27970aa02946267092770927a02df7)
    #13 COMMAND_POOL_STATE::Free(unsigned int, VkCommandBuffer_T* const*) /home/juan/projects/vvl/layers/cmd_buffer_state.cpp:53:23 (libVkLayer_khronos_validation.so+0x1f99a15) (BuildId: 036adb65bc27970aa02946267092770927a02df7)
    #14 ValidationStateTracker::PreCallRecordFreeCommandBuffers(VkDevice_T*, VkCommandPool_T*, unsigned int, VkCommandBuffer_T* const*) /home/juan/projects/vvl/layers/state_tracker.cpp:2241:15 (libVkLayer_khronos_validation.so+0x1c6f9c0) (BuildId: 036adb65bc27970aa02946267092770927a02df7)
    #15 vulkan_layer_chassis::FreeCommandBuffers(VkDevice_T*, VkCommandPool_T*, unsigned int, VkCommandBuffer_T* const*) /home/juan/projects/vvl/layers/generated/chassis.cpp:2645:20 (libVkLayer_khronos_validation.so+0x17f8732) (BuildId: 036adb65bc27970aa02946267092770927a02df7)
    #16 vk_testing::CommandBuffer::destroy() /home/juan/projects/vvl/tests/vktestbinding.cpp:1063:5 (vk_layer_validation_tests+0xfb796e) (BuildId: 655a6717424f7bc5707081155d2c11ce71651f2f)
    #17 vk_testing::CommandBuffer::~CommandBuffer() /home/juan/projects/vvl/tests/vktestbinding.cpp:1066:44 (vk_layer_validation_tests+0xfb79c5) (BuildId: 655a6717424f7bc5707081155d2c11ce71651f2f)
    #18 VkCommandBufferObj::~VkCommandBufferObj() /home/juan/projects/vvl/tests/vkrenderframework.h:363:7 (vk_layer_validation_tests+0x3be365) (BuildId: 655a6717424f7bc5707081155d2c11ce71651f2f)
    #19 VkLayerTest_DynamicRenderingNullDepthStencilExecuteCommands_Test::TestBody() /home/juan/projects/vvl/tests/vklayertests_dynamic_rendering.cpp:5651:1 (vk_layer_validation_tests+0xb9aa9d) (BuildId: 655a6717424f7bc5707081155d2c11ce71651f2f)
    #20 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/juan/projects/vvl/external/googletest/googletest/src/gtest.cc:2599:10 (vk_layer_validation_tests+0x12b309a) (BuildId: 655a6717424f7bc5707081155d2c11ce71651f2f)
    #21 main /home/juan/projects/vvl/tests/layer_validation_tests.cpp:3758:14 (vk_layer_validation_tests+0x3b6c9c) (BuildId: 655a6717424f7bc5707081155d2c11ce71651f2f)

SUMMARY: ThreadSanitizer: lock-order-inversion (potential deadlock) (/home/juan/projects/vvl/build/tests/vk_layer_validation_tests+0x31688a) (BuildId: 655a6717424f7bc5707081155d2c11ce71651f2f) in __interceptor_pthread_rwlock_rdlock
==================
[       OK ] VkLayerTest.DynamicRenderingNullDepthStencilExecuteCommands (6522 ms)
```

</details>

### PR DESCRIPTION
**Pull request by juan-lunarg**
closes #5011

### CODE REVIEW

**Review by jeremyg-lunarg — COMMENTED** [review]
I bet the GPUAV test failure is because it has its own CommandBuffer object which overrides Reset() and now some of its extra state is not being cleaned up correctly in Destroy().  Probably it needs to also override Destroy() as well and do a similar trick as you're doing in CMD_BUFFER_STATE. Ugh, sorry this is such a mess.

**Comment by juan-lunarg** [comment]
> I bet the GPUAV test failure is because it has its own CommandBuffer object which overrides Reset() and now some of its extra state is not being cleaned up correctly in Destroy(). Probably it needs to also override Destroy() as well and do a similar trick as you're doing in CMD_BUFFER_STATE. Ugh, sorry this is such a mess.

Looks like you are correct since I'm able to pass both `VkLayerTest.DynamicRenderingNullDepthStencilExecuteCommands` and `VkGpuAssistedLayerTest.DrawingWithUnboundUnusedSet` with `-fsanitize=thread` with your suggestion.

```
Note: Google Test filter = VkLayerTest.DynamicRenderingNullDepthStencilExecuteCommands:VkGpuAssistedLayerTest.DrawingWithUnboundUnusedSet
[==========] Running 2 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 1 test from VkLayerTest
[ RUN      ] VkLayerTest.DynamicRenderingNullDepthStencilExecuteCommands
[       OK ] VkLayerTest.DynamicRenderingNullDepthStencilExecuteCommands (802 ms)
[----------] 1 test from VkLayerTest (802 ms total)

[----------] 1 test from VkGpuAssistedLayerTest
[ RUN      ] VkGpuAssistedLayerTest.DrawingWithUnboundUnusedSet
[       OK ] VkGpuAssistedLayerTest.DrawingWithUnboundUnusedSet (4188 ms)
[----------] 1 test from VkGpuAssistedLayerTest (4188 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 2 test suites ran. (5015 ms total)
[  PASSED  ] 2 tests.
```

File: layers/cmd_buffer_state.h [hunk 1]
```diff
@@ -373,6 +373,7 @@ class CMD_BUFFER_STATE : public REFCOUNTED_NODE {
     }
 
     virtual void Reset();
+    void ResetCBState();
```
Comment (jeremyg-lunarg) [inline layers/cmd_buffer_state.h:376]: I know CMD_BUFFER_STATE is very lax with method permissions, but it seems like this one should be private to avoid confusion.

File: layers/gpu_validation.h [hunk 2]
```diff
@@ -161,8 +161,10 @@ class CommandBuffer : public gpu_utils_state::CommandBuffer {
 
     bool NeedsProcessing() const final { return !per_draw_buffer_list.empty() || has_build_as_cmd; }
 
+    void Destroy() final;
     void Process(VkQueue queue) final;
     void Reset() final;
+    void ResetCBState();
```
Comment (jeremyg-lunarg) [inline layers/gpu_validation.h:167]: This one should be private too.

**Comment by juan-lunarg** [comment]
> CI Vulkan-ValidationLayers build # 9974 failed.

CI failed because I didn't fix `debug_printf_state::CommandBuffer`. I ended up just searching the codebase for `Reset`
I think I found all of them and fixed them appropriately.

**Review by jeremyg-lunarg — APPROVED** [review]
LGTM
