### PR TITLE
layers:Fix descriptor not updated false positive

### LINKED ISSUE #521: "Descriptor in binding #X at global descriptor index Y is being used in draw but has not been updated." error when using VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT
"Descriptor in binding #X at global descriptor index Y is being used in draw but has not been updated." error when using VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT in VkDescriptorBindingFlagsEXT.

Full message:

> UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotUpdated(WARN / SPEC): msgNum: 0 - Descriptor Set 0x4 bound but it was never updated. You may want to either update it or not bind it.
>     Objects: 1
>        [0] 0x4, type: 23, name: (null)
> Validation(WARN): msg_code: 0:  [ UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotUpdated ]  [ UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotUpdated ] Object: 0x4 (Type = 23) | Descriptor Set 0x4 bound but it was never updated. You may want to either update it or not bind it.
> UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotUpdated(ERROR / SPEC): msgNum: 0 - Descriptor set 0x4 bound as set #0 encountered the following validation error at vkCmdDraw() time: Descriptor in binding #0 at global descriptor index 0 is being used in draw but has not been updated.
>     Objects: 1
>        [0] 0x4, type: 23, name: (null)
> Validation(ERROR): msg_code: 0:  [ UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotUpdated ]  [ UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotUpdated ] Object: 0x4 (Type = 23) | Descriptor set 0x4 bound as set #0 encountered the following validation error at vkCmdDraw() time: Descriptor in binding #0 at global descriptor index 0 is being used in draw but has not been updated.

The problem seems to be in following code snippet:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/sdk-1.1.92/layers/descriptor_sets.cpp#L716

```
        for (uint32_t i = index_range.start; i < index_range.end; ++i, ++array_idx) {
            if ((p_layout_->GetDescriptorBindingFlagsFromBinding(binding) & VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT_EXT) ||
                descriptors_[i]->GetClass() == InlineUniform) {
                // Can't validate the descriptor because it may not have been updated,
                // or the view could have been destroyed
                continue;
            } else if (!descriptors_[i]->updated) {
```

VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT flag allows updating descriptor later:
```
VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT indicates that if descriptors in this binding are
updated between when the descriptor set is bound in a command buffer and when that
command buffer is submitted to a queue, then the submission will use the most recently set
descriptors for this binding and the updates do not invalidate the command buffer. 
```
> 
so I believe it should be also included in the code.

### PR DESCRIPTION
**Pull request by tobine**
Fixes #521 
This prevents a false positive reported in #521 when VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT is enabled.
However, it does not address a number of other validation updates required for VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT.

I'll file a separate issue to track complete validation for that bit.

### CODE REVIEW

File: layers/descriptor_sets.cpp [hunk 1]
```diff
@@ -719,7 +719,8 @@ bool cvdescriptorset::DescriptorSet::ValidateDrawState(const std::map<uint32_t,
         }
 
         for (uint32_t i = index_range.start; i < index_range.end; ++i, ++array_idx) {
-            if ((p_layout_->GetDescriptorBindingFlagsFromBinding(binding) & VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT_EXT) ||
+            if ((p_layout_->GetDescriptorBindingFlagsFromBinding(binding) &
+                 (VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT_EXT | VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT)) ||
                 descriptors_[i]->GetClass() == InlineUniform) {
                 // Can't validate the descriptor because it may not have been updated,
                 // or the view could have been destroyed
```
Comment (jzulauf-lunarg) [inline layers/descriptor_sets.cpp]: The comment here is very odd... If we're cleaning up the check, the comment should make sense and the "or the view could have been destroyed" comment baffles me.

**Comment by flisgd** [comment]
> I'll file a separate issue to track complete validation for that bit.

Some other related warnings that you may want to add to this separate issue:

```
UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotUpdated(WARN / SPEC): msgNum: 0 - Descriptor Set 0x4 bound but it was never updated. You may want to either update it or not bind it.
    Objects: 1
       [0] 0x4, type: 23, name: (null)
Validation(WARN): msg_code: 0:  [ UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotUpdated ]  [ UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotUpdated ] Object: 0x4 (Type = 23) | Descriptor Set 0x4 bound but it was never updated. You may want to either update it or not bind it.
```

**Comment by karl-lunarg** [comment]
Is there checking done elsewhere to see if the descriptor indexing extension is enabled and that the corresponding descriptor indexing features are enabled?

**Comment by tobine** [comment]
@karl-lunarg where validation is currently supporting descriptor indexing extension (which is not comprehensive), there are checks to verify the feature is enabled.

File: layers/descriptor_sets.cpp (hunk 1 above)
Comment (tobine) [reply layers/descriptor_sets.cpp]: @mark-lunarg or @jeffbolznv you're on the git blame for this comment. I assume it's referring to some special treatment for InlineUniform descriptors but agree with @jzulauf-lunarg observation. Clarify please?
