### PR TITLE
Validate VkCommandBufferInheritanceRenderingInfo formats match pipeline formats

### LINKED ISSUE #5909: VUID-vkCmdDrawIndexed-pDepthAttachment-06181 not triggered from secondary command buffers
**Describe the situation in which you encountered the missing validation**
Issue description:

This could be a limitation in how the inheritance works with secondary command buffers. 

Basically, I was stuck debugging a failure to write to the depth buffer which came down to my missing this setting in my pipeline creation:
```cpp
VkPipelineRenderingCreateInfoKHR renderingCreateInfo { VK_STRUCTURE_TYPE_PIPELINE_RENDERING_CREATE_INFO_KHR };
        renderingCreateInfo.colorAttachmentCount = 1;
        renderingCreateInfo.pColorAttachmentFormats = &_config.SwapchainColorFormat;
        renderingCreateInfo.depthAttachmentFormat = VK_FORMAT_D32_SFLOAT;   // < --- here
```

When I ruled out all the other issues, I converted my codebase to use primary buffers and I immediately got the proper message through the validation layers:

> Validation Error: [ VUID-vkCmdDrawIndexed-pDepthAttachment-06181 ] Object 0: handle = 0x20bedcc2e30, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0x1417070000000
0d7, type = VK_OBJECT_TYPE_PIPELINE; Object 2: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0xc365da88 | vkCmdDrawIndexed: VkRenderingInfo::pDepthAttachment->imageView format (VK_FORMAT_D32_SFLOAT) must match
 corresponding format in VkPipelineRenderingCreateInfo::depthAttachmentFormat (VK_FORMAT_UNDEFINED) The Vulkan spec states: If the current render pass instance was begun with vkCmdBeginRendering and VkRenderingInfo::pDepthAttach
ment->imageView was not VK_NULL_HANDLE, the value of VkPipelineRenderingCreateInfo::depthAttachmentFormat used to create the currently bound graphics pipeline must be equal to the VkFormat used to create VkRenderingInfo::pDepthA
ttachment->imageView

**Valid Usage IDs requested**
Please include the valid usage IDs for the checks you are requesting:
VUID-vkCmdDrawIndexed-pDepthAttachment-06181 

I suspect the other vkCmdDraw commands will have the same issue but I haven't tested it.

**Additional Context**

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #5909

### CODE REVIEW

File: tests/unit/dynamic_rendering.cpp [hunk 1]
```diff
@@ -6709,3 +6709,42 @@ TEST_F(NegativeDynamicRendering, MissingMultisampleState) {
...
     m_errorMonitor->VerifyFound();
 }
+
+TEST_F(NegativeDynamicRendering, MismatchingDepthAttachmentFormatInSecondaryCmdBuffer) {
+    TEST_DESCRIPTION("Use a pipeline with a depth attachment format that doesn't match that of the dynamic render pass");
+    InitBasicDynamicRendering();
+    if (::testing::Test::IsSkipped()) return;
+
+    VkFormat depth_format1 = VK_FORMAT_D32_SFLOAT_S8_UINT;
+    VkFormat depth_format2 = VK_FORMAT_D24_UNORM_S8_UINT;
```
Comment (spencer-lunarg) [inline tests/unit/dynamic_rendering.cpp:6719]: will see what CI says, but might need to query for valid types, but might not since we are not creating a `VkImage`

**Review by spencer-lunarg — APPROVED** [review]
