### PR TITLE
corechecks: Avoid crashing in ValidateBufferUpdate

### LINKED ISSUE #7972: Crash in CoreChecks::ValidateMemoryIsBoundToBuffer, ValidateBufferUpdate doesn't check for nullptr
I'm getting a crash with VVL that looks like this:

```
 	VkLayer_khronos_validation.dll!CoreChecks::ValidateMemoryIsBoundToBuffer(LogObjectList objlist, const vvl::Buffer & buffer_state, const Location & buffer_loc, const char * vuid) Line 2280	C++
>	VkLayer_khronos_validation.dll!CoreChecks::ValidateBufferUpdate(const VkDescriptorBufferInfo & buffer_info, VkDescriptorType type, const Location & buffer_info_loc) Line 1557	C++
 	VkLayer_khronos_validation.dll!CoreChecks::VerifyWriteUpdateContents(const vvl::DescriptorSet & dst_set, const VkWriteDescriptorSet & update, const unsigned int index, const Location & write_loc, bool push) Line 2042	C++
 	VkLayer_khronos_validation.dll!CoreChecks::ValidateWriteUpdate(const vvl::DescriptorSet & dst_set, const VkWriteDescriptorSet & update, const Location & write_loc, bool push) Line 1878	C++
 	VkLayer_khronos_validation.dll!CoreChecks::ValidateUpdateDescriptorSets(unsigned int descriptorWriteCount, const VkWriteDescriptorSet * pDescriptorWrites, unsigned int descriptorCopyCount, const VkCopyDescriptorSet * pDescriptorCopies, const Location & loc) Line 1348	C++
 	VkLayer_khronos_validation.dll!CoreChecks::PreCallValidateUpdateDescriptorSetWithTemplate(VkDevice_T * device, VkDescriptorSet_T * descriptorSet, VkDescriptorUpdateTemplate_T * descriptorUpdateTemplate, const void * pData, const ErrorObject & error_obj) Line 3616	C++
 	VkLayer_khronos_validation.dll!CoreChecks::PreCallValidateUpdateDescriptorSetWithTemplateKHR(VkDevice_T * device, VkDescriptorSet_T * descriptorSet, VkDescriptorUpdateTemplate_T * descriptorUpdateTemplate, const void * pData, const ErrorObject & error_obj) Line 3626	C++
 	VkLayer_khronos_validation.dll!vulkan_layer_chassis::UpdateDescriptorSetWithTemplateKHR(VkDevice_T * device, VkDescriptorSet_T * descriptorSet, VkDescriptorUpdateTemplate_T * descriptorUpdateTemplate, const void * pData) Line 7538	C++
```
In `ValidateBufferUpdate `it dereferences buffer_state without nullptr checking it:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/5079c310359e9ff5273657e6818b203263b0bcfb/layers/core_checks/cc_descriptor.cpp#L1601

In other places in the code it always checks that buffer_state is non-null before dereferencing it and prints a validation error if so.  I think this place in the code needs to do the same.

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**
Avoid a null pointer dereference if this function encounters an invalid VkBuffer handle. This error should be caught by the object tracker but core validation shouldn't crash.

Additionally, doing:
`    auto &state_object = *Get<>(handle);
`
Defeats the state tracker reference counting scheme and could cause a use after free error if a buggy application deletes a handle while validation is using its state object.

Fixes #7972

### CODE REVIEW

**Review by artem-lunarg — APPROVED** [review]

File: layers/core_checks/cc_descriptor.cpp [hunk 1]
```diff
@@ -1598,25 +1598,29 @@ bool CoreChecks::ValidateBufferUsage(const vvl::Buffer &buffer_state, VkDescript
 bool CoreChecks::ValidateBufferUpdate(const VkDescriptorBufferInfo &buffer_info, VkDescriptorType type,
                                       const Location &buffer_info_loc) const {
     bool skip = false;
-    const auto &buffer_state = *Get<vvl::Buffer>(buffer_info.buffer);
-    skip |= ValidateMemoryIsBoundToBuffer(device, buffer_state, buffer_info_loc.dot(Field::buffer),
+    // Invalid handles should be caught by the object tracker, but lets make sure not to crash anyways.
```
Comment (spencer-lunarg) [inline layers/core_checks/cc_descriptor.cpp:1601]: I guess this worries me a bit, there is clearly a bug in Object Tracker missing logic around descriptors as this should be caught


...but agree the crashing is worse

**Review by spencer-lunarg — APPROVED** [review]
