### PR TITLE
Fix descriptorCount bindings being checked

### LINKED ISSUE #2600: CTS crashing due to #2540
CTS is crashing due to #2540.

From @Tony-LunarG: the issue can be reproduced with `dEQP-VK.binding_model.shader_access.primary_cmd_buf.uniform_buffer_dynamic.no_access.multiple_discontiguous_descriptors.offset_view_zero_dynamic_nonzero`. At https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/476f5e2a9f6525143ee9cc48f4c4c8108d00f22a/layers/core_validation.cpp#L6972 the returned `descriptor` is null.

@sfricke-samsung Let me know if there's a particular way you'd like to proceed with this. Thanks!

### PR DESCRIPTION
**Pull request by sfricke-samsung**
Closes #2600 

From spec

> dynamicOffsetCount must equal the total number of dynamic **descriptors** in the sets being bound

I didn't even realize until now you could have a `VkDescriptorSetLayoutBinding` with a `dynamicOffsetCount` of zero (special case in spec) and now it will skip a binding with a dynamic descriptor type that doesn't actually have a descriptor to it.. this solves #2600

While adding this, I realize I wasn't handling the case where `descriptorCount` was greater then `1` so added that support. It consisted of removing the old descriptor dynamic index helper functions and added a new one that will just track which `cvdescriptorset::Descriptor` to grab by the offset.

I also added the `dstArrayElement` field to all the `VkWriteDescriptorSet` wrappers in the testing framework

### CODE REVIEW

**Comment by ncesario-lunarg** [comment]
Running through [internal CI](http://erusea:4040/8504).

File: layers/descriptor_sets.cpp [hunk 1]
```diff
@@ -636,10 +628,16 @@ cvdescriptorset::DescriptorSet::DescriptorSet(const VkDescriptorSet set, DESCRIP
                     descriptors_.emplace_back(new ((free_descriptor++)->Texel()) TexelDescriptor(type));
                 }
                 break;
-            case VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER:
             case VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC:
-            case VK_DESCRIPTOR_TYPE_STORAGE_BUFFER:
             case VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC:
+                for (uint32_t di = 0; di < layout_->GetDescriptorCountFromIndex(i); ++di) {
+                    // TODO - Not using IsDyanmicDescriptor() so need to be careful if new dynamic descriptor ever added in future
```
Comment (ncesario-lunarg) [inline layers/descriptor_sets.cpp:634]: Would it make sense to handle dynamic descriptors outside of the switch, and remove the dynamic cases from the switch?

**Review by ncesario-lunarg — APPROVED** [review]
Minor question, but in general LGTM. Thanks again for the quick turnaround with this issue @sfricke-samsung!

File: layers/descriptor_sets.cpp (hunk 1 above)
Comment (sfricke-samsung) [reply layers/descriptor_sets.cpp:634]: hm, ya, I guess let's just do that, I was keeping it in there for consistency... you want me to fix this now, or you have internal CI already done and ready to go to do it in another commit?

Comment (ncesario-lunarg) [reply layers/descriptor_sets.cpp:634]: Internal CI is :heavy_check_mark:, so I'm good with merging this now and handling that in another commit if you like (should be a small change).

Comment (sfricke-samsung) [reply layers/descriptor_sets.cpp:634]: ya, lets do that, I might have other small clean-ups around the descriptor_set class I would make while I am at it (as I found some other small stuff while fixing this)
