### PR TITLE
layers: Check if iterator is not empty before increment

### LINKED ISSUE #3609: Syncval crashes in the presence of multiple subpasses with secondary command buffers
To repro:

- Take ToT ANGLE and apply the following patches (if not landed already):
  * https://chromium-review.googlesource.com/c/angle/angle/+/3344373
  * https://chromium-review.googlesource.com/c/angle/angle/+/3344774
- Build with the following `gn` args specified:
  * `is_debug=true`
  * `angle_enable_custom_vulkan_cmd_buffers=false`
- Run `./angle_end2end_tests --gtest_filter=MultisampledRenderToTextureTest.2DColorAttachmentMultisampleDrawTest/ES2_Vulkan`

Observe a crash inside syncval:

```
angle_end2end_tests: ../../third_party/vulkan-deps/vulkan-validation-layers/src/layers/range_vector.h:1623: parallel_iterator<MapA, MapB, KeyType> &sparse_container::parallel_iterator<sparse_container::range_map<unsigned long, ResourceAccessState>, const sparse_container::range_map<unsigned long, ResourceAccessState>, sparse_container::range<unsigned long>>::operator++() [MapA = sparse_container::range_map<unsigned long, ResourceAccessState>, MapB = const sparse_container::range_map<unsigned long, ResourceAccessState>, KeyType = sparse_container::range<unsigned long>]: Assertion `delta != 0' failed.
```

In `AccessContext::ResolveAccessRange`, I see the following at the time of the assertion failure:

```
(gdb) p range
$2 = ... {
  begin = 0,
  end = 18446744073709551615
}
(gdb) p current->range
$1 = ... {
  begin = 18446744073709551614,
  end = 18446744073709551614
}
```

**Environment:**
 - OS: Linux
 - GPU: Nvidia
 - SDK or header version if building from repo: 9f537109d
 - Options enabled (synchronization, best practices, etc.): synchronization

Note that the test would be disabled on Windows/Intel, Windows/AMD and SwiftShader, but any other configuration should trigger this.

### LINKED ISSUE #3862: syncval: crash in 1.3.1 CTS
**Describe the Issue**
With sync validation enabled, this CTS crashes:
dEQP-VK.pipeline.multisample.sample_locations_ext.draw.color.samples_8.separate_subpass_no_clear_secondary_cmd_buf

Assertion failed: delta != 0, file c:\users\lunarg\vulkan-validationlayers\layers\range_vector.h, line 1623
```
 	VkLayer_khronos_validation.dll!sparse_container::parallel_iterator<sparse_container::range_map<unsigned __int64,ResourceAccessState,sparse_container::range<unsigned __int64>,std::map<sparse_container::range<unsigned __int64>,ResourceAccessState,std::less<sparse_container::range<unsigned __int64>>,std::allocator<std::pair<sparse_container::range<unsigned __int64> const ,ResourceAccessState>>>>,sparse_container::range_map<unsigned __int64,ResourceAccessState,sparse_container::range<unsigned __int64>,std::map<sparse_container::range<unsigned __int64>,ResourceAccessState,std::less<sparse_container::range<unsigned __int64>>,std::allocator<std::pair<sparse_container::range<unsigned __int64> const ,ResourceAccessState>>>> const ,sparse_container::range<unsigned __int64>>::operator++() Line 1623	C++
 	VkLayer_khronos_validation.dll!AccessContext::ResolveAccessRange<ApplyTrackbackStackAction const>(AccessAddressType type, const sparse_container::range<unsigned __int64> & range, const ApplyTrackbackStackAction & barrier_action, sparse_container::range_map<unsigned __int64,ResourceAccessState,sparse_container::range<unsigned __int64>,std::map<sparse_container::range<unsigned __int64>,ResourceAccessState,std::less<sparse_container::range<unsigned __int64>>,std::allocator<std::pair<sparse_container::range<unsigned __int64> const ,ResourceAccessState>>>> * resolve_map, const ResourceAccessState * infill_state, bool recur_to_infill) Line 970	C++
 	VkLayer_khronos_validation.dll!AccessContext::ResolvePreviousAccess(AccessAddressType type, const sparse_container::range<unsigned __int64> & range, sparse_container::range_map<unsigned __int64,ResourceAccessState,sparse_container::range<unsigned __int64>,std::map<sparse_container::range<unsigned __int64>,ResourceAccessState,std::less<sparse_container::range<unsigned __int64>>,std::allocator<std::pair<sparse_container::range<unsigned __int64> const ,ResourceAccessState>>>> * descent_map, const ResourceAccessState * infill_state, const std::function<void __cdecl(ResourceAccessState *)> * previous_barrier) Line 1008	C++
 	VkLayer_khronos_validation.dll!AccessContext::ResolvePreviousAccessStack<NoopBarrierAction const>(AccessAddressType type, const sparse_container::range<unsigned __int64> & range, sparse_container::range_map<unsigned __int64,ResourceAccessState,sparse_container::range<unsigned __int64>,std::map<sparse_container::range<unsigned __int64>,ResourceAccessState,std::less<sparse_container::range<unsigned __int64>>,std::allocator<std::pair<sparse_container::range<unsigned __int64> const ,ResourceAccessState>>>> * descent_map, const ResourceAccessState * infill_state, const NoopBarrierAction & previous_barrier) Line 984	C++
 	VkLayer_khronos_validation.dll!AccessContext::ResolveAccessRange<NoopBarrierAction const>(AccessAddressType type, const sparse_container::range<unsigned __int64> & range, const NoopBarrierAction & barrier_action, sparse_container::range_map<unsigned __int64,ResourceAccessState,sparse_container::range<unsigned __int64>,std::map<sparse_container::range<unsigned __int64>,ResourceAccessState,std::less<sparse_container::range<unsigned __int64>>,std::allocator<std::pair<sparse_container::range<unsigned __int64> const ,ResourceAccessState>>>> * resolve_map, const ResourceAccessState * infill_state, bool recur_to_infill) Line 975	C++
 	VkLayer_khronos_validation.dll!CommandBufferAccessContext::CommandBufferAccessContext(const CommandBufferAccessContext & from, CommandBufferAccessContext::AsProxyContext dummy) Line 213	C++
 	VkLayer_khronos_validation.dll!SyncValidator::PreCallValidateCmdExecuteCommands(VkCommandBuffer_T * commandBuffer, unsigned int commandBufferCount, VkCommandBuffer_T * const * pCommandBuffers) Line 6481	C++
 	VkLayer_khronos_validation.dll!vulkan_layer_chassis::CmdExecuteCommands(VkCommandBuffer_T * commandBuffer, unsigned int commandBufferCount, VkCommandBuffer_T * const * pCommandBuffers) Line 3754	C++
 	deqp-vk.exe!vkt::pipeline::`anonymous namespace'::Draw::DrawTest::drawSubpasses() Line 2909	C++
 	deqp-vk.exe!vkt::pipeline::`anonymous namespace'::Draw::DrawTest::iterate() Line 2172	C++
 	deqp-vk.exe!vkt::TestCaseExecutor::iterate(tcu::TestCase * __formal) Line 401	C++
 	deqp-vk.exe!tcu::TestSessionExecutor::iterateTestCase(tcu::TestCase * testCase) Line 302	C++
 	deqp-vk.exe!tcu::TestSessionExecutor::iterate() Line 141	C++
 	deqp-vk.exe!tcu::App::iterate() Line 221	C++
 	deqp-vk.exe!main(int argc, char * * argv) Line 58	C++

```

**Valid Usage ID**
none

**Environment:**
 - OS:  Windows (though probably any)
 - GPU: RTX 2080 (probably any)
 - SDK or header version if building from repo: master at 852187f10
 - Options enabled (synchronization, best practices, etc.):

**Additional context**

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #3609 
Closes #3862

### CODE REVIEW

**Review by jeremyg-lunarg — APPROVED** [review]

File: layers/synchronization_validation.cpp [hunk 1]
```diff
@@ -966,7 +966,9 @@ void AccessContext::ResolveAccessRange(AccessAddressType type, const ResourceAcc
                 current.invalidate_A(inserted);  // Update the parallel iterator to point at the correct segment after insert
             }
         }
-        ++current;
+        if (current->range.non_empty()) {
```
Comment (jzulauf-lunarg) [inline layers/synchronization_validation.cpp:969]: Given the while condition at the top, this seems correct... curious the conditions under which range becomes empty -- seems like the seek would have to have moved one of the positions to end.

Given the complexity of some of these range traversers, probably an algorithmic review of the them would be useful to schedule... but I haven't looked at it in so long that beyond "Looks good" I' don't have a deep comment.

**Review by jzulauf-lunarg — APPROVED** [review]
LGTM -- funny we haven't hit the underlying assert more.

File: layers/synchronization_validation.cpp (hunk 1 above)
Comment (ncesario-lunarg) [reply layers/synchronization_validation.cpp:969]: > Given the complexity of some of these range traversers, probably an algorithmic review of the them would be useful to schedule

+1 for sure :)
