### PR TITLE
Fix Query validation when used across multiple command buffers

### LINKED ISSUE #1364: vkCmdResetQueryPool + vkCmdBeginQuery/vkCmdWriteTimestamp false positive
Hello,

I have encountered a problem with vkCmdResetQueryPool and vkCmdBeginQuery/vkCmdWriteTimestamp validation. 
I'm getting messages:

vkCmdBeginQuery(): VkQueryPool 0x4655610000000064[] and query 99: query not reset. After query pool creation, each query must be reset before it is used. Queries must also be reset between uses.

But the problem is that vkCmdResetQueryPool is executed in different command buffer than buffer that is executing vkCmdBeginQuery and validation layer is not recording query reset state between command buffers.

I have traced it down to ValidateCommandBuffersForSubmit and this function is not tracking query state proper.

Thanks,
Jarek

SDK 1.1.126.0

### PR DESCRIPTION
**Pull request by mark-lunarg**
Local per-CB query-state data went out of scope during QueueSubmit-time validation.  Moved state data up to the submit-level and added a positive test.

Fixes #1364.

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@jeffbolznv, the local state was used to maintain the state across all the CBs within the submitInfo, but it was also needed to maintain the state across all of the submitInfos, so it's now moved outside of that loop.

File: tests/vkpositivelayertests.cpp [hunk 1]
```diff
@@ -746,6 +746,77 @@ TEST_F(VkPositiveLayerTest, DestroyPipelineRenderPass) {
...
+    m_errorMonitor->ExpectSuccess();
+
+    VkQueryPool query_pool;
+    VkQueryPoolCreateInfo query_pool_create_info{};
+    query_pool_create_info.sType = VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO;
+    query_pool_create_info.queryType = VK_QUERY_TYPE_TIMESTAMP;
+    query_pool_create_info.queryCount = 1;
+    vk::CreateQueryPool(m_device->device(), &query_pool_create_info, nullptr, &query_pool);
+
+    VkCommandPool command_pool;
```
Comment (Tony-LunarG) [inline tests/vkpositivelayertests.cpp]: Any reason not to use m_commandPool?

Comment (mark-lunarg) [reply tests/vkpositivelayertests.cpp]: No, fixed that, and the use of the second queue which was totally hosing the mock ICD.
