### PR TITLE
layers: Add check and test for relax block layout

### LINKED ISSUE #275: Layers report layout violations when relaxed block layout extension is enabled
Originally reported in [LunarXchange](https://vulkan.lunarg.com/issue/view/5b6ac13666315148d1e44936).

SPIRV-Tools `spirv-val` was recently updated to check for conforming uniform block layouts.  The `--relax-block-layout` option can be used to quiet the error messages from intentionally non-conforming blocks.  Good so far.

But the validation layers still report a non-conforming layout even when the `VK_KHR_relaxed_block_layout` extension is active.  I'm not completely certain but it seems that the shader validation steps in the validation layers should also ignore these errors when the extension is enabled.  This could be done by somehow setting the equivalent of `--relax-block-layout` in the library interface to `spirv-val`, if possible,  or some other approach.  I took a quick look and didn't see any special steps taken if the extension is enabled.

Here's the sample shader with the non-conforming layout and notes from the reporter:

```
// This file is cutdown.vert
//
// The following happens with Vulkan SDK 1.1.82.0, but not with Vulkan SDK 1.1.77.0
//
// Run the following:
// glslangValidator -V cutdown.vert
// spirv-val vert.spv
//
// Results in:
// error: line 28: Structure id 8 decorated as Block must follow standard uniform buffer layout rules: member 2 at offset 28 // overlaps previous member ending at offset 31
//   OpFunctionEnd
//
// When running the application (using the non-cutdown shader code) with Vulkan validation
// layers enabled, it also results in errors such as:
//
// ERRR: @[Validation]:  [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object: VK_NULL_HANDLE (Type = 0) | SPIR-V module not valid: Structure id 212 decorated as Block must follow standard uniform buffer layout rules: member 2 at offset 28 overlaps previous member ending at offset 31
//   OpFunctionEnd

#version 450 core

layout(set = 0, binding = 1, std140) uniform uniforms {
    float a;
    vec3 b;
    float c;
};

void main() {
}
```

### PR DESCRIPTION
**Pull request by karl-lunarg**
Tell the SPIR-V validator to skip block layout checking if the
VK_KHR_relaxed_block_layout extension is enabled.
This prevents validation error messages for shaders with
non-compliant layouts when the extension is enabled.

The VK_KHR_relaxed_block_layout extension was promoted to core
in 1.1, so it is "enabled" for 1.1 and later apps all the time.

Since block layout checking is always relaxed in 1.1 or later,
there is really no way to write a negative test for 1.1 or later.
Therefore there is just a positive test that checks that no error
is generated for a shader with a non-compiliant layout.

Fixes #275

### CODE REVIEW

File: tests/layer_validation_tests.cpp [hunk 1]
```diff
@@ -17702,6 +17702,52 @@ TEST_F(VkLayerTest, CreateShaderModuleCheckBadCapability) {
...
+        return;
+    }
+    m_device_extension_names.push_back(VK_KHR_RELAXED_BLOCK_LAYOUT_EXTENSION_NAME);
+    ASSERT_NO_FATAL_FAILURE(InitState());
+    ASSERT_NO_FATAL_FAILURE(InitRenderTarget());
+
+    // Vertex shader requiring relaxed layout
+    char const *vsSource =
+        "#version 450\n"
+        "layout(set = 0, binding = 1, std140) uniform uniforms {\n"
```
Comment (chrisforbes) [inline tests/layer_validation_tests.cpp]: Not a fan of this test case. It needs to be clear that you're doing something beyond std140.

Can't fault the implementation, though.

Comment (karl-lunarg) [reply tests/layer_validation_tests.cpp]: Can you be more specific about what should be here instead so I don't have to guess?

This test case seems to me to be the minimal one needed to reproduce the problem and parallels the case supplied by the original reporter.

Comment (chrisforbes) [reply tests/layer_validation_tests.cpp]: With no extra options, this shader should be compiled to something that /doesn't/ require relaxed layout - you ask for std140, you should get it.

Is glslang just doing this /always/ now? Are we enabling it by default somewhere in the plumbing?

Comment (karl-lunarg) [reply tests/layer_validation_tests.cpp]: The _SPIR-V Validator_ was recently tightened up to report an error if the layout needs to be relaxed.  This evidentially happens even if you supply std140.  This applies to both the command and the library forms of the validator.  

This happens all the time and I don't think that it is happening because of something in the Vulkan validation plumbing because this is happening outside of the context of Vulkan validation.

You can suppress the message by passing an option to tell the validator to not perform checks for the relaxed layout.   

It seems a little weird for the _SPIR-V Validator_ to throw an error if the existence of std140 is supposed to connote "I know I need relaxed layout and I'm asking for it via std140".

I suppose that the new behavior is supposed to communicate to the caller of the vaildator that there is relaxed layout in the shader, whether it was explicitly asked for (via std140) or not.

This is therefore an indicator to the Vulkan app/layers that the Vulkan implementation (driver) needs to support relaxed if this shader is to be used.  Relaxed support became required in Vulkan 1.1 and so for 1.1, we really don't have to check the implementation and we _could_ just always call the validator with the option for not doing the layout check, since we don't care if the layout is relaxed or not in 1.1.  But if 1.0 and the extension is not enabled, then we want the validator to tell us if there is a relaxed layout because the shader won't work if relaxed layout support is not available or is not enabled.

Really, all this test is doing is making sure that the shader validation layer is suppressing the error from the validator with the layout is relaxed and the extension is enabled.  (The extension is always enabled in 1.1, from the layer's POV.) To obtain that goal, the test shader needs to require relaxed layout.

Without this fix, any shader with relaxed layout is going to get a validation error message, even if they are on 1.1 or on 1.0 with the relaxed extension enabled.  I view that as a bit of a problem.  And we've already had one person report it via the LunarXchange issue I noted in #275.

Comment (chrisforbes) [reply tests/layer_validation_tests.cpp]: I'm saying this smells like bad compiler behavior, because this _isn't a shader with relaxed layout_. It's a shader where std140 requires some unfortunate padding that relaxed layout allows you to remove, along with (as far as I can see, at least) no additional instruction to glslang to assume the extension is available.

Without any special instruction to glslang to tell it "please use relaxed layouts", that shader /must not/ compile to use a layout that deviates from std140. That is, the block should be laid out as follows:

```
layout(std140, ...) uniform uniforms {
    float a;     // offset 0
    vec3 b;    // offset 16 due to base alignment of 16
    float c;     // offset 28 due to base alignment of 4
}
```

Comment (chrisforbes) [reply tests/layer_validation_tests.cpp]: (or a third option, disagreement between glslang and spirv-tools about std140 rules / vulkan 1.0 layout rules, and relaxed layout "fixes" that)

**Comment by chrisforbes** [comment]
What about an actual relaxed layout case? I think you do still need this change, just not for the test case that motivated it.

**Comment by karl-lunarg** [comment]
If you can post a test shader that has an actual relaxed layout, I can see how the validator reacts to it and will put back the change as needed.

**Comment by chrisforbes** [comment]
@chaoticbob has examples

**Comment by karl-lunarg** [comment]
> @chaoticbob has examples

This would help a lot.

**Comment by karl-lunarg** [comment]
I was able to find a test shader in SPIR-V assembler form that is suitable.  It came from the SPIRV-Tools test suite.  I have the test using that shader working in my branch.  I'll update this PR soon.

**Comment by karl-lunarg** [comment]
It turns out that the changes to `shader_validation.cpp` are not needed for 1.1 devices because the SPIR-V validator turns on the relaxed block option if the device is > 1.0.  That means that the validator has been running with relaxed checking on 1.1 devices since the checking was introduced, which is great.  Still, we need these changes for 1.0 devices.

I updated the test case as shown in the latest commit.  @chrisforbes please review.

About the only improvement I can think of is to add support to the testing framework to assemble the SPIR-V assembly code from the source instead of sticking the SPIR-V binary in there.  @chrisforbes Do you think that's worth doing?

**Comment by chrisforbes** [comment]
I'd go for assembling the shader. You've got to have a copy of the assembly there for the humans anyway; may as well make it do something.

**Comment by karl-lunarg** [comment]
I went ahead and added support to the framework to convert SPIR-V assembly text to binary.
