### PR TITLE
layers: Initialize SURFACE_STATE::swapchain in the constructor

### LINKED ISSUE #3087: Incorrect: VUID-vkDestroySurfaceKHR-surface-01266
**Describe the Issue**
The VVL error VUID-vkDestroySurfaceKHR-surface-01266 is being reported incorrectly on Windows.

```
RendererVk.cpp:363 (DebugUtilsMessenger): [ VUID-vkDestroySurfaceKHR-surface-01266 ] Validation Error: [ VUID-vkDestroySurfaceKHR-surface-01266 ] Object 0: handle = 0x1aa751acc20, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xbed408e4 | vkDestroySurfaceKHR() called before its associated VkSwapchainKHR was destroyed. The Vulkan spec states: All VkSwapchainKHR objects created for surface must have been destroyed prior to destroying surface (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkDestroySurfaceKHR-surface-01266)
```

These tests were passing until a recent VVL roll into ANGLE.   We suspect:
https://chromium.googlesource.com/external/github.com/KhronosGroup/Vulkan-ValidationLayers.git/+/5a542f5e261170ae180c79218149f1464a08773a

**Environment:**
 - OS: Windows
 - GPU: NVIDIA
 - SDK or header version if building from repo:
 - Options enabled (synchronization, best practices, etc.):

**Additional context**
Running with commit: `ab7fb262470211d69e498bd3564a89eaa57697d1`

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**
This field used to be a smart pointer and skated by with default
constructor initialization.

Fixes #3087

### CODE REVIEW

File: layers/image_state.h [hunk 1]
```diff
@@ -272,7 +272,7 @@ class SURFACE_STATE : public BASE_NODE {
     SWAPCHAIN_NODE *swapchain;
     layer_data::unordered_map<GpuQueue, bool> gpu_queue_support;
 
-    SURFACE_STATE(VkSurfaceKHR s) : BASE_NODE(s, kVulkanObjectTypeSurfaceKHR) {}
+    SURFACE_STATE(VkSurfaceKHR s) : BASE_NODE(s, kVulkanObjectTypeSurfaceKHR), swapchain(nullptr), gpu_queue_support() {}
```
Comment (ncesario-lunarg) [inline layers/image_state.h:275]: I personally like initializing at declaration time where possible (so, `swapchain = nullptr` above) as the "post constructor list" seems to get a bit unwieldy (plus you have to make sure the order of this list matches the order of declaration, lest warnings ensue), but this LGTM if this is clearer (or something that has been standardized...can't recall if it has; something tells me @jzulauf-lunarg has an opinion on this?).

I don't think you need `gpu_queue_support()`, though, again, if it's clearer this way, LGTM.

**Review by ncesario-lunarg — APPROVED** [review]

File: layers/image_state.h (hunk 1 above)
Comment (jeremyg-lunarg) [reply layers/image_state.h:275]: I guess I don't have a good understanding of how the declaration initializers interact with the constructor list and have to look at  https://en.cppreference.com/w/cpp/language/constructor every time I see them. This case in particular always makes me confused:
```
struct S {
    int n = 42;   // default member initializer
    S() : n(7) {} // will set n to 7, not 42
};
```
So I'm just used to pedantically listing out everything to make sure I don't miss a member. But if want to go one way or the other it is fine with me.  Probably the real test of clarity is something like IMAGE_STATE, which has many more members and multiple constructors...
