### PR TITLE
Fix issue 3410, Fix CmdClearAttachment layer count

### LINKED ISSUE #3410: Unexpected validation error on VkClearRect layer range when doing vkCmdClearAttachments wtih a 2D_ARRAY view on 3D image.
After building the layers with the current changes in the main branch (1.2.195, I think), the following message may be incorrectly generated: Validation Error: [ VUID-vkCmdClearAttachments-pRects-00017 ] Object 0: handle = 0x555b82cdc238, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xcdbae8f3 | vkCmdClearAttachments(): The layers defined in pRects[0] are not contained in the layers of pAttachment[0]. The Vulkan spec states: The layers specified by each element of pRects must be contained within every attachment that pAttachments refers to (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdClearAttachments-pRects-00017)}

This happens when calling a vkCmdClearAttachments with a VK_IMAGE_VIEW_TYPE_2D_ARRAY VkImageView on a VK_IMAGE_TYPE_3D VkImage. The VkClearRect baseArrayLayer is 0 and it's layerCount is the same as the view's layerCount. The VkImageView is valid and creating it produces no validation messages after the commit linked to issue #3237.

Here's some partial code that exhibits the issue: https://gist.github.com/Jonathan-Weinstein/ca527bedfac590f7b57a580ae35a293b

Thanks.

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #3410

### CODE REVIEW

File: layers/buffer_validation.cpp [hunk 1]
```diff
@@ -3359,7 +3359,10 @@ bool CoreChecks::ValidateClearAttachmentExtent(VkCommandBuffer command_buffer, u
         if (image_view_state) {
             // The layers specified by a given element of pRects must be contained within every attachment that
             // pAttachments refers to
-            const auto attachment_layer_count = image_view_state->normalized_subresource_range.layerCount;
+            const uint32_t attachment_layer_count =
+                image_view_state->create_info.subresourceRange.layerCount == VK_REMAINING_ARRAY_LAYERS
+                                            ? GetImageState(image_view_state->create_info.image)->createInfo.arrayLayers
```
Comment (jeremyg-lunarg) [inline layers/buffer_validation.cpp:3364]: you should skip the GetImageState() hash look up and just use image_view_state->image_state

File: layers/buffer_validation.cpp [hunk 2]
```diff
@@ -3359,7 +3359,7 @@ bool CoreChecks::ValidateClearAttachmentExtent(VkCommandBuffer command_buffer, u
         if (image_view_state) {
             // The layers specified by a given element of pRects must be contained within every attachment that
             // pAttachments refers to
-            const auto attachment_layer_count = image_view_state->normalized_subresource_range.layerCount;
+            const uint32_t attachment_layer_count = image_view_state->GetImageLayerCount();
```
Comment (jeremyg-lunarg) [inline layers/buffer_validation.cpp:3362]: Does normalize_subresource_range give you a different answer than GetImageLayerCount()? It should be doing the same thing.

Comment (ziga-lunarg) [reply layers/buffer_validation.cpp:3362]: Yes it does, that is exactly the issue. I believe you made a change a couple of weeks ago to it, already fixed one issue with it, by replacing it with this.

File: tests/vkpositivelayertests.cpp [hunk 3]
```diff
@@ -15891,6 +15891,105 @@ TEST_F(VkPositiveLayerTest, TestPervertexNVShaderAttributes) {
...
+    image_ci.arrayLayers = 1;
+    image_ci.samples = VK_SAMPLE_COUNT_1_BIT;
+    image_ci.tiling = VK_IMAGE_TILING_OPTIMAL;
+    image_ci.usage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;
+    image_ci.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
+
+    VkImageObj image(m_device);
+    image.init(&image_ci);
+    VkImageView image_view =
+        image.targetView(image_ci.format, VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, image_ci.extent.depth, VK_IMAGE_VIEW_TYPE_2D_ARRAY);
```
Comment (jeremyg-lunarg) [inline tests/vkpositivelayertests.cpp:15923]: Does the test still work if you use VK_REMAINING_ARRAY_LAYERS here? I think in IMAGE_VIEW_STATE::GetImageLayerCount()  you'd have image_state->createInfo.arrayLayers == 1. But you'd really want 32, same as image_ci.extent.depth.

File: layers/image_state.cpp [hunk 4]
```diff
@@ -458,6 +458,11 @@ VkExtent3D IMAGE_VIEW_STATE::GetExtent() const {
     return result;
 }
 
+uint32_t IMAGE_VIEW_STATE::GetImageLayerCount() const {
+    return create_info.subresourceRange.layerCount == VK_REMAINING_ARRAY_LAYERS ? image_state->createInfo.arrayLayers
```
Comment (jeremyg-lunarg) [inline layers/image_state.cpp:462]: I suspect you need to handle the VK_REMAINING_ARRAY_LAYERS case differently.  If IsDepthSliced() == true, I think you want to return the extent.depth from the image create info.

Comment (jeremyg-lunarg) [reply layers/image_state.cpp:462]: and if I'm finally understanding the problem correctly, GetImageLayerCount() might not be the best name. Maybe GetAttachmentLayerCount() since these weird image views can only be used as attachments and that's where you want to use this layer count rather than what is in normalized_subresource_range. Or at the very least add a comment explaining when to use this method.

Comment (ziga-lunarg) [reply layers/image_state.cpp]: You are right, added the test for that.
