### PR TITLE
layers: CommandBufferSingleSubmitViolation cleanup

### LINKED ISSUE #6109: CommandBufferSingleSubmitViolation cleanup
This one currently prints like

```
UNASSIGNED-CoreValidation-DrawState-CommandBufferSingleSubmitViolation(ERROR / SPEC): msgNum: -329268476 - Validation Error: [ UNASSIGNED-CoreValidation-DrawState-CommandBufferSingleSubmitViolation ] Object 0: handle = 0x26a1e60, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xec5fc304 | VkCommandBuffer 0x26a1e60[] was begun w/ VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT set, but has been submitted 0x2times
```

There's some missing whitespace, but also printing the number of times a cmdbuf has been submitted in hex is not ideal--anything of this sort should always print in decimal.

### PR DESCRIPTION
**Pull request by juan-lunarg**
closes #6109

Now the error messages reads like this:

> Validation Error: [ UNASSIGNED-CoreValidation-DrawState-CommandBufferSingleSubmitViolation ] Object 0: handle = 0x7ba00000c000, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xec5fc304 | VkCommandBuffer 0x7ba00000c000[] recorded with VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT has been submitted 2 times.

### CODE REVIEW

File: layers/core_checks/cc_queue.cpp [hunk 1]
```diff
@@ -472,17 +472,19 @@ bool CoreChecks::ValidateQueueFamilyIndices(const Location &loc, const CMD_BUFFE
...
-    if ((cb_state.beginInfo.flags & VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT) &&
-        (cb_state.submitCount + current_submit_count > 1)) {
+    if (const uint32_t submissions = cb_state.submitCount + current_submit_count;
+        (cb_state.beginInfo.flags & VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT) && (submissions > 1)) {
         skip |= LogError(cb_state.commandBuffer(), kVUID_Core_DrawState_CommandBufferSingleSubmitViolation,
-                         "%s was begun w/ VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT set, but has been submitted 0x%" PRIxLEAST64
-                         "times.",
-                         report_data->FormatHandle(cb_state.commandBuffer()).c_str(), cb_state.submitCount + current_submit_count);
+                         "%s recorded with VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT has been submitted %" PRIu32 " times.",
+                         report_data->FormatHandle(cb_state.commandBuffer()).c_str(), submissions);
```
Comment (juan-lunarg) [inline layers/core_checks/cc_queue.cpp:487]: - Print as decimal
- Space as needed
- Succinct error message

File: layers/core_checks/cc_queue.cpp [hunk 2]
```diff
@@ -472,17 +472,19 @@ bool CoreChecks::ValidateQueueFamilyIndices(const Location &loc, const CMD_BUFFE
     return skip;
 }
 
-bool CoreChecks::ValidateCommandBufferState(const CMD_BUFFER_STATE &cb_state, const char *call_source, int current_submit_count,
-                                            const char *vu_id) const {
+bool CoreChecks::ValidateCommandBufferState(const CMD_BUFFER_STATE &cb_state, const char *call_source,
+                                            uint32_t current_submit_count, const char *vu_id) const {
```
Comment (juan-lunarg) [inline layers/core_checks/cc_queue.cpp:476]: Doesn't make sense for submission count to use a signed integer. It should be unsigned.

uint32_t seems good enough.

File: tests/unit/command.cpp
Comment (juan-lunarg) [inline tests/unit/command.cpp:1]: Using the unassigned VUID name instead of the error message.

Make it easier to search for corresponding tests.
UNASSIGNED-CoreValidation-DrawState-CommandBufferSingleSubmitViolation

**Review by jeremyg-lunarg — APPROVED** [review]
LGTM
