### PR TITLE
Move swapchain image state setup to ValidationStateTracker 

### LINKED ISSUE #1312: Validation layer crashes in ValidationStateTracker::AddCommandBufferBindingImage when calling vkCmdCopyImage and dstImage is a swapchain image
The parameter `IMAGE_STATE *image_state` is nullptr - is there no recorded image state for swap chain images? I assume this will affect any of the functions in `state_tracker.cpp` that accept an image that might have been obtained from a swap chain.

Some extra details:

- SDK version 1.1.121
- Occurs on both MacOS (MoltenVK) and Windows
- Only occurs when enabling `VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT`

### PR DESCRIPTION
**Pull request by jzulauf-lunarg**
Two changes: 

 1 Refactor PostCallRecordGetSwapchainImagesKHR s.t. the common state tracking is in the ValidationStateTracker.
2 Move VST function into state_tracker.cpp  

Fixes #1312 , which broke BestPractices, but all VST derived classes (except CoreChecks) would find the same issue.

### CODE REVIEW

File: layers/core_validation.cpp [hunk 1]
```diff
@@ -9625,71 +9625,35 @@ bool CoreChecks::PreCallValidateGetSwapchainImagesKHR(VkDevice device, VkSwapcha
 
 void CoreChecks::PostCallRecordGetSwapchainImagesKHR(VkDevice device, VkSwapchainKHR swapchain, uint32_t *pSwapchainImageCount,
                                                      VkImage *pSwapchainImages, VkResult result) {
-    if ((result != VK_SUCCESS) && (result != VK_INCOMPLETE)) return;
-    auto swapchain_state = GetSwapchainState(swapchain);
+    // Usually we'd call the StateTracker first, but
+    //     a) none of the new state needed below is from the StateTracker
+    //     b) StateTracker *will* update swapchain_state->images which we use to guard against double initialization
+    // so we'll do it in the opposite ordre.  CoreChecks then StateTracker
```
Comment (mark-lunarg) [inline layers/core_validation.cpp]: Using the French again, huh?

Comment (jzulauf-lunarg) [reply layers/core_validation.cpp]: Oui?
