### PR TITLE
layers: Move SwapchainInvalidCount to BP

### LINKED ISSUE #2841: Unexpected validation error regarding swapchain image count
**Describe the Issue**
There is a set of CTS tests called "dEQP-VK.wsi.*.swapchain.get_images.count" (e.g. dEQP-VK.wsi.xlib.swapchain.get_images.count) that call vkGetSwapchainImagesKHR() with a pSwapchainImageCount pointing to an integer that is one more than what the initial count returns. That is:

* Call vkGetSwapchainImagesKHR passing a non-null pSwapchainImageCount and a null pSwapchainImages. This returns a count (let's suppose 3).
* Create an array of size 4 of VkImage, and call vkGetSwapchainImagesKHR passing a non-null pSwapchainImageCount containing 4 and a non-null pSwapchainImages pointing to the previous array.

The test then checks the second call overwrites the counter setting it to 3, the same number as in the first call. This is legal according to the spec and making sure the implementation behaves as expected is the purpose of the test.

> If pSwapchainImages is NULL, then the number of presentable images for swapchain is returned in pSwapchainImageCount. Otherwise, pSwapchainImageCount must point to a variable set by the user to the number of elements in the pSwapchainImages array, and on return the variable is overwritten with the number of structures actually written to pSwapchainImages.

However, when validation is enabled the test fails with the following validation error:

```
ERROR: Validation Error: [ UNASSIGNED-CoreValidation-SwapchainInvalidCount ] Object 0: handle = 0x8c96500, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x1a620b0e | vkGetSwapchainImagesKHR() called with non-NULL pSwapchainImages, and with pSwapchainImageCount set to a value (4) that is greater than the value (3) that was returned when pSwapchainImages was NULL. (code 0x00000000 from Validation at Device:1a620b0e)
```

The message is useful but, since the app behavior is perfectly legal, I don't think it should be a validation error. A warning perhaps.

**Valid Usage ID**
UNASSIGNED-CoreValidation-SwapchainInvalidCount

**Environment:**
 - OS: Fedora 34
 - GPU: Intel Corporation UHD Graphics 620
 - SDK or header version if building from repo: git master (8a22bcf6bf741e5fa9d49a50629a66d9e57b0620).
 - Options enabled (synchronization, best practices, etc.): Standard options.

**Additional context**

### PR DESCRIPTION
**Pull request by ncesario-lunarg**
Closes #2841.

### CODE REVIEW

File: layers/core_validation_error_enums.h [hunk 1]
```diff
@@ -207,7 +207,6 @@ static const char DECORATE_UNUSED *kVUID_Core_DevLimit_MustQueryCount = "UNASSIG
 //static const char DECORATE_UNUSED *kVUID_Core_DevLimit_InvalidPhysicalDevice = "UNASSIGNED-CoreValidation-DevLimit-InvalidPhysicalDevice";
 
 // static const char DECORATE_UNUSED *kVUID_Core_Swapchain_GetSupportedDisplaysWithoutQuery = "UNASSIGNED-CoreValidation-Swapchain-GetSupportedDisplaysWithoutQuery";
-static const char DECORATE_UNUSED *kVUID_Core_Swapchain_InvalidCount = "UNASSIGNED-CoreValidation-SwapchainInvalidCount";
```
Comment (mark-lunarg) [inline layers/core_validation_error_enums.h:210]: This is one place where we've been leaving dead code!  We try to avoid deleting any old VUIDs from these files for the sake of traceability, so please just comment this puppy out, IYWM.  You should be able to see all the old ones commented below, and you may event want to move this down into that section. Yet more tribal knowledge...

Comment (ncesario-lunarg) [reply layers/core_validation_error_enums.h:210]: Yep, I know better, too! Just completely forgot (as I often do). Will update accordingly.

**Comment by ncesario-lunarg** [comment]
@mikes-lunarg @mark-lunarg Could `best_practices_error_enums.h` be added to [vk_validation_stats.py](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/93883725f2d9a764f65b286bd63b6de39adabcf7/scripts/vk_validation_stats.py#L75)? I can get around the [error](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2844/checks?check_run_id=2696542767#step:5:990) by copy/pasting the unassigned VUID string into the test, but I'd rather use the string constant if possible.

**Comment by mikes-lunarg** [comment]
> @mikes-lunarg @mark-lunarg Could `best_practices_error_enums.h` be added to [vk_validation_stats.py](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/93883725f2d9a764f65b286bd63b6de39adabcf7/scripts/vk_validation_stats.py#L75)? I can get around the [error](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2844/checks?check_run_id=2696542767#step:5:990) by copy/pasting the unassigned VUID string into the test, but I'd rather use the string constant if possible.

You can add `'layers/best_practices_error_enums.h'` to `unassigned_vuid_files` to fix it, ie:

```
unassigned_vuid_files = [common_codegen.repo_relative(path) for path in [
    'layers/best_practices_error_enums.h',
    'layers/stateless_validation.h',
    'layers/core_validation_error_enums.h',
    'layers/object_lifetime_validation.h'
]]
```

**Comment by ncesario-lunarg** [comment]
:+1: thanks Mike!

**Review by Tony-LunarG — APPROVED** [review]
LGTM
