### PR TITLE
Fix log message for barrier stage mask

### LINKED ISSUE #6560: Possible false positive for UNASSIGNED-CoreChecks-unhandled-bad-access-flags
**Environment:**
 - OS: Windows 10
 - GPU and driver version: NVIDIA RTX 2070 super on driver 537.42
 - SDK or header version if building from repo: 1.3.261.1
 - Options enabled (synchronization, best practices, etc.): none

**Describe the Issue**

This validation error is triggered when I insert a memory barrier which has srcAccessMask = eAccelerationStructureReadKHR | eAccelerationStructureWriteKHR (6291456) and reports that I am using pipeline stages instead.

Validation Error: [ UNASSIGNED-CoreChecks-unhandled-bad-access-flags ] Object 0: handle = 0x1f6901414b0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xbbe6b7b8 | vkCmdPipelineBarrier(): INVALID_EMPTYpMemoryBarriers[2].srcAccessMask contains pipeline stages VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT|VK_PIPELINE_STAGE_VERTEX_SHADER_BIT|VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT|VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT|VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT|VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT|VK_PIPELINE_STAGE_TRANSFER_BIT|VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR.

**Expected behavior**

I expected to not see such an error.

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #6560

### CODE REVIEW

File: layers/core_checks/cc_synchronization.cpp [hunk 1]
```diff
@@ -957,7 +957,7 @@ bool CoreChecks::ValidateAccessMask(const LogObjectList &objlist, const Location
         if (stage_mask & illegal_pipeline_stages) {
             // Select right vuid based on enabled extensions
             const auto &vuid = sync_vuid_maps::GetAccessMaskRayQueryVUIDSelector(access_mask_loc, device_extensions);
-            skip |= LogError(vuid, objlist, access_mask_loc, "contains pipeline stages %s.",
+            skip |= LogError(objlist, vuid, "srcStageMask contains pipeline stages %s.",
```
Comment (artem-lunarg) [inline layers/core_checks/cc_synchronization.cpp:960]: `ValidateAccessMask` is used to validate both `srcAccessMask` and `dstAccessMask`. We might need additional `Location` parameter to pass stage mask location.

Comment (ziga-lunarg) [reply layers/core_checks/cc_synchronization.cpp:960]: Good catch

**Review by artem-lunarg — APPROVED** [review]
