### PR TITLE
Fix validating shaders struct interface

### LINKED ISSUE #3279: CoreValidation-Shader-InterfaceTypeMismatch failures with structs
We're rolling in the latest validation layers for the ANGLE project.  A number of tests are triggering validation errors like the following:
> [ UNASSIGNED-CoreValidation-Shader-InterfaceTypeMismatch ] Validation Error: [ UNASSIGNED-CoreValidation-Shader-InterfaceTypeMismatch ] Object 0: handle = 0x470000000047, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0xb6cf33fe | Type mismatch on location 1.0: 'ptr to output struct of (vec4 of float32)' vs 'ptr to input struct of (vec4 of float32)'

From the output, it looks like the types match.

You can see the list of tests failing over here:
https://bugs.chromium.org/p/angleproject/issues/detail?id=6382

They are all struct related.  It might be that https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/8346fe841e59fce7f39f46cff81011be6d969933 does not handle structs correctly?

I can confirm that reverting that commit clears up the validation error.

@ziga-lunarg Would it be possible to revert this CL so we can continue to roll the validation layers?

If you need an example to work through, you can run ANGLE's end2end tests.  Let me know if you need help getting them running.  Example GLSL shader combination here:
https://source.chromium.org/chromium/chromium/src/+/main:third_party/angle/src/tests/gl_tests/GLSLTest.cpp;l=6292

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #3279

### CODE REVIEW

File: layers/shader_validation.cpp [hunk 1]
```diff
@@ -64,8 +64,14 @@ static bool BaseTypesMatch(SHADER_MODULE_STATE const *a, SHADER_MODULE_STATE con
...
 
-            for (unsigned i = 2; i < a_base_insn.len(); i++) {
-                if (!BaseTypesMatch(a, b, a->get_def(a_base_insn.word(i)), b->get_def(b_base_insn.word(i)))) {
+            for (uint32_t i = 2; i < a_base_insn.len(); i++) {
+                const auto &c_insn = a->get_def(a_base_insn.word(i));
+                const auto &d_insn = b->get_def(b_base_insn.word(i));
+                const uint32_t c_base_insn_id = a->GetBaseType(c_insn);
+                const uint32_t d_base_insn_id = b->GetBaseType(d_insn);
+                const auto &c_base_insn = a->get_def(c_base_insn_id);
+                const auto &d_base_insn = b->get_def(d_base_insn_id);
```
Comment (ncesario-lunarg) [inline layers/shader_validation.cpp:73]: It would be great if we could keep something closer to the original code for this loop, as this is not really clear (to me, at least) why this is necessary. Would it make sense to call `GetBaseType` on each `*insn` at the start of this function? That seems like it _might_ eliminate the need for some of this, but not 100% sure if that would work. e.g., the following seems to work for the test added in the PR (though, I don't know what the original issue is that this is solving):
```diff
diff --git a/layers/shader_validation.cpp b/layers/shader_validation.cpp
index 039c89485..5dcd03bf0 100644
--- a/layers/shader_validation.cpp
+++ b/layers/shader_validation.cpp
@@ -47,8 +47,20 @@ static shader_stage_attributes shader_stage_attribs[] = {
     {"fragment shader", false, false, VK_SHADER_STAGE_FRAGMENT_BIT},
 };
 
-static bool BaseTypesMatch(SHADER_MODULE_STATE const *a, SHADER_MODULE_STATE const *b, const spirv_inst_iter &a_base_insn,
-                           const spirv_inst_iter &b_base_insn) {
+static bool BaseTypesMatch(SHADER_MODULE_STATE const &a, SHADER_MODULE_STATE const &b, const spirv_inst_iter &a_insn, const spirv_inst_iter &b_insn) {
+    // Bail early if neither instruction can be reduced to a type
+    const auto a_base_insn_id = a.GetBaseType(a_insn);
+    if (!a_base_insn_id) {
+        return false;
+    }
+    const auto b_base_insn_id = b.GetBaseType(b_insn);
+    if (!b_base_insn_id) {
+        return false;
+    }
+
+    const auto& a_base_insn = a.get_def(a_base_insn_id);
+    const auto& b_base_insn = b.get_def(b_base_insn_id);
+
     const uint32_t a_opcode = a_base_insn.opcode();
     const uint32_t b_opcode = b_base_insn.opcode();
     if (a_opcode == b_opcode) {
@@ -64,8 +76,8 @@ static bool BaseTypesMatch(SHADER_MODULE_STATE const *a, SHADER_MODULE_STATE con
                 return false;  // Structs cannot match if member counts differ
             }
 
-            for (unsigned i = 2; i < a_base_insn.len(); i++) {
-                if (!BaseTypesMatch(a, b, a->get_def(a_base_insn.word(i)), b->get_def(b_base_insn.word(i)))) {
+            for (uint32_t i = 2; i < a_base_insn.len(); ++i) {
+                if (!BaseTypesMatch(a, b, a.get_def(a_base_insn.word(i)), b.get_def(b_base_insn.word(i)))) {
                     return false;
                 }
             }
@@ -79,12 +91,8 @@ static bool BaseTypesMatch(SHADER_MODULE_STATE const *a, SHADER_MODULE_STATE con
 static bool TypesMatch(SHADER_MODULE_STATE const *a, SHADER_MODULE_STATE const *b, unsigned a_type, unsigned b_type) {
     const auto &a_insn = a->get_def(a_type);
     const auto &b_insn = b->get_def(b_type);
-    const uint32_t a_base_insn_id = a->GetBaseType(a_insn);
-    const uint32_t b_base_insn_id = b->GetBaseType(b_insn);
-    const auto &a_base_insn = a->get_def(a_base_insn_id);
-    const auto &b_base_insn = b->get_def(b_base_insn_id);
 
-    return BaseTypesMatch(a, b, a_base_insn, b_base_insn);
+    return BaseTypesMatch(*a, *b, a_insn, b_insn);
 }
 
 static unsigned GetLocationsConsumedByFormat(VkFormat format) {
```

File: layers/shader_validation.cpp [hunk 2]
```diff
@@ -64,8 +64,14 @@ static bool BaseTypesMatch(SHADER_MODULE_STATE const *a, SHADER_MODULE_STATE con
                 return false;  // Structs cannot match if member counts differ
             }
 
-            for (unsigned i = 2; i < a_base_insn.len(); i++) {
-                if (!BaseTypesMatch(a, b, a->get_def(a_base_insn.word(i)), b->get_def(b_base_insn.word(i)))) {
```
[the remark this answers is not in the document]
Comment (ziga-lunarg) [reply layers/shader_validation.cpp:68]: The added positive tests is what this fixes, comparing structs. I must pass a base type into BaseTypesMatch, otherwise it will retrun false.

File: layers/shader_validation.cpp [hunk 3]
```diff
@@ -64,8 +70,10 @@ static bool BaseTypesMatch(SHADER_MODULE_STATE const *a, SHADER_MODULE_STATE con
...
+            for (uint32_t i = 2; i < a_base_insn.len(); i++) {
+                const auto &c_base_insn = GetBaseTypeIter(a, a_base_insn.word(i));
+                const auto &d_base_insn = GetBaseTypeIter(b, b_base_insn.word(i));
```
Comment (ncesario-lunarg) [inline layers/shader_validation.cpp:75]: I guess I'm still confused as to why this isn't called at the beginning of this function on each `spirv_inst_iter` parameter as that seems to be me more in line with what this function says it's doing?

**Review by ncesario-lunarg — APPROVED** [review]

**Comment by ziga-lunarg** [comment]
@sfricke-samsung Can you verify that the test `TestShaderInputAndOutputStructComponents` is valid? We are currently getting a crash inside the driver on S10.

**Review by sjfricke — APPROVED** [review]
