### PR TITLE
layers: Dynamic Rendering - Validate FS Outputs

### LINKED ISSUE #3554: Possibly wrong positive for fragment shader attachment writes with VK_KHR_dynamic_rendering
**Describe the Issue**
When using dynamic rendering instead of render passes, validation will report an error that an attachment in the fragment shader is written, that is not bound.

**Valid Usage ID**
WARNING: [101294395][UNASSIGNED-CoreValidation-Shader-OutputNotConsumed] : Validation Warning: [ UNASSIGNED-CoreValidation-Shader-OutputNotConsumed ] Object 0: handle = 0x9389c50000000061, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x609a13b | fragment shader writes to output location 0 with no matching attachment

**Environment:**
 - OS: Windows 10
 - GPU: NVIDIA RTX 2060
 - SDK or header version if building from repo: Vulkan header 1.2.199
 - Options enabled (synchronization, best practices, etc.): none

**Additional context**
The color attachment is definitely set by the app:

```cpp
VkRenderingAttachmentInfoKHR colorAttachment{};
colorAttachment.sType = VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO_KHR;
colorAttachment.imageView = swapChain.buffers[i].view;
colorAttachment.imageLayout = VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL_KHR;
colorAttachment.loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
colorAttachment.storeOp = VK_ATTACHMENT_STORE_OP_STORE;
colorAttachment.clearValue.color = { 0.0f,0.0f,0.0f,0.0f };

VkRenderingAttachmentInfoKHR depthStencilAttachment{};
depthStencilAttachment.sType = VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO_KHR;
depthStencilAttachment.imageView = depthStencil.view;
depthStencilAttachment.imageLayout = VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL_KHR;
depthStencilAttachment.loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
depthStencilAttachment.storeOp = VK_ATTACHMENT_STORE_OP_STORE;
depthStencilAttachment.clearValue.depthStencil = { 1.0f,  0 };

VkRenderingInfoKHR renderingInfo{};
renderingInfo.sType = VK_STRUCTURE_TYPE_RENDERING_INFO_KHR;
renderingInfo.renderArea = { 0, 0, width, height };
renderingInfo.layerCount = 1;
renderingInfo.colorAttachmentCount = 1;
renderingInfo.pColorAttachments = &colorAttachment;
renderingInfo.pDepthAttachment = &depthStencilAttachment;
renderingInfo.pStencilAttachment = &depthStencilAttachment;
```

The fragment shader is very basic, and only has one output:

```glsl
#version 450

layout (set = 1, binding = 0) uniform sampler2D samplerColor;

layout (location = 0) in vec2 inUV;

layout (location = 0) out vec4 outFragColor;

void main() 
{
	outFragColor = texture(samplerColor, inUV);
}
```

The very same shader in a normal render pass setup does not produce that error.

### PR DESCRIPTION
**Pull request by AaronHaganAMD**
Closes #3554 by adding a dynamic render path for FS ouput validation

### CODE REVIEW

File: layers/shader_validation.cpp [hunk 1]
```diff
@@ -196,6 +196,61 @@ bool CoreChecks::ValidateViAgainstVsInputs(VkPipelineVertexInputStateCreateInfo
...
+        location_map[location].output = &output_it.second;
+    }
+
+    const bool alpha_to_coverage_enabled = pipeline->create_info.graphics.pMultisampleState != NULL &&
+        pipeline->create_info.graphics.pMultisampleState->alphaToCoverageEnable == VK_TRUE;
+
+    for (uint32_t location = 0; location < pipeline->rp_state->dynamic_rendering_pipeline_create_info.colorAttachmentCount; ++location) {
+         const auto output = location_map[location].output;
+
+        if (!output && pipeline->attachments[location].colorWriteMask != 0) {
```
Comment (jeremyg-lunarg) [inline layers/shader_validation.cpp:221]: Looks like the VkPositiveLayerTest.CreateGraphicsPipelineDynamicRendering test is failing in the windows debug because of std::vector debug checks.  output is nullptr, location is 1, pipeline->attachments.size() is 1.

It is possible that the the test case has a problem,  I wrote it in a hurry. :) 

stack trace:
```
 	ucrtbased.dll!_invoke_watson(const wchar_t * expression, const wchar_t * function_name, const wchar_t * file_name, unsigned int line_number, unsigned __int64 reserved) Line 224	C++
 	ucrtbased.dll!_invalid_parameter(const wchar_t * expression, const wchar_t * function_name, const wchar_t * file_name, unsigned int line_number, unsigned __int64 reserved) Line 113	C++
 	VkLayer_khronos_validation.dll!std::vector<VkPipelineColorBlendAttachmentState,std::allocator<VkPipelineColorBlendAttachmentState>>::operator[](const unsigned __int64 _Pos) Line 1575	C++
>	VkLayer_khronos_validation.dll!CoreChecks::ValidateFsOutputsAgainstDynamicRenderingRenderPass(const SHADER_MODULE_STATE * fs, spirv_inst_iter entrypoint, const PIPELINE_STATE * pipeline) Line 221	C++
 	VkLayer_khronos_validation.dll!CoreChecks::ValidateGraphicsPipelineShaderState(const PIPELINE_STATE * pipeline) Line 2836	C++
 	VkLayer_khronos_validation.dll!CoreChecks::ValidatePipelineUnlocked(const PIPELINE_STATE * pPipeline, unsigned int pipelineIndex) Line 1677	C++
 	VkLayer_khronos_validation.dll!CoreChecks::PreCallValidateCreateGraphicsPipelines(VkDevice_T * device, VkPipelineCache_T * pipelineCache, unsigned int count, const VkGraphicsPipelineCreateInfo * pCreateInfos, const VkAllocationCallbacks * pAllocator, VkPipeline_T * * pPipelines, void * cgpl_state_data) Line 5629	C++
 	VkLayer_khronos_validation.dll!vulkan_layer_chassis::CreateGraphicsPipelines(VkDevice_T * device, VkPipelineCache_T * pipelineCache, unsigned int createInfoCount, const VkGraphicsPipelineCreateInfo * pCreateInfos, const VkAllocationCallbacks * pAllocator, VkPipeline_T * * pPipelines) Line 572	C++
 	vk_layer_validation_tests.exe!vk_testing::Pipeline::init_try(const vk_testing::Device & dev, const VkGraphicsPipelineCreateInfo & info) Line 763	C++
 	vk_layer_validation_tests.exe!VkPipelineObj::CreateVKPipeline(VkPipelineLayout_T * layout, VkRenderPass_T * render_pass, VkGraphicsPipelineCreateInfo * gp_ci) Line 2289	C++
 	vk_layer_validation_tests.exe!VkPositiveLayerTest_CreateGraphicsPipelineDynamicRendering_Test::TestBody() Line 6454	C++
 	gtestd.dll!testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test,void>(testing::Test * object, void(testing::Test::*)() method, const char * location) Line 2428	C++
 	gtestd.dll!testing::internal::HandleExceptionsInMethodIfSupported<testing::Test,void>(testing::Test * object, void(testing::Test::*)() method, const char * location) Line 2479	C++
 	gtestd.dll!testing::Test::Run() Line 2524	C++
 	gtestd.dll!testing::TestInfo::Run() Line 2697	C++
 	gtestd.dll!testing::TestCase::Run() Line 2812	C++
 	gtestd.dll!testing::internal::UnitTestImpl::RunAllTests() Line 5178	C++
 	gtestd.dll!testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl,bool>(testing::internal::UnitTestImpl * object, bool(testing::internal::UnitTestImpl::*)() method, const char * location) Line 2428	C++
 	gtestd.dll!testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl,bool>(testing::internal::UnitTestImpl * object, bool(testing::internal::UnitTestImpl::*)() method, const char * location) Line 2479	C++
 	gtestd.dll!testing::UnitTest::Run() Line 4786	C++
 	vk_layer_validation_tests.exe!RUN_ALL_TESTS() Line 2342	C++
 	vk_layer_validation_tests.exe!main(int argc, char * * argv) Line 3701	C++
 	[External Code]	
```

Comment (AaronHaganAMD) [reply layers/shader_validation.cpp:221]: Yes.. I believe VkPipelineRenderingCreateInfoKHR should be updated for only 1 attachment.

**Review by jeremyg-lunarg — APPROVED** [review]
LGTM
