### PR TITLE
Fix binding index bug for dynamic offsets

### LINKED ISSUE #2600: CTS crashing due to #2540
CTS is crashing due to #2540.

From @Tony-LunarG: the issue can be reproduced with `dEQP-VK.binding_model.shader_access.primary_cmd_buf.uniform_buffer_dynamic.no_access.multiple_discontiguous_descriptors.offset_view_zero_dynamic_nonzero`. At https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/476f5e2a9f6525143ee9cc48f4c4c8108d00f22a/layers/core_validation.cpp#L6972 the returned `descriptor` is null.

@sfricke-samsung Let me know if there's a particular way you'd like to proceed with this. Thanks!

### PR DESCRIPTION
**Pull request by sfricke-samsung**
closes #2600 

So the CTS test had a descriptor layout with bindings `0` and `2` and the loop of the bindings when it was `1` 

```c++
// binding_idx == 1

// Returned binding index of 2
VkDescriptorSetLayoutBinding *binding = dsl->GetDescriptorSetLayoutBindingPtrFromIndex(binding_idx);

// Was looking for binding index of 1
Descriptor *descriptor = descriptor_set->GetDescriptorFromBinding(binding_idx);
```

So the simple fix was fixing some naming so that the `binding_index` is the actual binding index value and not the loop of the **number** of bindings

----

Second commit is various tests and small tweaks that are general improvements and replicated the same error the CTS tests had

### CODE REVIEW

**Comment by ncesario-lunarg** [comment]
Running through [internal CI](http://erusea:4040/8455).

File: layers/core_validation.cpp [hunk 1]
```diff
@@ -6941,8 +6941,10 @@ bool CoreChecks::PreCallValidateCmdBindDescriptorSets(VkCommandBuffer commandBuf
                     const auto dsl = descriptor_set->GetLayout();
                     const auto binding_count = dsl->GetBindingCount();
                     const auto &limits = phys_dev_props.limits;
-                    for (uint32_t binding_idx = 0; binding_idx < binding_count; binding_idx++) {
-                        const auto *binding = dsl->GetDescriptorSetLayoutBindingPtrFromIndex(binding_idx);
+                    for (uint32_t i = 0; i < binding_count; i++) {
+                        const auto *binding = dsl->GetDescriptorSetLayoutBindingPtrFromIndex(i);
+                        // If a descriptor set has only binding 0 and 2 the binding_index will be 0 and 2
+                        const uint32_t binding_index = binding->binding;
```
Comment (ncesario-lunarg) [inline layers/core_validation.cpp:6947]: Nice!

**Review by ncesario-lunarg — APPROVED** [review]
LGTM! Will merge once internal CI finishes.

Thanks for the quick fix @sfricke-samsung!

**Comment by Tony-LunarG** [comment]
This fixes the problems I was seeing yesterday
