### PR TITLE
layers: Dynamic Rendering render_area fixes

### LINKED ISSUE #3614: Unexpected validation error in dynamic rendering CTS tests
**Describe the Issue**
A few CTS tests related to dynamic rendering are reporting `VUID-vkCmdClearAttachments-pRects-00016` incorrectly, if I'm not mistaken. These tests begin rendering using `vkCmdBeginRenderingKHR` and a `VkRenderingInfoKHR` structure in which they indicate the render area. Later, they call `vkCmdClearAttachments` with the same rectangle and the layers report the error I mentioned.

```
VUID-vkCmdClearAttachments-pRects-00016(ERROR / SPEC): msgNum: -1720222274 - Validation Error: [ VUID-vkCmdClearAttachments-pRects-00016 ] Object 0: handle = 0x10459d10, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x99777dbe | vkCmdClearAttachments(): The area defined by pRects[0] is not contained in the area of the current render pass instance. The Vulkan spec states: The rectangular region specified by each element of pRects must be contained within the render area of the current render pass instance (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdClearAttachments-pRects-00016)
```

One example of such a test is `dEQP-VK.dynamic_rendering.suballocation.load_store_op_none.color_load_op_none_store_op_store`.

**Valid Usage ID**
VUID-vkCmdClearAttachments-pRects-00016

**Environment:**
 - OS: Linux
 - GPU: RTX 2060
 - SDK or header version if building from repo: 0965e77eb083b8b4becf01cd8aa39284e56e6338
 - Options enabled (synchronization, best practices, etc.): default

**Additional context**

### PR DESCRIPTION
**Pull request by AaronHaganAMD**
Uses VkRenderingInfoKHR->render_area if dynamic area is active.

Fixes #3614

### CODE REVIEW

**Review by ncesario-lunarg — APPROVED** [review]
LGTM, thanks!

Are there other areas where this might be a problem? e.g., https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/a44b81881710a6ba2fdfd29fb24f4aee3921eff9/layers/best_practices_utils.cpp#L2959 or https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/a44b81881710a6ba2fdfd29fb24f4aee3921eff9/layers/synchronization_validation.cpp#L1898?

File: tests/positive/dynamic_rendering.cpp [hunk 1]
```diff
@@ -122,3 +122,65 @@ TEST_F(VkPositiveLayerTest, DynamicRenderingDraw) {
     m_errorMonitor->VerifyNotFound();
 }
 
+TEST_F(VkPositiveLayerTest, CmdClearAttachmentTestsDynamicRendering) {
+    TEST_DESCRIPTION("Various tests for validating usage of vkCmdClearAttachments with Dynamic Rendering");
```
Comment (ncesario-lunarg) [inline tests/positive/dynamic_rendering.cpp:126]: Sorry if I missed this before, but positive tests currently need to start with `m_errorMonitor->ExpectSuccess()` and end with `m_errorMonitor->VerifyNotFound()`. This will not be necessary with an upcoming change, but is required for now.

**Review by ncesario-lunarg — CHANGES_REQUESTED** [review]
One necessary change for the positive test, but everything else LGTM!

File: tests/positive/dynamic_rendering.cpp (hunk 1 above)
Comment (AaronHaganAMD) [reply tests/positive/dynamic_rendering.cpp:126]: Added the ExpectSuccess and VerifyNotFound

**Review by ncesario-lunarg — APPROVED** [review]

**Comment by ncesario-lunarg** [comment]
Looks like these files now need to get their copyrights updated (happy new year!).

We are also seeing a crash on nvidia hardware in test `VkPositiveLayerTest.CmdClearAttachmentTestsDynamicRendering`. I can try to dig into the root cause later today.
