### PR TITLE
Fix validating shader inputs

### LINKED ISSUE #6354: broken 64bit vertex attrib validation
With latest zink from mesa main, I get spurious 64bit validation errors like:

```
VUID-vkCmdDrawMultiEXT-format-08937(ERROR / SPEC): msgNum: -1392102134 - Validation Error: [ VUID-vkCmdDrawMultiEXT-format-08937 ] Object 0: handle = 0x56c9bd0000000040, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0xad06350a | vkCmdDrawMultiEXT():  Attribute at location 1 is a 32-bit format (VK_FORMAT_R32G32B32A32_UINT) but vertex shader input is 64-bit type (oddtype) The Vulkan spec states: If there is a shader object bound to a graphics stage or the currently bound graphics pipeline was created with the VK_DYNAMIC_STATE_VERTEX_INPUT_EXT dynamic state enabled, and the scalar width associated with a Location decorated Input variable in the Vertex {ExecutionModel} OpEntryPoint is 64-bit, then the corresponding VkVertexInputAttributeDescription2EXT::format must have a 64-bit component (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdDrawMultiEXT-format-08937)
```

The shader in question from `KHR-Single-GL46.enhanced_layouts.varying_array_components`:

```
; SPIR-V
; Version: 1.6
; Generator: Khronos; 0
; Bound: 147
; Schema: 0
               OpCapability Int64
               OpCapability VulkanMemoryModel
               OpCapability VulkanMemoryModelDeviceScope
               OpCapability Float64
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical Vulkan
               OpEntryPoint Vertex %main "main" %gfx_pushconst %in_vs_g64vec2_l0_c0 %in_vs_g64vec2_l0_c0_0 %in_vs_g64vec2_l0_c0_1 %in_vs_g64vec2_l0_c0_2 %in_vs_g64vec2_l12_c0 %in_vs_g64vec2_l12_c0_0 %in_vs_g64vec2_l12_c0_1 %in_vs_g64vec2_l12_c0_2 %vs_tcs_result %vs_tcs_g64vec2_l0_c0 %vs_tcs_g64vec2_l0_c0_0 %vs_tcs_g64vec2_l0_c0_1 %vs_tcs_g64vec2_l0_c0_2 %vs_tcs_g64vec2_l24_c0 %vs_tcs_g64vec2_l24_c0_0 %vs_tcs_g64vec2_l24_c0_1 %vs_tcs_g64vec2_l24_c0_2
               OpSource Unknown 0
               OpName %main "main"
               OpName %gfx_pushconst "gfx_pushconst"
               OpName %in_vs_g64vec2_l0_c0 "in_vs_g64vec2_l0_c0"
               OpName %in_vs_g64vec2_l0_c0_0 "in_vs_g64vec2_l0_c0"
               OpName %in_vs_g64vec2_l0_c0_1 "in_vs_g64vec2_l0_c0"
               OpName %in_vs_g64vec2_l0_c0_2 "in_vs_g64vec2_l0_c0"
               OpName %in_vs_g64vec2_l12_c0 "in_vs_g64vec2_l12_c0"
               OpName %in_vs_g64vec2_l12_c0_0 "in_vs_g64vec2_l12_c0"
               OpName %in_vs_g64vec2_l12_c0_1 "in_vs_g64vec2_l12_c0"
               OpName %in_vs_g64vec2_l12_c0_2 "in_vs_g64vec2_l12_c0"
               OpName %vs_tcs_result "vs_tcs_result"
               OpName %vs_tcs_g64vec2_l0_c0 "vs_tcs_g64vec2_l0_c0"
               OpName %vs_tcs_g64vec2_l0_c0_0 "vs_tcs_g64vec2_l0_c0"
               OpName %vs_tcs_g64vec2_l0_c0_1 "vs_tcs_g64vec2_l0_c0"
               OpName %vs_tcs_g64vec2_l0_c0_2 "vs_tcs_g64vec2_l0_c0"
               OpName %vs_tcs_g64vec2_l24_c0 "vs_tcs_g64vec2_l24_c0"
               OpName %vs_tcs_g64vec2_l24_c0_0 "vs_tcs_g64vec2_l24_c0"
               OpName %vs_tcs_g64vec2_l24_c0_1 "vs_tcs_g64vec2_l24_c0"
               OpName %vs_tcs_g64vec2_l24_c0_2 "vs_tcs_g64vec2_l24_c0"
               OpDecorate %_arr_uint_uint_1 ArrayStride 4
               OpDecorate %_arr_uint_uint_2 ArrayStride 4
               OpDecorate %_arr_uint_uint_4 ArrayStride 4
               OpMemberDecorate %_struct_12 0 Offset 0
               OpMemberDecorate %_struct_12 1 Offset 4
               OpMemberDecorate %_struct_12 2 Offset 8
               OpMemberDecorate %_struct_12 3 Offset 12
               OpMemberDecorate %_struct_12 4 Offset 20
               OpMemberDecorate %_struct_12 5 Offset 36
               OpMemberDecorate %_struct_12 6 Offset 40
               OpMemberDecorate %_struct_12 7 Offset 48
               OpDecorate %_struct_12 Block
               OpDecorate %in_vs_g64vec2_l0_c0 Location 0
               OpDecorate %in_vs_g64vec2_l0_c0_0 Location 1
               OpDecorate %in_vs_g64vec2_l0_c0_1 Location 2
               OpDecorate %in_vs_g64vec2_l0_c0_2 Location 3
               OpDecorate %in_vs_g64vec2_l12_c0 Location 4
               OpDecorate %in_vs_g64vec2_l12_c0_0 Location 5
               OpDecorate %in_vs_g64vec2_l12_c0_1 Location 6
               OpDecorate %in_vs_g64vec2_l12_c0_2 Location 7
               OpDecorate %vs_tcs_result Location 0
               OpDecorate %vs_tcs_g64vec2_l0_c0 Location 1
               OpDecorate %vs_tcs_g64vec2_l0_c0_0 Location 2
               OpDecorate %vs_tcs_g64vec2_l0_c0_1 Location 3
               OpDecorate %vs_tcs_g64vec2_l0_c0_2 Location 4
               OpDecorate %vs_tcs_g64vec2_l24_c0 Location 5
               OpDecorate %vs_tcs_g64vec2_l24_c0_0 Location 6
               OpDecorate %vs_tcs_g64vec2_l24_c0_1 Location 7
               OpDecorate %vs_tcs_g64vec2_l24_c0_2 Location 8
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
       %uint = OpTypeInt 32 0
     %uint_1 = OpConstant %uint 1
%_arr_uint_uint_1 = OpTypeArray %uint %uint_1
     %uint_2 = OpConstant %uint 2
%_arr_uint_uint_2 = OpTypeArray %uint %uint_2
     %uint_4 = OpConstant %uint 4
%_arr_uint_uint_4 = OpTypeArray %uint %uint_4
 %_struct_12 = OpTypeStruct %_arr_uint_uint_1 %_arr_uint_uint_1 %_arr_uint_uint_1 %_arr_uint_uint_2 %_arr_uint_uint_4 %_arr_uint_uint_1 %_arr_uint_uint_2 %_arr_uint_uint_1
%_ptr_PushConstant__struct_12 = OpTypePointer PushConstant %_struct_12
%gfx_pushconst = OpVariable %_ptr_PushConstant__struct_12 PushConstant
     %v4uint = OpTypeVector %uint 4
%_ptr_Input_v4uint = OpTypePointer Input %v4uint
%in_vs_g64vec2_l0_c0 = OpVariable %_ptr_Input_v4uint Input
%in_vs_g64vec2_l0_c0_0 = OpVariable %_ptr_Input_v4uint Input
%in_vs_g64vec2_l0_c0_1 = OpVariable %_ptr_Input_v4uint Input
%in_vs_g64vec2_l0_c0_2 = OpVariable %_ptr_Input_v4uint Input
%in_vs_g64vec2_l12_c0 = OpVariable %_ptr_Input_v4uint Input
%in_vs_g64vec2_l12_c0_0 = OpVariable %_ptr_Input_v4uint Input
%in_vs_g64vec2_l12_c0_1 = OpVariable %_ptr_Input_v4uint Input
%in_vs_g64vec2_l12_c0_2 = OpVariable %_ptr_Input_v4uint Input
%_ptr_Output_uint = OpTypePointer Output %uint
%vs_tcs_result = OpVariable %_ptr_Output_uint Output
     %double = OpTypeFloat 64
   %v2double = OpTypeVector %double 2
%_ptr_Output_v2double = OpTypePointer Output %v2double
%vs_tcs_g64vec2_l0_c0 = OpVariable %_ptr_Output_v2double Output
%vs_tcs_g64vec2_l0_c0_0 = OpVariable %_ptr_Output_v2double Output
%vs_tcs_g64vec2_l0_c0_1 = OpVariable %_ptr_Output_v2double Output
%vs_tcs_g64vec2_l0_c0_2 = OpVariable %_ptr_Output_v2double Output
%vs_tcs_g64vec2_l24_c0 = OpVariable %_ptr_Output_v2double Output
%vs_tcs_g64vec2_l24_c0_0 = OpVariable %_ptr_Output_v2double Output
%vs_tcs_g64vec2_l24_c0_1 = OpVariable %_ptr_Output_v2double Output
%vs_tcs_g64vec2_l24_c0_2 = OpVariable %_ptr_Output_v2double Output
     %v2uint = OpTypeVector %uint 2
      %ulong = OpTypeInt 64 0
%double_n0_625 = OpConstant %double -0.625
%double_n0_5 = OpConstant %double -0.5
         %92 = OpConstantComposite %v2double %double_n0_625 %double_n0_5
       %bool = OpTypeBool
        %int = OpTypeInt 32 1
      %int_0 = OpConstant %int 0
      %int_1 = OpConstant %int 1
       %main = OpFunction %void None %3
         %39 = OpLabel
               OpBranch %38
         %38 = OpLabel
         %40 = OpLoad %v4uint %in_vs_g64vec2_l0_c0
         %42 = OpVectorShuffle %v2uint %40 %40 0 1
         %44 = OpExtInst %double %1 PackDouble2x32 %42
         %45 = OpVectorShuffle %v2uint %40 %40 2 3
         %46 = OpExtInst %double %1 PackDouble2x32 %45
         %47 = OpCompositeConstruct %v2double %44 %46
         %48 = OpLoad %v4uint %in_vs_g64vec2_l0_c0_0
         %49 = OpVectorShuffle %v2uint %48 %48 0 1
         %50 = OpExtInst %double %1 PackDouble2x32 %49
         %51 = OpVectorShuffle %v2uint %48 %48 2 3
         %52 = OpExtInst %double %1 PackDouble2x32 %51
         %53 = OpCompositeConstruct %v2double %50 %52
         %54 = OpLoad %v4uint %in_vs_g64vec2_l0_c0_1
         %55 = OpVectorShuffle %v2uint %54 %54 0 1
         %56 = OpExtInst %double %1 PackDouble2x32 %55
         %57 = OpVectorShuffle %v2uint %54 %54 2 3
         %58 = OpExtInst %double %1 PackDouble2x32 %57
         %59 = OpCompositeConstruct %v2double %56 %58
         %60 = OpLoad %v4uint %in_vs_g64vec2_l0_c0_2
         %61 = OpVectorShuffle %v2uint %60 %60 0 1
         %62 = OpExtInst %double %1 PackDouble2x32 %61
         %63 = OpVectorShuffle %v2uint %60 %60 2 3
         %64 = OpExtInst %double %1 PackDouble2x32 %63
         %65 = OpCompositeConstruct %v2double %62 %64
         %66 = OpLoad %v4uint %in_vs_g64vec2_l12_c0
         %67 = OpVectorShuffle %v2uint %66 %66 0 1
         %68 = OpExtInst %double %1 PackDouble2x32 %67
         %69 = OpVectorShuffle %v2uint %66 %66 2 3
         %70 = OpExtInst %double %1 PackDouble2x32 %69
         %71 = OpCompositeConstruct %v2double %68 %70
         %72 = OpLoad %v4uint %in_vs_g64vec2_l12_c0_0
         %73 = OpVectorShuffle %v2uint %72 %72 0 1
         %74 = OpExtInst %double %1 PackDouble2x32 %73
         %75 = OpVectorShuffle %v2uint %72 %72 2 3
         %76 = OpExtInst %double %1 PackDouble2x32 %75
         %77 = OpCompositeConstruct %v2double %74 %76
         %78 = OpLoad %v4uint %in_vs_g64vec2_l12_c0_1
         %79 = OpVectorShuffle %v2uint %78 %78 0 1
         %80 = OpExtInst %double %1 PackDouble2x32 %79
         %81 = OpVectorShuffle %v2uint %78 %78 2 3
         %82 = OpExtInst %double %1 PackDouble2x32 %81
         %83 = OpCompositeConstruct %v2double %80 %82
         %84 = OpLoad %v4uint %in_vs_g64vec2_l12_c0_2
         %85 = OpVectorShuffle %v2uint %84 %84 0 1
         %86 = OpExtInst %double %1 PackDouble2x32 %85
         %87 = OpVectorShuffle %v2uint %84 %84 2 3
         %88 = OpExtInst %double %1 PackDouble2x32 %87
         %89 = OpCompositeConstruct %v2double %86 %88
         %93 = OpCompositeExtract %double %92 0
         %95 = OpFUnordNotEqual %bool %93 %44
         %96 = OpCompositeExtract %double %92 1
         %97 = OpFUnordNotEqual %bool %96 %46
         %98 = OpLogicalOr %bool %95 %97
         %99 = OpCompositeExtract %double %92 0
        %100 = OpFUnordNotEqual %bool %99 %50
        %101 = OpCompositeExtract %double %92 1
        %102 = OpFUnordNotEqual %bool %101 %52
        %103 = OpLogicalOr %bool %100 %102
        %104 = OpLogicalOr %bool %98 %103
        %105 = OpCompositeExtract %double %92 0
        %106 = OpFUnordNotEqual %bool %105 %56
        %107 = OpCompositeExtract %double %92 1
        %108 = OpFUnordNotEqual %bool %107 %58
        %109 = OpLogicalOr %bool %106 %108
        %110 = OpLogicalOr %bool %104 %109
        %111 = OpCompositeExtract %double %92 0
        %112 = OpFUnordNotEqual %bool %111 %62
        %113 = OpCompositeExtract %double %92 1
        %114 = OpFUnordNotEqual %bool %113 %64
        %115 = OpLogicalOr %bool %112 %114
        %116 = OpLogicalOr %bool %110 %115
        %117 = OpCompositeExtract %double %92 0
        %118 = OpFUnordNotEqual %bool %117 %68
        %119 = OpCompositeExtract %double %92 1
        %120 = OpFUnordNotEqual %bool %119 %70
        %121 = OpLogicalOr %bool %118 %120
        %122 = OpLogicalOr %bool %116 %121
        %123 = OpCompositeExtract %double %92 0
        %124 = OpFUnordNotEqual %bool %123 %74
        %125 = OpCompositeExtract %double %92 1
        %126 = OpFUnordNotEqual %bool %125 %76
        %127 = OpLogicalOr %bool %124 %126
        %128 = OpLogicalOr %bool %122 %127
        %129 = OpCompositeExtract %double %92 0
        %130 = OpFUnordNotEqual %bool %129 %80
        %131 = OpCompositeExtract %double %92 1
        %132 = OpFUnordNotEqual %bool %131 %82
        %133 = OpLogicalOr %bool %130 %132
        %134 = OpLogicalOr %bool %128 %133
        %135 = OpCompositeExtract %double %92 0
        %136 = OpFUnordNotEqual %bool %135 %86
        %137 = OpCompositeExtract %double %92 1
        %138 = OpFUnordNotEqual %bool %137 %88
        %139 = OpLogicalOr %bool %136 %138
        %140 = OpLogicalOr %bool %134 %139
        %141 = OpLogicalNot %bool %140
        %145 = OpSelect %int %141 %int_1 %int_0
        %146 = OpBitcast %uint %145
               OpStore %vs_tcs_result %146
               OpStore %vs_tcs_g64vec2_l0_c0 %47
               OpStore %vs_tcs_g64vec2_l0_c0_0 %53
               OpStore %vs_tcs_g64vec2_l0_c0_1 %59
               OpStore %vs_tcs_g64vec2_l0_c0_2 %65
               OpStore %vs_tcs_g64vec2_l24_c0 %71
               OpStore %vs_tcs_g64vec2_l24_c0_0 %77
               OpStore %vs_tcs_g64vec2_l24_c0_1 %83
               OpStore %vs_tcs_g64vec2_l24_c0_2 %89
               OpReturn
               OpFunctionEnd
```

There are no 64bit inputs.

Using VVL 05281f093453634fd107195712eab230b4353f56

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #6354

### CODE REVIEW

**Review by juan-lunarg — APPROVED** [review]

File: layers/core_checks/cc_cmd_buffer_dynamic.cpp [hunk 1]
```diff
@@ -270,10 +270,11 @@ bool CoreChecks::ValidateDrawDynamicState(const LAST_BOUND_STATE& last_bound_sta
     }
     if ((!pipeline_state || pipeline_state->IsDynamic(VK_DYNAMIC_STATE_VERTEX_INPUT_EXT)) && entrypoint) {
         for (uint32_t i = 0; i < cb_state.dynamic_state_value.vertex_attribute_descriptions.size(); ++i) {
-            const auto &description = cb_state.dynamic_state_value.vertex_attribute_descriptions[i];
+            const auto& description = cb_state.dynamic_state_value.vertex_attribute_descriptions[i];
```
Comment (spencer-lunarg) [inline layers/core_checks/cc_cmd_buffer_dynamic.cpp:273]: ok, are we using the same clang-format? I noticed this happened a lot in the shader_object PR, I curious why these things are getting touched

**Review by spencer-lunarg — APPROVED** [review]
