### PR TITLE
Unwrap generic object handles in Get/SetPrivateDataEXT calls

### LINKED ISSUE #2082: Validation Layers cause crash in vkSetPrivateDataEXT
Validation Layers Version: `1.2.146`

The Validation Layers seem to cause a crash in `vkSetPrivateDataEXT` with some objects. I was able to reproduce it on `VkSwapchainKHR` and `VkSampler`, `VkDevice` was fine. My guess would be that the layer wraps these object and doesn't unwrap them for `VK_EXT_private_data`.

Test to reproduce:
[private_data_test.c.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/5003951/private_data_test.c.txt)
It runs fine but crashes with `VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation`.
(Please don't mind the slightly messy code, I hacked my wine test to work standalone)

### PR DESCRIPTION
**Pull request by mark-lunarg**
Dispatcher codegen was unaware of these object handles and neglected to unwrap them, causing crashes when used with handle wrapping enabled.  Moved to manually generated and unwrapped the handles.  Also added a test.

Fixes #2082.

### CODE REVIEW

File: tests/vklayertests_others.cpp [hunk 1]
```diff
@@ -103,6 +103,81 @@ class DuplicateMsgLimit {
...
+    VkPrivateDataSlotCreateInfoEXT data_create_info;
+    data_create_info.sType = VK_STRUCTURE_TYPE_PRIVATE_DATA_SLOT_CREATE_INFO_EXT;
+    data_create_info.pNext = NULL;
+    data_create_info.flags = 0;
+    VkResult err = pfn_vkCreatePrivateDataSlotEXT(m_device->handle(), &data_create_info, NULL, &data_slot);
+    if (err != VK_SUCCESS) {
+        printf("%s Failed to create private data slot, VkResult %d.\n", kSkipPrefix, err);
+    }
+
+    VkSampler sampler;
```
Comment (Tony-LunarG) [inline tests/vklayertests_others.cpp:143]: Just a suggestion, but how about "VkSamplerCreateInfo sampler_info = SafeSaneSamplerCreateInfo();"

**Comment by DadSchoorse** [comment]
@mark-lunarg Unfortunately, while this solves the issue with wrapped handles, it now causes crashes with non wrapped handles, e.g. `VkDevice`.

**Comment by mark-lunarg** [comment]
@DadSchoorse, thanks so much for the feedback -- I basically cribbed your testcase and it never occurred to me to check dispatchable handles.  I'll address this today and get it in ASAP.
