### PR TITLE
Fix issue 3257,  GpuAV with unbound descriptor set

### LINKED ISSUE #3257: bound_descriptor_set was nullptr, bug inside GPUAV
**Describe the Issue**
After binding the Gfx pipeline, I bind a descriptor set at set = 1 ( set = 0 is not used ). After this I bind my index buffer and then I issue vkCmdDrawIndexedIndirectCount which goes all the way to GPUAV_RESTORABLE_PIPELINE_STATE -> Create() to throw an exception saying: bound_descriptor_set was nullptr. Yet nothing in my sequence of vkCmds is null state, so I'm guessing it must be smth inside the validation layer.

**Valid Usage ID**
No validation message was thrown.

**Environment:**
 - OS: Win10 BUILD 19041
 - GPU: 1050 mobile with latest driver: 471.96
 - SDK or header version if building from repo: SDK 1.2.189
 - Options enabled (synchronization, best practices, etc.): 
 VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT &&
VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_RESERVE_BINDING_SLOT_EXT

**Additional context**
Without GPU Assisted Validation my app works fine. And before updating to 1.2.189 from 1.2.175 ( iirc ) it worked find with GPUAV too.

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #3257

### CODE REVIEW

File: tests/vklayertests_gpu.cpp [hunk 1]
```diff
@@ -2808,3 +2808,98 @@ TEST_F(VkDebugPrintfTest, MeshTaskShadersPrintf) {
...
+
+    VkValidationFeatureEnableEXT enables[] = {VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT,
+                                              VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_RESERVE_BINDING_SLOT_EXT};
+    VkValidationFeaturesEXT features = {};
+    features.sType = VK_STRUCTURE_TYPE_VALIDATION_FEATURES_EXT;
+    features.enabledValidationFeatureCount = 2;
+    features.pEnabledValidationFeatures = enables;
+
+    SetTargetApiVersion(VK_API_VERSION_1_1);
+    ASSERT_NO_FATAL_FAILURE(InitFramework(m_errorMonitor, &features));
```
Comment (Tony-LunarG) [inline tests/vklayertests_gpu.cpp:2825]: 2817-2825 can be replaced with just the SetTargetApiVersion and  InitGpuAssistedFramework(false);

**Review by Tony-LunarG — APPROVED** [review]
LGTM with a testing nit

File: tests/vklayertests_gpu.cpp (hunk 1 above)
Comment (ziga-lunarg) [reply tests/vklayertests_gpu.cpp]: Good to know, thanks!
